In [1]:
'''
task: RQ0: can model identify correct ontology classes to answer CQ?
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: hmas
evaluation: few-shot with and without RAG
'''
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# install rdflib
!pip install rdflib

Collecting rdflib
  Downloading rdflib-7.4.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from rdflib) (3.2.5)
Downloading rdflib-7.4.0-py3-none-any.whl (569 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 569.0/569.0 kB 36.6 MB/s eta 0:00:00
Installing collected packages: rdflib
Successfully installed rdflib-7.4.0

In [3]:
!pip install pymongo sentence_transformers

Collecting pymongo
  Downloading pymongo-4.15.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.1.2)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.57.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.8.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2025.10.5)
Downloading pymongo-4.15.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 79.7 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 34.9 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.15.3

In [4]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.8.0+cu126)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2025.10.5)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.10.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [5]:
# let's work on metrics now starting with a levenshtein distance computation followed by sem@k
!pip install python-Levenshtein

Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.3-py3-none-any.whl.metadata (3.9 kB)
Collecting Levenshtein==0.27.3 (from python-Levenshtein)
  Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.3->python-Levenshtein)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading python_levenshtein-0.27.3-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 12.7 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 123.7 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.27.3 python-Levenshtein-0.27.3 rapidfuzz-3.14.3

# Experimental Setup

Design an automated experiment:
- Pandas dataframe containing the list of CQs and source ontologies
- RAG pipeline for refined search on source ontology using CQ
- LLM pipeline testing several LLMs in zero-shot state on RQ0: identify the classes and/or properties to answer CQ

In [6]:
# read dataset of CQs into pandas dataframe
import os
import pandas as pd
from rdflib import Graph

def load_ontology_into_triples(ontology_path):
  print("*** ONTOLOGY:", ontology_path)
  g = Graph()
  g.parse(ontology_path)
  # store axioms in string
  target = ""

  for s, p, o in g:
    # trim dataset a bit by removing all SHACL restrictions
    subj = s.n3(g.namespace_manager)
    prop = p.n3(g.namespace_manager)
    obj = o.n3(g.namespace_manager)
    target += subj + " " + prop + " " + obj + "\n"
  return target

hmas_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/hmas/data/hmas_complete_dataset.csv")

# now load source ontologies
# dynamically list all ontologies
path = "/content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies"
onto_list = os.listdir(path)
# now clean onto names to match domain name in dataframe
onto_list = list(map(lambda x: x.replace("_onto.ttl", ""), onto_list))

# fill the dataframe with the source ontologies for easier use
for onto in onto_list:
  # transform ontology into graph and read it as string
  onto_name = onto + "_onto.ttl"
  onto_path = os.path.join(path, onto_name)
  onto_string = load_ontology_into_triples(onto_path)
  hmas_df.loc[hmas_df["domain"] == onto, "source_ontology"] = onto_string

hmas_df.head()

*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/discover-platforms_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/discover-core_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/configure-organization_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/create-organization_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/discover-behavior-specifications_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/scenario-template_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/discover-organization_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/discover-signifiers_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/coordinate-activities_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/safety-rules_onto.ttl
*** ONTOLOGY: /content/drive/MyDrive/Colab Notebooks/hmas/data/ontologies/structure-organization_onto.ttl

,domain,question,query,answer,source_ontology
0,scenario-template,What are the instances of the example class?,prefix ex: <http://example.org/>\n\nask {\n ...,[ex:Class],"ex:Class rdfs:comment ""Example class for testi..."
1,configure-organization,What are the artifacts that an agent of the or...,prefix ex: <http://example.org/>\nprefix hmas:...,"[hasFacility, isAccessIn, isAccessFor, isAcces...",:hasFacility rdfs:range :Facility\n:isAccessFo...
2,configure-organization,What are the settings of an organization X?,prefix ex: <http://example.org/>\nprefix hmas:...,[proposesSetting],:hasFacility rdfs:range :Facility\n:isAccessFo...
3,configure-organization,What are the facilities that the artifact X have?,prefix ex: <http://example.org/>\nprefix hmas:...,[hasFacility],:hasFacility rdfs:range :Facility\n:isAccessFo...
4,configure-organization,What are the agents currently in the setting Y?,prefix ex: <http://example.org/>\nprefix hmas:...,"[isAccessIn, isAccessOf]",:hasFacility rdfs:range :Facility\n:isAccessFo...

In [7]:
# compute sentence embeddings for semantic universal primes
from sentence_transformers import SentenceTransformer
import Levenshtein
import math
import pandas as pd
import pymongo
import time
import json
import re

embedding_model = SentenceTransformer("thenlper/gte-large")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/619 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/670M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/342 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [8]:
def get_embedding(text: str) -> list[float]:
    # https://huggingface.co/thenlper/gte-large
    if not text.strip():
        print("Attempted to get embedding for empty text.")
        return []
    embedding = embedding_model.encode(text)
    return embedding.tolist()


def get_mongo_client(mongo_uri):
    """Establish connection to the MongoDB."""
    try:
        client = pymongo.MongoClient(mongo_uri)
        print("Connection to MongoDB successful")
        return client
    except pymongo.errors.ConnectionFailure as e:
        print(f"Connection failed: {e}")
        return None

def ingest_data_into_mongodb(data_df, collection):
    """Ingest data into MongoDB."""
    # delete all previous documents from collection
    collection.delete_many({})
    documents = data_df.to_dict("records")
    collection.insert_many(documents)
    print("Data ingestion into MongoDB completed")

def vector_search(user_query, collection, num_candidate_answers):
    """
    Perform a vector search in the MongoDB collection based on the user query.

    Args:
    user_query (str): The user's query string.
    collection (MongoCollection): The MongoDB collection to search.

    Returns:
    list: A list of matching documents.
    """
    # Generate embedding for the user query
    query_embedding = get_embedding(user_query)
    if query_embedding is None:
        return "Invalid query or embedding generation failed."
    # Define the vector search pipeline
    pipeline = [
        {
            "$vectorSearch": {
                "index": "wordnet_vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": num_candidate_answers,  # Number of candidate matches to consider
                "limit": int(num_candidate_answers/2) + 1,  # Return top half matches
            }
        },
        {
            "$project": {
                "_id": 0,  # Exclude the _id field
                "axiom": 1,  # Include the axiom field
                "embedding": 1, # Include the embedding field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
            }
        },
    ]
    # Execute the search
    results = collection.aggregate(pipeline)
    return list(results)

def get_search_result(query, collection, num_candidate_answers):
    get_knowledge = vector_search(query, collection, num_candidate_answers)
    search_result = ""
    for result in get_knowledge:
        search_result += f"{result.get('axiom', 'N/A')}"
        search_result += "\n"
    return search_result

def get_all_documents(collection):
    cursor = collection.find({})
    source_information = '\n'.join([cursordoc['axiom'] for cursordoc in cursor])
    return source_information

def generate_triples_from_ontology_string(ontology_string):
  # create dataset of axioms as triples and embeddings to store in vector db
  axioms_embeddings = pd.DataFrame(ontology_string.split("\n"), columns=['axiom'])
  axioms_embeddings["embedding"] = axioms_embeddings["axiom"].apply(get_embedding)
  return axioms_embeddings

def predict_answer(model, tokenizer, query, source_knowledge, fs_examples):
  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert ontologist. You are given an OWL ontology between <SOURCE></SOURCE> tags. Each line is a triple of the form subject relation object. Give the classes and properties from the ontology that answer the question: {query}. Output your answer as the following template with 'classes' and 'properties' fileld with your answer:
  ""<start_of_turn>model{{'classes': [], 'properties': []}}<eos>""
  <SOURCE>{source_knowledge}</SOURCE>
  You are given some examples to follow between <EXAMPLES></EXAMPLES> tags:
  <EXAMPLES>{fs_examples}</EXAMPLES>
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  response_string = tokenizer.decode(response[0])
  # try to manipulate answer to return list of classes and properties
  # Define the start and end substrings
  pattern = r"(?<=<start_of_turn>model)(.*?)(?=<eos>)"
  matches = re.findall(pattern, response_string, flags=re.DOTALL)
  # find all elements between brackets: ["'Mission'", "'includesOrganizationalGoal', 'isDependentOnOrganizationalGoal'"]
  res = re.findall(r"\[(.*?)\]", matches[-1])  # always work with the last match - it is usuall the one filled with the answer
  res2 = [elem.split(',') for elem in res]   # break off sublists of comma-separated elements in classes or properties
  predicted_answer = [x for xs in res2 for x in xs]     # concatenate list of lists into one single list
  predicted_answer = [x.strip().strip("'") for x in predicted_answer]  # strip added quotation marks by model for each string element
  return predicted_answer

def evaluate_levenshtein_ratio(actual, predicted):
  # normalize lists
  actual = sorted(list(map(lambda x: x.lower(), actual)))  # transform all elements to lowercase and sort them
  predicted = sorted(list(map(lambda x: x.lower(), predicted)))  # transform all elements to lowercase and sort them
  levenshtein_ratio = Levenshtein.ratio(actual, predicted)
  return levenshtein_ratio

def precision_at_k(actual, predicted):
    act_set = set(actual)
    pred_set = set(predicted)
    result = len(act_set & pred_set) / float(len(predicted))
    return result*100

def apk(actual, predicted, k):
    """
    Computes the average precision at k.
    This function computes the average prescision at k between two lists of
    items.
    Parameters
    ----------
    actual : list
             A list of elements that are to be predicted (order doesn't matter)
    predicted : list
                A list of predicted elements (order does matter)
    k : int
        The maximum number of predicted elements
    Returns
    -------
    score : double
            The average precision at k over the input lists
    """
    if not actual:
        return 0.0
    if len(predicted)>k:
        predicted = predicted[:k]
    score = 0.0
    num_hits = 0.0
    for i,p in enumerate(predicted):
        # first condition checks whether it is valid prediction
        # second condition checks if prediction is not repeated
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)
    return score / min(len(actual), k)

def hits_at_k(predicted, actual, k):
    # normalize lowercasing for all elements in both lists for fair evaluation
    actual = list(map(lambda x: x.lower(), actual))
    predicted = list(map(lambda x: x.lower(), predicted))
    hits = []
    for p, t in zip(actual, predicted):
        top_k = p[:k]
        hit = int(any(item in t for item in top_k))
        hits.append(hit)
    try:
        hits_score = sum(hits) / len(hits)
    except ZeroDivisionError:
        hits_score = 0.0
    return hits_score

def mrr_at_k(predicted, actual, k):
    # normalize lowercasing for all elements in both lists for fair evaluation
    actual = list(map(lambda x: x.lower(), actual))
    predicted = list(map(lambda x: x.lower(), predicted))
    rr_list = []
    for p, t in zip(predicted, actual):
        rr = 0.0
        for i, item in enumerate(p[:k], start=1):
            if item in t:
                rr = 1.0 / i
                break
        rr_list.append(rr)
    try:
        mrr_score = sum(rr_list) / len(rr_list)
    except ZeroDivisionError:
        mrr_score = 0.0
    return mrr_score

def map_at_k(predicted, actual, k):
    """
    Computes the mean average precision at k.
    This function computes the mean average prescision at k between two lists
    of lists of items.
    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int,
        The maximum number of predicted elements
    Returns
    -------
    score : double
            The mean average precision at k over the input lists
    """
    # normalize lowercasing for all elements in both lists for fair evaluation
    actual = list(map(lambda x: x.lower(), actual))
    predicted = list(map(lambda x: x.lower(), predicted))
    return np.mean([apk(a, p, k) for a,p in zip(actual, predicted)])

In [9]:
def prepare_few_shot_examples(dataset, num_few_shot_examples=3):
  # get list of top most frequent domains from dataframe
  most_frequent_domains_list = dataset['domain'].value_counts()[:num_few_shot_examples].index.tolist()
  # filter initial dataframe to curate one CQ from each of the most frequent domains
  filtered = (
      dataset[dataset['domain'].isin(most_frequent_domains_list)]
      .drop_duplicates(subset='domain')   # keep only first per subvalue
      .set_index('domain')
      .loc[most_frequent_domains_list]                  # preserve order of your list
      .reset_index()
  )

  fs_prompt = ""
  # prepare answers to correspond to model promp format
  answers = [
     "<start_of_turn>model{{'classes': [OrganizationModel], 'properties': []}}<eos>",
     "<start_of_turn>model{{'classes': [Workspace], 'properties': [contains]}}<eos>",
     "<start_of_turn>model{{'classes': [], 'properties': [hasFacility, isAccessIn, isAccessFor, isAccessTo]}}<eos>"
  ]
  for index, row in filtered.iterrows():
    fs_prompt += f"""<SOURCE>{row['source_ontology']}</SOURCE>\nQuestion: {row['question']}\nAnswer: {answers[index]}\n"""
  return fs_prompt

def infer_from_ontology(dataset, model, tokenizer, mode='default'):
  # test automated dynamic RAG pipeline for all ontologies
  mongo_uri = "mongodb+srv://habiakl:aYItN6CjNIPBhgSc@fhfyoiv.mongodb.net/?retryWrites=true&w=majority&appName=Kerberos"
  mongo_client = get_mongo_client(mongo_uri)
  # set vector store config variables
  db = mongo_client["semantic_tower"]
  collection = db["wordnet"]
  # set the domain to the first domain ontology and ingest to avoid repeating ontology ingestion for same-domain CQs
  current_domain = dataset["domain"][0]
  current_onto_df = generate_triples_from_ontology_string(dataset["source_ontology"][0])
  ingest_data_into_mongodb(current_onto_df, collection)
  # add wait time
  time.sleep(15) # sleep 15 seconds to ingest data in the ontology
  # create metrics dataframe
  evaluation_metrics_df = pd.DataFrame(columns=["levenshtein_ratio", "hits@k", "mrr@k", "map@k"])
  levenshtein_ratio_values = []
  hits_k_values = []
  mrr_k_values = []
  map_k_values = []
  # prepare Levenshtein Ratio dictionary for per-domain average ratio calculation (all CQs in same domain)
  domains = dataset['domain'].unique().tolist()
  levenshtein_ratio_domains_dict = {key: [] for key in domains}
  hits_k_domains_dict = {key: [] for key in domains}
  mrr_k_domains_dict = {key: [] for key in domains}
  map_k_domains_dict = {key: [] for key in domains}
  # for the HITS@K, MRR@K and MAP@K metrics, choose k = max length of ground truth
  hmas_df['answer_list'] = [val.split(',') for val in hmas_df['answer']] # transform stringed lists into lists
  k = hmas_df['answer_list'].apply(len).max()
  # prepare few-shot example template
  fs_examples = prepare_few_shot_examples(hmas_df)

  for index, row in dataset.iterrows():
      row_domain = row["domain"]
      dataset_df = generate_triples_from_ontology_string(row["source_ontology"])
      # add k dynamically depending on the length of the ground truth answer of current question
      k = len(row['answer_list'])
      query = row["question"].lower()
      print("*** QUERY: ",query)
      # ingest data into MongoDB triples vector store only if the domain is different
      if row_domain != current_domain:
        ingest_data_into_mongodb(dataset_df, collection)
        # add wait time
        time.sleep(15)
      if mode.lower() == "rag":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        num_candidate_answers = math.ceil(len(dataset_df)/2)
        source_information = get_search_result(query, collection, num_candidate_answers)
        print("*** RAG INFORMATION:", source_information)
      else:
        source_information = get_all_documents(collection)
        print("*** SOURCE INFORMATION:", source_information)
      # predict answer with model
      model_prediction = predict_answer(model, tokenizer, query, source_information, fs_examples)
      # now evaluate on key metrics: Levenshtein Ratio, HITS@K, MAP@K
      gold_answer = row["answer"].strip('[]').split(', ') # list by default is loaded as a string, example: '[Class, Role]' and is transformed to a list: ['Class', 'Role']
      print("*** GROUND TRUTH:", gold_answer)
      print("*** MODEL PREDICTION:", model_prediction)
      # Levenshtein Ratio
      levenshtein_ratio = evaluate_levenshtein_ratio(gold_answer, model_prediction)
      levenshtein_ratio_values.append(levenshtein_ratio)
      levenshtein_ratio_domains_dict[row_domain].append(levenshtein_ratio)
      # HITS@K
      hits_at_k_score = hits_at_k(model_prediction, gold_answer, k)
      hits_k_values.append(hits_at_k_score)
      hits_k_domains_dict[row_domain].append(hits_at_k_score)
      # MRR@K
      mrr_at_k_score = mrr_at_k(model_prediction, gold_answer, k)
      mrr_k_values.append(mrr_at_k_score)
      mrr_k_domains_dict[row_domain].append(mrr_at_k_score)
      # MAP@K
      map_k_score = map_at_k(model_prediction, gold_answer, k)
      map_k_values.append(map_k_score)
      map_k_domains_dict[row_domain].append(map_k_score)

  levenshtein_ratio_averages = {key: sum(values) / len(values) if values else 0 for key, values in levenshtein_ratio_domains_dict.items()}
  hits_k_averages = {key: sum(values) / len(values) if values else 0 for key, values in hits_k_domains_dict.items()}
  mrr_k_averages = {key: sum(values) / len(values) if values else 0 for key, values in mrr_k_domains_dict.items()}
  map_k_averages = {key: sum(values) / len(values) if values else 0 for key, values in map_k_domains_dict.items()}
  # fill evaluation metrics dataframe
  evaluation_metrics_df["levenshtein_ratio"] = levenshtein_ratio_values
  evaluation_metrics_df["hits@k"] = hits_k_values
  evaluation_metrics_df["mrr@k"] = mrr_k_values
  evaluation_metrics_df["map@k"] = map_k_values
  print("*************** INFERENCE COMPLETE ***************")
  return evaluation_metrics_df, levenshtein_ratio_averages, hits_k_averages, mrr_k_averages, map_k_averages

In [10]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [11]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2025.10.5)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [12]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [13]:
# experiment: FS prediction without RAG
eval_results, levenshtein_ratio_avgs, hits_k_avgs, mrr_k_avgs, map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='default')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?
*** SOURCE INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdfs:label "Class"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['OrganizationModel', 'hasOrganizationalGoal', 'hasRole']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['OrganizationModel', 'hasOrganizationalGoal', 'hasRole']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :Mission rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:isDefinedBy :regulation
:includesMission rdfs:domain :Process
:Process rdfs:isDefinedBy :regulation
:includesMission rdfs:range :Mission
:Mission rdfs:label "mission"@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:Mission rdfs:label "mission"@fr
:isCommitmentOf rdfs:domain :Commitment
:includesMission rdfs:label "inclut la mission"@fr
:includesOrganizationalGoal rdf:type owl:ObjectProperty
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Commitment rdf:type owl:Class
:Mission rdf:type owl:Class
:Process rdfs:label "processus"@fr
:proposesProcess rdfs:label "fournit un processus"@fr
:proposesProcess rdf:type owl:ObjectProperty
:includesMission rdfs:label "includes mission"@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdf:type owl:ObjectProperty
:Process rdf:type owl:Class
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isCommitmentOf rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "is commitment for"@en
:proposesProcess rdfs:range :Process
:isCommitmentOf rdfs:label "is commitment of"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isCommitmentOf rdfs:range :Agent
:Commitment rdfs:label "commitment"@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:label "proposes process"@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdf:type owl:ObjectProperty
:includesOrganizationalGoal rdfs:domain :Mission
:isCommitmentFor rdfs:range :Mission
:isCommitmentOf rdf:type owl:ObjectProperty
:includesMission rdfs:isDefinedBy :regulation
:Commitment rdfs:label "engagement"@fr
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:Process rdfs:label "process"@en
:proposesProcess rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "est engagement pour"@fr
:isCommitmentOf rdfs:label "est engagement de"@fr
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isCommitmentFor rdfs:domain :Commitment
:includesMission rdfs:comment "A relation that refers to a Mission part of a Process."@en
:includesOrganizationalGoal rdfs:isDefinedBy :regulation

In [14]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(hits_k_avgs)
print("***** MRR@K *****")
print(mrr_k_avgs)
print("***** MAP@K *****")
print(map_k_avgs)
eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.3944444444444445, 'coordinate-activities': 0.0, 'create-organization': 0.0, 'structure-organization': 0.0, 'discover-behavior-specifications': 0.0, 'discover-core': 0.0, 'discover-organization': 0.0, 'discover-platforms': 0.0, 'discover-signifiers': 0.0, 'safety-rules': 0.0}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.4833333333333333, 'coordinate-activities': 0.38888888888888884, 'create-organization': 0.1259259259259259, 'structure-organization': 0.5222222222222223, 'discover-behavior-specifications': 0.0, 'discover-core': 0.0, 'discover-organization': 0.6666666666666666, 'discover-platforms': 0.125, 'discover-signifiers': 1.0, 'safety-rules': 0.25}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.475, 'coordinate-activities': 0.7037037037037037, 'create-organization': 0.17962962962962964, 'structure-organization': 0.5018518518518519, 'discover-behavior-specifications': 0.0, 'discover-core': 0.0, 'discover-organization': 0.25, 'discover-platforms': 0.125, 'discover-signifiers': 0.25, 'safety-rules': 0.25}
***** MAP@K *****
{'scenario-template': np.float64(0.0), 'configure-organization': np.float64(0.43217592592592585), 'coordinate-activities': np.float64(0.5462962962962963), 'create-organization': np.float64(0.07473055065647657), 'structure-organization': np.float64(nan), 'discover-behavior-specifications': np.float64(0.0), 'discover-core': np.float64(nan), 'discover-organization': np.float64(0.20833333333333334), 'discover-platforms': np.float64(0.0625), 'discover-signifiers': np.float64(0.125), 'safety-rules': np.float64(nan)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000  0.000000
1            0.888889  0.750000  0.625000  0.572917
2            0.000000  0.000000  1.000000  1.000000
3            0.333333  0.000000  0.000000  0.000000
4            0.000000  1.000000  0.250000  0.125000
5            0.750000  0.666667  0.500000  0.462963
6            0.000000  0.000000  1.000000  1.000000
7            0.000000  0.500000  0.500000  0.250000
8            0.000000  0.666667  0.611111  0.388889
9            0.000000  0.000000  0.000000  0.000000
10           0.000000  0.000000  0.000000  0.000000
11           0.000000  0.000000  0.000000  0.000000
12           0.000000  0.000000  0.000000  0.000000
13           0.000000  0.000000  0.000000  0.000000
14           0.000000  0.800000  0.700000  0.251279
15           0.000000  0.000000  0.166667  0.055556
16           0.000000  0.000000  0.250000  0.125000
17           0.000000  0.333333  0.500000  0.240741
18           0.000000  0.000000  0.000000       NaN
19           0.000000  0.800000  0.700000  0.285374
20           0.000000  1.000000  0.866667  0.338889
21           0.000000  0.000000  0.000000  0.000000
22           0.000000  0.333333  0.444444  0.259259
23           0.000000  1.000000  1.000000  0.611111
24           0.000000  0.000000  0.000000  0.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.000000  0.000000  0.000000  0.000000
27           0.000000  0.000000  0.000000  0.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.000000  0.000000  0.000000       NaN
30           0.000000  0.000000  0.000000       NaN
31           0.000000  0.000000  0.000000       NaN
32           0.000000  0.000000  0.000000       NaN
33           0.000000  0.000000  0.000000       NaN
34           0.000000  0.000000  0.000000       NaN
35           0.000000  0.000000  0.000000       NaN
36           0.000000  1.000000  0.500000  0.500000
37           0.000000  0.500000  0.000000  0.000000
38           0.000000  0.500000  0.250000  0.125000
39           0.000000  0.500000  0.500000  0.250000
40           0.000000  0.000000  0.000000  0.000000
41           0.000000  0.000000  0.000000  0.000000
42           0.000000  0.000000  0.000000  0.000000
43           0.000000  1.000000  0.250000  0.125000
44           0.000000  1.000000  0.250000  0.125000
45           0.000000  1.000000  0.250000  0.125000
46           0.000000  1.000000  1.000000  1.000000
47           0.000000  0.000000  0.000000  0.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.000000  0.000000  0.000000       NaN

In [15]:
# experiment: FS prediction with RAG
rag_eval_results, rag_levenshtein_ratio_avgs, rag_hits_k_avgs, rag_mrr_k_avgs, rag_map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='rag')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?
*** RAG INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:hasFacility rdfs:domain :Artifact
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:isSettingOf rdfs:range :Organization
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isAccessIn rdfs:label "is access in"@en
:isAccessTo rdfs:label "is access to"@en
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "contexte d'accès"@fr

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['Role', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :proposesSetting rdfs:domain :Organization
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:range :Organization
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "setting"@en
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:Setting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:label "proposes setting"@en
:proposesSetting rdfs:range :Setting
:isSettingOf rdfs:label "is setting of"@en
:isAccessIn rdfs:range :Setting
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:hasFacility rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :hasFacility rdfs:domain :Artifact
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:hasFacility rdfs:range :Facility
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:hasFacility rdfs:label "has facility"@en
:isAccessFor rdfs:range :Facility
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:Access rdfs:label "accès"@fr
:Setting rdfs:label "contexte d'accès"@fr
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:label "est accès dans"@fr

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :isAccessOf rdfs:range :Agent
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:range :Facility
:isSettingOf rdfs:domain :Setting
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:isDefinedBy :regulation
:isAccessIn rdfs:isDefinedBy :regulation
:proposesSetting rdfs:domain :Organization
:isSettingOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:domain :Artifact
:Access rdfs:isDefinedBy :regulation
:isAccessIn rdfs:label "est accès dans"@fr
:isAccessTo rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed
*** RAG INFORMATION:
*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:domain :Mission
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdfs:range :Mission

*** GROUND TRUTH: ['includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals in process z proposed by the organization x and how these organizational goals are dependent on each other?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:proposesProcess rdfs:domain :Organization
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:includesOrganizationalGoal rdfs:range :OrganizationalGoal

*** GROUND TRUTH: ['includesMission', 'includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents responsible for fulfilling the organizational goals of process y in the organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr

*** GROUND TRUTH: ['includesMission', 'isCommitmentOf', 'isCommitmentFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the organization x's organization model that can be used to create a new organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:proposesRole rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations that follow a different organization model than organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations with the same organization model as the organization x and situated on y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:hasOrganizationalGoal rdfs:domain :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the available organization models that can be used to create a new organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:hasOrganizationalGoal rdfs:domain :Organization
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalValue rdfs:domain :Organization
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdf:type owl:Class
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalGoal rdfs:label "has organizational goal"@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational values of a given organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:OrganizationalValue rdfs:label "organizational value"@en
:hasOrganizationalValue rdfs:label "has organizational value"@en
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:OrganizationModel skos:related :Organization
:OrganizationalValue rdf:type owl:Class
:hasOrganizationalValue rdfs:range :OrganizationalValue
:OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationalGoal rdfs:label "organizational goal"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en

*** GROUND TRUTH: ['hasOrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the elements composing a given organization model?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel skos:related :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalValue rdfs:label "has organizational value"@en
:proposesFacility rdfs:domain :Organization
:OrganizationalGoal rdf:type owl:Class
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdf:type owl:Class
:hasOrganizationalGoal rdfs:label "has organizational goal"@en

*** GROUND TRUTH: ['proposesFacility', 'hasOrganizationalGoal', 'proposesRole', 'hasOrganizationalValue', 'OrganizationModel', 'Facility', 'Role', 'OrganizationalGoal', 'OrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the roles provided by the organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:domain :Organization
:hasOrganizationalGoal rdfs:domain :Organization
:Role rdfs:label "rôle"@fr
:Role rdfs:label "role"@en
:proposesRole rdfs:label "provides role"@en

In [16]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(rag_levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(rag_hits_k_avgs)
print("***** MRR@K *****")
print(rag_mrr_k_avgs)
print("***** MAP@K *****")
print(rag_map_k_avgs)
rag_eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.4515873015873016, 'coordinate-activities': 0.0, 'create-organization': 0.0, 'structure-organization': 0.0, 'discover-behavior-specifications': 0.0, 'discover-core': 0.0, 'discover-organization': 0.0, 'discover-platforms': 0.0, 'discover-signifiers': 0.0, 'safety-rules': 0.0}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.3833333333333333, 'coordinate-activities': 0.38888888888888884, 'create-organization': 0.18148148148148147, 'structure-organization': 0.6, 'discover-behavior-specifications': 0.0, 'discover-core': 0.21428571428571427, 'discover-organization': 0.5, 'discover-platforms': 0.125, 'discover-signifiers': 0.5, 'safety-rules': 0.375}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.2916666666666667, 'coordinate-activities': 0.23148148148148148, 'create-organization': 0.2351851851851852, 'structure-organization': 0.4824074074074074, 'discover-behavior-specifications': 0.0, 'discover-core': 0.35714285714285715, 'discover-organization': 0.08333333333333333, 'discover-platforms': 0.375, 'discover-signifiers': 0.16666666666666666, 'safety-rules': 0.625}
***** MAP@K *****
{'scenario-template': np.float64(0.0), 'configure-organization': np.float64(0.2363425925925926), 'coordinate-activities': np.float64(0.1280864197530864), 'create-organization': np.float64(0.13028610621203213), 'structure-organization': np.float64(0.22325680272108847), 'discover-behavior-specifications': np.float64(0.0), 'discover-core': np.float64(0.21428571428571427), 'discover-organization': np.float64(0.041666666666666664), 'discover-platforms': np.float64(0.3125), 'discover-signifiers': np.float64(0.08333333333333333), 'safety-rules': np.float64(0.625)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000  0.000000
1            0.888889  0.750000  0.708333  0.593750
2            0.000000  0.000000  0.000000  0.000000
3            0.333333  0.000000  0.000000  0.000000
4            0.285714  0.500000  0.250000  0.125000
5            0.750000  0.666667  0.500000  0.462963
6            0.000000  0.000000  0.000000  0.000000
7            0.000000  0.500000  0.250000  0.125000
8            0.000000  0.666667  0.444444  0.259259
9            0.000000  0.000000  0.000000  0.000000
10           0.000000  0.000000  0.000000  0.000000
11           0.000000  0.000000  0.000000  0.000000
12           0.000000  0.000000  0.000000  0.000000
13           0.000000  0.000000  0.000000  0.000000
14           0.000000  0.800000  0.700000  0.251279
15           0.000000  0.000000  0.166667  0.055556
16           0.000000  0.500000  0.750000  0.625000
17           0.000000  0.333333  0.500000  0.240741
18           0.000000  1.000000  0.750000  0.337500
19           0.000000  0.800000  0.700000  0.285374
20           0.000000  0.800000  0.666667  0.272222
21           0.000000  0.000000  0.000000  0.000000
22           0.000000  0.333333  0.111111  0.037037
23           0.000000  0.666667  0.666667  0.407407
24           0.000000  0.000000  0.000000  0.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.000000  0.000000  0.000000  0.000000
27           0.000000  0.000000  0.000000  0.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.000000  0.000000  0.250000  0.125000
30           0.000000  0.500000  0.750000  0.625000
31           0.000000  0.000000  0.500000  0.250000
32           0.000000  0.500000  0.250000  0.125000
33           0.000000  0.500000  0.250000  0.125000
34           0.000000  0.000000  0.500000  0.250000
35           0.000000  0.000000  0.000000  0.000000
36           0.000000  0.500000  0.000000  0.000000
37           0.000000  0.500000  0.000000  0.000000
38           0.000000  0.500000  0.250000  0.125000
39           0.000000  0.500000  0.500000  0.250000
40           0.000000  0.000000  0.000000  0.000000
41           0.000000  0.000000  1.000000  1.000000
42           0.000000  0.000000  0.000000  0.000000
43           0.000000  0.500000  0.000000  0.000000
44           0.000000  0.500000  0.500000  0.250000
45           0.000000  0.500000  0.000000  0.000000
46           0.000000  1.000000  1.000000  1.000000
47           0.000000  0.000000  1.000000  1.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.000000  0.500000  0.500000  0.500000

In [19]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.46G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [20]:
# experiment: FS prediction without RAG
eval_results, levenshtein_ratio_avgs, hits_k_avgs, mrr_k_avgs, map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='default')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdfs:label "Class"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Mission rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:isDefinedBy :regulation
:includesMission rdfs:domain :Process
:Process rdfs:isDefinedBy :regulation
:includesMission rdfs:range :Mission
:Mission rdfs:label "mission"@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:Mission rdfs:label "mission"@fr
:isCommitmentOf rdfs:domain :Commitment
:includesMission rdfs:label "inclut la mission"@fr
:includesOrganizationalGoal rdf:type owl:ObjectProperty
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Commitment rdf:type owl:Class
:Mission rdf:type owl:Class
:Process rdfs:label "processus"@fr
:proposesProcess rdfs:label "fournit un processus"@fr
:proposesProcess rdf:type owl:ObjectProperty
:includesMission rdfs:label "includes mission"@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdf:type owl:ObjectProperty
:Process rdf:type owl:Class
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isCommitmentOf rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "is commitment for"@en
:proposesProcess rdfs:range :Process
:isCommitmentOf rdfs:label "is commitment of"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isCommitmentOf rdfs:range :Agent
:Commitment rdfs:label "commitment"@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:label "proposes process"@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdf:type owl:ObjectProperty
:includesOrganizationalGoal rdfs:domain :Mission
:isCommitmentFor rdfs:range :Mission
:isCommitmentOf rdf:type owl:ObjectProperty
:includesMission rdfs:isDefinedBy :regulation
:Commitment rdfs:label "engagement"@fr
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:Process rdfs:label "process"@en
:proposesProcess rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "est engagement pour"@fr
:isCommitmentOf rdfs:label "est engagement de"@fr
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isCommitmentFor rdfs:domain :Commitment
:includesMission rdfs:comment "A relation that refers to a Mission part of a Process."@en
:includesOrganizationalGoal rdfs:isDefinedBy :regulation
:Commitment rdfs:isDefinedBy :regulation
:includesMission rdf:type owl:ObjectProperty
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr

*** GROUND TRUTH: ['includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals in process z proposed by the organization x and how these organizational goals are dependent on each other?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Mission rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:isDefinedBy :regulation
:includesMission rdfs:domain :Process
:Process rdfs:isDefinedBy :regulation
:includesMission rdfs:range :Mission
:Mission rdfs:label "mission"@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:Mission rdfs:label "mission"@fr
:isCommitmentOf rdfs:domain :Commitment
:includesMission rdfs:label "inclut la mission"@fr
:includesOrganizationalGoal rdf:type owl:ObjectProperty
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Commitment rdf:type owl:Class
:Mission rdf:type owl:Class
:Process rdfs:label "processus"@fr
:proposesProcess rdfs:label "fournit un processus"@fr
:proposesProcess rdf:type owl:ObjectProperty
:includesMission rdfs:label "includes mission"@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdf:type owl:ObjectProperty
:Process rdf:type owl:Class
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isCommitmentOf rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "is commitment for"@en
:proposesProcess rdfs:range :Process
:isCommitmentOf rdfs:label "is commitment of"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isCommitmentOf rdfs:range :Agent
:Commitment rdfs:label "commitment"@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:label "proposes process"@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdf:type owl:ObjectProperty
:includesOrganizationalGoal rdfs:domain :Mission
:isCommitmentFor rdfs:range :Mission
:isCommitmentOf rdf:type owl:ObjectProperty
:includesMission rdfs:isDefinedBy :regulation
:Commitment rdfs:label "engagement"@fr
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:Process rdfs:label "process"@en
:proposesProcess rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "est engagement pour"@fr
:isCommitmentOf rdfs:label "est engagement de"@fr
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isCommitmentFor rdfs:domain :Commitment
:includesMission rdfs:comment "A relation that refers to a Mission part of a Process."@en
:includesOrganizationalGoal rdfs:isDefinedBy :regulation
:Commitment rdfs:isDefinedBy :regulation
:includesMission rdf:type owl:ObjectProperty
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr

*** GROUND TRUTH: ['includesMission', 'includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents responsible for fulfilling the organizational goals of process y in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Mission rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:isDefinedBy :regulation
:includesMission rdfs:domain :Process
:Process rdfs:isDefinedBy :regulation
:includesMission rdfs:range :Mission
:Mission rdfs:label "mission"@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:Mission rdfs:label "mission"@fr
:isCommitmentOf rdfs:domain :Commitment
:includesMission rdfs:label "inclut la mission"@fr
:includesOrganizationalGoal rdf:type owl:ObjectProperty
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Commitment rdf:type owl:Class
:Mission rdf:type owl:Class
:Process rdfs:label "processus"@fr
:proposesProcess rdfs:label "fournit un processus"@fr
:proposesProcess rdf:type owl:ObjectProperty
:includesMission rdfs:label "includes mission"@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdf:type owl:ObjectProperty
:Process rdf:type owl:Class
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isCommitmentOf rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "is commitment for"@en
:proposesProcess rdfs:range :Process
:isCommitmentOf rdfs:label "is commitment of"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isCommitmentOf rdfs:range :Agent
:Commitment rdfs:label "commitment"@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:label "proposes process"@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdf:type owl:ObjectProperty
:includesOrganizationalGoal rdfs:domain :Mission
:isCommitmentFor rdfs:range :Mission
:isCommitmentOf rdf:type owl:ObjectProperty
:includesMission rdfs:isDefinedBy :regulation
:Commitment rdfs:label "engagement"@fr
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:Process rdfs:label "process"@en
:proposesProcess rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "est engagement pour"@fr
:isCommitmentOf rdfs:label "est engagement de"@fr
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isCommitmentFor rdfs:domain :Commitment
:includesMission rdfs:comment "A relation that refers to a Mission part of a Process."@en
:includesOrganizationalGoal rdfs:isDefinedBy :regulation
:Commitment rdfs:isDefinedBy :regulation
:includesMission rdf:type owl:ObjectProperty
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr

*** GROUND TRUTH: ['includesMission', 'isCommitmentOf', 'isCommitmentFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the organization x's organization model that can be used to create a new organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations that follow a different organization model than organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['OrganizationModel', 'OrganizationModel', 'Role', 'Facility', 'hasOrganizationalGoal']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations with the same organization model as the organization x and situated on y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the available organization models that can be used to create a new organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational values of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['hasOrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the elements composing a given organization model?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['proposesFacility', 'hasOrganizationalGoal', 'proposesRole', 'hasOrganizationalValue', 'OrganizationModel', 'Facility', 'Role', 'OrganizationalGoal', 'OrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the roles provided by the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['proposesRole', 'OrganizationModel', 'Role']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals of the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: [' OrganizationModel', 'OrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities proposed by the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:proposesFacility rdfs:range :Facility
:proposesFacility rdfs:label "proposes facility"@en
:Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:Facility rdfs:isDefinedBy :regulation
:OrganizationModel skos:related :Organization
:hasOrganizationalGoal rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:isDefinedBy :regulation
:OrganizationalGoal rdfs:isDefinedBy :regulation
:proposesRole rdfs:isDefinedBy :regulation
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:proposesRole rdfs:label "fournit un rôle"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdf:type owl:ObjectProperty
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:hasOrganizationalValue rdfs:range :OrganizationalValue
:proposesFacility rdf:type owl:ObjectProperty
:Role rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:Facility rdf:type owl:Class
:proposesRole rdf:type owl:ObjectProperty
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationalValue rdf:type owl:Class
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:isDefinedBy :regulation
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:label "provides role"@en
:OrganizationalGoal rdf:type owl:Class
:Facility rdfs:label "potentialité d'usage"@fr
:Facility rdfs:label "facility"@en
:hasOrganizationalValue rdfs:domain :Organization
:OrganizationalValue rdfs:isDefinedBy :regulation
:hasOrganizationalValue rdfs:label "has organizational value"@en
:Role rdfs:label "role"@en
:Role rdf:type owl:Class
:hasOrganizationalValue rdf:type owl:ObjectProperty
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:Role rdfs:label "rôle"@fr
:proposesRole rdfs:range :Role
:proposesFacility rdfs:label "fournit une potentialité d'usage"@fr

*** GROUND TRUTH: ['proposesFacility', 'OrganizationModel', 'Facility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the job positions including their department and associated membership that are not being played by anyone in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['(Membership', 'isMembershipFor', 'isMembershipIn', 'isStructuredBy', 'proposesRole', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents to whom agent a can interact with in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isMembershipOf', 'isMembershipFor', 'isMembershipIn', 'hasMembershipRelationshipWith', 'proposesRole', 'isStructuredBy', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the job positions of agent a in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesRole', 'isStructuredBy', 'isMembershipOf', 'isMembershipFor', 'isMembershipIn', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the departments in the organization x
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isStructuredBy', 'Group']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the departments under the department y in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isSubGroupOf', 'isStructuredBy', 'Group']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the memberships incompatibility constraints applied to agents in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isSubGroupOf rdfs:domain :Group
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isSubGroupOf rdfs:range :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipFor rdfs:label "is membership for"@en
:isMembershipIn rdfs:label "is membership in"@en
:hasMembershipRelationshipWith rdf:type owl:ObjectProperty
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:isDefinedBy :regulation
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:domain :Membership
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:isStructuredBy rdfs:label "est structuré par"@fr
:isStructuredBy rdfs:isDefinedBy :regulation
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdf:type owl:Class
:isSubGroupOf rdfs:label "is subgroup of"@en
:structures rdfs:inverseOf :isStructuredBy
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdf:type owl:ObjectProperty
:isStructuredBy rdfs:domain :Organization
:isMembershipIn rdf:type owl:ObjectProperty
:isStructuredBy rdfs:inverseOf :structures
:Membership rdf:type owl:Class
:structures rdfs:label "structure"@fr
:isStructuredBy rdfs:label "is structured by"@en
:isStructuredBy rdf:type owl:ObjectProperty
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:isMembershipOf rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:Membership rdfs:label "membership"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:range :Organization
:isMembershipIn rdfs:domain :Membership
:structures rdfs:domain :Group
:Group rdfs:label "group"@en
:Group rdfs:label "groupe"@fr
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdf:type owl:ObjectProperty
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:label "structures"@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group rdfs:isDefinedBy :regulation
:structures rdfs:isDefinedBy :regulation
:Membership rdfs:label "l'appartenance"@fr
:isStructuredBy rdfs:range :Group
:isMembershipOf rdfs:domain :Membership
:isMembershipFor rdf:type owl:ObjectProperty
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isMembershipOf', 'isMembershipFor', 'Membership']
*** MODEL PREDICTION: ['']
Attempted to get embedding for empty text.
*** QUERY:  what is the action execution specification that a given signifier signifies?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :ActionExecution rdfs:isDefinedBy :interaction
:BehaviorExecution rdfs:isDefinedBy :interaction
:hasInput rdf:type owl:ObjectProperty
:ActionExecution rdfs:label "exécution de l'action"@fr
:hasInput rdfs:domain :ActionExecution
:signifies rdf:type owl:ObjectProperty
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:isDefinedBy :interaction
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:BehaviorExecution rdf:type owl:Class
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:signifies rdfs:domain :Signifier
:ActionExecution rdf:type owl:Class
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:signifies rdfs:label "signifies"@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:signifies rdfs:isDefinedBy :interaction
:hasInput rdfs:label "has input"@en
:signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:signifies rdfs:label "signifie"@fr
:hasInput rdfs:label "a une entrée"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['ActionExecution']
*** MODEL PREDICTION: ['OrganizationModel', '', 'Workspace', 'contains', '', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the specification of the input based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :ActionExecution rdfs:isDefinedBy :interaction
:BehaviorExecution rdfs:isDefinedBy :interaction
:hasInput rdf:type owl:ObjectProperty
:ActionExecution rdfs:label "exécution de l'action"@fr
:hasInput rdfs:domain :ActionExecution
:signifies rdf:type owl:ObjectProperty
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:isDefinedBy :interaction
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:BehaviorExecution rdf:type owl:Class
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:signifies rdfs:domain :Signifier
:ActionExecution rdf:type owl:Class
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:signifies rdfs:label "signifies"@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:signifies rdfs:isDefinedBy :interaction
:hasInput rdfs:label "has input"@en
:signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:signifies rdfs:label "signifie"@fr
:hasInput rdfs:label "a une entrée"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the type of the input that an action execution should have based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :ActionExecution rdfs:isDefinedBy :interaction
:BehaviorExecution rdfs:isDefinedBy :interaction
:hasInput rdf:type owl:ObjectProperty
:ActionExecution rdfs:label "exécution de l'action"@fr
:hasInput rdfs:domain :ActionExecution
:signifies rdf:type owl:ObjectProperty
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:isDefinedBy :interaction
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:BehaviorExecution rdf:type owl:Class
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:signifies rdfs:domain :Signifier
:ActionExecution rdf:type owl:Class
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:signifies rdfs:label "signifies"@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:signifies rdfs:isDefinedBy :interaction
:hasInput rdfs:label "has input"@en
:signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:signifies rdfs:label "signifie"@fr
:hasInput rdfs:label "a une entrée"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the properties that the input of an action execution should have based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :ActionExecution rdfs:isDefinedBy :interaction
:BehaviorExecution rdfs:isDefinedBy :interaction
:hasInput rdf:type owl:ObjectProperty
:ActionExecution rdfs:label "exécution de l'action"@fr
:hasInput rdfs:domain :ActionExecution
:signifies rdf:type owl:ObjectProperty
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:isDefinedBy :interaction
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:BehaviorExecution rdf:type owl:Class
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:signifies rdfs:domain :Signifier
:ActionExecution rdf:type owl:Class
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:signifies rdfs:label "signifies"@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:signifies rdfs:isDefinedBy :interaction
:hasInput rdfs:label "has input"@en
:signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:signifies rdfs:label "signifie"@fr
:hasInput rdfs:label "a une entrée"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are forms that an action execution should use based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :ActionExecution rdfs:isDefinedBy :interaction
:BehaviorExecution rdfs:isDefinedBy :interaction
:hasInput rdf:type owl:ObjectProperty
:ActionExecution rdfs:label "exécution de l'action"@fr
:hasInput rdfs:domain :ActionExecution
:signifies rdf:type owl:ObjectProperty
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:isDefinedBy :interaction
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:BehaviorExecution rdf:type owl:Class
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:signifies rdfs:domain :Signifier
:ActionExecution rdf:type owl:Class
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:signifies rdfs:label "signifies"@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:signifies rdfs:isDefinedBy :interaction
:hasInput rdfs:label "has input"@en
:signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:signifies rdfs:label "signifie"@fr
:hasInput rdfs:label "a une entrée"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['ActionExecution']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the workspaces directly contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['contains', 'Workspace']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are all the workspaces contained in a given workspace (directly or indirectly)?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['transitivelyContains', 'Workspace']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the parent workspace of a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['isContainedIn', 'Workspace']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['contains', 'Artifact']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['contains', 'Agent']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are all the workspaces that contain a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['isContainedIn', 'Workspace']
*** MODEL PREDICTION: ['Workspace', 'contains', '', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the profile of a given resource?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :Workspace rdfs:label "Workspace"@en
:Workspace rdfs:isDefinedBy :core
:Artifact rdfs:label "Artifact"@en
:Workspace rdf:type owl:Class
:contains owl:inverseOf :isContainedIn
:isProfileOf owl:inverseOf :hasProfile
:Agent rdfs:isDefinedBy :core
:hasProfile rdfs:range :ResourceProfile
:isProfileOf rdfs:label "is profile of"@en
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:contains rdfs:label "directlyContains"@en
:contains rdfs:isDefinedBy :core
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent
:isProfileOf rdf:type owl:ObjectProperty
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdf:type owl:ObjectProperty
:isProfileOf rdfs:isDefinedBy :core
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:isTransitivelyContainedIn rdf:type owl:TransitiveProperty
:transitivelyContains rdfs:isDefinedBy :core
:contains rdfs:subPropertyOf :transitivelyContains
_:nac5a921a04b54f5ba05aee99d34485e7b1 rdf:type owl:AllDisjointClasses
_:nac5a921a04b54f5ba05aee99d34485e7b1 owl:members _:nac5a921a04b54f5ba05aee99d34485e7b2
:isContainedIn rdfs:label "is contained in"@en
:ResourceProfile rdfs:isDefinedBy :core
:transitivelyContains rdfs:label "transitivelyContains"@en
:Artifact rdf:type owl:Class
:ResourceProfile rdfs:label "Resource Profile"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:isContainedIn rdf:type owl:ObjectProperty
:isContainedIn rdfs:isDefinedBy :core
:transitivelyContains rdf:type owl:TransitiveProperty
:isTransitivelyContainedIn rdfs:isDefinedBy :core
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:Agent rdf:type owl:Class
:contains rdf:type owl:ObjectProperty
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b5
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:transitivelyContains rdfs:domain :Workspace
:hasProfile owl:inverseOf :isProfileOf
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:isContainedIn owl:inverseOf :contains
:Artifact rdfs:label "Artefact"@fr
:hasProfile rdf:type owl:AsymmetricProperty
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:rest rdf:nil
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn owl:inverseOf :transitivelyContains
:hasProfile rdf:type owl:ObjectProperty
:Agent rdfs:label "Agent"@fr
:hasProfile rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b3
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:ResourceProfile rdf:type owl:Class
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:hasProfile rdfs:label "has profile"@en
:Artifact rdfs:isDefinedBy :core
:isTransitivelyContainedIn rdf:type owl:ObjectProperty
:isProfileOf rdfs:domain :ResourceProfile
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:rest _:nac5a921a04b54f5ba05aee99d34485e7b4
:Agent rdfs:label "Agent"@en
:transitivelyContains owl:inverseOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['hasProfile', 'ResourceProfile']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the discoverable organizations in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :isMaterialOf rdfs:comment "A relation between an Artifact and an Organization it belongs to."@en
:Organization rdfs:label "organization"@en-us
:Organization rdfs:isDefinedBy :core
:Organization rdf:type owl:Class
:Organization rdfs:comment "An Organization is an entity situated on Agents and Artifacts, and regulated by a regulation system."@en
:isMemberOf rdfs:label "is member of"@en
:isMemberOf rdfs:range :Organization
:isMemberOf rdfs:comment "A relation between an Agent and an Organization it belongs to."@en
:isMemberOf rdfs:domain :Agent
:isMaterialOf rdfs:label "is material of"@en
:isMaterialOf rdfs:range :Organization
:isMaterialOf rdfs:isDefinedBy :core
:Organization rdfs:label "organisation"@fr
:Organization rdfs:label "organisation"@en-GB
:Organization rdfs:label "organization"@en
:isMemberOf rdfs:isDefinedBy :core
:isMemberOf rdf:type owl:ObjectProperty
:isMaterialOf rdfs:domain :Artifact
:isMaterialOf rdf:type owl:ObjectProperty

*** GROUND TRUTH: ['Organization', 'isMemberOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the members of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :isMaterialOf rdfs:comment "A relation between an Artifact and an Organization it belongs to."@en
:Organization rdfs:label "organization"@en-us
:Organization rdfs:isDefinedBy :core
:Organization rdf:type owl:Class
:Organization rdfs:comment "An Organization is an entity situated on Agents and Artifacts, and regulated by a regulation system."@en
:isMemberOf rdfs:label "is member of"@en
:isMemberOf rdfs:range :Organization
:isMemberOf rdfs:comment "A relation between an Agent and an Organization it belongs to."@en
:isMemberOf rdfs:domain :Agent
:isMaterialOf rdfs:label "is material of"@en
:isMaterialOf rdfs:range :Organization
:isMaterialOf rdfs:isDefinedBy :core
:Organization rdfs:label "organisation"@fr
:Organization rdfs:label "organisation"@en-GB
:Organization rdfs:label "organization"@en
:isMemberOf rdfs:isDefinedBy :core
:isMemberOf rdf:type owl:ObjectProperty
:isMaterialOf rdfs:domain :Artifact
:isMaterialOf rdf:type owl:ObjectProperty

*** GROUND TRUTH: ['Organization', 'isMemberOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the materials of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :isMaterialOf rdfs:comment "A relation between an Artifact and an Organization it belongs to."@en
:Organization rdfs:label "organization"@en-us
:Organization rdfs:isDefinedBy :core
:Organization rdf:type owl:Class
:Organization rdfs:comment "An Organization is an entity situated on Agents and Artifacts, and regulated by a regulation system."@en
:isMemberOf rdfs:label "is member of"@en
:isMemberOf rdfs:range :Organization
:isMemberOf rdfs:comment "A relation between an Agent and an Organization it belongs to."@en
:isMemberOf rdfs:domain :Agent
:isMaterialOf rdfs:label "is material of"@en
:isMaterialOf rdfs:range :Organization
:isMaterialOf rdfs:isDefinedBy :core
:Organization rdfs:label "organisation"@fr
:Organization rdfs:label "organisation"@en-GB
:Organization rdfs:label "organization"@en
:isMemberOf rdfs:isDefinedBy :core
:isMemberOf rdf:type owl:ObjectProperty
:isMaterialOf rdfs:domain :Artifact
:isMaterialOf rdf:type owl:ObjectProperty

*** GROUND TRUTH: ['Organization', 'isMaterialOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the hypermedia mas platform that hosts a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:hosts rdf:type owl:AsymmetricProperty
:isHostedOn owl:inverseOf :hosts
:isHostedOn rdfs:domain :Hostable
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>
:isHostedOn rdf:type owl:ObjectProperty
:isHostedOn rdfs:label "is hosted on"@en
:hosts rdfs:range :Hostable
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:isHostedOn rdfs:isDefinedBy :core
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/49>
:HypermediaMASPlatform rdfs:isDefinedBy :core
:hosts rdf:type owl:ObjectProperty
:HypermediaMASPlatform rdf:type owl:Class
:hosts rdfs:isDefinedBy :core
:hosts dct:source <https://github.com/HyperAgents/ns.hyperagents.org/issues/8#issuecomment-1025991719>
:isHostedOn rdf:type owl:AsymmetricProperty
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en
:hosts rdfs:domain :HypermediaMASPlatform
:hosts rdfs:label "hosts"@en

*** GROUND TRUTH: ['HypermediaMASPlatform', 'isHostedOn']
*** MODEL PREDICTION: ['Workspace', 'contains']
Attempted to get embedding for empty text.
*** QUERY:  what is the resource profile of a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:hosts rdf:type owl:AsymmetricProperty
:isHostedOn owl:inverseOf :hosts
:isHostedOn rdfs:domain :Hostable
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>
:isHostedOn rdf:type owl:ObjectProperty
:isHostedOn rdfs:label "is hosted on"@en
:hosts rdfs:range :Hostable
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:isHostedOn rdfs:isDefinedBy :core
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/49>
:HypermediaMASPlatform rdfs:isDefinedBy :core
:hosts rdf:type owl:ObjectProperty
:HypermediaMASPlatform rdf:type owl:Class
:hosts rdfs:isDefinedBy :core
:hosts dct:source <https://github.com/HyperAgents/ns.hyperagents.org/issues/8#issuecomment-1025991719>
:isHostedOn rdf:type owl:AsymmetricProperty
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en
:hosts rdfs:domain :HypermediaMASPlatform
:hosts rdfs:label "hosts"@en

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the resource profile of a given hypermedia mas platform?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:hosts rdf:type owl:AsymmetricProperty
:isHostedOn owl:inverseOf :hosts
:isHostedOn rdfs:domain :Hostable
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>
:isHostedOn rdf:type owl:ObjectProperty
:isHostedOn rdfs:label "is hosted on"@en
:hosts rdfs:range :Hostable
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:isHostedOn rdfs:isDefinedBy :core
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/49>
:HypermediaMASPlatform rdfs:isDefinedBy :core
:hosts rdf:type owl:ObjectProperty
:HypermediaMASPlatform rdf:type owl:Class
:hosts rdfs:isDefinedBy :core
:hosts dct:source <https://github.com/HyperAgents/ns.hyperagents.org/issues/8#issuecomment-1025991719>
:isHostedOn rdf:type owl:AsymmetricProperty
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en
:hosts rdfs:domain :HypermediaMASPlatform
:hosts rdfs:label "hosts"@en

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is a signifier for a fipa message transport service of a given platform?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:hosts rdf:type owl:AsymmetricProperty
:isHostedOn owl:inverseOf :hosts
:isHostedOn rdfs:domain :Hostable
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>
:isHostedOn rdf:type owl:ObjectProperty
:isHostedOn rdfs:label "is hosted on"@en
:hosts rdfs:range :Hostable
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:isHostedOn rdfs:isDefinedBy :core
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/49>
:HypermediaMASPlatform rdfs:isDefinedBy :core
:hosts rdf:type owl:ObjectProperty
:HypermediaMASPlatform rdf:type owl:Class
:hosts rdfs:isDefinedBy :core
:hosts dct:source <https://github.com/HyperAgents/ns.hyperagents.org/issues/8#issuecomment-1025991719>
:isHostedOn rdf:type owl:AsymmetricProperty
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en
:hosts rdfs:domain :HypermediaMASPlatform
:hosts rdfs:label "hosts"@en

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['', 'isHostedOn']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in a given resource profile?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: _:n949de3a6cb4648aebafef186eb149536b1 dct:bibliographicCitation "Chemero, A., & Turvey, M. T. (2007). Complexity, hypersets, and the ecological perspective on perception-action. Biological Theory, 2(1), 23-36."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:Affordance skos:related :Signifier
:isExposedIn owl:inverseOf :exposesSignifier
:Affordance skos:definition "A behavior possibility that is a relationship between an ability of an agent and a situation that includes agents and features of the environment."@en
:Affordance rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 dct:bibliographicCitation "Norman, D. (2013). The design of everyday things: Revised and expanded edition. Basic books."@en
:exposesSignifier rdf:type owl:ObjectProperty
:exposesSignifier owl:inverseOf :isExposedIn
:exposesSignifier rdfs:label "expose le signifiant"@fr
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b1
:isExposedIn rdfs:domain :Signifier
:exposesSignifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b1 rdfs:label "Chemero and Turvey, 2007"@en
:isExposedIn rdfs:range :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:Affordance skos:prefLabel "affordance"@en
:Signifier rdfs:label "Signifiant"@fr
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en
:exposesSignifier rdfs:range :Signifier
:exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdf:type owl:ObjectProperty
:Signifier rdfs:label "Signifier"@en
:isExposedIn rdfs:isDefinedBy :core
:Affordance skos:historyNote "The definition of the concept follows affordance theorists [Chemero and Turvey, 2007]."@en
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:Affordance rdf:type skos:Concept
:isExposedIn rdfs:label "is exposed in"@en
:Signifier skos:related :Signifier
:Signifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 rdfs:label "Norman, 2013"@en
:Signifier rdf:type owl:Class
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b2
:exposesSignifier rdfs:domain :ResourceProfile
:Signifier rdfs:subClassOf :Hostable

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in resource profiles of artifacts contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: _:n949de3a6cb4648aebafef186eb149536b1 dct:bibliographicCitation "Chemero, A., & Turvey, M. T. (2007). Complexity, hypersets, and the ecological perspective on perception-action. Biological Theory, 2(1), 23-36."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:Affordance skos:related :Signifier
:isExposedIn owl:inverseOf :exposesSignifier
:Affordance skos:definition "A behavior possibility that is a relationship between an ability of an agent and a situation that includes agents and features of the environment."@en
:Affordance rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 dct:bibliographicCitation "Norman, D. (2013). The design of everyday things: Revised and expanded edition. Basic books."@en
:exposesSignifier rdf:type owl:ObjectProperty
:exposesSignifier owl:inverseOf :isExposedIn
:exposesSignifier rdfs:label "expose le signifiant"@fr
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b1
:isExposedIn rdfs:domain :Signifier
:exposesSignifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b1 rdfs:label "Chemero and Turvey, 2007"@en
:isExposedIn rdfs:range :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:Affordance skos:prefLabel "affordance"@en
:Signifier rdfs:label "Signifiant"@fr
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en
:exposesSignifier rdfs:range :Signifier
:exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdf:type owl:ObjectProperty
:Signifier rdfs:label "Signifier"@en
:isExposedIn rdfs:isDefinedBy :core
:Affordance skos:historyNote "The definition of the concept follows affordance theorists [Chemero and Turvey, 2007]."@en
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:Affordance rdf:type skos:Concept
:isExposedIn rdfs:label "is exposed in"@en
:Signifier skos:related :Signifier
:Signifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 rdfs:label "Norman, 2013"@en
:Signifier rdf:type owl:Class
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b2
:exposesSignifier rdfs:domain :ResourceProfile
:Signifier rdfs:subClassOf :Hostable

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in resource profiles of a given artifact?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: _:n949de3a6cb4648aebafef186eb149536b1 dct:bibliographicCitation "Chemero, A., & Turvey, M. T. (2007). Complexity, hypersets, and the ecological perspective on perception-action. Biological Theory, 2(1), 23-36."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:Affordance skos:related :Signifier
:isExposedIn owl:inverseOf :exposesSignifier
:Affordance skos:definition "A behavior possibility that is a relationship between an ability of an agent and a situation that includes agents and features of the environment."@en
:Affordance rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 dct:bibliographicCitation "Norman, D. (2013). The design of everyday things: Revised and expanded edition. Basic books."@en
:exposesSignifier rdf:type owl:ObjectProperty
:exposesSignifier owl:inverseOf :isExposedIn
:exposesSignifier rdfs:label "expose le signifiant"@fr
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b1
:isExposedIn rdfs:domain :Signifier
:exposesSignifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b1 rdfs:label "Chemero and Turvey, 2007"@en
:isExposedIn rdfs:range :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:Affordance skos:prefLabel "affordance"@en
:Signifier rdfs:label "Signifiant"@fr
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en
:exposesSignifier rdfs:range :Signifier
:exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdf:type owl:ObjectProperty
:Signifier rdfs:label "Signifier"@en
:isExposedIn rdfs:isDefinedBy :core
:Affordance skos:historyNote "The definition of the concept follows affordance theorists [Chemero and Turvey, 2007]."@en
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:Affordance rdf:type skos:Concept
:isExposedIn rdfs:label "is exposed in"@en
:Signifier skos:related :Signifier
:Signifier rdfs:isDefinedBy :core
_:n949de3a6cb4648aebafef186eb149536b2 rdfs:label "Norman, 2013"@en
:Signifier rdf:type owl:Class
:Affordance dct:references _:n949de3a6cb4648aebafef186eb149536b2
:exposesSignifier rdfs:domain :ResourceProfile
:Signifier rdfs:subClassOf :Hostable

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the set of norms ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasException rdfs:domain :Contextable
:hasException rdfs:comment "Associates exceptions to a context of application of a norm"@en
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:hasNormativeTarget rdfs:domain :RegulativeNorm
:prohibits rdfs:label "prohibits"@en
:hasException rdfs:label "has exception"@en
:hasException rdf:type owl:ObjectProperty
:hasRespectStatus rdf:type owl:ObjectProperty
:hasNormativeTarget rdf:type owl:ObjectProperty
:hasNormativeObject rdfs:range :Behavior
:enforcesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganization>
:hasNormativeObject rdfs:domain :RegulativeNorm
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:definesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganizationSpecification>
:hasRespectStatus rdfs:range xsd:boolean
:enforcesNorm rdfs:range :Norm
:obliges rdfs:domain :Norm
:hasRespectStatus rdfs:label "has respect status"@en
:enforcesNorm rdf:type owl:ObjectProperty
:hasNormativeTarget rdfs:range :Role
:obliges rdf:type owl:ObjectProperty
:hasNormativeContext rdfs:label "has normative context"@en
:hasNormativeObject rdf:type owl:ObjectProperty
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:hasNormativeContext rdfs:domain :RegulativeNorm
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
<https://ci.mines-stetienne.fr/regulation#> owl:imports <https://ci.mines-stetienne.fr/hmas#>
:obliges rdfs:range rdfs:Container
:prohibits rdf:type owl:ObjectProperty
<https://ci.mines-stetienne.fr/regulation#> rdf:type owl:Ontology
:RegulativeNorm rdf:type owl:Class
:hasNormativeObject rdfs:comment "A specification which defines the expected behavior by describing explicitly the expected behavior or implictly by describing the state of affairs."
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:AuthorityRole rdf:subClassOf <https://ci.mines-stetienne.fr/regulationSocialRole>
:NormativeContext rdfs:label "Normative Context"@en
:NormativeContext rdf:type owl:Class
:hasNormativeContext rdfs:range :NormativeContext
:prohibits rdfs:domain :Norm
:AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:hasNormativeTarget rdfs:label "has normative target"
:permits rdf:type owl:ObjectProperty
:AuthorityRole rdfs:label "Authority"@en
:prohibits rdfs:range rdfs:Container
:hasNormativeObject rdfs:label "has normative object"
:hasNormativeContext rdf:type owl:ObjectProperty
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:obliges rdfs:label "obliges"@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:permits rdfs:label "allows"@en
:RegulativeNorm rdfs:label "Norm"@en
:permits rdfs:domains :Norm
:permits rdfs:range rdfs:Container
:hasRespectStatus rdfs:domain :RegulativeNorm
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:definesNorm rdfs:range :Norm
:definesNorm rdf:type owl:ObjectProperty
:definesNorm rdfs:label "defines the norm"@en

*** GROUND TRUTH: ['RegulativeNorm']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  who are the agents under the regulation of a norm ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasException rdfs:domain :Contextable
:hasException rdfs:comment "Associates exceptions to a context of application of a norm"@en
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:hasNormativeTarget rdfs:domain :RegulativeNorm
:prohibits rdfs:label "prohibits"@en
:hasException rdfs:label "has exception"@en
:hasException rdf:type owl:ObjectProperty
:hasRespectStatus rdf:type owl:ObjectProperty
:hasNormativeTarget rdf:type owl:ObjectProperty
:hasNormativeObject rdfs:range :Behavior
:enforcesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganization>
:hasNormativeObject rdfs:domain :RegulativeNorm
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:definesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganizationSpecification>
:hasRespectStatus rdfs:range xsd:boolean
:enforcesNorm rdfs:range :Norm
:obliges rdfs:domain :Norm
:hasRespectStatus rdfs:label "has respect status"@en
:enforcesNorm rdf:type owl:ObjectProperty
:hasNormativeTarget rdfs:range :Role
:obliges rdf:type owl:ObjectProperty
:hasNormativeContext rdfs:label "has normative context"@en
:hasNormativeObject rdf:type owl:ObjectProperty
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:hasNormativeContext rdfs:domain :RegulativeNorm
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
<https://ci.mines-stetienne.fr/regulation#> owl:imports <https://ci.mines-stetienne.fr/hmas#>
:obliges rdfs:range rdfs:Container
:prohibits rdf:type owl:ObjectProperty
<https://ci.mines-stetienne.fr/regulation#> rdf:type owl:Ontology
:RegulativeNorm rdf:type owl:Class
:hasNormativeObject rdfs:comment "A specification which defines the expected behavior by describing explicitly the expected behavior or implictly by describing the state of affairs."
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:AuthorityRole rdf:subClassOf <https://ci.mines-stetienne.fr/regulationSocialRole>
:NormativeContext rdfs:label "Normative Context"@en
:NormativeContext rdf:type owl:Class
:hasNormativeContext rdfs:range :NormativeContext
:prohibits rdfs:domain :Norm
:AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:hasNormativeTarget rdfs:label "has normative target"
:permits rdf:type owl:ObjectProperty
:AuthorityRole rdfs:label "Authority"@en
:prohibits rdfs:range rdfs:Container
:hasNormativeObject rdfs:label "has normative object"
:hasNormativeContext rdf:type owl:ObjectProperty
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:obliges rdfs:label "obliges"@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:permits rdfs:label "allows"@en
:RegulativeNorm rdfs:label "Norm"@en
:permits rdfs:domains :Norm
:permits rdfs:range rdfs:Container
:hasRespectStatus rdfs:domain :RegulativeNorm
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:definesNorm rdfs:range :Norm
:definesNorm rdf:type owl:ObjectProperty
:definesNorm rdfs:label "defines the norm"@en

*** GROUND TRUTH: ['hasNormativeTarget']
*** MODEL PREDICTION: ['', '', 'Agent', 'NormativeTarget', 'hasNormativeTarget', 'enforcesNorm']
Attempted to get embedding for empty text.
*** QUERY:  what are the norms that have not been respected ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasException rdfs:domain :Contextable
:hasException rdfs:comment "Associates exceptions to a context of application of a norm"@en
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:hasNormativeTarget rdfs:domain :RegulativeNorm
:prohibits rdfs:label "prohibits"@en
:hasException rdfs:label "has exception"@en
:hasException rdf:type owl:ObjectProperty
:hasRespectStatus rdf:type owl:ObjectProperty
:hasNormativeTarget rdf:type owl:ObjectProperty
:hasNormativeObject rdfs:range :Behavior
:enforcesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganization>
:hasNormativeObject rdfs:domain :RegulativeNorm
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:definesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganizationSpecification>
:hasRespectStatus rdfs:range xsd:boolean
:enforcesNorm rdfs:range :Norm
:obliges rdfs:domain :Norm
:hasRespectStatus rdfs:label "has respect status"@en
:enforcesNorm rdf:type owl:ObjectProperty
:hasNormativeTarget rdfs:range :Role
:obliges rdf:type owl:ObjectProperty
:hasNormativeContext rdfs:label "has normative context"@en
:hasNormativeObject rdf:type owl:ObjectProperty
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:hasNormativeContext rdfs:domain :RegulativeNorm
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
<https://ci.mines-stetienne.fr/regulation#> owl:imports <https://ci.mines-stetienne.fr/hmas#>
:obliges rdfs:range rdfs:Container
:prohibits rdf:type owl:ObjectProperty
<https://ci.mines-stetienne.fr/regulation#> rdf:type owl:Ontology
:RegulativeNorm rdf:type owl:Class
:hasNormativeObject rdfs:comment "A specification which defines the expected behavior by describing explicitly the expected behavior or implictly by describing the state of affairs."
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:AuthorityRole rdf:subClassOf <https://ci.mines-stetienne.fr/regulationSocialRole>
:NormativeContext rdfs:label "Normative Context"@en
:NormativeContext rdf:type owl:Class
:hasNormativeContext rdfs:range :NormativeContext
:prohibits rdfs:domain :Norm
:AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:hasNormativeTarget rdfs:label "has normative target"
:permits rdf:type owl:ObjectProperty
:AuthorityRole rdfs:label "Authority"@en
:prohibits rdfs:range rdfs:Container
:hasNormativeObject rdfs:label "has normative object"
:hasNormativeContext rdf:type owl:ObjectProperty
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:obliges rdfs:label "obliges"@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:permits rdfs:label "allows"@en
:RegulativeNorm rdfs:label "Norm"@en
:permits rdfs:domains :Norm
:permits rdfs:range rdfs:Container
:hasRespectStatus rdfs:domain :RegulativeNorm
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:definesNorm rdfs:range :Norm
:definesNorm rdf:type owl:ObjectProperty
:definesNorm rdfs:label "defines the norm"@en

*** GROUND TRUTH: ['hasRespectStatus']
*** MODEL PREDICTION: ['', '']
Attempted to get embedding for empty text.
*** QUERY:  what norms are activated in an organization w.r.t. a context ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** SOURCE INFORMATION: :hasException rdfs:domain :Contextable
:hasException rdfs:comment "Associates exceptions to a context of application of a norm"@en
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:hasNormativeTarget rdfs:domain :RegulativeNorm
:prohibits rdfs:label "prohibits"@en
:hasException rdfs:label "has exception"@en
:hasException rdf:type owl:ObjectProperty
:hasRespectStatus rdf:type owl:ObjectProperty
:hasNormativeTarget rdf:type owl:ObjectProperty
:hasNormativeObject rdfs:range :Behavior
:enforcesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganization>
:hasNormativeObject rdfs:domain :RegulativeNorm
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:definesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganizationSpecification>
:hasRespectStatus rdfs:range xsd:boolean
:enforcesNorm rdfs:range :Norm
:obliges rdfs:domain :Norm
:hasRespectStatus rdfs:label "has respect status"@en
:enforcesNorm rdf:type owl:ObjectProperty
:hasNormativeTarget rdfs:range :Role
:obliges rdf:type owl:ObjectProperty
:hasNormativeContext rdfs:label "has normative context"@en
:hasNormativeObject rdf:type owl:ObjectProperty
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:hasNormativeContext rdfs:domain :RegulativeNorm
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
<https://ci.mines-stetienne.fr/regulation#> owl:imports <https://ci.mines-stetienne.fr/hmas#>
:obliges rdfs:range rdfs:Container
:prohibits rdf:type owl:ObjectProperty
<https://ci.mines-stetienne.fr/regulation#> rdf:type owl:Ontology
:RegulativeNorm rdf:type owl:Class
:hasNormativeObject rdfs:comment "A specification which defines the expected behavior by describing explicitly the expected behavior or implictly by describing the state of affairs."
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:AuthorityRole rdf:subClassOf <https://ci.mines-stetienne.fr/regulationSocialRole>
:NormativeContext rdfs:label "Normative Context"@en
:NormativeContext rdf:type owl:Class
:hasNormativeContext rdfs:range :NormativeContext
:prohibits rdfs:domain :Norm
:AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:hasNormativeTarget rdfs:label "has normative target"
:permits rdf:type owl:ObjectProperty
:AuthorityRole rdfs:label "Authority"@en
:prohibits rdfs:range rdfs:Container
:hasNormativeObject rdfs:label "has normative object"
:hasNormativeContext rdf:type owl:ObjectProperty
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:obliges rdfs:label "obliges"@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:permits rdfs:label "allows"@en
:RegulativeNorm rdfs:label "Norm"@en
:permits rdfs:domains :Norm
:permits rdfs:range rdfs:Container
:hasRespectStatus rdfs:domain :RegulativeNorm
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:definesNorm rdfs:range :Norm
:definesNorm rdf:type owl:ObjectProperty
:definesNorm rdfs:label "defines the norm"@en

*** GROUND TRUTH: ['enforcesNorm', 'hasNormativeContext']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*************** INFERENCE COMPLETE ***************

In [21]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(hits_k_avgs)
print("***** MRR@K *****")
print(mrr_k_avgs)
print("***** MAP@K *****")
print(map_k_avgs)
eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.4515873015873016, 'coordinate-activities': 0.0, 'create-organization': 0.03703703703703704, 'structure-organization': 0.0, 'discover-behavior-specifications': 0.0, 'discover-core': 0.031746031746031744, 'discover-organization': 0.0, 'discover-platforms': 0.0, 'discover-signifiers': 0.0, 'safety-rules': 0.07142857142857142}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.3833333333333333, 'coordinate-activities': 0.38888888888888884, 'create-organization': 0.23703703703703705, 'structure-organization': 0.45555555555555555, 'discover-behavior-specifications': 0.2, 'discover-core': 0.2857142857142857, 'discover-organization': 0.5, 'discover-platforms': 0.125, 'discover-signifiers': 0.5, 'safety-rules': 0.125}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.275, 'coordinate-activities': 0.23148148148148148, 'create-organization': 0.29074074074074074, 'structure-organization': 0.36296296296296293, 'discover-behavior-specifications': 0.2, 'discover-core': 0.2857142857142857, 'discover-organization': 0.08333333333333333, 'discover-platforms': 0.125, 'discover-signifiers': 0.0, 'safety-rules': 0.125}
***** MAP@K *****
{'scenario-template': np.float64(0.0), 'configure-organization': np.float64(0.2321759259259259), 'coordinate-activities': np.float64(0.1280864197530864), 'create-organization': np.float64(0.18584166176758768), 'structure-organization': np.float64(0.15003149407911312), 'discover-behavior-specifications': np.float64(0.2), 'discover-core': np.float64(0.17857142857142858), 'discover-organization': np.float64(0.041666666666666664), 'discover-platforms': np.float64(0.0625), 'discover-signifiers': np.float64(0.0), 'safety-rules': np.float64(0.125)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000  0.000000
1            0.888889  0.750000  0.625000  0.572917
2            0.000000  0.000000  0.000000  0.000000
3            0.333333  0.000000  0.000000  0.000000
4            0.285714  0.500000  0.250000  0.125000
5            0.750000  0.666667  0.500000  0.462963
6            0.000000  0.000000  0.000000  0.000000
7            0.000000  0.500000  0.250000  0.125000
8            0.000000  0.666667  0.444444  0.259259
9            0.000000  0.000000  0.000000  0.000000
10           0.333333  1.000000  1.000000  1.000000
11           0.000000  0.000000  0.000000  0.000000
12           0.000000  0.000000  0.000000  0.000000
13           0.000000  0.000000  0.000000  0.000000
14           0.000000  0.800000  0.700000  0.251279
15           0.000000  0.000000  0.166667  0.055556
16           0.000000  0.000000  0.250000  0.125000
17           0.000000  0.333333  0.500000  0.240741
18           0.000000  0.800000  0.700000  0.305556
19           0.000000  0.800000  0.700000  0.285374
20           0.000000  0.800000  0.666667  0.272222
21           0.000000  0.000000  0.000000  0.000000
22           0.000000  0.333333  0.111111  0.037037
23           0.000000  0.000000  0.000000  0.000000
24           0.000000  1.000000  1.000000  1.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.000000  0.000000  0.000000  0.000000
27           0.000000  0.000000  0.000000  0.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.000000  0.000000  0.250000  0.125000
30           0.000000  0.000000  0.250000  0.125000
31           0.000000  0.000000  0.250000  0.125000
32           0.000000  0.500000  0.250000  0.125000
33           0.000000  0.500000  0.250000  0.125000
34           0.222222  1.000000  0.750000  0.625000
35           0.000000  0.000000  0.000000  0.000000
36           0.000000  0.500000  0.000000  0.000000
37           0.000000  0.500000  0.000000  0.000000
38           0.000000  0.500000  0.250000  0.125000
39           0.000000  0.500000  0.500000  0.250000
40           0.000000  0.000000  0.000000  0.000000
41           0.000000  0.000000  0.000000  0.000000
42           0.000000  0.000000  0.000000  0.000000
43           0.000000  0.500000  0.000000  0.000000
44           0.000000  0.500000  0.000000  0.000000
45           0.000000  0.500000  0.000000  0.000000
46           0.000000  0.000000  0.000000  0.000000
47           0.285714  0.000000  0.000000  0.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.000000  0.500000  0.500000  0.500000

In [22]:
# experiment: FS prediction with RAG
rag_eval_results, rag_levenshtein_ratio_avgs, rag_hits_k_avgs, rag_mrr_k_avgs, rag_map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='rag')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:hasFacility rdfs:domain :Artifact
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:isSettingOf rdfs:range :Organization
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isAccessIn rdfs:label "is access in"@en
:isAccessTo rdfs:label "is access to"@en
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "contexte d'accès"@fr

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :proposesSetting rdfs:domain :Organization
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:range :Organization
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "setting"@en
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:Setting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:label "proposes setting"@en
:proposesSetting rdfs:range :Setting
:isSettingOf rdfs:label "is setting of"@en
:isAccessIn rdfs:range :Setting
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:hasFacility rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hasFacility rdfs:domain :Artifact
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:hasFacility rdfs:range :Facility
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:hasFacility rdfs:label "has facility"@en
:isAccessFor rdfs:range :Facility
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:Access rdfs:label "accès"@fr
:Setting rdfs:label "contexte d'accès"@fr
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:label "est accès dans"@fr

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isAccessOf rdfs:range :Agent
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:range :Facility
:isSettingOf rdfs:domain :Setting
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:isDefinedBy :regulation
:isAccessIn rdfs:isDefinedBy :regulation
:proposesSetting rdfs:domain :Organization
:isSettingOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:domain :Artifact
:Access rdfs:isDefinedBy :regulation
:isAccessIn rdfs:label "est accès dans"@fr
:isAccessTo rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:hasFacility rdfs:domain :Artifact
:isAccessTo rdfs:range :Artifact
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:hasFacility rdfs:range :Facility
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isAccessFor rdfs:range :Facility
:hasFacility rdfs:label "has facility"@en
:Access rdfs:label "access"@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:domain :Access
:isAccessFor rdfs:domain :Access
:isAccessOf rdfs:domain :Access
:isAccessFor rdfs:label "is access for"@en
:isAccessIn rdfs:label "is access in"@en

*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:domain :Mission
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdfs:range :Mission

*** GROUND TRUTH: ['includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals in process z proposed by the organization x and how these organizational goals are dependent on each other?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:proposesProcess rdfs:domain :Organization
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:includesOrganizationalGoal rdfs:range :OrganizationalGoal

*** GROUND TRUTH: ['includesMission', 'includesOrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents responsible for fulfilling the organizational goals of process y in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr

*** GROUND TRUTH: ['includesMission', 'isCommitmentOf', 'isCommitmentFor']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the organization x's organization model that can be used to create a new organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:proposesRole rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations that follow a different organization model than organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations with the same organization model as the organization x and situated on y?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:hasOrganizationalGoal rdfs:domain :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the available organization models that can be used to create a new organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:hasOrganizationalGoal rdfs:domain :Organization
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalValue rdfs:domain :Organization
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdf:type owl:Class
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalGoal rdfs:label "has organizational goal"@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational values of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:OrganizationalValue rdfs:label "organizational value"@en
:hasOrganizationalValue rdfs:label "has organizational value"@en
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:OrganizationModel skos:related :Organization
:OrganizationalValue rdf:type owl:Class
:hasOrganizationalValue rdfs:range :OrganizationalValue
:OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationalGoal rdfs:label "organizational goal"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en

*** GROUND TRUTH: ['hasOrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the elements composing a given organization model?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel skos:related :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalValue rdfs:label "has organizational value"@en
:proposesFacility rdfs:domain :Organization
:OrganizationalGoal rdf:type owl:Class
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:OrganizationalValue rdf:type owl:Class
:hasOrganizationalGoal rdfs:label "has organizational goal"@en

*** GROUND TRUTH: ['proposesFacility', 'hasOrganizationalGoal', 'proposesRole', 'hasOrganizationalValue', 'OrganizationModel', 'Facility', 'Role', 'OrganizationalGoal', 'OrganizationalValue']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the roles provided by the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Role rdfs:comment "A Role defines positions of members (i.e., Agents) in an Organization."@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesRole rdfs:domain :Organization
:hasOrganizationalGoal rdfs:domain :Organization
:Role rdfs:label "rôle"@fr
:Role rdfs:label "role"@en
:proposesRole rdfs:label "provides role"@en
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:proposesRole rdfs:comment "A relation that refers to a Role made available to Agents in the context of an Organization."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalValue rdfs:domain :Organization

*** GROUND TRUTH: ['proposesRole', 'OrganizationModel', 'Role']
*** MODEL PREDICTION: ['', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals of the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :OrganizationalGoal rdfs:label "organizational goal"@en
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "has organizational value"@en
:OrganizationalValue rdfs:label "organizational value"@en
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr

*** GROUND TRUTH: [' OrganizationModel', 'OrganizationalGoal']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities proposed by the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :proposesFacility rdfs:label "proposes facility"@en
:Facility rdfs:comment "A Facility defines functions of materials (i.e., Artifacts) in an Organization."@en
:proposesFacility rdfs:comment "A relation that refers to a Facility made available to Artifacts in the context of an Organization."@en
:OrganizationModel skos:related :Organization
:Facility rdfs:isDefinedBy :regulation
:Facility rdfs:label "facility"@en
:OrganizationModel skos:prefLabel "organization model"@en
:proposesFacility rdfs:range :Facility
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:proposesFacility rdfs:domain :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:domain :Organization
:OrganizationalGoal rdfs:label "organizational goal"@en

*** GROUND TRUTH: ['proposesFacility', 'OrganizationModel', 'Facility']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the job positions including their department and associated membership that are not being played by anyone in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:Group skos:example "In a human organization, a HR department is seen as a group."
:isStructuredBy rdfs:domain :Organization
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:structures rdfs:range :Organization
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:isMembershipIn rdfs:domain :Membership
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:isMembershipIn rdfs:label "is membership in"@en
:isMembershipIn rdfs:isDefinedBy :regulation
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:hasMembershipRelationshipWith rdfs:range :Membership
:isMembershipOf rdfs:label "is membership of"@en
:hasMembershipRelationshipWith rdfs:domain :Membership

*** GROUND TRUTH: ['(Membership', 'isMembershipFor', 'isMembershipIn', 'isStructuredBy', 'proposesRole', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents to whom agent a can interact with in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:isStructuredBy rdfs:domain :Organization
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:hasMembershipRelationshipWith rdfs:label "a une relation d'affiliation avec"@fr
:hasMembershipRelationshipWith rdfs:range :Membership
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:Group skos:example "In a human organization, a HR department is seen as a group."
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:structures rdfs:range :Organization

*** GROUND TRUTH: ['isMembershipOf', 'isMembershipFor', 'isMembershipIn', 'hasMembershipRelationshipWith', 'proposesRole', 'isStructuredBy', 'Membership']
*** MODEL PREDICTION: ['', '', 'Agent', 'Group', 'Membership', 'Organization', 'hasMembershipRelationshipWith', 'isMembershipOf', 'isMembershipIn', 'isStructuredBy', 'isSubGroupOf']
Attempted to get embedding for empty text.
*** QUERY:  what are the job positions of agent a in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isStructuredBy rdfs:domain :Organization
:structures rdfs:range :Organization
:Group skos:example "In a human organization, a HR department is seen as a group."
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:isMembershipIn rdfs:label "est l'appartenance à"@fr
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isMembershipFor rdfs:comment "A relation that refers to the Role involved in a Membership."@en
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:structures rdfs:domain :Group
:Membership rdfs:label "l'appartenance"@fr
:isMembershipFor rdfs:label "est l'adhésion pour"@fr
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr

*** GROUND TRUTH: ['proposesRole', 'isStructuredBy', 'isMembershipOf', 'isMembershipFor', 'isMembershipIn', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the departments in the organization x
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isStructuredBy rdfs:domain :Organization
:structures rdfs:range :Organization
:Group skos:example "In a human organization, a HR department is seen as a group."
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:structures rdfs:domain :Group
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:structures rdfs:isDefinedBy :regulation
:Group rdfs:label "groupe"@fr
:Group rdfs:label "group"@en
:structures rdfs:label "structures"@en
:structures rdfs:label "structure"@fr
:isMembershipOf rdfs:label "est l'appartenance à"@fr
:isStructuredBy rdfs:label "est structuré par"@fr

*** GROUND TRUTH: ['isStructuredBy', 'Group']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the departments under the department y in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isStructuredBy rdfs:domain :Organization
:structures rdfs:range :Organization
:Group skos:example "In a human organization, a HR department is seen as a group."
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en
:structures rdfs:comment "A relation that refers to a Group that structures an Organization."@en
:isSubGroupOf rdfs:label "est un sous-groupe de"@fr
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:structures rdfs:isDefinedBy :regulation
:structures rdfs:domain :Group
:isSubGroupOf rdfs:comment "A relation that refers to a subgroup relationship between two Groups."@en
:Group rdfs:label "groupe"@fr
:isSubGroupOf rdfs:isDefinedBy :regulation
:structures rdfs:label "structure"@fr
:structures rdfs:label "structures"@en
:isSubGroupOf rdfs:label "is subgroup of"@en

*** GROUND TRUTH: ['isSubGroupOf', 'isStructuredBy', 'Group']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the memberships incompatibility constraints applied to agents in the organization x?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Membership rdfs:comment "A Membership indicates the Role played by an Agent in a Group of an Organization."
:isMembershipIn rdfs:isDefinedBy :regulation
:isMembershipOf rdfs:comment "A relation that refers to the Agent involved in a Membership."@en
:hasMembershipRelationshipWith rdfs:comment "A relation that refers to the relationship between Agents member of two Memberships."@en
:hasMembershipRelationshipWith rdfs:isDefinedBy :regulation
:hasMembershipRelationshipWith rdfs:domain :Membership
:hasMembershipRelationshipWith rdfs:range :Membership
:Membership rdfs:isDefinedBy :regulation
:isMembershipIn rdfs:domain :Membership
:isMembershipIn rdfs:comment "A relation that refers to the Group involved in a Membership."@en
:hasMembershipRelationshipWith rdfs:label "has membership interaction with"@en
:Group rdfs:comment "A Group is a subset of Agents in an Organization that belong together."@en
:isMembershipFor rdfs:domain :Membership
:isMembershipFor rdfs:isDefinedBy :regulation
:isMembershipOf rdfs:domain :Membership
:isStructuredBy rdfs:comment "A relation that refers to an Organization that is structured by a Group."@en

*** GROUND TRUTH: ['isMembershipOf', 'isMembershipFor', 'Membership']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the action execution specification that a given signifier signifies?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :signifies rdfs:comment "A relation between a signifier and the specification of a behavior execution. For instance, a SHACL shape can be used to specify an expected behavior execution."@en
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:ActionExecution rdfs:label "action execution"@en
:ActionExecution rdfs:label "exécution de l'action"@fr
:BehaviorExecution rdfs:comment "A course of action performed by an agent upon exploiting a behavior possibility."@en
:BehaviorExecution rdfs:label "exécution du comportement"@fr
:BehaviorExecution rdfs:label "behavior execution"@en

*** GROUND TRUTH: ['ActionExecution']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the specification of the input based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:ActionExecution rdfs:label "action execution"@en
:hasInput rdfs:domain :ActionExecution
:ActionExecution rdfs:label "exécution de l'action"@fr
:ActionExecution rdfs:subClassOf :BehaviorExecution
:BehaviorExecution rdfs:label "exécution du comportement"@fr

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the type of the input that an action execution should have based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:hasInput rdfs:domain :ActionExecution
:ActionExecution rdfs:label "exécution de l'action"@fr
:ActionExecution rdfs:subClassOf :BehaviorExecution
:ActionExecution rdf:type owl:Class

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the properties that the input of an action execution should have based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hasInput rdfs:comment "A relation between an action execution and the input that it has."@en
:ActionExecution rdfs:label "action execution"@en
:hasInput rdfs:domain :ActionExecution
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:ActionExecution rdfs:label "exécution de l'action"@fr
:ActionExecution rdfs:subClassOf :BehaviorExecution
:BehaviorExecution rdfs:label "exécution du comportement"@fr

*** GROUND TRUTH: ['hasInput']
*** MODEL PREDICTION: ['', '']
Attempted to get embedding for empty text.
*** QUERY:  what are forms that an action execution should use based on a given action execution specification?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :ActionExecution rdfs:label "action execution"@en
:ActionExecution rdfs:label "exécution de l'action"@fr
:ActionExecution rdfs:comment "A behavior execution that is the execution of exactly one context-free action, e.g. of a context-free HTTP request."@en
:ActionExecution rdfs:subClassOf :BehaviorExecution
:hasInput rdfs:domain :ActionExecution
:ActionExecution rdf:type owl:Class
:hasInput rdfs:comment "A relation between an action execution and the input that it has."@en

*** GROUND TRUTH: ['ActionExecution']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the workspaces directly contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:Workspace rdfs:label "Workspace"@en
:isTransitivelyContainedIn rdfs:range :Workspace
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:transitivelyContains rdfs:domain :Workspace
:Workspace rdfs:label "Espace de Travail"@fr
:Workspace rdfs:isDefinedBy :core
:contains rdfs:label "directlyContains"@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:Workspace rdf:type owl:Class
:isContainedIn rdfs:label "is contained in"@en
:contains rdfs:subPropertyOf :transitivelyContains
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:contains rdfs:isDefinedBy :core
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn

*** GROUND TRUTH: ['contains', 'Workspace']
*** MODEL PREDICTION: ['Workspace', 'contains', '', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are all the workspaces contained in a given workspace (directly or indirectly)?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:isTransitivelyContainedIn rdfs:range :Workspace
:Workspace rdfs:label "Workspace"@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:transitivelyContains rdfs:domain :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:Workspace rdfs:label "Espace de Travail"@fr
:Workspace rdfs:isDefinedBy :core
:contains rdfs:label "directlyContains"@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:Workspace rdf:type owl:Class
:isContainedIn rdfs:label "is contained in"@en
:contains rdfs:subPropertyOf :transitivelyContains
:isTransitivelyContainedIn rdfs:label "is transitively contained in"@en
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:contains rdfs:isDefinedBy :core

*** GROUND TRUTH: ['transitivelyContains', 'Workspace']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the parent workspace of a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:Workspace rdfs:label "Workspace"@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:isTransitivelyContainedIn rdfs:range :Workspace
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdfs:domain :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:Workspace rdfs:label "Espace de Travail"@fr
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:isDefinedBy :core
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:Workspace rdf:type owl:Class
:isContainedIn rdfs:subPropertyOf :isTransitivelyContainedIn
:contains rdfs:subPropertyOf :transitivelyContains
:contains rdfs:label "directlyContains"@en
:isContainedIn rdfs:isDefinedBy :core
:contains rdfs:isDefinedBy :core
:transitivelyContains rdfs:isDefinedBy :core

*** GROUND TRUTH: ['isContainedIn', 'Workspace']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:Artifact rdfs:label "Artefact"@fr
:Workspace rdfs:label "Workspace"@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:Artifact rdfs:label "Artifact"@en
:Artifact rdfs:comment "A resource that can be dynamically constructed, shared, and used by agents to support their activities. In a Hypermedia MAS, an artifact exposes and can be accessed through a hypermedia interface (in addition to other possible interfaces, such as a physical interface)."@en
:isTransitivelyContainedIn rdfs:range :Workspace
_:nac5a921a04b54f5ba05aee99d34485e7b3 rdf:first :Artifact
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:Workspace rdfs:label "Espace de Travail"@fr
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:transitivelyContains rdfs:domain :Workspace
:Workspace rdf:type owl:Class
:Workspace rdfs:isDefinedBy :core
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:Artifact rdfs:isDefinedBy :core
:Artifact rdf:type owl:Class

*** GROUND TRUTH: ['contains', 'Artifact']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:Workspace rdfs:label "Workspace"@en
:Agent rdfs:label "Agent"@en
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:isTransitivelyContainedIn rdfs:range :Workspace
:Agent rdfs:label "Agent"@fr
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:transitivelyContains rdfs:domain :Workspace
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:Workspace rdfs:label "Espace de Travail"@fr
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Agent rdf:type owl:Class
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:Agent rdfs:isDefinedBy :core
:Workspace rdf:type owl:Class
:Workspace rdfs:isDefinedBy :core
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent

*** GROUND TRUTH: ['contains', 'Agent']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are all the workspaces that contain a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Workspace rdfs:comment "A logical container of one or multiple interactions among agents and potentially artifacts. Workspaces can contain any resource in general and in particular agents, artifacts, other workspaces, or platforms. A workspace can be a LDP container and this can be done by multi-typing the container or by multiple inheritance on a Class ex:Workcontainer. "@en
:Agent rdfs:label "Agent"@en
:Workspace rdfs:label "Workspace"@en
_:nac5a921a04b54f5ba05aee99d34485e7b5 rdf:first :Workspace
:isTransitivelyContainedIn rdfs:comment "A relation that refers to all workspaces in which a resource is contained. "@en
:isTransitivelyContainedIn rdfs:range :Workspace
:Agent rdfs:label "Agent"@fr
:transitivelyContains rdfs:domain :Workspace
:isContainedIn rdfs:comment "A relation that describes a workspace that contains a resource."@en
:Workspace rdfs:label "Espace de Travail"@fr
:contains rdfs:comment "A relation that refers to a logical containment relation and is related to the definition of a workspace as a logical container."@en
:Workspace rdfs:seeAlso <https://www.w3.org/ns/ldp#>
:transitivelyContains rdfs:comment "Links all the resources that are logically contained in a workspaces."@en
:Agent rdfs:comment "An entity that is capable of autonomous behavior."@en
:Agent rdfs:isDefinedBy :core
:Workspace rdfs:isDefinedBy :core
:Agent rdf:type owl:Class
:Workspace rdf:type owl:Class
_:nac5a921a04b54f5ba05aee99d34485e7b2 rdf:first :Agent

*** GROUND TRUTH: ['isContainedIn', 'Workspace']
*** MODEL PREDICTION: ['Workspace', 'contains', '', '']
Attempted to get embedding for empty text.
*** QUERY:  what is the profile of a given resource?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :ResourceProfile rdfs:label "Resource Profile"@en
:ResourceProfile rdfs:comment "Structured data describing a resource through general metadata, domain- and application-specific metadata, and signifiers."@en
:isProfileOf rdfs:comment "A relation that links a resource profile to the resource it is a profile of."@en
:hasProfile rdfs:range :ResourceProfile
:hasProfile rdfs:comment "A relation that links a resource to its profile."@en
:ResourceProfile rdfs:isDefinedBy :core
:isProfileOf rdfs:domain :ResourceProfile
:ResourceProfile skos:example "e.g., a Thing Description document, a Hydra document, an Socio-Technical Network platform description, a fipa:AgentDescription"@en
:ResourceProfile rdf:type owl:Class
:isProfileOf rdfs:label "is profile of"@en
:ResourceProfile rdfs:label "Profil de Ressource"@fr
_:nac5a921a04b54f5ba05aee99d34485e7b4 rdf:first :ResourceProfile
:hasProfile rdfs:label "has profile"@en
:hasProfile rdfs:isDefinedBy :core
:isProfileOf rdfs:isDefinedBy :core
:isProfileOf rdf:type owl:ObjectProperty
:hasProfile owl:inverseOf :isProfileOf
:hasProfile rdf:type owl:AsymmetricProperty
:hasProfile rdf:type owl:ObjectProperty

*** GROUND TRUTH: ['hasProfile', 'ResourceProfile']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the discoverable organizations in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Organization rdfs:label "organization"@en
:Organization rdfs:label "organization"@en-us
:Organization rdfs:label "organisation"@en-GB
:Organization rdfs:label "organisation"@fr
:isMaterialOf rdfs:range :Organization
:isMemberOf rdfs:range :Organization

*** GROUND TRUTH: ['Organization', 'isMemberOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the members of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :Organization rdfs:label "organization"@en-us
:Organization rdfs:label "organization"@en
:Organization rdfs:comment "An Organization is an entity situated on Agents and Artifacts, and regulated by a regulation system."@en
:isMemberOf rdfs:range :Organization
:Organization rdfs:label "organisation"@fr
:Organization rdfs:label "organisation"@en-GB

*** GROUND TRUTH: ['Organization', 'isMemberOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the materials of a given organization?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :isMaterialOf rdfs:range :Organization
:isMaterialOf rdfs:comment "A relation between an Artifact and an Organization it belongs to."@en
:isMaterialOf rdfs:label "is material of"@en
:Organization rdfs:label "organization"@en-us
:Organization rdfs:label "organization"@en
:Organization rdfs:comment "An Organization is an entity situated on Agents and Artifacts, and regulated by a regulation system."@en

*** GROUND TRUTH: ['Organization', 'isMaterialOf']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the hypermedia mas platform that hosts a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:hosts rdfs:domain :HypermediaMASPlatform
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>

*** GROUND TRUTH: ['HypermediaMASPlatform', 'isHostedOn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is the resource profile of a given agent?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/18>
:hosts rdfs:seeAlso <https://github.com/HyperAgents/ns.hyperagents.org/issues/49>
:hosts dct:source <https://github.com/HyperAgents/ns.hyperagents.org/issues/8#issuecomment-1025991719>
:hosts rdfs:isDefinedBy :core
:isHostedOn rdfs:isDefinedBy :core
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['OrganizationModel', 'proposesRole', 'proposesFacility', 'isHostedOn', 'Workspace', 'contains', 'isProfileOf', 'transitivelyContains', 'Membership', 'isMembershipOf', 'isMembershipIn', 'isMembershipFor', 'isSubGroupOf', '', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo', 'OrganizationModel', '']
Attempted to get embedding for empty text.
*** QUERY:  what is the resource profile of a given hypermedia mas platform?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:isHostedOn rdfs:range :HypermediaMASPlatform
:HypermediaMASPlatform rdfs:isDefinedBy :core
:hosts rdfs:domain :HypermediaMASPlatform

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what is a signifier for a fipa message transport service of a given platform?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :HypermediaMASPlatform skos:example "Examples of hmas:HypermediaMASPlatform include Twitter, Facebook, a JADE node/deployment, or a JaCaMo node/deployment — all of which provide features that could support Hypermedia MAS & hybrid communities."@en
:hosts rdfs:comment "A relation that refers to an information resource or a process (e.g., agent) that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts an information resource or a process."@en
:HypermediaMASPlatform rdfs:label "Platforme SMA"@fr
:HypermediaMASPlatform rdfs:label "MAS Platform"@en
:HypermediaMASPlatform rdfs:comment "A Hypermedia MAS platform is a system providing a collection of features to support Hypermedia MAS. Common features include support for communication and interaction, runtime environments for agents, artifacts, or organizations, etc."@en
:isHostedOn owl:inverseOf :hosts

*** GROUND TRUTH: ['HypermediaMASPlatform']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in a given resource profile?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:exposesSignifier rdfs:domain :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:isExposedIn rdfs:range :ResourceProfile
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en
:isExposedIn rdfs:domain :Signifier
:exposesSignifier rdfs:label "expose le signifiant"@fr
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:Signifier rdfs:label "Signifier"@en

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in resource profiles of artifacts contained in a given workspace?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:exposesSignifier rdfs:domain :ResourceProfile
:isExposedIn rdfs:range :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:isExposedIn rdfs:domain :Signifier
:Signifier rdfs:isDefinedBy :core
:Signifier rdfs:label "Signifier"@en
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the signifiers exposed in resource profiles of a given artifact?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :exposesSignifier rdfs:comment "A relation between a resource profile and a signifier it exposes."@en
:isExposedIn rdfs:comment "A relation between a signifier and a resource profile it is exposed in."@en
:exposesSignifier rdfs:domain :ResourceProfile
:isExposedIn rdfs:range :ResourceProfile
:exposesSignifier rdfs:label "exposes signifier"@en
:isExposedIn rdfs:domain :Signifier
:Signifier rdfs:comment "A perceivable sign/cue that can be interpreted meaningfully by an agent to reveal information about a behavior possibility."@en
:Signifier rdfs:label "Signifier"@en
:Affordance skos:editorialNote "The concept has been considered as a candidate term for representing interaction cues and metadata in the Hypermedia MAS Core Ontology. The term :Signifier is selected instead for the following reasons: 1) Affordances emerge upon the presence of individual agents in the appropriate situation, while signifiers are defined with respect to agent types to preserve the evolvability and reusability of interaction cues without requiring prior knowledge about individual agents; 2) Affordances are defined in [Chemero and Turvey, 2007] for studying interactions of animals, while signifiers are defined here for supporting interactions of autonomous agents, which exhibit more heterogeneous abilities than animals — including agents whose cognitive abilities exclusively rely on computational processes such as reasoning over representations. Here, the concept is provided to support the discussion, management, and modelling of signifiers, which reveal information about affordances [Norman, 2013]. For example, the association between the two terms enables examining the dynamic exposure of signifiers based on the run-time availability of agent abilities and situations, or the modelling of signifiers that reveal information about affordances for both artificial and human agents."@en
:exposesSignifier rdfs:label "expose le signifiant"@fr

*** GROUND TRUTH: ['Signifier', 'isExposedIn']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the set of norms ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :definesNorm rdfs:label "defines the norm"@en
:RegulativeNorm rdfs:label "Norm"@en
:enforcesNorm rdfs:label "enforces the norm"@en
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:obliges rdfs:domain :Norm
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:permits rdfs:domains :Norm
:NormativeContext rdfs:label "Normative Context"@en
:definesNorm rdfs:range :Norm
:hasNormativeObject rdfs:label "has normative object"
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:enforcesNorm rdfs:range :Norm
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:hasNormativeContext rdfs:range :NormativeContext

*** GROUND TRUTH: ['RegulativeNorm']
*** MODEL PREDICTION: ['Workspace', 'contains', '', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo', 'RegulativeNorm', 'definesNorm', 'enforcesNorm']
Attempted to get embedding for empty text.
*** QUERY:  who are the agents under the regulation of a norm ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:permits rdfs:domains :Norm
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:RegulativeNorm rdfs:label "Norm"@en
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:definesNorm rdfs:label "defines the norm"@en
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:AuthorityRole rdf:subClassOf <https://ci.mines-stetienne.fr/regulationSocialRole>
:enforcesNorm rdfs:domain <https://ci.mines-stetienne.fr/regulationOrganization>
<https://ci.mines-stetienne.fr/regulation#> rdf:type owl:Ontology
:obliges rdfs:domain :Norm

*** GROUND TRUTH: ['hasNormativeTarget']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the norms that have not been respected ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:enforcesNorm rdfs:label "enforces the norm"@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:prohibits rdfs:domain :Norm
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:definesNorm rdfs:label "defines the norm"@en
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:hasNormativeContext rdfs:range :NormativeContext
:hasNormativeContext rdfs:label "has normative context"@en
:NormativeContext rdfs:label "Normative Context"@en
:hasNormativeObject rdfs:label "has normative object"
:obliges rdfs:domain :Norm
:hasException rdfs:comment "Associates exceptions to a context of application of a norm"@en

*** GROUND TRUTH: ['hasRespectStatus']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what norms are activated in an organization w.r.t. a context ?
Data ingestion into MongoDB completed

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** RAG INFORMATION: :enforcesNorm rdfs:comment "An organization enforces a norm. "@en
:NormativeContext rdfs:comment "A context in which a norm is applicable"@en
:RegulativeNorm rdfs:comment "A specification of the standard behaviors one expects from others in an organization."@en
:definesNorm rdfs:comment "An organization Specification defines a norm. "@en
:AuthorityRole rdfs:comment "The authority who has a power to apply a norm and which is in charge of applying the norm. It may be an :Agent or an :Organization. "@en
:obliges rdfs:comment "An obligation is associated with a norm and describes a state of affairs that must be maintained when a norm is applied."@en
:NormativeContext rdfs:label "Normative Context"@en
:hasNormativeContext rdfs:label "has normative context"@en
:hasNormativeContext rdfs:comment "A specification which defines when a norm is applicable. "@en
:enforcesNorm rdfs:label "enforces the norm"@en
:hasNormativeTarget rdfs:comment "An agent or a group of agents concerned by a norm."
:permits rdfs:comment "A permission is associated with a norm and describes a state of affairs which is explicitly permitted when a norm is applied."@en
:hasRespectStatus rdfs:comment "Indicates whether a norm has been respected or not"@en
:hasNormativeContext rdfs:range :NormativeContext
:prohibits rdfs:comment "A prohibition is associated with a norm and describes a state of affairs that shouldn't be verified when a norm is applied. "@en
:definesNorm rdfs:label "defines the norm"@en

*** GROUND TRUTH: ['enforcesNorm', 'hasNormativeContext']
*** MODEL PREDICTION: ['OrganizationModel', 'hasOrganizationalGoal']
*************** INFERENCE COMPLETE ***************

In [23]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(rag_levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(rag_hits_k_avgs)
print("***** MRR@K *****")
print(rag_mrr_k_avgs)
print("***** MAP@K *****")
print(rag_map_k_avgs)
rag_eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.4515873015873016, 'coordinate-activities': 0.0, 'create-organization': 0.0, 'structure-organization': 0.0925925925925926, 'discover-behavior-specifications': 0.0, 'discover-core': 0.11111111111111112, 'discover-organization': 0.0, 'discover-platforms': 0.0, 'discover-signifiers': 0.0, 'safety-rules': 0.04545454545454544}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.3833333333333333, 'coordinate-activities': 0.38888888888888884, 'create-organization': 0.1259259259259259, 'structure-organization': 0.5285714285714286, 'discover-behavior-specifications': 0.0, 'discover-core': 0.42857142857142855, 'discover-organization': 0.5, 'discover-platforms': 0.125, 'discover-signifiers': 0.5, 'safety-rules': 0.5}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.275, 'coordinate-activities': 0.23148148148148148, 'create-organization': 0.1611111111111111, 'structure-organization': 0.42486772486772484, 'discover-behavior-specifications': 0.0, 'discover-core': 0.35714285714285715, 'discover-organization': 0.08333333333333333, 'discover-platforms': 0.375, 'discover-signifiers': 0.0, 'safety-rules': 0.25}
***** MAP@K *****
{'scenario-template': np.float64(0.0), 'configure-organization': np.float64(0.2321759259259259), 'coordinate-activities': np.float64(0.1280864197530864), 'create-organization': np.float64(0.06855771115030374), 'structure-organization': np.float64(0.19971115430299102), 'discover-behavior-specifications': np.float64(0.0), 'discover-core': np.float64(0.25), 'discover-organization': np.float64(0.041666666666666664), 'discover-platforms': np.float64(0.3125), 'discover-signifiers': np.float64(0.0), 'safety-rules': np.float64(0.25)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000  0.000000
1            0.888889  0.750000  0.625000  0.572917
2            0.000000  0.000000  0.000000  0.000000
3            0.333333  0.000000  0.000000  0.000000
4            0.285714  0.500000  0.250000  0.125000
5            0.750000  0.666667  0.500000  0.462963
6            0.000000  0.000000  0.000000  0.000000
7            0.000000  0.500000  0.250000  0.125000
8            0.000000  0.666667  0.444444  0.259259
9            0.000000  0.000000  0.000000  0.000000
10           0.000000  0.000000  0.000000  0.000000
11           0.000000  0.000000  0.000000  0.000000
12           0.000000  0.000000  0.000000  0.000000
13           0.000000  0.000000  0.000000  0.000000
14           0.000000  0.800000  0.700000  0.251279
15           0.000000  0.000000  0.000000  0.000000
16           0.000000  0.000000  0.250000  0.125000
17           0.000000  0.333333  0.500000  0.240741
18           0.000000  0.800000  0.700000  0.305556
19           0.555556  0.571429  0.404762  0.176045
20           0.000000  0.800000  0.666667  0.272222
21           0.000000  0.000000  0.000000  0.000000
22           0.000000  0.333333  0.111111  0.037037
23           0.000000  0.666667  0.666667  0.407407
24           0.000000  0.000000  0.000000  0.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.000000  0.000000  0.000000  0.000000
27           0.000000  0.000000  0.000000  0.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.444444  1.000000  0.750000  0.625000
30           0.000000  0.000000  0.250000  0.125000
31           0.000000  0.000000  0.250000  0.125000
32           0.000000  0.500000  0.250000  0.125000
33           0.000000  0.500000  0.250000  0.125000
34           0.333333  1.000000  0.750000  0.625000
35           0.000000  0.000000  0.000000  0.000000
36           0.000000  0.500000  0.000000  0.000000
37           0.000000  0.500000  0.000000  0.000000
38           0.000000  0.500000  0.250000  0.125000
39           0.000000  0.500000  0.500000  0.250000
40           0.000000  0.000000  1.000000  1.000000
41           0.000000  0.000000  0.000000  0.000000
42           0.000000  0.000000  0.000000  0.000000
43           0.000000  0.500000  0.000000  0.000000
44           0.000000  0.500000  0.000000  0.000000
45           0.000000  0.500000  0.000000  0.000000
46           0.181818  1.000000  0.000000  0.000000
47           0.000000  0.000000  0.000000  0.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.000000  1.000000  1.000000  1.000000

In [25]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [26]:
# experiment: FS prediction without RAG
eval_results, levenshtein_ratio_avgs, hits_k_avgs, mrr_k_avgs, map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='default')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?
*** SOURCE INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdfs:label "Class"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: []
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['Agent', 'Role', 'OrganizationalGoal', 'Facility', 'Workspace', 'ResourceProfile', 'proposesRole', 'hasOrganizationalGoal', 'proposesFacility', 'isProfileOf', 'isAccessFor', 'isAccessIn', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['Workspace', 'contains']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['Facility', 'hasFacility']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['Workspace', 'Artifact', 'Agent', 'OrganizationModel', 'OrganizationalGoal', 'Facility', 'Role', 'OrganizationalValue', 'contains', 'isProfileOf', 'isTransitivelyContainedIn', 'isStructuredBy', 'isMembershipOf', 'isMembershipIn', 'hasOrganizationalValue', 'hasOrganizationalGoal', 'proposesFacility', 'proposesRole']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :hasFacility rdfs:range :Facility
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdf:type owl:ObjectProperty
:isAccessIn rdfs:range :Setting
:isAccessIn rdf:type owl:ObjectProperty
:isAccessOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:label "has facility"@en
:isSettingOf rdfs:domain :Setting
:isAccessOf rdfs:label "est accès de"@fr
:hasFacility rdf:type owl:ObjectProperty
:isAccessOf rdfs:range :Agent
:proposesSetting rdfs:isDefinedBy :regulation
:Access rdfs:isDefinedBy :regulation
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:label "est accès dans"@fr
:proposesSetting rdfs:label "fournit contexte d'usage"@fr
:Setting rdf:type owl:Class
:isAccessTo rdfs:isDefinedBy :regulation
:isAccessTo rdfs:label "is access to"@en
:isAccessIn rdfs:label "is access in"@en
:proposesSetting rdfs:domain :Organization
:isAccessFor rdfs:label "is access for"@en
:isAccessFor rdfs:label "est accès pour"@fr
:hasFacility rdfs:domain :Artifact
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:isAccessTo rdfs:domain :Access
:isAccessOf rdf:type owl:ObjectProperty
:isAccessFor rdfs:domain :Access
:Setting rdfs:label "contexte d'accès"@fr
:proposesSetting rdfs:label "proposes setting"@en
:isAccessFor rdfs:isDefinedBy :regulation
:isAccessIn rdfs:domain :Access
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:proposesSetting rdfs:range :Setting
:isAccessFor rdfs:range :Facility
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessTo rdfs:label "est accès à"@fr
:proposesSetting rdf:type owl:ObjectProperty
:isAccessOf rdfs:label "is access of"@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:isDefinedBy :regulation
:Access rdfs:label "access"@en
:Access rdf:type owl:Class
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:isSettingOf rdfs:label "is setting of"@en
:isSettingOf rdfs:label "est contexte d'usage de"@fr
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:range :Artifact
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:Setting rdfs:label "setting"@en
:isAccessFor rdf:type owl:ObjectProperty
:isAccessOf rdfs:domain :Access
:isAccessTo rdf:type owl:ObjectProperty
:hasFacility rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['Facility', 'Setting', 'Access', 'Organization', 'Agent', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed
*** SOURCE INFORMATION: :Mission rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:isDefinedBy :regulation
:includesMission rdfs:domain :Process
:Process rdfs:isDefinedBy :regulation
:includesMission rdfs:range :Mission
:Mission rdfs:label "mission"@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:Mission rdfs:label "mission"@fr
:isCommitmentOf rdfs:domain :Commitment
:includesMission rdfs:label "inclut la mission"@fr
:includesOrganizationalGoal rdf:type owl:ObjectProperty
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Commitment rdf:type owl:Class
:Mission rdf:type owl:Class
:Process rdfs:label "processus"@fr
:proposesProcess rdfs:label "fournit un processus"@fr
:proposesProcess rdf:type owl:ObjectProperty
:includesMission rdfs:label "includes mission"@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdf:type owl:ObjectProperty
:Process rdf:type owl:Class
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isCommitmentOf rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "is commitment for"@en
:proposesProcess rdfs:range :Process
:isCommitmentOf rdfs:label "is commitment of"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isCommitmentOf rdfs:range :Agent
:Commitment rdfs:label "commitment"@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:label "proposes process"@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdf:type owl:ObjectProperty
:includesOrganizationalGoal rdfs:domain :Mission
:isCommitmentFor rdfs:range :Mission
:isCommitmentOf rdf:type owl:ObjectProperty
:includesMission rdfs:isDefinedBy :regulation
:Commitment rdfs:label "engagement"@fr
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:Process rdfs:label "process"@en
:proposesProcess rdfs:isDefinedBy :regulation
:isCommitmentFor rdfs:label "est engagement pour"@fr

In [27]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(hits_k_avgs)
print("***** MRR@K *****")
print(mrr_k_avgs)
print("***** MAP@K *****")
print(map_k_avgs)
eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.30392156862745096, 'coordinate-activities': 0.0625, 'create-organization': 0.2202020202020202, 'structure-organization': 0.31666666666666665, 'discover-behavior-specifications': 0.08, 'discover-core': 0.3196825396825397, 'discover-organization': 0.11111111111111112, 'discover-platforms': 0.4166666666666667, 'discover-signifiers': 0.0, 'safety-rules': 0.1138888888888889}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.75, 'coordinate-activities': 0.8888888888888888, 'create-organization': 0.5555555555555556, 'structure-organization': 0.7984126984126984, 'discover-behavior-specifications': 0.2, 'discover-core': 0.7857142857142857, 'discover-organization': 0.6666666666666666, 'discover-platforms': 0.5, 'discover-signifiers': 1.0, 'safety-rules': 0.5}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.6375, 'coordinate-activities': 1.0, 'create-organization': 0.7777777777777778, 'structure-organization': 0.6743386243386243, 'discover-behavior-specifications': 0.2, 'discover-core': 0.6428571428571429, 'discover-organization': 0.5833333333333334, 'discover-platforms': 0.75, 'discover-signifiers': 0.5, 'safety-rules': 0.5}
***** MAP@K *****
{'scenario-template': np.float64(nan), 'configure-organization': np.float64(0.501736111111111), 'coordinate-activities': np.float64(0.7314814814814815), 'create-organization': np.float64(0.7066186556927297), 'structure-organization': np.float64(0.3460114998380304), 'discover-behavior-specifications': np.float64(0.2), 'discover-core': np.float64(0.5), 'discover-organization': np.float64(0.5416666666666666), 'discover-platforms': np.float64(0.75), 'discover-signifiers': np.float64(0.25), 'safety-rules': np.float64(0.5)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000       NaN
1            0.352941  0.750000  0.687500  0.369792
2            0.000000  1.000000  0.000000  0.000000
3            0.666667  0.000000  1.000000  1.000000
4            0.000000  1.000000  0.500000  0.250000
5            0.500000  1.000000  1.000000  0.888889
6            0.000000  1.000000  1.000000  1.000000
7            0.000000  1.000000  1.000000  0.750000
8            0.187500  0.666667  1.000000  0.444444
9            0.000000  1.000000  1.000000  1.000000
10           0.333333  1.000000  1.000000  1.000000
11           0.000000  1.000000  1.000000  1.000000
12           0.000000  0.000000  1.000000  1.000000
13           0.666667  0.000000  1.000000  1.000000
14           0.181818  0.500000  0.500000  0.220679
15           0.000000  0.500000  0.250000  0.194444
16           0.000000  0.500000  0.500000  0.250000
17           0.800000  0.500000  0.750000  0.694444
18           0.000000  0.600000  0.800000  0.336111
19           0.500000  0.857143  0.690476  0.351069
20           0.555556  1.000000  0.722222  0.212963
21           0.200000  1.000000  0.500000  0.250000
22           0.200000  1.000000  0.666667  0.518519
23           0.444444  0.333333  0.666667  0.407407
24           0.400000  1.000000  1.000000  1.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.000000  0.000000  0.000000  0.000000
27           0.000000  0.000000  0.000000  0.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.500000  0.500000  0.750000  0.625000
30           0.400000  1.000000  0.750000  0.625000
31           0.160000  0.500000  0.750000  0.625000
32           0.400000  1.000000  0.750000  0.375000
33           0.000000  1.000000  0.000000  0.000000
34           0.444444  0.500000  0.750000  0.625000
35           0.333333  1.000000  0.750000  0.625000
36           0.333333  1.000000  1.000000  1.000000
37           0.000000  0.500000  0.500000  0.500000
38           0.000000  0.500000  0.250000  0.125000
39           1.000000  1.000000  1.000000  1.000000
40           0.000000  0.000000  0.000000  0.000000
41           0.000000  0.000000  1.000000  1.000000
42           0.666667  1.000000  1.000000  1.000000
43           0.000000  1.000000  0.750000  0.375000
44           0.000000  1.000000  0.000000  0.000000
45           0.000000  1.000000  0.750000  0.375000
46           0.055556  1.000000  0.000000  0.000000
47           0.000000  0.000000  1.000000  1.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.400000  1.000000  1.000000  1.000000

In [28]:
# experiment: FS prediction with RAG
rag_eval_results, rag_levenshtein_ratio_avgs, rag_hits_k_avgs, rag_mrr_k_avgs, rag_map_k_avgs = infer_from_ontology(hmas_df, model, tokenizer, mode='rag')

Connection to MongoDB successful
Attempted to get embedding for empty text.
Data ingestion into MongoDB completed
Attempted to get embedding for empty text.
*** QUERY:  what are the instances of the example class?
*** RAG INFORMATION: ex:Class rdfs:comment "Example class for testing purposes"
ex:Class rdf:type owl:Class

*** GROUND TRUTH: ['ex:Class']
*** MODEL PREDICTION: ['', 'hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the artifacts that an agent of the organization x has access to in the setting y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:hasFacility rdfs:domain :Artifact
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:isSettingOf rdfs:range :Organization
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isAccessIn rdfs:label "is access in"@en
:isAccessTo rdfs:label "is access to"@en
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "contexte d'accès"@fr

*** GROUND TRUTH: ['hasFacility', 'isAccessIn', 'isAccessFor', 'isAccessTo']
*** MODEL PREDICTION: ['OrganizationModel', 'Organization', 'Facility', 'Role', 'Agent', 'Workspace', 'ResourceProfile', 'Group', 'Membership', 'proposesFacility', 'proposesRole', 'hasOrganizationalGoal', 'hasOrganizationalValue', 'isAccessIn', 'isAccessFor', 'isAccessTo']
Attempted to get embedding for empty text.
*** QUERY:  what are the settings of an organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :proposesSetting rdfs:domain :Organization
:proposesSetting rdfs:comment "A relation that refers to a Setting that can be used in the context of an Organization."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:isSettingOf rdfs:range :Organization
:isSettingOf rdfs:domain :Setting
:Setting rdfs:label "setting"@en
:Setting rdfs:comment "A Setting is the context in which an Access is set."@en
:Setting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:isDefinedBy :regulation
:proposesSetting rdfs:label "proposes setting"@en
:proposesSetting rdfs:range :Setting
:isSettingOf rdfs:label "is setting of"@en
:isAccessIn rdfs:range :Setting
:isAccessIn rdfs:comment "A relation that refers to a Setting involved in an Access."@en
:isAccessIn rdfs:isDefinedBy :regulation
:hasFacility rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['proposesSetting']
*** MODEL PREDICTION: ['Agent', 'Facility', 'Role', 'Workspace', 'Organization', 'Group', 'Membership', 'proposesFacility', 'proposesRole', 'hasOrganizationalGoal', 'hasOrganizationalValue', 'isAccessIn', 'isAccessTo', 'isSubGroupOf', 'isMembershipOf', 'isMembershipFor', 'isStructuredBy']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that the artifact x have?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :hasFacility rdfs:domain :Artifact
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:isAccessTo rdfs:range :Artifact
:hasFacility rdfs:range :Facility
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:hasFacility rdfs:label "has facility"@en
:isAccessFor rdfs:range :Facility
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:label "a pour potentialité d'usage"@fr
:Access rdfs:label "accès"@fr
:Setting rdfs:label "contexte d'accès"@fr
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:proposesSetting rdfs:domain :Organization
:isAccessIn rdfs:label "est accès dans"@fr

*** GROUND TRUTH: ['hasFacility']
*** MODEL PREDICTION: ['Facility', 'proposesFacility', 'proposesRole', 'proposesSetting']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents currently in the setting y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :isAccessOf rdfs:range :Agent
:isAccessOf rdfs:comment "A relation that refers to an Agent involved in an Access."@en
:isSettingOf rdfs:range :Organization
:hasFacility rdfs:range :Facility
:isSettingOf rdfs:domain :Setting
:Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:isSettingOf rdfs:comment "A relation that refers to a Setting of an Organization."@en
:hasFacility rdfs:isDefinedBy :regulation
:isAccessIn rdfs:isDefinedBy :regulation
:proposesSetting rdfs:domain :Organization
:isSettingOf rdfs:isDefinedBy :regulation
:hasFacility rdfs:domain :Artifact
:Access rdfs:isDefinedBy :regulation
:isAccessIn rdfs:label "est accès dans"@fr
:isAccessTo rdfs:isDefinedBy :regulation
:Setting rdfs:isDefinedBy :regulation

*** GROUND TRUTH: ['isAccessIn', 'isAccessOf']
*** MODEL PREDICTION: ['OrganizationModel', 'Organization', 'OrganizationalGoal', 'OrganizationalValue', 'Role', 'Facility', 'Agent', 'Workspace', 'ResourceProfile', 'proposesFacility', 'proposesRole', 'proposesOrganizationalGoal', 'hasOrganizationalValue', 'hasOrganizationalGoal', 'isSettingOf', 'isAccessOf', 'isAccessIn', 'isTransitivelyContainedIn', 'isProfileOf', 'isContainedIn', 'isStructuredBy']
Attempted to get embedding for empty text.
*** QUERY:  what are the facilities that artifact x has in each access?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Access rdfs:comment "An opportunity an Agent has to use Facilities of Artifacts in a Setting. Agents have access even if they never use these Facilities. One Access should not be understood as one 'use' of these Facilities."@en
:hasFacility rdfs:domain :Artifact
:isAccessTo rdfs:range :Artifact
:hasFacility rdfs:comment "A relation that refers to a Facility of an Artifact."@en
:hasFacility rdfs:range :Facility
:isAccessTo rdfs:comment "A relation that refers to an Artifact involved in an Access."@en
:isAccessFor rdfs:comment "A relation that refers to a Facility involved in an Access."@en
:isAccessFor rdfs:range :Facility
:hasFacility rdfs:label "has facility"@en
:Access rdfs:label "access"@en
:Access rdfs:label "accès"@fr
:isAccessIn rdfs:domain :Access
:isAccessFor rdfs:domain :Access
:isAccessOf rdfs:domain :Access
:isAccessFor rdfs:label "is access for"@en
:isAccessIn rdfs:label "is access in"@en

*** GROUND TRUTH: ['hasFacility', 'isAccessTo', 'isAccessFor']
*** MODEL PREDICTION: ['Workspace', 'Artifact', 'Agent', 'OrganizationModel', 'OrganizationalValue', 'OrganizationalGoal', 'Role', 'Facility', 'contains', 'isProfileOf', 'isTransitivelyContainedIn', 'isStructuredBy', 'isMembershipOf', 'isMembershipFor', 'isMembershipRelationshipWith', 'hasOrganizationalValue', 'hasOrganizationalGoal', 'proposesFacility', 'proposesRole']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals and subgoals an agent has to achieve because it commits to the mission z in the organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:domain :Mission
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isCommitmentFor rdfs:comment "A relation that refers to a commitment for a Mission."@en
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:isCommitmentOf rdfs:comment "A relation that refers to a commitment of an Agent."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isCommitmentFor rdfs:range :Mission

*** GROUND TRUTH: ['includesOrganizationalGoal']
*** MODEL PREDICTION: ['OrganizationalGoal', 'Mission', 'Commitment', 'OrganizationalValue', 'Role', 'Facility', 'Agent', 'includesOrganizationalGoal', 'isDependentOnOrganizationalGoal', 'isCommitmentFor', 'proposesFacility', 'proposesRole', 'hasOrganizationalValue', 'hasOrganizationalGoal']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational goals in process z proposed by the organization x and how these organizational goals are dependent on each other?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr
:proposesProcess rdfs:domain :Organization
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:isDefinedBy :regulation
:includesOrganizationalGoal rdfs:range :OrganizationalGoal

*** GROUND TRUTH: ['includesMission', 'includesOrganizationalGoal']
*** MODEL PREDICTION: ['OrganizationModel', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the agents responsible for fulfilling the organizational goals of process y in the organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :Mission rdfs:comment "A set of duties that Agents can commit to for achieving Organizational Goals."@en
:isDependentOnOrganizationalGoal rdfs:label "is dependent on organizational goal"@en
:includesOrganizationalGoal rdfs:label "includes organizational goal"@en
:includesOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal involved in a Mission."@en
:proposesProcess rdfs:comment "A relation that refers to a Process that can be executed in the context of an Organization. "@en
:isDependentOnOrganizationalGoal rdfs:comment "A relation that refers to the way in which two Organizational Goals are related to each other, and one is affected by the other."@en
:isDependentOnOrganizationalGoal rdfs:domain :OrganizationalGoal
:Process rdfs:comment "A plan specified as a set of Missions to be executed by several coordinating Agents."@en
:proposesProcess rdfs:domain :Organization
:includesOrganizationalGoal rdfs:domain :Mission
:includesOrganizationalGoal rdfs:label "inclut le but de l'organization"@fr
:isDependentOnOrganizationalGoal rdfs:range :OrganizationalGoal
:Commitment rdfs:comment "An engagement of an Agent with the duties of a Mission."@en
:includesOrganizationalGoal rdfs:range :OrganizationalGoal
:isDependentOnOrganizationalGoal rdfs:label "dépend du but de l'organisation"@fr

*** GROUND TRUTH: ['includesMission', 'isCommitmentOf', 'isCommitmentFor']
*** MODEL PREDICTION: ['Agent', 'Facility', 'proposesProcess', 'includesOrganizationalGoal', 'commitment']
Attempted to get embedding for empty text.
*** QUERY:  what is the organization x's organization model that can be used to create a new organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:proposesRole rdfs:domain :Organization
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['OrganizationModel', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations that follow a different organization model than organization x?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:domain :Organization
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['Facility', 'proposesFacility']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizations with the same organization model as the organization x and situated on y?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:related :Organization
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:hasOrganizationalGoal rdfs:domain :Organization
:OrganizationModel rdf:type skos:Concept
:hasOrganizationalGoal rdfs:comment "A relation that refers to an Organizational Goal of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalGoal rdfs:label "has organizational goal"@en
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:OrganizationalGoal rdfs:label "but organisationnel"@fr
:proposesFacility rdfs:domain :Organization

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['OrganizationModel', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the available organization models that can be used to create a new organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationModel skos:prefLabel "organization model"@en
:OrganizationModel skos:related :Organization
:OrganizationModel skos:editorialNote "The Organization Model is represented as SHACL Shapes."@en
:OrganizationModel rdf:type skos:Concept
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:hasOrganizationalGoal rdfs:domain :Organization
:proposesFacility rdfs:domain :Organization
:hasOrganizationalGoal rdfs:range :OrganizationalGoal
:hasOrganizationalValue rdfs:domain :Organization
:proposesRole rdfs:domain :Organization
:OrganizationalGoal rdf:type owl:Class
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:hasOrganizationalGoal rdfs:label "a un but organisationnel"@fr
:hasOrganizationalGoal rdfs:label "has organizational goal"@en

*** GROUND TRUTH: ['OrganizationModel']
*** MODEL PREDICTION: ['OrganizationModel', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the organizational values of a given organization?
Data ingestion into MongoDB completed
*** RAG INFORMATION: :OrganizationalValue rdfs:comment "An Organizational Value is a belief about socially or personally desirable end state or action that are explicitly or implicitly shared by members of an Organization."@en
:OrganizationalValue rdfs:label "organizational value"@en
:hasOrganizationalValue rdfs:label "has organizational value"@en
:hasOrganizationalValue rdfs:comment "A relation that refers to an Organization Value of an Organization."@en
:hasOrganizationalValue rdfs:domain :Organization
:hasOrganizationalValue rdfs:label "a une valeur organisationnelle"@fr
:OrganizationModel skos:related :Organization
:OrganizationalValue rdf:type owl:Class
:hasOrganizationalValue rdfs:range :OrganizationalValue
:OrganizationalGoal rdfs:comment "An Organizational Goal is a pursued state of affairs."@en
:OrganizationalValue rdfs:label "valeur organisationnelle"@fr
:OrganizationalGoal rdfs:label "organizational goal"@en
:OrganizationModel skos:definition "An Organization Model is the combination of Roles, Organizational Goals, and Facilities in a consistent way used to enact one or multiple Organizations."@en
:OrganizationModel skos:prefLabel "organization model"@en

*** GROUND TRUTH: ['hasOrganizationalValue']
*** MODEL PREDICTION: ['OrganizationModel', 'proposesFacility', 'proposesRole', 'hasOrganizationalGoal', 'hasOrganizationalValue', 'OrganizationalValue', 'OrganizationalGoal', '']
Attempted to get embedding for empty text.
*** QUERY:  what are the elements composing a given organization model?
Data ingestion into MongoDB completed

In [29]:
# output results
print("***** LEVENSHTEIN RATIO *****")
print(rag_levenshtein_ratio_avgs)
print("***** HITS@K *****")
print(rag_hits_k_avgs)
print("***** MRR@K *****")
print(rag_mrr_k_avgs)
print("***** MAP@K *****")
print(rag_map_k_avgs)
rag_eval_results

***** LEVENSHTEIN RATIO *****
{'scenario-template': 0.0, 'configure-organization': 0.09478260869565218, 'coordinate-activities': 0.04444444444444443, 'create-organization': 0.5326278659611994, 'structure-organization': 0.30198412698412697, 'discover-behavior-specifications': 0.07333333333333332, 'discover-core': 0.3009523809523809, 'discover-organization': 0.055555555555555546, 'discover-platforms': 0.0, 'discover-signifiers': 0.0, 'safety-rules': 0.07692307692307693}
***** HITS@K *****
{'scenario-template': 0.0, 'configure-organization': 0.55, 'coordinate-activities': 0.8333333333333334, 'create-organization': 0.7777777777777778, 'structure-organization': 0.7817460317460317, 'discover-behavior-specifications': 0.2, 'discover-core': 0.7857142857142857, 'discover-organization': 0.6666666666666666, 'discover-platforms': 0.125, 'discover-signifiers': 0.6666666666666666, 'safety-rules': 0.5}
***** MRR@K *****
{'scenario-template': 0.0, 'configure-organization': 0.5333333333333333, 'coordinate-activities': 0.7037037037037037, 'create-organization': 0.8055555555555556, 'structure-organization': 0.6263227513227513, 'discover-behavior-specifications': 0.6, 'discover-core': 0.6428571428571429, 'discover-organization': 0.8333333333333334, 'discover-platforms': 0.9375, 'discover-signifiers': 0.3333333333333333, 'safety-rules': 0.75}
***** MAP@K *****
{'scenario-template': np.float64(0.0), 'configure-organization': np.float64(0.39282407407407405), 'coordinate-activities': np.float64(0.5339506172839507), 'create-organization': np.float64(0.7184224965706447), 'structure-organization': np.float64(0.34298041968109994), 'discover-behavior-specifications': np.float64(0.6), 'discover-core': np.float64(0.4642857142857143), 'discover-organization': np.float64(0.8333333333333334), 'discover-platforms': np.float64(0.84375), 'discover-signifiers': np.float64(0.3333333333333333), 'safety-rules': np.float64(0.75)}

    levenshtein_ratio    hits@k     mrr@k     map@k
0            0.000000  0.000000  0.000000  0.000000
1            0.300000  0.750000  0.500000  0.343750
2            0.000000  0.000000  0.000000  0.000000
3            0.000000  0.000000  1.000000  1.000000
4            0.173913  1.000000  0.500000  0.250000
5            0.000000  1.000000  0.666667  0.370370
6            0.133333  1.000000  1.000000  1.000000
7            0.000000  0.500000  0.500000  0.250000
8            0.000000  1.000000  0.611111  0.351852
9            0.666667  1.000000  1.000000  1.000000
10           0.000000  0.000000  0.000000  0.000000
11           0.666667  1.000000  1.000000  1.000000
12           0.666667  1.000000  1.000000  1.000000
13           0.222222  0.000000  1.000000  1.000000
14           0.714286  1.000000  0.666667  0.377840
15           0.500000  1.000000  1.000000  0.777778
16           0.500000  1.000000  0.750000  0.625000
17           0.857143  1.000000  0.833333  0.685185
18           0.500000  0.833333  0.722222  0.406481
19           0.750000  0.857143  0.785714  0.487512
20           0.428571  0.833333  0.833333  0.316667
21           0.000000  0.500000  0.250000  0.125000
22           0.133333  1.000000  0.500000  0.314815
23           0.000000  0.666667  0.666667  0.407407
24           0.000000  1.000000  1.000000  1.000000
25           0.000000  0.000000  0.000000  0.000000
26           0.200000  0.000000  1.000000  1.000000
27           0.166667  0.000000  1.000000  1.000000
28           0.000000  0.000000  0.000000  0.000000
29           0.160000  0.500000  0.750000  0.625000
30           0.066667  0.500000  0.750000  0.625000
31           0.400000  0.500000  0.750000  0.625000
32           0.500000  1.000000  1.000000  0.500000
33           0.400000  1.000000  0.250000  0.125000
34           0.500000  1.000000  0.750000  0.625000
35           0.080000  1.000000  0.250000  0.125000
36           0.166667  1.000000  1.000000  1.000000
37           0.000000  0.500000  1.000000  1.000000
38           0.000000  0.500000  0.500000  0.500000
39           0.000000  0.500000  0.750000  0.375000
40           0.000000  0.000000  1.000000  1.000000
41           0.000000  0.000000  1.000000  1.000000
42           0.000000  0.000000  1.000000  1.000000
43           0.000000  0.500000  0.000000  0.000000
44           0.000000  1.000000  1.000000  1.000000
45           0.000000  0.500000  0.000000  0.000000
46           0.000000  1.000000  1.000000  1.000000
47           0.000000  0.000000  1.000000  1.000000
48           0.000000  0.000000  0.000000  0.000000
49           0.307692  1.000000  1.000000  1.000000

In [30]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)