In [1]:
'''
task: classify syllogism validity with CLINGO notation
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: pfolio
evaluation: zero-shot + sef category
'''
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 152.7 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.4.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)

In [3]:
import pandas as pd

pfolio_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/p-folio/data/pfolio_kr_gold_train_sef.csv")

In [4]:
# evaluation metrics

import numpy as np
import re
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

def predict_answer(model, tokenizer, obj, subject, sef, ref_relation=None, source_knowledge=None):
  # define sef categories
  sef_disjunctive = r"""
  A disjunctive syllogism contains "∨" or "⊕". Here is an example:
  <PREMISES>forall (kid(x) -: young(x))
forall (toddler(x) -: kid(x))
forall (young(x) -: notelderly(x))
forall (pirate(x) -: seafarer(x))
notpirate(nancy) -: young(nancy)
nottoddler(nancy) -: seafarer(nancy)</PREMISES>
  <CONCLUSION>not(pirate(nancy) ^ toddler(nancy))</CONCLUSION>
  """

  sef_complex = r"""
  A complex syllogism has more than 2 premises. Here is an example:
  <PREMISES>woncup(aberdeen, year2013final)
woncup(rangers, year2014final)
not(aberdeen=rangers)
forall forall forall forall (not(x=y) , woncup(x, z) , woncup(y, w) -: not(z=w))</PREMISES>
  <CONCLUSION>exists x (woncup(aberdeen, x))</CONCLUSION>
  """

  sef_categorical = r"""
  A categorical syllogism contains any word from the list ["all", "any", "some", "no", "few", "most", "none", "several"]. Here is an example:
  <PREMISES>unincorporatedcommunity(ordinary)
locatedin(ordinary, elliotcounty) , on(ordinary, kentuckyroute32)
locatednorthwestof(ordinary, sandyhook)</PREMISES>
  <CONCLUSION>(unincorporatedcommunity(x) , locatedin(x, elliotcounty))</CONCLUSION>
  """

  sef_hypothetical = r"""
  A hypothetical syllogism is not disjunctive, complex or categorical. Here is an example:
  <PREMISES>forall (homework(x) -: notfun(x))
 (reading(x) , homework(x))</PREMISES>
  <CONCLUSION>(reading(x) , fun(x))</CONCLUSION>
  """

  sef_categories = dict()
  sef_categories["disjunctive"] = sef_disjunctive
  sef_categories["complex"] = sef_complex
  sef_categories["categorical"] = sef_categorical
  sef_categories["hypothetical"] = sef_hypothetical


  # define notation grammar
  grammar = r"""
    start: program
    program: [stat]+
    stat: proposition newline | keyword* quantifier* symbol* leftparen* (quantifier symbol)* proposition rightparen* newline | keyword* (quantifier symbol)* leftparen* (quantifier symbol)* proposition rightparen* newline
    proposition: atomicproposition | complexproposition
    complexproposition: keyword* proposition keyword leftparen* (quantifier symbol)* proposition rightparen*
    atomicproposition: leftparen* term* leftparen* term* rightparen*
    !term: (LETTER+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠")* | (DIGIT+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠")*
    !leftparen: "("
    !rightparen: ")"
    !keyword: "," | "not" | "-:" | "|" | "^"
    !quantifier: "forall"
    symbol: LETTER
    newline: /\n/

    %import common.LETTER
    %import common.DIGIT
    %import common.INT -> NUMBER
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS
"""

  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert logician. You are given a syllogism in CLINGO with premises between <PREMISES></PREMISES> and conclusion between <CONCLUSION></CONCLUSION> tags.
  The CLINGO BNF grammar to understand and reason in the language is given in the <GRAMMAR></GRAMMAR> tags.
  <GRAMMAR>{grammar}</GRAMMAR>
  <PREMISES>{subject}</PREMISES>
  <CONCLUSION>{obj}</CONCLUSION>
  You are also given the category of the syllogism to help you understand it: {sef_categories[sef]}.
  Classify the conclusion as "T" if true, "F" if false or "U" if uncertain based on the premises. Present your answer only between <output></output> tags.
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  predicted_relation = tokenizer.decode(response[0])
  matches = re.findall('<output>(.*)</output>', predicted_relation, flags=re.DOTALL)
  res = re.findall(r"<output>(.*)", matches[-1])  # from ['</output> tags.\n  <end_of_turn>\n  <start_of_turn>model\n  <output>T'] to ['T']
  predicted_label = res[0] if res else "None" # take first element from list ['T'] to get 'T'

  print("*** Premises: \n", subject)
  print("*** Conclusion: \n", obj)
  print("*** True Label: \n", ref_relation)
  print("*** Predicted Label: \n", predicted_label)
  return predicted_label

In [5]:
def infer_from_ontology(dataset, model, tokenizer, mode='default', notation='NL'):
  evaluation_metrics_df = pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1"])
  reference_labels = []
  predicted_labels = []
  for index, row in dataset.iterrows():
      conclusion = row["Conclusions - " + notation]
      premises = row["Premises - " + notation]
      sef_category = row["sef"]
      label = row["Truth Values"]
      if mode.lower() == "grammar":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        source_information = """BNF GRAMMAR"""
        print("*** RAG INFORMATION:", source_information)
      # predict answer with model
      predicted_label = predict_answer(model, tokenizer, conclusion, premises, sef_category, label)
      reference_labels.append(label)
      predicted_labels.append(predicted_label)
  # fill evaluation metrics dataframe
  accuracy_metric = accuracy_score(reference_labels, predicted_labels)
  precision_metric = precision_score(reference_labels, predicted_labels, average="macro")
  recall_metric = recall_score(reference_labels, predicted_labels, average="macro")
  f1_metric = f1_score(reference_labels, predicted_labels, average="macro")
  evaluation_metrics_df["Accuracy"] = [accuracy_metric]
  evaluation_metrics_df["Precision"] = [precision_metric]
  evaluation_metrics_df["Recall"] = [recall_metric]
  evaluation_metrics_df["F1"] = [f1_metric]
  print("Classification Report:", classification_report(reference_labels, predicted_labels))
  print("*************** INFERENCE COMPLETE ***************")
  return reference_labels, predicted_labels, evaluation_metrics_df, accuracy_metric, precision_metric, recall_metric, f1_metric

In [6]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [7]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [10]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLINGO')

*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 has(mary, flu)
forall (has(x, flu) -: has(x, influenza))
nothas(susan, influenza)
*** Conclusion:
 has(mary, influenza) ^ has(susan, influenza)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (in(butte, x) , in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (city(pierre) , in(pierre, x) , city(bismarck) , in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
 city(missoula) , in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
  (soccerteam(x) , holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 notwakesup(thehulk) -: nothappy(thor)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 happy(thor) -: wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 nothappy(thor) -: notbreaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 notin(boves, europe)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
   (czech(x) , publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall (choralconductor(x) -: notspecializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 notlivein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notsetin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notworkedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (notin(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall ((water(x) , from(x, crotonriverwatershed)) -: (flowsto(x, y) , in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall (water(x) , from(x, crotonriver) -: flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (form(x, system7) , formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (single(x) , release(system7, x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
 notband(system7)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
  (museumship(x) , opentopublic(x) , servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 notlastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 (elephantopus(x) , in(x,africa) , elephantopus(y) , in(y,africa))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: notnativeto(x, southeasternunitedstates))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: traditionalmedicine(x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:


In [11]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.46511627906976744
***** PRECISION *****
0.4221821099077417
***** RECALL *****
0.42448720994693906
***** F1 *****
0.34387042876007223

   Accuracy  Precision    Recall       F1
0  0.465116   0.422182  0.424487  0.34387

In [13]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [14]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLINGO')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 has(mary, flu)
forall (has(x, flu) -: has(x, influenza))
nothas(susan, influenza)
*** Conclusion:
 has(mary, influenza) ^ has(susan, influenza)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (in(butte, x) , in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (city(pierre) , in(pierre, x) , city(bismarck) , in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
 city(missoula) , in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
  (soccerteam(x) , holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 notwakesup(thehulk) -: nothappy(thor)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 happy(thor) -: wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 nothappy(thor) -: notbreaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 notin(boves, europe)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
   (czech(x) , publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall (choralconductor(x) -: notspecializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 notlivein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notsetin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notworkedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (notin(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall ((water(x) , from(x, crotonriverwatershed)) -: (flowsto(x, y) , in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall (water(x) , from(x, crotonriver) -: flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (form(x, system7) , formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (single(x) , release(system7, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
 notband(system7)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
  (museumship(x) , opentopublic(x) , servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 notlastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 (elephantopus(x) , in(x,africa) , elephantopus(y) , in(y,africa))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: notnativeto(x, southeasternunitedstates))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: traditionalmedicine(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) , named(dagfinnaarskog, namedagfinn) , notableperson(dagfinnaarskog) , named(dagfinnbakke, namedagfinn) , notableperson(dagfinnbakke)  , named(dagfinndahl, namedagfinn) , notableperson(dagfinndahl)
norwegian(dagfinnaarskog) , physician(dagfinnaarskog)
norwegian(dagfinndahl) , barrister(dagfinndahl)
*** Conclusion:
 notableperson(dagfinnaarskog)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) , named(dagfinnaarskog, namedagfinn) , notableperson(dagfinnaarskog) , named(dagfinnbakke, namedagfinn) , notableperson(dagfinnbakke)  , named(dagfinndahl, namedagfinn) , notableperson(dagfinndahl)
norwegian(dagfinnaarskog) , physician(dagfinnaarskog)
norwegian(dagfinndahl) , barrister(dagfinndahl)
*** Conclusion:
 named(dagfinnaarskog, namedagfinn)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) , named(dagfinnaarskog, namedagfinn) , notableperson(dagfinnaarskog) , named(dagfinnbakke, namedagfinn) , notableperson(dagfinnbakke)  , named(dagfinndahl, namedagfinn) , notableperson(dagfinndahl)
norwegian(dagfinnaarskog) , physician(dagfinnaarskog)
norwegian(dagfinndahl) , barrister(dagfinndahl)
*** Conclusion:
 norwegian(dagfinndahl) , physician(dagfinndahl)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) , from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) , ((family(x) , named(x, nameo'dell) , (not(x=y)) , family(y) , named(y, nameo'dell))
named(amyodell, nameodell) , notableperson(amyodell) , named(jackodell, nameodell) , notableperson(jackodell) , named(matsodell, nameodell) , notableperson(matsodell)
british(amyodell) , singer(amyodell) , songwriter(amyodell)
english(jackodell) , toyinventor(jackodell)
*** Conclusion:
 notableperson(jackodell)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) , from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) , ((family(x) , named(x, nameo'dell) , (not(x=y)) , family(y) , named(y, nameo'dell))
named(amyodell, nameodell) , notableperson(amyodell) , named(jackodell, nameodell) , notableperson(jackodell) , named(matsodell, nameodell) , notableperson(matsodell)
british(amyodell) , singer(amyodell) , songwriter(amyodell)
english(jackodell) , toyinventor(jackodell)
*** Conclusion:
 named(amyodell, nameodell)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) , from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) , ((family(x) , named(x, nameo'dell) , (not(x=y)) , family(y) , named(y, nameo'dell))
named(amyodell, nameodell) , notableperson(amyodell) , named(jackodell, nameodell) , notableperson(jackodell) , named(matsodell, nameodell) , notableperson(matsodell)
british(amyodell) , singer(amyodell) , songwriter(amyodell)
english(jackodell) , toyinventor(jackodell)
*** Conclusion:
 english(amyodell) , toyinventor(amyodell)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) , from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) , ((family(x) , named(x, nameo'dell) , (not(x=y)) , family(y) , named(y, nameo'dell))
named(amyodell, nameodell) , notableperson(amyodell) , named(jackodell, nameodell) , notableperson(jackodell) , named(matsodell, nameodell) , notableperson(matsodell)
british(amyodell) , singer(amyodell) , songwriter(amyodell)
english(jackodell) , toyinventor(jackodell)
*** Conclusion:
 named(amyodell, nameodell) , named(amyodell, nameo'dell)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) , mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
  (thesecondsmallesteigenvalueof(x, thegraphlaplacian) , honoredby(miroslavfiedler, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) , mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
 french(miroslavfiedler) , mathematician(miroslavfiedler)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) , mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
  (czech(x) , mathematician(x) , knownfor(x, contributionstolinearalgebraandgraphtheory))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) , professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) , playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) , playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
 playedfor(thomasbarber, boltonwanderers) , playedin(boltonwanderers,thefootballleague)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) , professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) , playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) , playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
 playedas(thomasbarber, insideleft)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) , professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) , playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) , playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
  (english(x) , professionalfootballer(x) , scoredthewinninggoalin(x, facupfinal1913))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) ,  (japanese(x) , videogamecompany(x) , created(x, thelegendofzelda))
forall forall ((game(x) , intop10(x) , created(y,)) -: japanese(y))
forall ((game(x) , (greaterthan(y, onemillion) , copiessold(x, y))) -: top10(x)))
(greaterthan(y, onemillion) , copiessold(thelegendofzelda,))
*** Conclusion:
 top10(thelegendofzelda)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) ,  (japanese(x) , videogamecompany(x) , created(x, thelegendofzelda))
forall forall ((game(x) , intop10(x) , created(y,)) -: japanese(y))
forall ((game(x) , (greaterthan(y, onemillion) , copiessold(x, y))) -: top10(x)))
(greaterthan(y, onemillion) , copiessold(thelegendofzelda,))
*** Conclusion:
 (created(x, fifa22) , japanese(x) , videogamecompany(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) ,  (japanese(x) , videogamecompany(x) , created(x, thelegendofzelda))
forall forall ((game(x) , intop10(x) , created(y,)) -: japanese(y))
forall ((game(x) , (greaterthan(y, onemillion) , copiessold(x, y))) -: top10(x)))
(greaterthan(y, onemillion) , copiessold(thelegendofzelda,))
*** Conclusion:
 nottop10(thelegendofzelda)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) , from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall ((team(x) , attending(x, nbafinals)) -: wonmanygames(x))
team(bostonceltics) , lost(bostonceltics, nbafinals)
forall ((team(x) , won(x, nbafinals)) -: moreincome(x))
forall ((won(x, nbafinals) | lost(x, nbafinals)) -: attending(x, nbafinals))
*** Conclusion:
 from(bostonceltics, sanfrancisco)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) , from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall ((team(x) , attending(x, nbafinals)) -: wonmanygames(x))
team(bostonceltics) , lost(bostonceltics, nbafinals)
forall ((team(x) , won(x, nbafinals)) -: moreincome(x))
forall ((won(x, nbafinals) | lost(x, nbafinals)) -: attending(x, nbafinals))
*** Conclusion:
 hasmorethanthirtyyearsofhistory(bostonceltics)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) , from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall ((team(x) , attending(x, nbafinals)) -: wonmanygames(x))
team(bostonceltics) , lost(bostonceltics, nbafinals)
forall ((team(x) , won(x, nbafinals)) -: moreincome(x))
forall ((won(x, nbafinals) | lost(x, nbafinals)) -: attending(x, nbafinals))
*** Conclusion:
 moreincome(goldenstatewarriors)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (subscribedto(x, amcalist) -: eligibleforthreefreemovies(x))
 (cinemaeveryweek(x))
forall (prefer(x, tvseries) -: notwatchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 noteligibleforthreefreemovies(james)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (subscribedto(x, amcalist) -: eligibleforthreefreemovies(x))
 (cinemaeveryweek(x))
forall (prefer(x, tvseries) -: notwatchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 cinemaeveryweek(james)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (subscribedto(x, amcalist) -: eligibleforthreefreemovies(x))
 (cinemaeveryweek(x))
forall (prefer(x, tvseries) -: notwatchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 notwatchtvin(peter, cinemas)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((book(x) , writtenby(x, cixinliu)) -: (morethan(y, onemillion) , sold(x,)))
 (won(x, hugoaward) , book(x) , writtenby(x, cixinliu))
forall ((book(x) , aboutfuture(x)) -: fowardlooking(x))
book(threebodyproblem) , (morethan(y, onemillion) , sold(threebodyproblem,))
aboutfuture(threebodyproblem)
*** Conclusion:
 won(threebodyproblem, hugoaward)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((book(x) , writtenby(x, cixinliu)) -: (morethan(y, onemillion) , sold(x,)))
 (won(x, hugoaward) , book(x) , writtenby(x, cixinliu))
forall ((book(x) , aboutfuture(x)) -: fowardlooking(x))
book(threebodyproblem) , (morethan(y, onemillion) , sold(threebodyproblem,))
aboutfuture(threebodyproblem)
*** Conclusion:
 aboutfuture(threebodyproblem)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((book(x) , writtenby(x, cixinliu)) -: (morethan(y, onemillion) , sold(x,)))
 (won(x, hugoaward) , book(x) , writtenby(x, cixinliu))
forall ((book(x) , aboutfuture(x)) -: fowardlooking(x))
book(threebodyproblem) , (morethan(y, onemillion) , sold(threebodyproblem,))
aboutfuture(threebodyproblem)
*** Conclusion:
 writtenby(threebodyproblem, cixinliu)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (easy(x) -:  (lessthan(y, percent20) , acrate(x,)))
forall (recommended(x) -: easy(x))
forall (easy(x) ^ hard(x))
forall (starred(x)) -: hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 easy(twosum)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (easy(x) -:  (lessthan(y, percent20) , acrate(x,)))
forall (recommended(x) -: easy(x))
forall (easy(x) ^ hard(x))
forall (starred(x)) -: hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 recommended(foursum)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (easy(x) -:  (lessthan(y, percent20) , acrate(x,)))
forall (recommended(x) -: easy(x))
forall (easy(x) ^ hard(x))
forall (starred(x)) -: hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 (greaterthan(y, percent20) , acrate(2sum,))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (philateliclit(x) -: (stamp(x) | periodical(x) | auction(x) | book(x) | bibliography(x) | background(x)))
notstamp(mort)
not(periodical(mort) | auction(mort) | bibliography(mort) | background(mort))
philateliclit(mort)
*** Conclusion:
 background(mort)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (philateliclit(x) -: (stamp(x) | periodical(x) | auction(x) | book(x) | bibliography(x) | background(x)))
notstamp(mort)
not(periodical(mort) | auction(mort) | bibliography(mort) | background(mort))
philateliclit(mort)
*** Conclusion:
 philateliclit(eragon)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
   (mammal(x) , mammal(y) , (not(x=y)) , have(x, teeth) , have(y, teeth))
nothave(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 mammal(platypus) , (nothave(platypus, teeth))
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
   (mammal(x) , mammal(y) , (not(x=y)) , have(x, teeth) , have(y, teeth))
nothave(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 reptile(platypus)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
   (mammal(x) , mammal(y) , (not(x=y)) , have(x, teeth) , have(y, teeth))
nothave(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 mammal(humans)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) , districtin(xiangshan, guilin) , districtin(diecai, guilin) , districtin(qixing, guilin) , city(guilin)
notdistrictin(yangshuo, guilin)
*** Conclusion:
  (districtin(xiangshan, x) , districtin(diecai, x) , city(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) , districtin(xiangshan, guilin) , districtin(diecai, guilin) , districtin(qixing, guilin) , city(guilin)
notdistrictin(yangshuo, guilin)
*** Conclusion:
 districtin(xiufeng, guilin)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) , districtin(xiangshan, guilin) , districtin(diecai, guilin) , districtin(qixing, guilin) , city(guilin)
notdistrictin(yangshuo, guilin)
*** Conclusion:
 districtin(kowloon, hongkong)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) , american(jasonkramer)
  (american(x) , musicsupervisor(x) , radiopersonality(x) , (not(x=y)) , american(y) , musicsupervisor(y) , radiopersonality(y))
forall forall((hostshowon(x, y) , publicradiostation(x)) -: radiopersonality(x))
radiopersonality(joerogan)
(hostshowon(jasonkramer, x) , publicradiostation(x))
*** Conclusion:
 american(joerogan)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) , american(jasonkramer)
  (american(x) , musicsupervisor(x) , radiopersonality(x) , (not(x=y)) , american(y) , musicsupervisor(y) , radiopersonality(y))
forall forall((hostshowon(x, y) , publicradiostation(x)) -: radiopersonality(x))
radiopersonality(joerogan)
(hostshowon(jasonkramer, x) , publicradiostation(x))
*** Conclusion:
 musicsupervisor(jasonkramer)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) , american(jasonkramer)
  (american(x) , musicsupervisor(x) , radiopersonality(x) , (not(x=y)) , american(y) , musicsupervisor(y) , radiopersonality(y))
forall forall((hostshowon(x, y) , publicradiostation(x)) -: radiopersonality(x))
radiopersonality(joerogan)
(hostshowon(jasonkramer, x) , publicradiostation(x))
*** Conclusion:
 radiopersonality(jasonkramer)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) , province(drenthe) , in(gasteren, drenthe)
province(drenthe) , in(drenthe, netherlands)
forall (city(x) -: notvillage(x))
 (population(x, num155) , village(x) , in(x, drenthe))
*** Conclusion:
 village(gasteren) , in(gasteren, netherlands)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) , province(drenthe) , in(gasteren, drenthe)
province(drenthe) , in(drenthe, netherlands)
forall (city(x) -: notvillage(x))
 (population(x, num155) , village(x) , in(x, drenthe))
*** Conclusion:
 city(gasteren)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) , province(drenthe) , in(gasteren, drenthe)
province(drenthe) , in(drenthe, netherlands)
forall (city(x) -: notvillage(x))
 (population(x, num155) , village(x) , in(x, drenthe))
*** Conclusion:
 population(gasteren, num155)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) , released(endgame, yr2006)
setin(endgame, washington)
not(filmedin(endgame, washington))
(filmedin(x, newyork) , (not(x=y)) , filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 filmedin(endgame, newyork)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) , released(endgame, yr2006)
setin(endgame, washington)
not(filmedin(endgame, washington))
(filmedin(x, newyork) , (not(x=y)) , filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 forall (not(directed(x, endgame) , from(x, hongkong)))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) , released(endgame, yr2006)
setin(endgame, washington)
not(filmedin(endgame, washington))
(filmedin(x, newyork) , (not(x=y)) , filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 forall (directed(andychang, x) -: not(filmedin(x, washington)))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) ,  (colleagueofjustinkruger(y) , proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
 proposed(thomasgilovich, naivecynicism)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) ,  (colleagueofjustinkruger(y) , proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
  (proposed(justinkruger, x) , philosophyofmind(x))
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) ,  (colleagueofjustinkruger(y) , proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
  (workedon(thomasgilovich, x) , philosophyofmind(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
(greaterthan(x, num160) , litproductions(hughvanstone,))
(hometown(hughvanstone,) , attendedschoolin(hughvanstone,))
*** Conclusion:
 worldleadinglightingdesigner(hughvanstone) , from(hughvanstone, unitedkingdom)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
(greaterthan(x, num160) , litproductions(hughvanstone,))
(hometown(hughvanstone,) , attendedschoolin(hughvanstone,))
*** Conclusion:
 (greaterthan(x, num170) , litproductions(hughvanstone,))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
(greaterthan(x, num160) , litproductions(hughvanstone,))
(hometown(hughvanstone,) , attendedschoolin(hughvanstone,))
*** Conclusion:
 attendedschoolin(hughvanstone, unitedstates)
*** True Label:
 U
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall (professionalbaseballplayer(x) -: playinmlb(x))
forall (bornin(x, california) -: nationality(x, american))
forall (nationality(x, american)-: notnationality(x, german))
*** Conclusion:
 nationality(josephkmak, german)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall (professionalbaseballplayer(x) -: playinmlb(x))
forall (bornin(x, california) -: nationality(x, american))
forall (nationality(x, american)-: notnationality(x, german))
*** Conclusion:
 playinmlb(josephkmak)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall (professionalbaseballplayer(x) -: playinmlb(x))
forall (bornin(x, california) -: nationality(x, american))
forall (nationality(x, american)-: notnationality(x, german))
*** Conclusion:
 iscatcher(josephkmak)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall ((professionaltennisplayer(x) , inbig3(x)) -: highwinratio(x))
*** Conclusion:
 notbornin(rafanadal, mallorca)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall ((professionaltennisplayer(x) , inbig3(x)) -: highwinratio(x))
*** Conclusion:
 inbig3(rafanadal)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall ((professionaltennisplayer(x) , inbig3(x)) -: highwinratio(x))
*** Conclusion:
 greatestofalltime(rafanadal)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((doesolympicsport(x) , goestoolympicgames(x)) -: olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall (welterweight(x) -: not heavyweight(x))
*** Conclusion:
 olympian(carlosreyes)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((doesolympicsport(x) , goestoolympicgames(x)) -: olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall (welterweight(x) -: not heavyweight(x))
*** Conclusion:
 heavyweight(carlosreyes)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((doesolympicsport(x) , goestoolympicgames(x)) -: olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall (welterweight(x) -: not heavyweight(x))
*** Conclusion:
 wonolympicmedal(carlosreyes)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall forall ((israpper(x) , releasedalbum(x, y)) -: israpalbum(y))
releasedalbum(tyga, welldone3)
forall (israpper(x) -: notisoperasinger(x))
*** Conclusion:
 israpalbum(welldone3)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall forall ((israpper(x) , releasedalbum(x, y)) -: israpalbum(y))
releasedalbum(tyga, welldone3)
forall (israpper(x) -: notisoperasinger(x))
*** Conclusion:
 isoperasinger(tyga)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall forall ((israpper(x) , releasedalbum(x, y)) -: israpalbum(y))
releasedalbum(tyga, welldone3)
forall (israpper(x) -: notisoperasinger(x))
*** Conclusion:
 isworthlistening(welldone3)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sevendistinctworks(x) -: heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 heptalogy(harrypotter)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sevendistinctworks(x) -: heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 notheptalogy(chroniclesofnarnia)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sevendistinctworks(x) -: heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 heptalogy(lordofrings)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) , in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) , in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) , in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) , include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
  (museum(x) , in(x, nyc) , include(x, byzantineart) , include(x, islamicart))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) , in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) , in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) , in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) , include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
  (museum(x) , in(x, nyc) , include(x, americanart))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) , in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) , in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) , in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) , include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
  (museum(x) , in(x, nyc) , include(x, greekart))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) , onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall (((peak(x, y))) -: popular(x))
peak(yourwoman, iceland) , peak(yourwoman, israel) , peak(yourwoman, spain)
*** Conclusion:
 popular(yourwoman)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) , onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall (((peak(x, y))) -: popular(x))
peak(yourwoman, iceland) , peak(yourwoman, israel) , peak(yourwoman, spain)
*** Conclusion:
 forall (produce(whitetown, x) -: notpopular(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) , onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall (((peak(x, y))) -: popular(x))
peak(yourwoman, iceland) , peak(yourwoman, israel) , peak(yourwoman, spain)
*** Conclusion:
 successful(whitetown)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((runfar(x) , usemap(x)) -: orienteer(x))
forall (fit(x) -: runfar(x))
forall (sensedirection(x) -: usemap(x))
forall (militaryofficer(x) -: fit(x))
militaryofficer(hailee) , sensedirection(hailee)
notmilitaryofficer(karl) , usemap(karl)
*** Conclusion:
 orienteer(hailee)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((runfar(x) , usemap(x)) -: orienteer(x))
forall (fit(x) -: runfar(x))
forall (sensedirection(x) -: usemap(x))
forall (militaryofficer(x) -: fit(x))
militaryofficer(hailee) , sensedirection(hailee)
notmilitaryofficer(karl) , usemap(karl)
*** Conclusion:
 notorienteer(karl)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 talentedpoet(lorca) , support(lorca, populists)
forall (support(x, populists) -: opposed(nationalists, x))
forall (talentedpoet(x) -: popular(x))
forall ((opposed(nationalists, x) , popular(x)) -: killed(nationalists, x))
support(daniel, populists) , (notpopular(daniel))
*** Conclusion:
 notkilled(nationalists, daniel)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 talentedpoet(lorca) , support(lorca, populists)
forall (support(x, populists) -: opposed(nationalists, x))
forall (talentedpoet(x) -: popular(x))
forall ((opposed(nationalists, x) , popular(x)) -: killed(nationalists, x))
support(daniel, populists) , (notpopular(daniel))
*** Conclusion:
 killed(nationalists, lorca)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) , lawyer(james)
whig(james) , politician(james) , satinhouseofcommons(james)
forall (british(x) -: european(x))
forall (lawyer(x) -: familiarwithlaws(x))
  (whig(x) , speakfrench(x)) , (not(x=y)) , (whig(y) , speakfrench(y))
*** Conclusion:
 forall (lawyer(x) -: notsatinhouseofcommons(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) , lawyer(james)
whig(james) , politician(james) , satinhouseofcommons(james)
forall (british(x) -: european(x))
forall (lawyer(x) -: familiarwithlaws(x))
  (whig(x) , speakfrench(x)) , (not(x=y)) , (whig(y) , speakfrench(y))
*** Conclusion:
  (european(x) , familiarwithlaws(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) , lawyer(james)
whig(james) , politician(james) , satinhouseofcommons(james)
forall (british(x) -: european(x))
forall (lawyer(x) -: familiarwithlaws(x))
  (whig(x) , speakfrench(x)) , (not(x=y)) , (whig(y) , speakfrench(y))
*** Conclusion:
 speakfrench(james)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) , rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall forall (leadsinger(x, y) -: singer(y))
forall (singer(x) -: musician(x))
popularsingle(imaginedragon, demons)
  (popularsingle(imaginedragon, x) , billboardhot100(x)) , (not(x=y)) , (popularsingle(imaginedragon, y) , billboardhot100(y))
*** Conclusion:
   (rockband(x) , leadsinger(x, y) , songwriter(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) , rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall forall (leadsinger(x, y) -: singer(y))
forall (singer(x) -: musician(x))
popularsingle(imaginedragon, demons)
  (popularsingle(imaginedragon, x) , billboardhot100(x)) , (not(x=y)) , (popularsingle(imaginedragon, y) , billboardhot100(y))
*** Conclusion:
 notmusician(dan)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) , rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall forall (leadsinger(x, y) -: singer(y))
forall (singer(x) -: musician(x))
popularsingle(imaginedragon, demons)
  (popularsingle(imaginedragon, x) , billboardhot100(x)) , (not(x=y)) , (popularsingle(imaginedragon, y) , billboardhot100(y))
*** Conclusion:
 billboardhot100(demons)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) , historian(andrewwilson) , politicalscientist(andrewwilson)
forall (locatedin(x, easterneurope)-: specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
notlocatedin(britain, easterneurope)
*** Conclusion:
 bornin(andrewwilson, easterneurope)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) , historian(andrewwilson) , politicalscientist(andrewwilson)
forall (locatedin(x, easterneurope)-: specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
notlocatedin(britain, easterneurope)
*** Conclusion:
 specializein(andrewwilson, poland)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) , historian(andrewwilson) , politicalscientist(andrewwilson)
forall (locatedin(x, easterneurope)-: specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
notlocatedin(britain, easterneurope)
*** Conclusion:
 specializein(andrewwilson, britain)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) , historian(andrewwilson) , politicalscientist(andrewwilson)
forall (locatedin(x, easterneurope)-: specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
notlocatedin(britain, easterneurope)
*** Conclusion:
 forall (british(x) -: notpoliticalscientist(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
*** Conclusion:
 in(us31, alabama)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
*** Conclusion:
 notin(cr47, alabama)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
*** Conclusion:
 in(sr287, unitedstates)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (breedingback(x) -: (artificialselection(x) , deliberateselectivebreedingofdomesticanimals(x)))
  (heckcattle(x) , breedingback(x) , auroch(y) , resemble(x, y))
forall (heckcattle(x) -: animal(x))
forall (auroch(x) -: animal(x))
  (animal(x) , animal(y) , (not(x=y)) , breedingback(x) , breedingback(y) , ((dead(w) , resemble(x, w)) , (not(w=z)) , ((dead(z) , resemble(y, z))))
*** Conclusion:
  (heckcattle(x) , artificialselection(x) , (not(x=y)) , heckcattle(y) , artificialselection(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (breedingback(x) -: (artificialselection(x) , deliberateselectivebreedingofdomesticanimals(x)))
  (heckcattle(x) , breedingback(x) , auroch(y) , resemble(x, y))
forall (heckcattle(x) -: animal(x))
forall (auroch(x) -: animal(x))
  (animal(x) , animal(y) , (not(x=y)) , breedingback(x) , breedingback(y) , ((dead(w) , resemble(x, w)) , (not(w=z)) , ((dead(z) , resemble(y, z))))
*** Conclusion:
 forall (auroch(x) -: dead(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (controlledsubstances(x) -: drugs(x))
  (controlledsubstances(x) , controlledsubstances(y) , (not(x=y)) , beneficial(x) , harmful(y))
forall forall ((child(x) , controlledsubstances(y) , exposedto(x, y)) -: inchemicalendangerment(x))
forall (inchemicalendangerment(x) -: harmful(x))
passedin(controlledsubstancesact, yr1971) , act(controlledsubstancesact)
 (act(x) , preventsharm(x) , (not(x=y)) , act(y) , preventsharm(y))
*** Conclusion:
 preventsharm(controlledsubstancesact)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (controlledsubstances(x) -: drugs(x))
  (controlledsubstances(x) , controlledsubstances(y) , (not(x=y)) , beneficial(x) , harmful(y))
forall forall ((child(x) , controlledsubstances(y) , exposedto(x, y)) -: inchemicalendangerment(x))
forall (inchemicalendangerment(x) -: harmful(x))
passedin(controlledsubstancesact, yr1971) , act(controlledsubstancesact)
 (act(x) , preventsharm(x) , (not(x=y)) , act(y) , preventsharm(y))
*** Conclusion:
  (drugs(x) , beneficial(x) , (not(x=y)) , drugs(y) , beneficial(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (controlledsubstances(x) -: drugs(x))
  (controlledsubstances(x) , controlledsubstances(y) , (not(x=y)) , beneficial(x) , harmful(y))
forall forall ((child(x) , controlledsubstances(y) , exposedto(x, y)) -: inchemicalendangerment(x))
forall (inchemicalendangerment(x) -: harmful(x))
passedin(controlledsubstancesact, yr1971) , act(controlledsubstancesact)
 (act(x) , preventsharm(x) , (not(x=y)) , act(y) , preventsharm(y))
*** Conclusion:
 forall ((child(x) , inchemicalendangerment(x)) -: harmful(x))
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) , authored(douglasadams, thesalmonofdoubt) , book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) , about(thesalmonofdoubt, technology)
forall (author(x) -: writer(x))
forall (writer(x) -: create(x, innovativeidea))
  (contain(x, innovativeidea) , about(x, technology) , (not(x=y)) , (contain(y, innovativeidea) , about(y, technology)))
*** Conclusion:
 writer(douglasadams)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) , authored(douglasadams, thesalmonofdoubt) , book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) , about(thesalmonofdoubt, technology)
forall (author(x) -: writer(x))
forall (writer(x) -: create(x, innovativeidea))
  (contain(x, innovativeidea) , about(x, technology) , (not(x=y)) , (contain(y, innovativeidea) , about(y, technology)))
*** Conclusion:
 create(douglasadams, innovativeidea)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) , authored(douglasadams, thesalmonofdoubt) , book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) , about(thesalmonofdoubt, technology)
forall (author(x) -: writer(x))
forall (writer(x) -: create(x, innovativeidea))
  (contain(x, innovativeidea) , about(x, technology) , (not(x=y)) , (contain(y, innovativeidea) , about(y, technology)))
*** Conclusion:
 notcontain(thesalmonofdoubt, innovativeidea)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) , professional(quincymcduffie) , widereciever(quincymcduffie) , playsin(quincymcduffie, cfl)
forall (((cancatch(x, y) , ball(y))) -: goodwidereceiver(x))
  (football(x) , cancatch(quincymcduffie, x)) , (not(x=y) , (football(y) , cancatch(quincymcduffie, y))
forall (goodwidereceiver(x) -: professional(x))
forall (goodwidereceiver(x) -: (cancatchwith(x, lefthand) , cancatchwith(x, righthand)))
forall (football(x) -: ball(x))
*** Conclusion:
 goodwidereceiver(quincymcduffie)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) , professional(quincymcduffie) , widereciever(quincymcduffie) , playsin(quincymcduffie, cfl)
forall (((cancatch(x, y) , ball(y))) -: goodwidereceiver(x))
  (football(x) , cancatch(quincymcduffie, x)) , (not(x=y) , (football(y) , cancatch(quincymcduffie, y))
forall (goodwidereceiver(x) -: professional(x))
forall (goodwidereceiver(x) -: (cancatchwith(x, lefthand) , cancatchwith(x, righthand)))
forall (football(x) -: ball(x))
*** Conclusion:
 forall (ball(x) -: cancatch(quincymcduffie, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) , professional(quincymcduffie) , widereciever(quincymcduffie) , playsin(quincymcduffie, cfl)
forall (((cancatch(x, y) , ball(y))) -: goodwidereceiver(x))
  (football(x) , cancatch(quincymcduffie, x)) , (not(x=y) , (football(y) , cancatch(quincymcduffie, y))
forall (goodwidereceiver(x) -: professional(x))
forall (goodwidereceiver(x) -: (cancatchwith(x, lefthand) , cancatchwith(x, righthand)))
forall (football(x) -: ball(x))
*** Conclusion:
 forall ((professional(x) , widereciever(x)) -: good(x, catchingballs))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (topcover(x) -: ((roof(y)))
forall (roof(x) -: (protect(x) , blocksunlight(x)))
   (roof(x) , concrete(x)) , (not(x=y) , roof(y) , concrete(y))
   (roof(x) , seagrass(x)) , (not(x=y) , roof(y) , seagrass(y))
forall forall ((concrete(x) , seagrass(y)) -: stronger(x, y))
*** Conclusion:
 forall (notroof(x) -: notprotect(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (topcover(x) -: ((roof(y)))
forall (roof(x) -: (protect(x) , blocksunlight(x)))
   (roof(x) , concrete(x)) , (not(x=y) , roof(y) , concrete(y))
   (roof(x) , seagrass(x)) , (not(x=y) , roof(y) , seagrass(y))
forall forall ((concrete(x) , seagrass(y)) -: stronger(x, y))
*** Conclusion:
 forall forall ((roof(x) , concrete(x) , roof(y) , seagrass(y)) -: stronger(x, y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (topcover(x) -: ((roof(y)))
forall (roof(x) -: (protect(x) , blocksunlight(x)))
   (roof(x) , concrete(x)) , (not(x=y) , roof(y) , concrete(y))
   (roof(x) , seagrass(x)) , (not(x=y) , roof(y) , seagrass(y))
forall forall ((concrete(x) , seagrass(y)) -: stronger(x, y))
*** Conclusion:
 forall ((roof(x) , concrete(x)) -: (notblocksunlight(x)))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
 sportingevent(champs)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
 notlastsummerolympics(tokyo)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
  (lastsummerolympics(x) , mostmedals(unitedstates, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) , van(astro)
forall (vehicle(x) , producedby(x, chevrolet) , inthisbatch(x) -: (car(x) ^ van(x)))
*** Conclusion:
 van(luminaapv)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) , van(astro)
forall (vehicle(x) , producedby(x, chevrolet) , inthisbatch(x) -: (car(x) ^ van(x)))
*** Conclusion:
 car(luminaapv) ^ van(luminaapv)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) , van(astro)
forall (vehicle(x) , producedby(x, chevrolet) , inthisbatch(x) -: (car(x) ^ van(x)))
*** Conclusion:
 van(astro)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) , van(astro)
forall (vehicle(x) , producedby(x, chevrolet) , inthisbatch(x) -: (car(x) ^ van(x)))
*** Conclusion:
 car(astro)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pasifikanewzealanders(x) -: newzealanders(x)) ,  (pasifikanewzealanders(y) , pasifikanewzealanders(z) , differentethnicgroups(y,))
forall (asiannewzealanders(x) -: newzealanders(x)) ,  (asiannewzealanders(y) , asiannewzealanders(z) , differentethnicgroups(y,))
forall (pasifikanewzealanders(x) -: notasiannewzealanders(x))
forall (pasifikanewzealanders(x) -: speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 pasifikanewzealanders(amy)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pasifikanewzealanders(x) -: newzealanders(x)) ,  (pasifikanewzealanders(y) , pasifikanewzealanders(z) , differentethnicgroups(y,))
forall (asiannewzealanders(x) -: newzealanders(x)) ,  (asiannewzealanders(y) , asiannewzealanders(z) , differentethnicgroups(y,))
forall (pasifikanewzealanders(x) -: notasiannewzealanders(x))
forall (pasifikanewzealanders(x) -: speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 asiannewzealanders(amy)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pasifikanewzealanders(x) -: newzealanders(x)) ,  (pasifikanewzealanders(y) , pasifikanewzealanders(z) , differentethnicgroups(y,))
forall (asiannewzealanders(x) -: newzealanders(x)) ,  (asiannewzealanders(y) , asiannewzealanders(z) , differentethnicgroups(y,))
forall (pasifikanewzealanders(x) -: notasiannewzealanders(x))
forall (pasifikanewzealanders(x) -: speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 asiannewzealanders(joe)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pasifikanewzealanders(x) -: newzealanders(x)) ,  (pasifikanewzealanders(y) , pasifikanewzealanders(z) , differentethnicgroups(y,))
forall (asiannewzealanders(x) -: newzealanders(x)) ,  (asiannewzealanders(y) , asiannewzealanders(z) , differentethnicgroups(y,))
forall (pasifikanewzealanders(x) -: notasiannewzealanders(x))
forall (pasifikanewzealanders(x) -: speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 speaksamoan(joe)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (roundel(x) -: (rounded(x) , artilleryfortification(x)))
forall forall ((roundel(x) , adjacentwalls(x,)) -: nothigher(x, y))
forall (artilleryfortification(x) -: deploycannons(x))
forall forall ((roundel(x) , artilleryfortification(y)) -: older(x, y))
forall (batterytower(x) -: artilleryfortification(x))
*** Conclusion:
 forall (batterytower(x) -: deploycannons(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (roundel(x) -: (rounded(x) , artilleryfortification(x)))
forall forall ((roundel(x) , adjacentwalls(x,)) -: nothigher(x, y))
forall (artilleryfortification(x) -: deploycannons(x))
forall forall ((roundel(x) , artilleryfortification(y)) -: older(x, y))
forall (batterytower(x) -: artilleryfortification(x))
*** Conclusion:
 forall forall ((roundel(x) , batterytower(y)) -: older(x, y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (roundel(x) -: (rounded(x) , artilleryfortification(x)))
forall forall ((roundel(x) , adjacentwalls(x,)) -: nothigher(x, y))
forall (artilleryfortification(x) -: deploycannons(x))
forall forall ((roundel(x) , artilleryfortification(y)) -: older(x, y))
forall (batterytower(x) -: artilleryfortification(x))
*** Conclusion:
 forall forall ((batterytower(x) , adjacentwall(x,)) -: higher(x, y))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (roundel(x) -: (rounded(x) , artilleryfortification(x)))
forall forall ((roundel(x) , adjacentwalls(x,)) -: nothigher(x, y))
forall (artilleryfortification(x) -: deploycannons(x))
forall forall ((roundel(x) , artilleryfortification(y)) -: older(x, y))
forall (batterytower(x) -: artilleryfortification(x))
*** Conclusion:
 forall (roundel(x) -: deploycannons(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (businessperson(x) -: (company(y) , ownership(x, y)))
forall forall (ownership(x, y) -: makemoney(x, y))
forall (businessperson(x) -: (businessman(x) ^ businesswoman(x)))
 (businessperson(x) , extrovert(x))
forall (businessperson(x) -: handlemoney(x))
businessperson(bob) , ownership(bob, microsoft)
*** Conclusion:
 extrovert(bob)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (businessperson(x) -: (company(y) , ownership(x, y)))
forall forall (ownership(x, y) -: makemoney(x, y))
forall (businessperson(x) -: (businessman(x) ^ businesswoman(x)))
 (businessperson(x) , extrovert(x))
forall (businessperson(x) -: handlemoney(x))
businessperson(bob) , ownership(bob, microsoft)
*** Conclusion:
 handlemoney(bob)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (businessperson(x) -: (company(y) , ownership(x, y)))
forall forall (ownership(x, y) -: makemoney(x, y))
forall (businessperson(x) -: (businessman(x) ^ businesswoman(x)))
 (businessperson(x) , extrovert(x))
forall (businessperson(x) -: handlemoney(x))
businessperson(bob) , ownership(bob, microsoft)
*** Conclusion:
 businessperson(bob) , makemoney(bob, microsoft)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (leader(x) -: havepower(x))
forall (leader(x) -: (king(x) ^ queen(x)))
forall (queen(x) -: female(x))
forall (king(x) -: male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 king(elizabeth)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (leader(x) -: havepower(x))
forall (leader(x) -: (king(x) ^ queen(x)))
forall (queen(x) -: female(x))
forall (king(x) -: male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 havepower(elizabeth)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (leader(x) -: havepower(x))
forall (leader(x) -: (king(x) ^ queen(x)))
forall (queen(x) -: female(x))
forall (king(x) -: male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 leader(elizabeth)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pet(x) -: animal(x))
forall (pet(x) -: (dog(x) ^ cat(x)))
forall forall ((pet(y) , ownedby(x,)) -: cares(x, y))
  (cat(x) , naughty(x) , (not(x=y)) , dog(y) , naughty(y))
forall forall ((pet(x) , naughty(x) , ownedby(x,)) -: notliked(x, y))
ownedby(leo, charlie) , pet(leo) , dog(leo) , naughty(leo)
*** Conclusion:
 animal(leo)
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pet(x) -: animal(x))
forall (pet(x) -: (dog(x) ^ cat(x)))
forall forall ((pet(y) , ownedby(x,)) -: cares(x, y))
  (cat(x) , naughty(x) , (not(x=y)) , dog(y) , naughty(y))
forall forall ((pet(x) , naughty(x) , ownedby(x,)) -: notliked(x, y))
ownedby(leo, charlie) , pet(leo) , dog(leo) , naughty(leo)
*** Conclusion:
 notliked(leo, charlie) , notcares(charlie, leo)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (pet(x) -: animal(x))
forall (pet(x) -: (dog(x) ^ cat(x)))
forall forall ((pet(y) , ownedby(x,)) -: cares(x, y))
  (cat(x) , naughty(x) , (not(x=y)) , dog(y) , naughty(y))
forall forall ((pet(x) , naughty(x) , ownedby(x,)) -: notliked(x, y))
ownedby(leo, charlie) , pet(leo) , dog(leo) , naughty(leo)
*** Conclusion:
 forall (dog(x) -: notnaughty(x))
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (book(x) -: contains(x, knowledge))
forall forall (readbook(x, y) -: gains(x, knowledge))
forall (gains(x, knowledge) -: smarter(x))
readbook(harry, walden) , book(walden)
*** Conclusion:
 gains(harry, knowledge)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (book(x) -: contains(x, knowledge))
forall forall (readbook(x, y) -: gains(x, knowledge))
forall (gains(x, knowledge) -: smarter(x))
readbook(harry, walden) , book(walden)
*** Conclusion:
 smarter(harry)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (book(x) -: contains(x, knowledge))
forall forall (readbook(x, y) -: gains(x, knowledge))
forall (gains(x, knowledge) -: smarter(x))
readbook(harry, walden) , book(walden)
*** Conclusion:
 forall (smarter(x) -: gainknowledge(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
    (labmonitor(x) , aoc(x) , (not(x=y)) , labmonitor(y) , aoc(y))
forall (labmonitor(x) -: discounted(x))
forall (discounted(x) -: a1080p(x))
forall (a1080p(x) -: nottypec(x))
labmonitor(lg-34)
*** Conclusion:
 aoc(lg-34)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
    (labmonitor(x) , aoc(x) , (not(x=y)) , labmonitor(y) , aoc(y))
forall (labmonitor(x) -: discounted(x))
forall (discounted(x) -: a1080p(x))
forall (a1080p(x) -: nottypec(x))
labmonitor(lg-34)
*** Conclusion:
 nottypec(lg-34)
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
    (labmonitor(x) , aoc(x) , (not(x=y)) , labmonitor(y) , aoc(y))
forall (labmonitor(x) -: discounted(x))
forall (discounted(x) -: a1080p(x))
forall (a1080p(x) -: nottypec(x))
labmonitor(lg-34)
*** Conclusion:
 nota1080p(lg-34)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (in(x, newhaven) -: nothigh(x))
forall (yalehousing(x) -: in(x, newhaven))
forall (in(x, manhattan) -: high(x))
forall (bloomberg(x) -: in(x, manhattan))
forall (bloomberglogo(x) -: bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 nothigh(tower-a)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (in(x, newhaven) -: nothigh(x))
forall (yalehousing(x) -: in(x, newhaven))
forall (in(x, manhattan) -: high(x))
forall (bloomberg(x) -: in(x, manhattan))
forall (bloomberglogo(x) -: bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 notin(tower-b, manhattan)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (in(x, newhaven) -: nothigh(x))
forall (yalehousing(x) -: in(x, newhaven))
forall (in(x, manhattan) -: high(x))
forall (bloomberg(x) -: in(x, manhattan))
forall (bloomberglogo(x) -: bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 notin(tower-b, newhaven)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((coffee(x) , soldin(x, walmart)) -: notfrom(x, france))
forall ((coffee(x) , favoredby(x, localresidents)) -: from(x, colombia))
forall ((coffee(x) , highprice(x)) -: favoredbylocalresidents(x))
coffee(civetcoffee) , notfrom(colombia)
expensive(jamaicablue) , coffee(jamaicablue)
forall ((expensive(x) , coffee(x)) -: highprice(x))
*** Conclusion:
 from(civetcoffee, france)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((coffee(x) , soldin(x, walmart)) -: notfrom(x, france))
forall ((coffee(x) , favoredby(x, localresidents)) -: from(x, colombia))
forall ((coffee(x) , highprice(x)) -: favoredbylocalresidents(x))
coffee(civetcoffee) , notfrom(colombia)
expensive(jamaicablue) , coffee(jamaicablue)
forall ((expensive(x) , coffee(x)) -: highprice(x))
*** Conclusion:
 from(jamaicablue, colombia)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((coffee(x) , soldin(x, walmart)) -: notfrom(x, france))
forall ((coffee(x) , favoredby(x, localresidents)) -: from(x, colombia))
forall ((coffee(x) , highprice(x)) -: favoredbylocalresidents(x))
coffee(civetcoffee) , notfrom(colombia)
expensive(jamaicablue) , coffee(jamaicablue)
forall ((expensive(x) , coffee(x)) -: highprice(x))
*** Conclusion:
 favoredby(jamaicablue, localresidents)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (ownedby(x, company) -: connectedto(x, googlehome))
forall (ownedby(x, employee) -: connectedto(x, companywifi))
forall (connectedto(x, googlehome) -: controlledby(x, managers))
forall (connectedto(x, companywifi) -: easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 easytooperate(modelxx)
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (ownedby(x, company) -: connectedto(x, googlehome))
forall (ownedby(x, employee) -: connectedto(x, companywifi))
forall (connectedto(x, googlehome) -: controlledby(x, managers))
forall (connectedto(x, companywifi) -: easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 controlledby(modelxx, managers)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (ownedby(x, company) -: connectedto(x, googlehome))
forall (ownedby(x, employee) -: connectedto(x, companywifi))
forall (connectedto(x, googlehome) -: controlledby(x, managers))
forall (connectedto(x, companywifi) -: easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 connectedto(modelxx, googlehome)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (attendinperson(x) -: registered(x))
forall (attend(x) -: (attendinperson(x) ^ attendremotely(x)))
forall ((attend(x) , fromchina(x)) -: notattendremotely(x))
attend(james) , (notattendremotely(james))
fromchina(jack) , attend(jack)
*** Conclusion:
 attend(james) , (notattendinperson(james))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (attendinperson(x) -: registered(x))
forall (attend(x) -: (attendinperson(x) ^ attendremotely(x)))
forall ((attend(x) , fromchina(x)) -: notattendremotely(x))
attend(james) , (notattendremotely(james))
fromchina(jack) , attend(jack)
*** Conclusion:
 attend(jack) , attendinperson(jack)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (attendinperson(x) -: registered(x))
forall (attend(x) -: (attendinperson(x) ^ attendremotely(x)))
forall ((attend(x) , fromchina(x)) -: notattendremotely(x))
attend(james) , (notattendremotely(james))
fromchina(jack) , attend(jack)
*** Conclusion:
 registered(jack)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (podcast(x) -: notnovel(x))
forall(((bornin(x, y) , city(y) , locatedin(y,america)) -: american(x))
forall forall ((novel(x) , writtenby(x, y)) -: writesnovel(y))
american(dani_shapiro) , writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) , writtenin(family_history, yr2003)
podcast(family_secrets) , createdby(family_secrets, dani_shapiro)
city(boston) , american(boston)
*** Conclusion:
 writesnovel(dani_shapiro)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (podcast(x) -: notnovel(x))
forall(((bornin(x, y) , city(y) , locatedin(y,america)) -: american(x))
forall forall ((novel(x) , writtenby(x, y)) -: writesnovel(y))
american(dani_shapiro) , writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) , writtenin(family_history, yr2003)
podcast(family_secrets) , createdby(family_secrets, dani_shapiro)
city(boston) , american(boston)
*** Conclusion:
 isnovel(family_secrets)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (podcast(x) -: notnovel(x))
forall(((bornin(x, y) , city(y) , locatedin(y,america)) -: american(x))
forall forall ((novel(x) , writtenby(x, y)) -: writesnovel(y))
american(dani_shapiro) , writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) , writtenin(family_history, yr2003)
podcast(family_secrets) , createdby(family_secrets, dani_shapiro)
city(boston) , american(boston)
*** Conclusion:
 bornin(dani_shapiro, boston)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((coach(x, y) , footballclub(y)) -: footballcoach(x))
forall forall forall forall ((playpositionfor(x, w, y, z) , innfl(y, z)) -: playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 footballcoach(dennisgreen)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((coach(x, y) , footballclub(y)) -: footballcoach(x))
forall forall forall forall ((playpositionfor(x, w, y, z) , innfl(y, z)) -: playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 notplayinnfl(johnrandle)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((coach(x, y) , footballclub(y)) -: footballcoach(x))
forall forall forall forall ((playpositionfor(x, w, y, z) , innfl(y, z)) -: playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 playpositionfor(criscarter, wr, minnesotavikings, year1997)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((summerolympicsin(x,) , in(x, unitedstates)) -: summerolympicsin(x, unitedstates))
forall forall ((in(x, y) , in(y, unitedstates)) -: in(x, unitedstates))
forall forall forall ((in(x, z) , state(z) , summerolympicsin(x,)) -: summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
notinsummerolympicsin(boxing, yr2028) , (notinsummerolympicsin(modern_pentathlon, yr2028)) , (notinsummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 summerolympicsin(unitedstates, yr2028)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((summerolympicsin(x,) , in(x, unitedstates)) -: summerolympicsin(x, unitedstates))
forall forall ((in(x, y) , in(y, unitedstates)) -: in(x, unitedstates))
forall forall forall ((in(x, z) , state(z) , summerolympicsin(x,)) -: summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
notinsummerolympicsin(boxing, yr2028) , (notinsummerolympicsin(modern_pentathlon, yr2028)) , (notinsummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 notsummerolympicsin(georgia, yr1996)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall ((summerolympicsin(x,) , in(x, unitedstates)) -: summerolympicsin(x, unitedstates))
forall forall ((in(x, y) , in(y, unitedstates)) -: in(x, unitedstates))
forall forall forall ((in(x, z) , state(z) , summerolympicsin(x,)) -: summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
notinsummerolympicsin(boxing, yr2028) , (notinsummerolympicsin(modern_pentathlon, yr2028)) , (notinsummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 insummerolympicsin(skateboarding, yr2028)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall forall (albumbyband(x, y) , rockband(y, z) -: genre(x, rock))
forall forall forall (albumbyband(x, y) , albumaward(x, z) -: rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
 (songinfilm(x) , songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 genre(troubleatthehenhouse, rock)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall forall (albumbyband(x, y) , rockband(y, z) -: genre(x, rock))
forall forall forall (albumbyband(x, y) , albumaward(x, z) -: rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
 (songinfilm(x) , songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 not(rockband(x, canada) , award(x, thealbumoftheyear))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall forall forall (albumbyband(x, y) , rockband(y, z) -: genre(x, rock))
forall forall forall (albumbyband(x, y) , albumaward(x, z) -: rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
 (songinfilm(x) , songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 songinfilm(buttswigglin)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) , directedby(thedeparture, lanawilson) , directedby(missamericana, lanawilson)
forall forall (directedby(x, y) -: filmmaker(y))
documentary(aftertiller)
forall (documentary(x) -: film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall forall forall ((from(x, y) , in(y, z)) -: from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 from(lanawilson, unitedstates) , filmmaker(lanawilson)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) , directedby(thedeparture, lanawilson) , directedby(missamericana, lanawilson)
forall forall (directedby(x, y) -: filmmaker(y))
documentary(aftertiller)
forall (documentary(x) -: film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall forall forall ((from(x, y) , in(y, z)) -: from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 not(filmmaker(x) , from(x, kirkland) , directedby(missamericana, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) , directedby(thedeparture, lanawilson) , directedby(missamericana, lanawilson)
forall forall (directedby(x, y) -: filmmaker(y))
documentary(aftertiller)
forall (documentary(x) -: film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall forall forall ((from(x, y) , in(y, z)) -: from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 filmmakeraward(lanawilson, theindependentspiritawardforbestdocumentary)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) , footballreferee(brianwinter)
retired(brianwinter) , retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
 (footballreferee(x) , refereeobserver(x))
sonof(andywinter, brianwinter) , footballplayer(andywinter) , playsfor(andywinter, hamiltonacademical)
*** Conclusion:
  (sonof(x, y) , refereeobserver(y) , footballplayer(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) , footballreferee(brianwinter)
retired(brianwinter) , retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
 (footballreferee(x) , refereeobserver(x))
sonof(andywinter, brianwinter) , footballplayer(andywinter) , playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 notrefereeobserver(brianwinter)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) , footballreferee(brianwinter)
retired(brianwinter) , retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
 (footballreferee(x) , refereeobserver(x))
sonof(andywinter, brianwinter) , footballplayer(andywinter) , playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 retired(brianwinter)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) , footballreferee(brianwinter)
retired(brianwinter) , retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
 (footballreferee(x) , refereeobserver(x))
sonof(andywinter, brianwinter) , footballplayer(andywinter) , playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 referee(andywinter)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) , physician(michael) , journalist(michael) , author(michael) , broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) , editedby(worldmedicine, michael)
bornin(michael, yorkshire) , (sonof(michael, x) , generalpractitioner(x))
*** Conclusion:
   (sonof(x, y) , generalpractitioner(y) , wordsetter(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) , physician(michael) , journalist(michael) , author(michael) , broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) , editedby(worldmedicine, michael)
bornin(michael, yorkshire) , (sonof(michael, x) , generalpractitioner(x))
*** Conclusion:
 notmagazine(worldmedicine)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) , physician(michael) , journalist(michael) , author(michael) , broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) , editedby(worldmedicine, michael)
bornin(michael, yorkshire) , (sonof(michael, x) , generalpractitioner(x))
*** Conclusion:
 forall (british(x) -: notauthor(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) , physician(michael) , journalist(michael) , author(michael) , broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) , editedby(worldmedicine, michael)
bornin(michael, yorkshire) , (sonof(michael, x) , generalpractitioner(x))
*** Conclusion:
 forall (journalist(x) -: notbornin(x, yorkshire))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) , physician(michael) , journalist(michael) , author(michael) , broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) , editedby(worldmedicine, michael)
bornin(michael, yorkshire) , (sonof(michael, x) , generalpractitioner(x))
*** Conclusion:
   (son(x, y) , generalpractitioner(y) , notauthor(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) , physician(herodicus) , dietician(herodicus) , sophist(herodicus) , gymnast(herodicus)
born(herodicus, selymbia) , city(selymbia)
colony(selymbia, megara) , citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
  (theory(x) , from(x, herodicus) , foundationof(x, sportsmedicine) , (not(x=y)) , theory(y) , from(y, herodicus) , foundationof(y, sportsmedicine))
*** Conclusion:
 tutor(herodicus, hippocrates)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) , physician(herodicus) , dietician(herodicus) , sophist(herodicus) , gymnast(herodicus)
born(herodicus, selymbia) , city(selymbia)
colony(selymbia, megara) , citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
  (theory(x) , from(x, herodicus) , foundationof(x, sportsmedicine) , (not(x=y)) , theory(y) , from(y, herodicus) , foundationof(y, sportsmedicine))
*** Conclusion:
 tutor(hippocrates, herodicus)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) , physician(herodicus) , dietician(herodicus) , sophist(herodicus) , gymnast(herodicus)
born(herodicus, selymbia) , city(selymbia)
colony(selymbia, megara) , citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
  (theory(x) , from(x, herodicus) , foundationof(x, sportsmedicine) , (not(x=y)) , theory(y) , from(y, herodicus) , foundationof(y, sportsmedicine))
*** Conclusion:
  (born(herodicus, x) , citystate(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) , physician(herodicus) , dietician(herodicus) , sophist(herodicus) , gymnast(herodicus)
born(herodicus, selymbia) , city(selymbia)
colony(selymbia, megara) , citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
  (theory(x) , from(x, herodicus) , foundationof(x, sportsmedicine) , (not(x=y)) , theory(y) , from(y, herodicus) , foundationof(y, sportsmedicine))
*** Conclusion:
 notrecommend(herodicus, massages)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) , physician(herodicus) , dietician(herodicus) , sophist(herodicus) , gymnast(herodicus)
born(herodicus, selymbia) , city(selymbia)
colony(selymbia, megara) , citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
  (theory(x) , from(x, herodicus) , foundationof(x, sportsmedicine) , (not(x=y)) , theory(y) , from(y, herodicus) , foundationof(y, sportsmedicine))
*** Conclusion:
   (born(herodicus, x) , colony(x, y) , citystate(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (enterococcusdurans(x) -: species(x, enterococcus))
forall (enterococcusdurans(x) -: grampositive(x) , catalasenegative(x) , oxidasenegative(x) , coccus(x) , bacteria(x))
  (enterococcusdurans(x) , antiinflammatoryagent(y) , produces(x, y))
forall (antiinflammatoryagent(x) -: studied(x))
*** Conclusion:
 forall (enterococcusdurans(x) -: catalasenegative(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (enterococcusdurans(x) -: species(x, enterococcus))
forall (enterococcusdurans(x) -: grampositive(x) , catalasenegative(x) , oxidasenegative(x) , coccus(x) , bacteria(x))
  (enterococcusdurans(x) , antiinflammatoryagent(y) , produces(x, y))
forall (antiinflammatoryagent(x) -: studied(x))
*** Conclusion:
  (grampositive(x) , studied(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (enterococcusdurans(x) -: species(x, enterococcus))
forall (enterococcusdurans(x) -: grampositive(x) , catalasenegative(x) , oxidasenegative(x) , coccus(x) , bacteria(x))
  (enterococcusdurans(x) , antiinflammatoryagent(y) , produces(x, y))
forall (antiinflammatoryagent(x) -: studied(x))
*** Conclusion:
 forall forall (enterococcusdurans(x) , produces(x, y) -: notstudied(y))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) , birdgenus(ambiortus)
forall(knownspeciesof(x, ambiortus) -: isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
  (discover(yevgenykurochkin, x) , birdgenus(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) , birdgenus(ambiortus)
forall(knownspeciesof(x, ambiortus) -: isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
  (knownspeciesof(x, ambiortus) , notlivein(x, mongolia))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) , birdgenus(ambiortus)
forall(knownspeciesof(x, ambiortus) -: isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 livein(yevgenykurochkin, mongolia)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) , birdgenus(ambiortus)
forall(knownspeciesof(x, ambiortus) -: isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 forall (speciesof(x, ambiortus) -: livein(x, mongolia))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) , forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
  (old(x) , traditionalsummercamp(x) , forboysandgirls(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) , forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
  (traditionalsummercamp(x) , forboysandgirls(x) , operateduntil(ymca, x, year2015))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) , forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
 establishedin(campdavern, year1989)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) , philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall (essayist(x) -: writer(x))
*** Conclusion:
 bornin(robertzimmer, germany)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) , philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall (essayist(x) -: writer(x))
*** Conclusion:
 notwriter(robertzimmer)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) , philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall (essayist(x) -: writer(x))
*** Conclusion:
 biographer(robertzimmer)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
  (chessplayer(x) , grandmaster(x) , (not(x=y)) , chessplayer(y) , grandmaster(y))
forall ((bornin(x, newyorkcity) , livein(x, newyorkcity)) -: newyorker(x))
forall (livein(x, manhattan) -: livein(x, newyorkcity))
*** Conclusion:
 newyorker(asahoffmann)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
  (chessplayer(x) , grandmaster(x) , (not(x=y)) , chessplayer(y) , grandmaster(y))
forall ((bornin(x, newyorkcity) , livein(x, newyorkcity)) -: newyorker(x))
forall (livein(x, manhattan) -: livein(x, newyorkcity))
*** Conclusion:
 grandmaster(asahoffmann)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
  (chessplayer(x) , grandmaster(x) , (not(x=y)) , chessplayer(y) , grandmaster(y))
forall ((bornin(x, newyorkcity) , livein(x, newyorkcity)) -: newyorker(x))
forall (livein(x, manhattan) -: livein(x, newyorkcity))
*** Conclusion:
 notlivein(asahoffmann, newyorkcity)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) , make(janjelinek, minimaltechno)
forall ((make(x, glitch) | make(x, minimaltechno) | make(x, microhouse)) -: electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall (((publishthroughlabel(x, y))) -: signedmusician(x))
*** Conclusion:
 electronicmusician(janjelinek)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) , make(janjelinek, minimaltechno)
forall ((make(x, glitch) | make(x, minimaltechno) | make(x, microhouse)) -: electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall (((publishthroughlabel(x, y))) -: signedmusician(x))
*** Conclusion:
 notsignedmusician(janjelinek)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) , make(janjelinek, minimaltechno)
forall ((make(x, glitch) | make(x, minimaltechno) | make(x, microhouse)) -: electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall (((publishthroughlabel(x, y))) -: signedmusician(x))
*** Conclusion:
 german(janjelinek)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
notsamecountry(germany, unitedstates)
forall forall forall (officein(x, y) , officein(x, z) , (notsamecountry(y, z)) -: multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 multinationalcompany(ableton)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
notsamecountry(germany, unitedstates)
forall forall forall (officein(x, y) , officein(x, z) , (notsamecountry(y, z)) -: multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 makesaisoftware(ableton)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
notsamecountry(germany, unitedstates)
forall forall forall (officein(x, y) , officein(x, z) , (notsamecountry(y, z)) -: multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 notofficein(ableton, germany)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall (striker(x) -: soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall forall (left(x, y) -: notplaysfor(x, y))
*** Conclusion:
 soccerplayer(robertlewandowski)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall (striker(x) -: soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall forall (left(x, y) -: notplaysfor(x, y))
*** Conclusion:
 playsfor(robertlewandowski, bayernmunchen)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall (striker(x) -: soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall forall (left(x, y) -: notplaysfor(x, y))
*** Conclusion:
 soccerstar(robertlewandowski)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) , specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall ((book(x) , publishedby(x, newvesselpress)) -: in(x, english))
book(neapolitanchronicles) , publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) , publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 book(neapolitanchronicles) , in(neapolitanchronicles, english)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) , specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall ((book(x) , publishedby(x, newvesselpress)) -: in(x, english))
book(neapolitanchronicles) , publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) , publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 publishedby(harrypotter, newvesselpress)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) , specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall ((book(x) , publishedby(x, newvesselpress)) -: in(x, english))
book(neapolitanchronicles) , publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) , publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 translatedfrom(palaceofflies, italian)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sells(quiksilver, x) -: (sportswear(x) | clothing(x) | footwear(x) | accessory(x)))
clothing(flannel)
 (sells(quiksilver, x) , owns(joe, x))
*** Conclusion:
 sells(quiksilver, beer)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sells(quiksilver, x) -: (sportswear(x) | clothing(x) | footwear(x) | accessory(x)))
clothing(flannel)
 (sells(quiksilver, x) , owns(joe, x))
*** Conclusion:
 owns(joe, flannel)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (sells(quiksilver, x) -: (sportswear(x) | clothing(x) | footwear(x) | accessory(x)))
clothing(flannel)
 (sells(quiksilver, x) , owns(joe, x))
*** Conclusion:
  (owns(joe, x) , sportswear(x) | clothing(x) | footwear(x) | accessory(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall (residentof(x, lawtonpark) -: usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 usezipcode(tom, num98199)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall (residentof(x, lawtonpark) -: usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 notusezipcode(tom, num98199)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall (residentof(x, lawtonpark) -: usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 residentof(tom, washington)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall (residentof(x, lawtonpark) -: usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 residentof(daniel, lawtonpark)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (vehicleregistrationplatein(x, istanbul) -: beginwith(x, num34))
forall (notbeginwith(x, num34) -: notfromistanbul(x))
 (owns(joe, x) , vehicleregistrationplatein(x, istanbul))
 (owns(tom, x) , beginwith(x, num35))
forall (beginwith(x, num35) -: notbeginwith(x, num34))
*** Conclusion:
  (owns(joe, x) , beginwith(x, num34))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall (vehicleregistrationplatein(x, istanbul) -: beginwith(x, num34))
forall (notbeginwith(x, num34) -: notfromistanbul(x))
 (owns(joe, x) , vehicleregistrationplatein(x, istanbul))
 (owns(tom, x) , beginwith(x, num35))
forall (beginwith(x, num35) -: notbeginwith(x, num34))
*** Conclusion:
  (owns(tom, x) , vehicleregistrationplatein(x, istanbul))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) , in(luzon, philippines)
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon))
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon) , deadly(x))
*** Conclusion:
 island(leyte) , in(leyte, philippines)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) , in(luzon, philippines)
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon))
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon) , deadly(x))
*** Conclusion:
 forall forall ((earthquake(x) , strikeincity(x, y) , in(y, philippines)) -: notdeadly(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) , in(luzon, philippines)
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon))
 (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, luzon) , deadly(x))
*** Conclusion:
   (earthquake(x) , strikeinyr(x, year1999) , strikeinmo(x, december) , strikeincity(x, y) , in(y, philippines))
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) , discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not(is(diethylcarbamazine, ivermectin))
*** Conclusion:
 not(preferredtreatmentfor(riverblindness, diethylcarbamazine))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) , discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not(is(diethylcarbamazine, ivermectin))
*** Conclusion:
 treats(diethylcarbamazine, riverblindness)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) , discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not(is(diethylcarbamazine, ivermectin))
*** Conclusion:
 treats(diethylcarbamazine, filariasis)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((legislator(x) , stealsfunds(x)) -: suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) , stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 suspended(tiffanytalston)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((legislator(x) , stealsfunds(x)) -: suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) , stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 notsuspended(tiffanytalston)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall ((legislator(x) , stealsfunds(x)) -: suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) , stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 prison(tiffanytalston)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) , filmproducer(daveeddiggs)
 (playsin(daveeddiggs, x, hamilton) , (not(x=y)) , playsin(daveeddiggs, y, hamilton)) , onbroadway(hamilton) , musical(hamilton)
 (actor(x) , playsin(x, y, hamilton) , wins(x, bestactoraward))
 (actor(x) , playsin(x, thomasjefferson, hamilton) , wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall ((musical(x) , onbroadway(x)) -: notfilm(x))
*** Conclusion:
 film(hamilton)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) , filmproducer(daveeddiggs)
 (playsin(daveeddiggs, x, hamilton) , (not(x=y)) , playsin(daveeddiggs, y, hamilton)) , onbroadway(hamilton) , musical(hamilton)
 (actor(x) , playsin(x, y, hamilton) , wins(x, bestactoraward))
 (actor(x) , playsin(x, thomasjefferson, hamilton) , wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall ((musical(x) , onbroadway(x)) -: notfilm(x))
*** Conclusion:
 wins(daveeddiggs, bestactoraward)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) , filmproducer(daveeddiggs)
 (playsin(daveeddiggs, x, hamilton) , (not(x=y)) , playsin(daveeddiggs, y, hamilton)) , onbroadway(hamilton) , musical(hamilton)
 (actor(x) , playsin(x, y, hamilton) , wins(x, bestactoraward))
 (actor(x) , playsin(x, thomasjefferson, hamilton) , wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall ((musical(x) , onbroadway(x)) -: notfilm(x))
*** Conclusion:
  (wins(hamilton, x) , (not(x=y)) , wins(hamilton, y))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) , lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall (bornin(x, athensohio) -: american(x))
*** Conclusion:
 bornin(bernardabrysonshahn, greece)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) , lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall (bornin(x, athensohio) -: american(x))
*** Conclusion:
 american(bernardabrysonshahn)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) , lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall (bornin(x, athensohio) -: american(x))
*** Conclusion:
 divorced(bernardabrysonshahn)
*** True Label:
 U
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) , songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) , competesonaustralianidol(bobbyflynn)
forall (competesonaustralianidol(x) -: australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 australiancitizen(bobbyflynn)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) , songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) , competesonaustralianidol(bobbyflynn)
forall (competesonaustralianidol(x) -: australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 flewtoin(bobbyflynn, america, year2007)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) , songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) , competesonaustralianidol(bobbyflynn)
forall (competesonaustralianidol(x) -: australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 bornin(bobbyflynn, queens)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) , videogameholdingcompany(koeitecmo) , animeholdingcompany(koeitecmo) , holdingcompany(x)
forall (holdingcompany(x) -: (company(y) , holds(x, y)))
disbandsin(tecmo, japan) , survives(koei) , renames(koei)
forall (videogameholdingcompany(x) -: holdingcompany(x))
*** Conclusion:
  (company(x) , holds(koeitecmo, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) , videogameholdingcompany(koeitecmo) , animeholdingcompany(koeitecmo) , holdingcompany(x)
forall (holdingcompany(x) -: (company(y) , holds(x, y)))
disbandsin(tecmo, japan) , survives(koei) , renames(koei)
forall (videogameholdingcompany(x) -: holdingcompany(x))
*** Conclusion:
  (company(x) , holds(tecmo, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) , videogameholdingcompany(koeitecmo) , animeholdingcompany(koeitecmo) , holdingcompany(x)
forall (holdingcompany(x) -: (company(y) , holds(x, y)))
disbandsin(tecmo, japan) , survives(koei) , renames(koei)
forall (videogameholdingcompany(x) -: holdingcompany(x))
*** Conclusion:
 animeholdingcompany(koeitecmo)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) , rower(virginialee)
competesin(virginialee, sweepoaredevents) , competesin(virginialee, scullingevents)
city(sydney) , homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
 forall (rower(x) -: nothomecity(sydney, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) , rower(virginialee)
competesin(virginialee, sweepoaredevents) , competesin(virginialee, scullingevents)
city(sydney) , homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
 forall (australian(x) -: notrepresented(x, newsouthwales))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) , rower(virginialee)
competesin(virginialee, sweepoaredevents) , competesin(virginialee, scullingevents)
city(sydney) , homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
  (australian(x) , competesin(x, sweepoaredevents) , represents(x, newsouthwales))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) , childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
  (dramafilm(x) , produces(columbiapictures, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) , childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
  (adventurefilm(x) , produces(columbiapictures, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) , childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
  (childrensfilm(x) , produces(paramount, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) , childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
  (adventurefilm(x) , produces(paramount, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 cricketeer(royrichardson) , playsfor(royrichardson, sintmaarten) , constituentcountry(sintmaarten)
righthanded(royrichardson) , batsman(royrichardson) , mediumpacebowler(royrichardson)
oldatdebut(royrichardson)
dismisses(shervillehuggins, royrichardson)
*** Conclusion:
 forall forall ((consituentcountry(y) , playedfor(x, y)) -:  notdismissed(shervillehuggins, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 cricketeer(royrichardson) , playsfor(royrichardson, sintmaarten) , constituentcountry(sintmaarten)
righthanded(royrichardson) , batsman(royrichardson) , mediumpacebowler(royrichardson)
oldatdebut(royrichardson)
dismisses(shervillehuggins, royrichardson)
*** Conclusion:
 forall ((righthanded(x) , mediumpacebowler(x)) -: notplayedfor(x, sintmaarten))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(ainderbyquernhow) , civilparish(ainderbyquernhow) , in(ainderbyquernhow, hambletondistrict)
in(hambletondistrict, northyorkshire)
in(northyorkshire, england)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
*** Conclusion:
  (village(x) , in(x, england))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(ainderbyquernhow) , civilparish(ainderbyquernhow) , in(ainderbyquernhow, hambletondistrict)
in(hambletondistrict, northyorkshire)
in(northyorkshire, england)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
*** Conclusion:
 not( (civilparish(x) , in(x, england)))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 televisionseries(diray) , policeprocedural(diray)
creates(maya, diray) , writes(maya, diray)
produces(jed, diray)
british(maya) , british(jed)
*** Conclusion:
  (british(x) , creates(x, diray))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 televisionseries(diray) , policeprocedural(diray)
creates(maya, diray) , writes(maya, diray)
produces(jed, diray)
british(maya) , british(jed)
*** Conclusion:
  (british(x) , televisionseries(y) , produces(x, y))
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) , in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) , includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
  (leads(roderickstrong, x) , professionalwrestlingstable(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) , in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) , includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
 leads(roderickstrong, creedbrothers)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) , in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) , includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
 forall ((professionalwrestlingstable(x) , includes(x, ivynile)) -: notfeuds(imperium, x))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) , actress(deborahwallace) , playwright(deborahwallace) , producer(deborahwallace)
play(psyche) , basedon(psyche, lifeofjamesmirandabarry)
play(homesick) , writtenby(homesick, deborahwallace) , play(psyche) , writtenby(psyche, deborahwallace) , play(thevoid) , writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
  (coproduces(x, gasland) , writtenby(homesick, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) , actress(deborahwallace) , playwright(deborahwallace) , producer(deborahwallace)
play(psyche) , basedon(psyche, lifeofjamesmirandabarry)
play(homesick) , writtenby(homesick, deborahwallace) , play(psyche) , writtenby(psyche, deborahwallace) , play(thevoid) , writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
 forall (play(x) , writtenby(x, deborahwallace) -: notbasedon(x, lifeofjamesmirandabarry))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) , actress(deborahwallace) , playwright(deborahwallace) , producer(deborahwallace)
play(psyche) , basedon(psyche, lifeofjamesmirandabarry)
play(homesick) , writtenby(homesick, deborahwallace) , play(psyche) , writtenby(psyche, deborahwallace) , play(thevoid) , writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
 play(gasland)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) , screenwriter(maggiefriedman) , producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) , executiveproducerof(maggiefriedman, witchesofeastend) , lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) , series(witchesofeastend)
produces(maggiefriedman, eastwick) , develops(maggiefriedman, eastwick)
series(eastwick) , airedon(eastwick, abc)
*** Conclusion:
   (series(x) , airedon(x, abc) , develops(y, x) , showrunnerof(y, witchesofeastend))
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) , screenwriter(maggiefriedman) , producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) , executiveproducerof(maggiefriedman, witchesofeastend) , lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) , series(witchesofeastend)
produces(maggiefriedman, eastwick) , develops(maggiefriedman, eastwick)
series(eastwick) , airedon(eastwick, abc)
*** Conclusion:
 forall (series(x) , airedon(x, abc) , (showrunnerof(y, witchesofeastend)) -: notdevelops(y, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) , screenwriter(maggiefriedman) , producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) , executiveproducerof(maggiefriedman, witchesofeastend) , lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) , series(witchesofeastend)
produces(maggiefriedman, eastwick) , develops(maggiefriedman, eastwick)
series(eastwick) , airedon(eastwick, abc)
*** Conclusion:
 develops(maggiefriedman, witchesofeastend)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 largecomplex(shafaq-asiman) , largecomplex(shafaq-asiman) , offshore(shafaq-asiman) , geologicalstructures(shafaq-asiman) , in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall forall (northwestof(x, y) -: southeastof(y, x))
*** Conclusion:
 southeastof(baku, shafaq-asiman)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 largecomplex(shafaq-asiman) , largecomplex(shafaq-asiman) , offshore(shafaq-asiman) , geologicalstructures(shafaq-asiman) , in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall forall (northwestof(x, y) -: southeastof(y, x))
*** Conclusion:
  (largecomplex(x) , southeastof(x, baku))
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 largecomplex(shafaq-asiman) , largecomplex(shafaq-asiman) , offshore(shafaq-asiman) , geologicalstructures(shafaq-asiman) , in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall forall (northwestof(x, y) -: southeastof(y, x))
*** Conclusion:
 forall (geologicalstructures(x) , offshore(x) -: notnorthwestof(baku, x))
*** True Label:
 F
*** Predicted Label:
 None
Classification Report:               precision    recall  f1-score   support

                   0.00      0.00      0.00         0
           F       0.50      0.09      0.15        69
 F</output>        0.00      0.00      0.00         0
        None       0.00      0.00      0.00         0
           T       0.50      0.09      0.15       122
 T</output>        0.00      0.00      0.00         0
           U       1.00      0.01      0.02       110

    accuracy                           0.06       301
   macro avg       0.29      0.03      0.05       301
weighted avg       0.68      0.06      0.10       301

*************** INFERENCE COMPLETE ***************

In [15]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.059800664451827246
***** PRECISION *****
0.2857142857142857
***** RECALL *****
0.026601623608038433
***** F1 *****
0.04556342056342056

   Accuracy  Precision    Recall        F1
0  0.059801   0.285714  0.026602  0.045563

In [17]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

config.json: 0.00B [00:00, ?B/s]

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [18]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLINGO')

*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 forall (wildturkey(x) -: (easternwildturkey(x) | osceolawildturkey(x) | gouldswildturkey(x) | merriamswildturkey(x) | riograndewildturkey(x) | ocellatedwildturkey(x)))
not(easternwildturkey(tom))
not(osceolawildturkey(tom))
not(gouldswildturkey(tom))
not(merriamswildturkey(tom) | riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 has(mary, flu)
forall (has(x, flu) -: has(x, influenza))
nothas(susan, influenza)
*** Conclusion:
 has(mary, influenza) ^ has(susan, influenza)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (in(butte, x) , in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
  (city(pierre) , in(pierre, x) , city(bismarck) , in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 city(billings) , in(billings, montana)
city(butte) , in(butte, montana) , city(helena) , in(helena, montana) , city(missoula) , in(missoula, montana)
 (city(whitesulphursprings) , in(whitesulphursprings, x) , city(butte) , in(butte, x))
city(pierre) , not(in(pierre, montana))
forall ((city(x) , city(butte) , in(x, butte)) -: not(in(x, pierre)))
forall  ((city(x) , (in(x, y) , not(x=bristol) , not(x=texarkana) , not(x=texhoma) , not(x=unioncity)) -: not (not(z=y) , in(x, z)))
*** Conclusion:
 city(missoula) , in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
  (built(pierrederigauddevaudreuil, x) , locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
notlocatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
  (soccerteam(x) , holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 notwakesup(thehulk) -: nothappy(thor)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 happy(thor) -: wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 F
*** Premises:
 superhero(peterparker) ^ civilian(peterparker)
destroyer(thehulk)
angry(thehulk) -: wakesup(thehulk)
wakesup(thehulk) -: breaks(thehulk, bridge)
god(thor)
happy(thor) -: breaks(thor, bridge)
forall (god(x) -: notdestroyer(x))
superhero(peter) -: wears(peter, uniform)
forall ((destroyer(x) , breaks(x,bridge)) -: notcivilian(peter))
happy(thor) -: angry(thehulk)
*** Conclusion:
 nothappy(thor) -: notbreaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 F
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 notin(boves, europe)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 railwaystation(boves) , in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall forall forall ((situatedon(x, z) , (precede(x, y) | precede(y, x)) -: situatedon(y, z))
serve(boves, hautsdefrance)
forall forall forall ((in(x, y) , in(y, z)) -: in(x, z))
forall forall forall ((precede(x, y) , precede(y, z)) -: precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) , realnum(num7) , realnum(num8)
forall forall ((realnum(x) , realnum(y) , issuccessorof(x, y)) -: larger(x, y))
forall forall (larger(x, y) -: notlarger(y, x))
(issuccessorof(y, num6) , equals(num7, y))
(issuccessorof(y, num7) , equals(num8, y))
positive(num2)
forall forall ((positive(x) , isdouble(y, x)) -: positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
   (czech(x) , publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 czech(miroslav) , choralconductor(miroslav) , specializeinperformanceof(miroslav, renaissancemusic) , specializeinperformanceof(miroslav, baroquemusic)
forall (choralconductor(x) -: musician(x))
  ((musician(x) -: love(x, music)) , (not(x=y) , musician(y) -: love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall (choralconductor(x) -: notspecializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 vole(taigavole) , livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall ((livein(x, northamerica) , livein(x, borealtaigazone)) -: livein(x, coldplace))
*** Conclusion:
 notlivein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notsetin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 youngadultfantasy(thickastheives) , novel(thickastheives) , writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall forall forall ((writtenby(x, y) , publishedby(x, z)) -: workedwith(y, z))
fictional(medeempire) , setin(thickastheives, medeempire)
  ((country(x) , near(x, medeempire) , plotstoswallowup(medeempire, x)) , (not(x=y) , near(y, medeempire) , plotstoswallowup(medeempire, y)))
country(attolia) , near(attolia, medeempire) , country(sounis) , near(sounis, medeempire)
soldas(thickastheives, hardcover) , soldas(thickastheives, softcover)
*** Conclusion:
 notworkedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 americanpolitician(walterbrown) , lawyer(walterbrown) , servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) , graduatedwith(walterbrown, bachelorsofart)
(in(walterbrown, toledo, t) , in(walterbrownfather, toledo, t) , practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 (notin(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall ((water(x) , from(x, crotonriverwatershed)) -: (flowsto(x, y) , in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall ((water(x) , in(x, crotonriverwatershed)) -: flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall (water(x) , from(x, crotonriver) -: flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (form(x, system7) , formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
  (single(x) , release(system7, x))
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 basedin(system7, uk) , electronicdancemusicband(system7)
form(stevehillage, system7) , form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) , formermemberof(miquettegiraudy, gong)
forall (electronicdancemusicband(x) -: band(x))
 (clubsingle(x) , release(system7, x))
forall (clubsingle(x) -: notsingle(x))
*** Conclusion:
 notband(system7)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
  (museumship(x) , opentopublic(x) , servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) , builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall (museumship(x) -: opentopublic(x))
servedin(usssalem, atlantic) , servedin(usssalem, mediterranean)
*** Conclusion:
 notlastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 (elephantopus(x) , in(x,africa) , elephantopus(y) , in(y,africa))
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: notnativeto(x, southeasternunitedstates))
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 forall (elephantopus(x) -: (genus(x, perennialplants) , belongto(x, daisyfamily)))
  (elephantopus(x) , in(x,africa) , (not(x=y)) , elephantopus(y) , in(y, southernasia) , (not(x=z)) , (not(y=z)) , elephantopus(z) , in(z, australia))
  (elephantopus(x) , nativeto(x, southeasternunitedstates) , (not(x=y)) , elephantopus(y) , nativeto(y, southeasternunitedstates))
forall (elephantopusscaber(x) -: traditionalmedicine(x))
*** Conclusion:
 forall (elephantopus(x) -: traditionalmedicine(x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:


In [19]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.3853820598006645
***** PRECISION *****
0.26824146221359674
***** RECALL *****
0.1464910149247284
***** F1 *****
0.18602953212784493

   Accuracy  Precision    Recall       F1
0  0.385382   0.268241  0.146491  0.18603

In [16]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)