In [1]:
'''
task: classify syllogism validity with NL notation
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: pfolio
evaluation: zero-shot + sef category
'''
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 104.5 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.3.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)

In [3]:
import pandas as pd

pfolio_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/p-folio/data/pfolio_kr_gold_train_sef.csv")

In [4]:
# evaluation metrics

import numpy as np
import re
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

def predict_answer(model, tokenizer, obj, subject, sef, ref_relation=None, source_knowledge=None):
  # define sef categories
  sef_disjunctive = r"""
  A disjunctive syllogism contains "∨" or "⊕". Here is an example:
  <PREMISES>All kids are young.
All toddlers are kids.
If someone is young, then they are not elderly.
All pirates are seafarers.
If Nancy is not a pirate, then Nancy is young.
If Nancy is not a toddler, then Nancy is a seafarer.</PREMISES>
  <CONCLUSION>Nancy is either both a pirate and a toddler, or neither a pirate nor a toddler.</CONCLUSION>
  """

  sef_complex = r"""
  A complex syllogism has more than 2 premises. Here is an example:
  <PREMISES>Aberdeen won the cup in the 2013 final.
Rangers won the cup in the 2014 final.
Aberdeen and Rangers are different teams.
Different teams cannot win the cup in the same year's final.</PREMISES>
  <CONCLUSION>Aberdeen has once won a cup.</CONCLUSION>
  """

  sef_categorical = r"""
  A categorical syllogism contains any word from the list ["all", "any", "some", "no", "few", "most", "none", "several"]. Here is an example:
  <PREMISES>Ordinary is an unincorporated community.
Located within Elliot County, Ordinary is on Kentucky Route 32.
Ordinary is located northwest of Sandy Hook.</PREMISES>
  <CONCLUSION>There is an unincorporated community located in Elliot County.</CONCLUSION>
  """

  sef_hypothetical = r"""
  A hypothetical syllogism is not disjunctive, complex or categorical. Here is an example:
  <PREMISES>No homework is fun.
Some reading is homework.</PREMISES>
  <CONCLUSION>Some reading is fun.</CONCLUSION>
  """

  sef_categories = dict()
  sef_categories["disjunctive"] = sef_disjunctive
  sef_categories["complex"] = sef_complex
  sef_categories["categorical"] = sef_categorical
  sef_categories["hypothetical"] = sef_hypothetical


  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert logician. You are given a syllogism in with premises between <PREMISES></PREMISES> and conclusion between <CONCLUSION></CONCLUSION> tags.
  <PREMISES>{subject}</PREMISES>
  <CONCLUSION>{obj}</CONCLUSION>
  You are also given the category of the syllogism to help you understand it: {sef_categories[sef]}.
  Classify the conclusion as "T" if true, "F" if false or "U" if uncertain based on the premises. Present your answer only between <output></output> tags.
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  predicted_relation = tokenizer.decode(response[0])
  matches = re.findall('<output>(.*)</output>', predicted_relation, flags=re.DOTALL)
  res = re.findall(r"<output>(.*)", matches[-1])  # from ['</output> tags.\n  <end_of_turn>\n  <start_of_turn>model\n  <output>T'] to ['T']
  predicted_label = res[0] if res else "None" # take first element from list ['T'] to get 'T'

  print("*** Premises: \n", subject)
  print("*** Conclusion: \n", obj)
  print("*** True Label: \n", ref_relation)
  print("*** Predicted Label: \n", predicted_label)
  return predicted_label

In [5]:
def infer_from_ontology(dataset, model, tokenizer, mode='default', notation='NL'):
  evaluation_metrics_df = pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1"])
  reference_labels = []
  predicted_labels = []
  for index, row in dataset.iterrows():
      conclusion = row["Conclusions - " + notation]
      premises = row["Premises - " + notation]
      sef_category = row["sef"]
      label = row["Truth Values"]
      if mode.lower() == "grammar":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        source_information = """BNF GRAMMAR"""
        print("*** RAG INFORMATION:", source_information)
      # predict answer with model
      predicted_label = predict_answer(model, tokenizer, conclusion, premises, sef_category, label)
      reference_labels.append(label)
      predicted_labels.append(predicted_label)
  # fill evaluation metrics dataframe
  accuracy_metric = accuracy_score(reference_labels, predicted_labels)
  precision_metric = precision_score(reference_labels, predicted_labels, average="macro")
  recall_metric = recall_score(reference_labels, predicted_labels, average="macro")
  f1_metric = f1_score(reference_labels, predicted_labels, average="macro")
  evaluation_metrics_df["Accuracy"] = [accuracy_metric]
  evaluation_metrics_df["Precision"] = [precision_metric]
  evaluation_metrics_df["Recall"] = [recall_metric]
  evaluation_metrics_df["F1"] = [f1_metric]
  print("Classification Report:", classification_report(reference_labels, predicted_labels))
  print("*************** INFERENCE COMPLETE ***************")
  return reference_labels, predicted_labels, evaluation_metrics_df, accuracy_metric, precision_metric, recall_metric, f1_metric

In [6]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [9]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [10]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [11]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default')

*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Ocellated wild turkey.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Eastern wild turkey.
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Joey is a wild turkey.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Mary has the flu.
If someone has the flu, then they have influenza.
Susan doesn't have influenza.
*** Conclusion:
 Either Mary or Susan has influenza.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Butte and St Pierre are in the same state.
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 St Pierre and Bismarck are in the same state.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Montana is home to the city of Missoula.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New France.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New England.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Fort Carillon was located in Europe.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Sūduva Marijampolė holds the Lithuanian Super Cup.
Sūduva Marijampolė is a soccer team.
*** Conclusion:
 Some soccer team holds the Lithuanian Super Cup.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If the Hulk does not wake up, then Thor is not happy.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is happy, then Peter Parker wears a uniform.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is not happy, then no bridge will be broken.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is situated on the Paris–Lille railway.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Boves is not in Europe.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is served by regional TER Hauts-de-France trains.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is larger than seven.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is positive.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Six is larger than seven.
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 Miroslav Venhoda loved music.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 A Czech published a book in 1946.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 No choral conductor specialized in the performance of Renaissance.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Cats like playing with taiga vole.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Taiga vole's living place is not cold.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner worked with Greenwillow Books.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 The Mede Empire plans to swallow up Attolia.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Thick as Thieves is not set in the Mede Empire.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner did not work with Greenwillow Books.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown graduated with a Bachelor of Arts.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown's father was in Toledo.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown was not in Toledo.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River watershed flows to somewhere in New York.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 The Croton River watershed is in the Bronx.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River flows to the Bronx.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 was formed by former members of Gong.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 has released several singles.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 is not a band.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem is open to the public.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 There is a museum ship open to the public that served in the Mediterranean.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem was not the last heavy cruiser to enter service.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is found in Australia and Southern Asia.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 No Elephantopus is native to the southeastern United States.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is a traditional medicine.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn Aarskog is a notable person.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn is Dagfinn Aarskog's given name.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:

In [12]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.5548172757475083
***** PRECISION *****
0.40613961979600743
***** RECALL *****
0.5675140571790608
***** F1 *****
0.4648512900661898

   Accuracy  Precision    Recall        F1
0  0.554817    0.40614  0.567514  0.464851

In [14]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [15]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Ocellated wild turkey.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Eastern wild turkey.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Joey is a wild turkey.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Mary has the flu.
If someone has the flu, then they have influenza.
Susan doesn't have influenza.
*** Conclusion:
 Either Mary or Susan has influenza.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Butte and St Pierre are in the same state.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 St Pierre and Bismarck are in the same state.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Montana is home to the city of Missoula.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New France.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New England.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Fort Carillon was located in Europe.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Sūduva Marijampolė holds the Lithuanian Super Cup.
Sūduva Marijampolė is a soccer team.
*** Conclusion:
 Some soccer team holds the Lithuanian Super Cup.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If the Hulk does not wake up, then Thor is not happy.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is happy, then Peter Parker wears a uniform.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is not happy, then no bridge will be broken.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is situated on the Paris–Lille railway.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Boves is not in Europe.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is served by regional TER Hauts-de-France trains.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is larger than seven.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is positive.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Six is larger than seven.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 Miroslav Venhoda loved music.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 A Czech published a book in 1946.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 No choral conductor specialized in the performance of Renaissance.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Cats like playing with taiga vole.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Taiga vole's living place is not cold.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner worked with Greenwillow Books.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 The Mede Empire plans to swallow up Attolia.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Thick as Thieves is not set in the Mede Empire.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner did not work with Greenwillow Books.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown graduated with a Bachelor of Arts.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown's father was in Toledo.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown was not in Toledo.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River watershed flows to somewhere in New York.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 The Croton River watershed is in the Bronx.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River flows to the Bronx.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 was formed by former members of Gong.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 has released several singles.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 is not a band.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem is open to the public.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 There is a museum ship open to the public that served in the Mediterranean.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem was not the last heavy cruiser to enter service.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is found in Australia and Southern Asia.
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 No Elephantopus is native to the southeastern United States.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is a traditional medicine.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn Aarskog is a notable person.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn is Dagfinn Aarskog's given name.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn Dahl is a Norwegian physician.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Odell is an English surname originating in Odell, Bedfordshire.
In some families, Odell is spelled O'Dell in a mistaken Irish adaptation.
Notable people with surnames include Amy Odell, Jack Odell, and Mats Odell.
Amy Odell is a British singer-songwriter.
Jack Odell is an English toy inventor.
*** Conclusion:
 Jack Odell is a notable person.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Odell is an English surname originating in Odell, Bedfordshire.
In some families, Odell is spelled O'Dell in a mistaken Irish adaptation.
Notable people with surnames include Amy Odell, Jack Odell, and Mats Odell.
Amy Odell is a British singer-songwriter.
Jack Odell is an English toy inventor.
*** Conclusion:
 Odell is Amy Odell's surname.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Odell is an English surname originating in Odell, Bedfordshire.
In some families, Odell is spelled O'Dell in a mistaken Irish adaptation.
Notable people with surnames include Amy Odell, Jack Odell, and Mats Odell.
Amy Odell is a British singer-songwriter.
Jack Odell is an English toy inventor.
*** Conclusion:
 Amy Odell is an English toy inventor.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Odell is an English surname originating in Odell, Bedfordshire.
In some families, Odell is spelled O'Dell in a mistaken Irish adaptation.
Notable people with surnames include Amy Odell, Jack Odell, and Mats Odell.
Amy Odell is a British singer-songwriter.
Jack Odell is an English toy inventor.
*** Conclusion:
 Amy Odell is also Amy O'Dell.
*** True Label:
 U
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Fiedler was a Czech mathematician.
Miroslav Fiedler is known for his contributions to linear algebra and graph theory.
Miroslav Fiedler is honored by the Fiedler eigenvalue.
Fiedler eigenvalue is the second smallest eigenvalue of the graph Laplacian.
*** Conclusion:
 Miroslav Fiedler is honored by the second smallest eigenvalue of the graph Laplacian.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Fiedler was a Czech mathematician.
Miroslav Fiedler is known for his contributions to linear algebra and graph theory.
Miroslav Fiedler is honored by the Fiedler eigenvalue.
Fiedler eigenvalue is the second smallest eigenvalue of the graph Laplacian.
*** Conclusion:
 Miroslav Fiedler was a French mathematician.
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Miroslav Fiedler was a Czech mathematician.
Miroslav Fiedler is known for his contributions to linear algebra and graph theory.
Miroslav Fiedler is honored by the Fiedler eigenvalue.
Fiedler eigenvalue is the second smallest eigenvalue of the graph Laplacian.
*** Conclusion:
 A Czech mathematician is known for his contributions to linear algebra and graph theory.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thomas Barber was an English professional footballer.
Thomas Barber played in the Football League for Aston Villa.
Thomas Barber played as a halfback and inside left.
Thomas Barber scored the winning goal in the 1913 FA Cup Final.
*** Conclusion:
 Thomas Barber played in the Football League for Bolton Wanderers
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thomas Barber was an English professional footballer.
Thomas Barber played in the Football League for Aston Villa.
Thomas Barber played as a halfback and inside left.
Thomas Barber scored the winning goal in the 1913 FA Cup Final.
*** Conclusion:
 Thomas Barber played as an inside left.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Thomas Barber was an English professional footballer.
Thomas Barber played in the Football League for Aston Villa.
Thomas Barber played as a halfback and inside left.
Thomas Barber scored the winning goal in the 1913 FA Cup Final.
*** Conclusion:
 An English professional footballer scored the winning goal in the 1913 FA Cup Final.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A Japanese game company created the game the Legend of Zelda.
All games on the Top 10 list are made by Japanese game companies.
If a game sells more than one million copies, then it will be included in the Top 10 list.
The Legend of Zelda sold more than one million copies.
*** Conclusion:
 The Legend of Zelda is on the Top 10 list.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A Japanese game company created the game the Legend of Zelda.
All games on the Top 10 list are made by Japanese game companies.
If a game sells more than one million copies, then it will be included in the Top 10 list.
The Legend of Zelda sold more than one million copies.
*** Conclusion:
 FIFA 22 is made by a Japanese video game company.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A Japanese game company created the game the Legend of Zelda.
All games on the Top 10 list are made by Japanese game companies.
If a game sells more than one million copies, then it will be included in the Top 10 list.
The Legend of Zelda sold more than one million copies.
*** Conclusion:
 The Legend of Zelda is not on the Top 10 list.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Golden State Warriors are a team from San Francisco.
The Golden State Warriors won the NBA finals.
All teams attending the NBA finals have won many games.
Boston Celtics are a team that lost the NBA finals.
If a team wins the NBA finals, then they will have more income.
If a team wins or loses at the NBA finals, then they are attending the finals.
*** Conclusion:
 The Boston Celtics are from San Francisco.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Golden State Warriors are a team from San Francisco.
The Golden State Warriors won the NBA finals.
All teams attending the NBA finals have won many games.
Boston Celtics are a team that lost the NBA finals.
If a team wins the NBA finals, then they will have more income.
If a team wins or loses at the NBA finals, then they are attending the finals.
*** Conclusion:
 The Boston Celtics have more than 30 years of experience.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Golden State Warriors are a team from San Francisco.
The Golden State Warriors won the NBA finals.
All teams attending the NBA finals have won many games.
Boston Celtics are a team that lost the NBA finals.
If a team wins the NBA finals, then they will have more income.
If a team wins or loses at the NBA finals, then they are attending the finals.
*** Conclusion:
 The Golden State Warriors will have more income from gate receipts.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a customer subscribes to AMC A-List, then he/she can watch 3 movies every week without any additional fees.
Some customers go to cinemas every week.
Customers who prefer TV series will not watch TV series in cinemas.
James watches TV series in cinemas.
James subscribes to AMC A-List.
Peter prefers TV series.
*** Conclusion:
 James cannot watch 3 movies every week without any additional fees.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a customer subscribes to AMC A-List, then he/she can watch 3 movies every week without any additional fees.
Some customers go to cinemas every week.
Customers who prefer TV series will not watch TV series in cinemas.
James watches TV series in cinemas.
James subscribes to AMC A-List.
Peter prefers TV series.
*** Conclusion:
 James goes to cinemas every week.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a customer subscribes to AMC A-List, then he/she can watch 3 movies every week without any additional fees.
Some customers go to cinemas every week.
Customers who prefer TV series will not watch TV series in cinemas.
James watches TV series in cinemas.
James subscribes to AMC A-List.
Peter prefers TV series.
*** Conclusion:
 Peter will not watch TV series in cinemas.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All books written by Cixin Liu have sold more than 1 million copies.
Some books that have won the Hugo Award were written by Cixin Liu.
All books about the future are forward-looking.
The book Three-Body Problem has sold more than 1 million copies.
The Three-Body Problem is about the future.
*** Conclusion:
 The Three-Body Problem won the Hugo Award.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All books written by Cixin Liu have sold more than 1 million copies.
Some books that have won the Hugo Award were written by Cixin Liu.
All books about the future are forward-looking.
The book Three-Body Problem has sold more than 1 million copies.
The Three-Body Problem is about the future.
*** Conclusion:
 The Three-Body Problem is forward-looking.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All books written by Cixin Liu have sold more than 1 million copies.
Some books that have won the Hugo Award were written by Cixin Liu.
All books about the future are forward-looking.
The book Three-Body Problem has sold more than 1 million copies.
The Three-Body Problem is about the future.
*** Conclusion:
 The Three-Body Problem was written by Cixin Liu.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a Leetcode problem is at the easy level, then its AC rate is lower than 20 percent.
All Leetcode problems that are recommended to novices are easy.
A Leetode problem is either easy or hard.
Leetcode problems that are starred by more than one thousand users are hard.
2Sum is recommended to novices.
4Sum is starred by more than 1,000 users.
*** Conclusion:
 2Sum is a Leetcode problem at the easy level.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a Leetcode problem is at the easy level, then its AC rate is lower than 20 percent.
All Leetcode problems that are recommended to novices are easy.
A Leetode problem is either easy or hard.
Leetcode problems that are starred by more than one thousand users are hard.
2Sum is recommended to novices.
4Sum is starred by more than 1,000 users.
*** Conclusion:
 4Sum is a Leetcode problem recommended to the novice.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a Leetcode problem is at the easy level, then its AC rate is lower than 20 percent.
All Leetcode problems that are recommended to novices are easy.
A Leetode problem is either easy or hard.
Leetcode problems that are starred by more than one thousand users are hard.
2Sum is recommended to novices.
4Sum is starred by more than 1,000 users.
*** Conclusion:
 2Sum has an AC rate higher than 20 percent.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Philatelic literature is divided into the following categories: Stamp catalogs, Periodicals, Auction catalogs, Books, Bibliographies, and Background Material.
Mort is not a Stamp catalog.
Mort is not a periodical, auction catalog, bibliography, or background material.
Mort is a piece of Philatelic literature.
*** Conclusion:
 Mort is background material.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Philatelic literature is divided into the following categories: Stamp catalogs, Periodicals, Auction catalogs, Books, Bibliographies, and Background Material.
Mort is not a Stamp catalog.
Mort is not a periodical, auction catalog, bibliography, or background material.
Mort is a piece of Philatelic literature.
*** Conclusion:
 Eragon is a piece of Philatelic literature.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some mammals have teeth.
Platypuses have no teeth.
Platypuses are mammals.
Humans have teeth.
*** Conclusion:
 Platypuses are mammals with no teeth.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some mammals have teeth.
Platypuses have no teeth.
Platypuses are mammals.
Humans have teeth.
*** Conclusion:
 Platypuses are reptiles.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some mammals have teeth.
Platypuses have no teeth.
Platypuses are mammals.
Humans have teeth.
*** Conclusion:
 Humans are mammals.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Xiufeng, Xiangshan, Diecai, Qixing are districts in the city of Guilin.
Yangshuo is not a district in Guilin.
*** Conclusion:
 Xiangshan and Diecai are districts in the same city.
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Xiufeng, Xiangshan, Diecai, Qixing are districts in the city of Guilin.
Yangshuo is not a district in Guilin.
*** Conclusion:
 Xiufeng is a district in Guilin.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Xiufeng, Xiangshan, Diecai, Qixing are districts in the city of Guilin.
Yangshuo is not a district in Guilin.
*** Conclusion:
 Kowloon District is in Hong Kong.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jason Kramer is an American music supervisor.
Some American radio personalities are also music supervisors.
Anyone who hosts a show on a public radio station is a radio personality.
Joe Rogan is a radio personality.
Jason Kramer hosted a show on a public radio station.
*** Conclusion:
 Joe Rogan is American.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jason Kramer is an American music supervisor.
Some American radio personalities are also music supervisors.
Anyone who hosts a show on a public radio station is a radio personality.
Joe Rogan is a radio personality.
Jason Kramer hosted a show on a public radio station.
*** Conclusion:
 Jason Kramer is a music supervisor.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jason Kramer is an American music supervisor.
Some American radio personalities are also music supervisors.
Anyone who hosts a show on a public radio station is a radio personality.
Joe Rogan is a radio personality.
Jason Kramer hosted a show on a public radio station.
*** Conclusion:
 Jason Kramer is a radio personality.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Gasteren is a village located in the province of Drenthe.
Drenthe is a Dutch province.
No cities are villages.
The population of a village in Drenthe was 155 people.
*** Conclusion:
 Gasteren is a Dutch village.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Gasteren is a village located in the province of Drenthe.
Drenthe is a Dutch province.
No cities are villages.
The population of a village in Drenthe was 155 people.
*** Conclusion:
 Gasteren is a city.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Gasteren is a village located in the province of Drenthe.
Drenthe is a Dutch province.
No cities are villages.
The population of a village in Drenthe was 155 people.
*** Conclusion:
 Gasteren has a population of 155.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 EndGame is a movie released in 2006.
EndGame was set in Washington.
EndGame was filmed outside of Washington.
Some movies are filmed in New York.
Andy Chang directed EndGame.
Andy Chang is from Hong Kong.
*** Conclusion:
 EndGame was filmed in New York.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 EndGame is a movie released in 2006.
EndGame was set in Washington.
EndGame was filmed outside of Washington.
Some movies are filmed in New York.
Andy Chang directed EndGame.
Andy Chang is from Hong Kong.
*** Conclusion:
 EndGame was not directed by someone from Hong Kong.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 EndGame is a movie released in 2006.
EndGame was set in Washington.
EndGame was filmed outside of Washington.
Some movies are filmed in New York.
Andy Chang directed EndGame.
Andy Chang is from Hong Kong.
*** Conclusion:
 All of Andy Chang's movies are filmed outside of Washington.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Naive cynicism was proposed by Justin Kruger and a colleague.
Thomas Gilovich is a colleague of Justin Kruger.
Naive cynicism is a philosophy of mind.
*** Conclusion:
 Thomas Gilovich proposed naive cynicism.
*** True Label:
 U
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Naive cynicism was proposed by Justin Kruger and a colleague.
Thomas Gilovich is a colleague of Justin Kruger.
Naive cynicism is a philosophy of mind.
*** Conclusion:
 Justin Kruger proposed a philosophy of mind.
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Naive cynicism was proposed by Justin Kruger and a colleague.
Thomas Gilovich is a colleague of Justin Kruger.
Naive cynicism is a philosophy of mind.
*** Conclusion:
 Thomas Gilovich worked on philosophies of mind.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Hugh Vanstone is one of the world's leading lighting designers.
Hugh Vanstone is from the UK.
Hugh Vanstone has lit more than 160 productions.
Hugh Vanstone attended a school where he is from.
*** Conclusion:
 Hugh Vanstone is one of the world's leading lighting designers and is from the UK.
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Hugh Vanstone is one of the world's leading lighting designers.
Hugh Vanstone is from the UK.
Hugh Vanstone has lit more than 160 productions.
Hugh Vanstone attended a school where he is from.
*** Conclusion:
 Hugh Vanstone has lit 170 productions.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Hugh Vanstone is one of the world's leading lighting designers.
Hugh Vanstone is from the UK.
Hugh Vanstone has lit more than 160 productions.
Hugh Vanstone attended a school where he is from.
*** Conclusion:
 Hugh Vanstone attended a school in the United States.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Joseph Kmak was born in Napa.
Joseph Kmak was a professional baseball player.
Professional baseball players play in the MLB.
People born in California are Americans.
Americans are not Germans.
*** Conclusion:
 Joseph Kmak is German.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Joseph Kmak was born in Napa.
Joseph Kmak was a professional baseball player.
Professional baseball players play in the MLB.
People born in California are Americans.
Americans are not Germans.
*** Conclusion:
 Joseph Kmak played in the MLB.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Joseph Kmak was born in Napa.
Joseph Kmak was a professional baseball player.
Professional baseball players play in the MLB.
People born in California are Americans.
Americans are not Germans.
*** Conclusion:
 Joseph Kmak was a catcher
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Rafa Nadal was born in Mallorca.
Rafa Nadal is a professional tennis player.
Nadal's win ratio is high.
All players in the Big 3 are professionals who have a high win ratio.
*** Conclusion:
 Nadal was not born in Mallorca.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Rafa Nadal was born in Mallorca.
Rafa Nadal is a professional tennis player.
Nadal's win ratio is high.
All players in the Big 3 are professionals who have a high win ratio.
*** Conclusion:
 Nadal is in the Big 3.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Rafa Nadal was born in Mallorca.
Rafa Nadal is a professional tennis player.
Nadal's win ratio is high.
All players in the Big 3 are professionals who have a high win ratio.
*** Conclusion:
 Nadal is the greatest player of all time.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 An Olympian is a person who trains for an Olympic sport and goes to the Olympics.
Carlos Reyes trains for an Olympic sport.
Carlos Reyes went to the Olympics.
Carlos Reyes is a welterweight.
Heavy weights are not welterweights.
*** Conclusion:
 Carlos Reyes is an Olympian.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 An Olympian is a person who trains for an Olympic sport and goes to the Olympics.
Carlos Reyes trains for an Olympic sport.
Carlos Reyes went to the Olympics.
Carlos Reyes is a welterweight.
Heavy weights are not welterweights.
*** Conclusion:
 Carlos Reyes is a heavy weight.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 An Olympian is a person who trains for an Olympic sport and goes to the Olympics.
Carlos Reyes trains for an Olympic sport.
Carlos Reyes went to the Olympics.
Carlos Reyes is a welterweight.
Heavy weights are not welterweights.
*** Conclusion:
 Carlos Reyes won an Olympic medal.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Tyga is a rapper.
Rappers release rap albums.
Tyga released the Well Done 3 album.
Rappers are not opera singers.
*** Conclusion:
 Well Done 3 is a rap album.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Tyga is a rapper.
Rappers release rap albums.
Tyga released the Well Done 3 album.
Rappers are not opera singers.
*** Conclusion:
 Tyga is an opera singer.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Tyga is a rapper.
Rappers release rap albums.
Tyga released the Well Done 3 album.
Rappers are not opera singers.
*** Conclusion:
 Well Done 3 is worth listening to.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Heptalogyy is a compound literary or narrative work that is made up of seven distinct works.
The Harry Potter series consists of 7 distinct works.
The Chronicles of Narnia consists of 7 distinct works.
*** Conclusion:
 The Harry Potter series of books is Heptalogy.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Heptalogyy is a compound literary or narrative work that is made up of seven distinct works.
The Harry Potter series consists of 7 distinct works.
The Chronicles of Narnia consists of 7 distinct works.
*** Conclusion:
 The Chronicles of Narnia series of books is not Heptalogy.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Heptalogyy is a compound literary or narrative work that is made up of seven distinct works.
The Harry Potter series consists of 7 distinct works.
The Chronicles of Narnia consists of 7 distinct works.
*** Conclusion:
 The Lord of the Rings is Heptalogy.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Metropolitan Museum of Art is a museum in NYC.
Whitney Museum of American Art is a museum in NYC.
The Museum of Modern Art (MoMA) is a museum in NYC.
The Metropolitan Museum of Art includes Byzantine and Islamic Art.
Whitney Museum of American Art includes American art.
*** Conclusion:
 A museum in NYC includes Byzantine and Islamic Art.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Metropolitan Museum of Art is a museum in NYC.
Whitney Museum of American Art is a museum in NYC.
The Museum of Modern Art (MoMA) is a museum in NYC.
The Metropolitan Museum of Art includes Byzantine and Islamic Art.
Whitney Museum of American Art includes American art.
*** Conclusion:
 A museum in NYC includes American art.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Metropolitan Museum of Art is a museum in NYC.
Whitney Museum of American Art is a museum in NYC.
The Museum of Modern Art (MoMA) is a museum in NYC.
The Metropolitan Museum of Art includes Byzantine and Islamic Art.
Whitney Museum of American Art includes American art.
*** Conclusion:
 A museum in NYC includes Greek art.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 "Your Woman" is a song by the British one-person band White Town.
"Your Woman" song peaked at No. 1 on the UK Singles Chart.
If a song peaked at No.1 at a particular place, it was extremely popular.
"Your Woman" peaked at No. 1 in Iceland, Israel, and Spain.
*** Conclusion:
 "Your Woman" was extremely popular.
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 "Your Woman" is a song by the British one-person band White Town.
"Your Woman" song peaked at No. 1 on the UK Singles Chart.
If a song peaked at No.1 at a particular place, it was extremely popular.
"Your Woman" peaked at No. 1 in Iceland, Israel, and Spain.
*** Conclusion:
 White Town did not produce any popular songs.
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 "Your Woman" is a song by the British one-person band White Town.
"Your Woman" song peaked at No. 1 on the UK Singles Chart.
If a song peaked at No.1 at a particular place, it was extremely popular.
"Your Woman" peaked at No. 1 in Iceland, Israel, and Spain.
*** Conclusion:
 White Town was a successful band.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If someone can run far and navigate using a map, they can participate in orienteering.
Fit people can run far.
People who have a good sense of direction can use a map.
Military officers are fit.
Hailee is a military officer and has a good sense of direction.
Karl is not a military officer and can use a map.
*** Conclusion:
 Hailee can participate in orienteering.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If someone can run far and navigate using a map, they can participate in orienteering.
Fit people can run far.
People who have a good sense of direction can use a map.
Military officers are fit.
Hailee is a military officer and has a good sense of direction.
Karl is not a military officer and can use a map.
*** Conclusion:
 Karl can not participate in orienteering.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Federico Garcia Lorca was a talented Spanish poet, and he supported the Popular Front.
The Spanish Nationalists opposed anyone who supported the Popular Front
Talented poets are popular.
Spanish Nationalists killed anyone who they opposed and who was popular.
Daniel supported the Popular Front but was not popular.
*** Conclusion:
 The Spanish Nationalists killed Daniel.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Federico Garcia Lorca was a talented Spanish poet, and he supported the Popular Front.
The Spanish Nationalists opposed anyone who supported the Popular Front
Talented poets are popular.
Spanish Nationalists killed anyone who they opposed and who was popular.
Daniel supported the Popular Front but was not popular.
*** Conclusion:
 The Spanish Nationalists killed Lorca.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 James Cocks was a British lawyer.
James Cocks was a Whig politician who sat in the House of Commons.
A British is a European.
Any lawyer is familiar with laws.
Some Whigs speak French.
*** Conclusion:
 No lawyer ever sat in the House of Commons.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 James Cocks was a British lawyer.
James Cocks was a Whig politician who sat in the House of Commons.
A British is a European.
Any lawyer is familiar with laws.
Some Whigs speak French.
*** Conclusion:
 Some European was familiar with laws.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 James Cocks was a British lawyer.
James Cocks was a Whig politician who sat in the House of Commons.
A British is a European.
Any lawyer is familiar with laws.
Some Whigs speak French.
*** Conclusion:
 James Cocks speaks French.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Imagine Dragons are an American pop-rock band.
The lead singer of Imagine Dragons is Dan.
Dan is also a songwriter.
All lead singers are singers.
All singers are musicians.
Demons is one of the most popular singles of Imagine Dragons.
Some singles of Imagine Dragons have been on Billboard Hot 100.
*** Conclusion:
 Some rock band has a lead singer who is also a songwriter.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Imagine Dragons are an American pop-rock band.
The lead singer of Imagine Dragons is Dan.
Dan is also a songwriter.
All lead singers are singers.
All singers are musicians.
Demons is one of the most popular singles of Imagine Dragons.
Some singles of Imagine Dragons have been on Billboard Hot 100.
*** Conclusion:
 Dan is not a musician.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Imagine Dragons are an American pop-rock band.
The lead singer of Imagine Dragons is Dan.
Dan is also a songwriter.
All lead singers are singers.
All singers are musicians.
Demons is one of the most popular singles of Imagine Dragons.
Some singles of Imagine Dragons have been on Billboard Hot 100.
*** Conclusion:
 Demons has been on Billboard Hot 100.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Andrew Wilson is a British historian and political scientist.
Andrew Wilson specializes in all countries in Eastern Europe.
Poland is in Eastern Europe.
Andrew Wilson is born in Britain.
Britain is not in Eastern Europe.
*** Conclusion:
 Andrew Wilson is born in Eastern Europe.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Andrew Wilson is a British historian and political scientist.
Andrew Wilson specializes in all countries in Eastern Europe.
Poland is in Eastern Europe.
Andrew Wilson is born in Britain.
Britain is not in Eastern Europe.
*** Conclusion:
 Andrew Wilson specializes in Poland.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Andrew Wilson is a British historian and political scientist.
Andrew Wilson specializes in all countries in Eastern Europe.
Poland is in Eastern Europe.
Andrew Wilson is born in Britain.
Britain is not in Eastern Europe.
*** Conclusion:
 Andrew Wilson specializes in Britain.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Andrew Wilson is a British historian and political scientist.
Andrew Wilson specializes in all countries in Eastern Europe.
Poland is in Eastern Europe.
Andrew Wilson is born in Britain.
Britain is not in Eastern Europe.
*** Conclusion:
 No British are political scientists.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 SR 287 is in Alabama.
Alabama is in the United States.
US 31 intersects with SR 287.
CR 47 intersects with SR 287.
If place A is located in place B and place B is located in place C, then place A is located in place C.
*** Conclusion:
 US 31 is in Alabama.
*** True Label:
 U
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 SR 287 is in Alabama.
Alabama is in the United States.
US 31 intersects with SR 287.
CR 47 intersects with SR 287.
If place A is located in place B and place B is located in place C, then place A is located in place C.
*** Conclusion:
 CR 47 is not in Alabama.
*** True Label:
 U
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 SR 287 is in Alabama.
Alabama is in the United States.
US 31 intersects with SR 287.
CR 47 intersects with SR 287.
If place A is located in place B and place B is located in place C, then place A is located in place C.
*** Conclusion:
 SR 287 is in the United States.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Breeding back is a form of artificial selection by the deliberate selective breeding of domestic animals.
Heck cattle were bred back in the 1920s to resemble the aurochs.
Heck cattle are animals.
Aurochs are animals.
Some animals to be bred back resemble extinct animals.
*** Conclusion:
 Some Heck cattle are artificially selected.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Breeding back is a form of artificial selection by the deliberate selective breeding of domestic animals.
Heck cattle were bred back in the 1920s to resemble the aurochs.
Heck cattle are animals.
Aurochs are animals.
Some animals to be bred back resemble extinct animals.
*** Conclusion:
 Aurochs are extinct.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A controlled substance is a drug.
There exist both harmful and beneficial controlled substances.
If a child is exposed to a controlled substance, they are in chemical endangerment.
Chemical Endangerment is harmful.
The Controlled Substances Act was an act passed in 1971.
Some Acts prevent harmful things.
*** Conclusion:
 The Controlled Substances Act prevents harmful things.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A controlled substance is a drug.
There exist both harmful and beneficial controlled substances.
If a child is exposed to a controlled substance, they are in chemical endangerment.
Chemical Endangerment is harmful.
The Controlled Substances Act was an act passed in 1971.
Some Acts prevent harmful things.
*** Conclusion:
 Some drugs are beneficial.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A controlled substance is a drug.
There exist both harmful and beneficial controlled substances.
If a child is exposed to a controlled substance, they are in chemical endangerment.
Chemical Endangerment is harmful.
The Controlled Substances Act was an act passed in 1971.
Some Acts prevent harmful things.
*** Conclusion:
 A child in chemical endangerment is in harm.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Douglas Adams is an author who created the book collection called The Salmon of Doubt.
The Salmon of Doubt is about life experiences and technology.
All authors are writers.
Writers create innovative ideas.
Some books that contain innovative ideas are about technology.
*** Conclusion:
 Douglas Adams is a writer.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Douglas Adams is an author who created the book collection called The Salmon of Doubt.
The Salmon of Doubt is about life experiences and technology.
All authors are writers.
Writers create innovative ideas.
Some books that contain innovative ideas are about technology.
*** Conclusion:
 Douglas Adams created innovative ideas.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Douglas Adams is an author who created the book collection called The Salmon of Doubt.
The Salmon of Doubt is about life experiences and technology.
All authors are writers.
Writers create innovative ideas.
Some books that contain innovative ideas are about technology.
*** Conclusion:
 The Salmon of Doubt has no innovative Ideas.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quincy McDuffie is an American professional wide receiver in Canadian Football.
People who can catch balls are good wide receivers.
Quincy McDuffie can catch some footballs easily.
Good wide receivers play professionally.
Good wide receivers can catch with both their left and right hand.
All footballs are balls.
*** Conclusion:
 Quincy McDuffie is a good wide receiver.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quincy McDuffie is an American professional wide receiver in Canadian Football.
People who can catch balls are good wide receivers.
Quincy McDuffie can catch some footballs easily.
Good wide receivers play professionally.
Good wide receivers can catch with both their left and right hand.
All footballs are balls.
*** Conclusion:
 Quincy McDuffie can catch every ball.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quincy McDuffie is an American professional wide receiver in Canadian Football.
People who can catch balls are good wide receivers.
Quincy McDuffie can catch some footballs easily.
Good wide receivers play professionally.
Good wide receivers can catch with both their left and right hand.
All footballs are balls.
*** Conclusion:
 Professional wide receivers are good at catching balls.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a building has a top cover, that building has a roof.
Roofs protect people and block sunlight.
Some roofs are built out of concrete.
Some roofs are built out of seagrass.
Concrete is stronger than seagrass.
*** Conclusion:
 No roof means no protection.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a building has a top cover, that building has a roof.
Roofs protect people and block sunlight.
Some roofs are built out of concrete.
Some roofs are built out of seagrass.
Concrete is stronger than seagrass.
*** Conclusion:
 Roofs built out of concrete are stronger than roofs built out of seagrass.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a building has a top cover, that building has a roof.
Roofs protect people and block sunlight.
Some roofs are built out of concrete.
Some roofs are built out of seagrass.
Concrete is stronger than seagrass.
*** Conclusion:
 Concrete roofs do not block out sunlight.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The summer Olympic games is a sporting event.
The last summer Olympic games was in Tokyo.
The United States won the most medals in Tokyo.
*** Conclusion:
 The world championships is a sporting event.
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The summer Olympic games is a sporting event.
The last summer Olympic games was in Tokyo.
The United States won the most medals in Tokyo.
*** Conclusion:
 The last summer Olympic games were not in Tokyo.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The summer Olympic games is a sporting event.
The last summer Olympic games was in Tokyo.
The United States won the most medals in Tokyo.
*** Conclusion:
 The United States won the most medals in the last summer Olympic games.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Lumina APV is produced by Chevrolet.
The Astro is a van produced by Chevrolet.
Vehicles produced by Chevrolet in this batch are either cars or vans.
*** Conclusion:
 The Lumina APV is a van.
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Lumina APV is produced by Chevrolet.
The Astro is a van produced by Chevrolet.
Vehicles produced by Chevrolet in this batch are either cars or vans.
*** Conclusion:
 The Lumina APV is either a car or a van.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Lumina APV is produced by Chevrolet.
The Astro is a van produced by Chevrolet.
Vehicles produced by Chevrolet in this batch are either cars or vans.
*** Conclusion:
 The Astro is a van.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 The Lumina APV is produced by Chevrolet.
The Astro is a van produced by Chevrolet.
Vehicles produced by Chevrolet in this batch are either cars or vans.
*** Conclusion:
 The Astro is a car.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Pasifika New Zealanders are a pan-ethnic group of New Zealanders.
Asian New Zealanders are a pan-ethnic group of New Zealanders.
Pasifika New Zealanders are not Asian New Zealanders.
Pasifika New Zealanders speak Samoan.
Joe is a Pasifika New Zealander.
Amy speaks Samoan.
*** Conclusion:
 Amy is an Pasifika New Zealander.
*** True Label:
 U
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Pasifika New Zealanders are a pan-ethnic group of New Zealanders.
Asian New Zealanders are a pan-ethnic group of New Zealanders.
Pasifika New Zealanders are not Asian New Zealanders.
Pasifika New Zealanders speak Samoan.
Joe is a Pasifika New Zealander.
Amy speaks Samoan.
*** Conclusion:
 Amy is an Asian New Zealander.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Pasifika New Zealanders are a pan-ethnic group of New Zealanders.
Asian New Zealanders are a pan-ethnic group of New Zealanders.
Pasifika New Zealanders are not Asian New Zealanders.
Pasifika New Zealanders speak Samoan.
Joe is a Pasifika New Zealander.
Amy speaks Samoan.
*** Conclusion:
 Joe is an Asian New Zealander.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Pasifika New Zealanders are a pan-ethnic group of New Zealanders.
Asian New Zealanders are a pan-ethnic group of New Zealanders.
Pasifika New Zealanders are not Asian New Zealanders.
Pasifika New Zealanders speak Samoan.
Joe is a Pasifika New Zealander.
Amy speaks Samoan.
*** Conclusion:
 Joe speaks Samoan.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A roundel is a rounded artillery fortification.
A roundel is not higher than adjacent walls.
Cannons can be deployed on artillery fortifications.
Roundels are the oldest artillery fortifications.
Battery towers are artillery fortifications.
*** Conclusion:
 Cannons can be deployed on battery towers.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A roundel is a rounded artillery fortification.
A roundel is not higher than adjacent walls.
Cannons can be deployed on artillery fortifications.
Roundels are the oldest artillery fortifications.
Battery towers are artillery fortifications.
*** Conclusion:
 Roundels are older than battery towers.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A roundel is a rounded artillery fortification.
A roundel is not higher than adjacent walls.
Cannons can be deployed on artillery fortifications.
Roundels are the oldest artillery fortifications.
Battery towers are artillery fortifications.
*** Conclusion:
 Battery towers are higher than adjacent walls.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A roundel is a rounded artillery fortification.
A roundel is not higher than adjacent walls.
Cannons can be deployed on artillery fortifications.
Roundels are the oldest artillery fortifications.
Battery towers are artillery fortifications.
*** Conclusion:
 Cannons can be deployed on roundels.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A businessperson is someone who has ownership over part of a company.
People who own a company make money from it.
A businessperson can be either a businessman or a businesswoman.
Many businesspersons are extroverted.
Businesspersons can handle money well.
Bob is a businessman who has ownership over Microsoft.
*** Conclusion:
 Bob is extroverted.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A businessperson is someone who has ownership over part of a company.
People who own a company make money from it.
A businessperson can be either a businessman or a businesswoman.
Many businesspersons are extroverted.
Businesspersons can handle money well.
Bob is a businessman who has ownership over Microsoft.
*** Conclusion:
 Bob can handle money well.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A businessperson is someone who has ownership over part of a company.
People who own a company make money from it.
A businessperson can be either a businessman or a businesswoman.
Many businesspersons are extroverted.
Businesspersons can handle money well.
Bob is a businessman who has ownership over Microsoft.
*** Conclusion:
 Bob is a businessperson who makes money off Microsoft.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person is the leader of a country for life, that person has power.
Leaders of a country for life are either a king or a queen.
Queens are female.
Kings are male.
Elizabeth is a queen.
Elizabeth is a leader of a country for life.
*** Conclusion:
 Elizabeth is a king.
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person is the leader of a country for life, that person has power.
Leaders of a country for life are either a king or a queen.
Queens are female.
Kings are male.
Elizabeth is a queen.
Elizabeth is a leader of a country for life.
*** Conclusion:
 Elizabeth has power.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person is the leader of a country for life, that person has power.
Leaders of a country for life are either a king or a queen.
Queens are female.
Kings are male.
Elizabeth is a queen.
Elizabeth is a leader of a country for life.
*** Conclusion:
 Elizabeth is a leader of a country for life.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All pets are animals.
Pets can be either a dog or a cat.
If a person has a pet, they care for that pet.
Dogs and cats can be naughty.
Pets who are naughty are not liked as much.
Charlie has a naughty pet dog named Leo.
*** Conclusion:
 Leo is an animal.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All pets are animals.
Pets can be either a dog or a cat.
If a person has a pet, they care for that pet.
Dogs and cats can be naughty.
Pets who are naughty are not liked as much.
Charlie has a naughty pet dog named Leo.
*** Conclusion:
 Charlie does not like Leo and does not care for Leo.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All pets are animals.
Pets can be either a dog or a cat.
If a person has a pet, they care for that pet.
Dogs and cats can be naughty.
Pets who are naughty are not liked as much.
Charlie has a naughty pet dog named Leo.
*** Conclusion:
 Dogs are not always naughty.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Books contain tons of knowledge.
When a person reads a book, that person gains knowledge.
If a person gains knowledge, they become smarter.
Harry read the book “Walden” by Henry Thoreau.
*** Conclusion:
 Walden contains knowledge.
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Books contain tons of knowledge.
When a person reads a book, that person gains knowledge.
If a person gains knowledge, they become smarter.
Harry read the book “Walden” by Henry Thoreau.
*** Conclusion:
 Harry is smarter than before.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Books contain tons of knowledge.
When a person reads a book, that person gains knowledge.
If a person gains knowledge, they become smarter.
Harry read the book “Walden” by Henry Thoreau.
*** Conclusion:
 A smarter person has gained knowledge.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some monitors equipped in the lab are produced by the company named AOC.
All monitors equipped in the lab are cheaper than their original prices.
If a monitor is cheaper than its original price, then its resolution is 1080p.
If a monitor has a resolution of 1080p, then it does not support the type-c port.
LG34 is equipped in the lab.
*** Conclusion:
 LG34 machine is produced by AOC.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some monitors equipped in the lab are produced by the company named AOC.
All monitors equipped in the lab are cheaper than their original prices.
If a monitor is cheaper than its original price, then its resolution is 1080p.
If a monitor has a resolution of 1080p, then it does not support the type-c port.
LG34 is equipped in the lab.
*** Conclusion:
 LG34 machine does not support the type-c port.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Some monitors equipped in the lab are produced by the company named AOC.
All monitors equipped in the lab are cheaper than their original prices.
If a monitor is cheaper than its original price, then its resolution is 1080p.
If a monitor has a resolution of 1080p, then it does not support the type-c port.
LG34 is equipped in the lab.
*** Conclusion:
 LG34 is not with a resolution of 1080p.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All buildings in New Haven are not high.
All buildings managed by Yale Housing are located in New Haven.
All buildings in Manhattans are high.
All buildings owned by Bloomberg are located in Manhattans.
All buildings with the Bloomberg logo are owned by Bloomberg.
Tower A is managed by Yale Housing.
Tower B is with the Bloomberg logo.
*** Conclusion:
 Tower A is low.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All buildings in New Haven are not high.
All buildings managed by Yale Housing are located in New Haven.
All buildings in Manhattans are high.
All buildings owned by Bloomberg are located in Manhattans.
All buildings with the Bloomberg logo are owned by Bloomberg.
Tower A is managed by Yale Housing.
Tower B is with the Bloomberg logo.
*** Conclusion:
 Tower B is not located in Manhattans.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All buildings in New Haven are not high.
All buildings managed by Yale Housing are located in New Haven.
All buildings in Manhattans are high.
All buildings owned by Bloomberg are located in Manhattans.
All buildings with the Bloomberg logo are owned by Bloomberg.
Tower A is managed by Yale Housing.
Tower B is with the Bloomberg logo.
*** Conclusion:
 Tower B is located in New Haven.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 No coffee sold in Walmart is from France.
All coffee favored by local residents is from Columbia.
All coffee with high prices is favored by Jack.
Civet Coffee is coffee that's not from Columbia.
Jamaica Blue is expensive coffee.
Expensive coffee has a high price.
*** Conclusion:
 Civet Coffee is from France.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 No coffee sold in Walmart is from France.
All coffee favored by local residents is from Columbia.
All coffee with high prices is favored by Jack.
Civet Coffee is coffee that's not from Columbia.
Jamaica Blue is expensive coffee.
Expensive coffee has a high price.
*** Conclusion:
 Jamaica Blue is from Columbia.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 No coffee sold in Walmart is from France.
All coffee favored by local residents is from Columbia.
All coffee with high prices is favored by Jack.
Civet Coffee is coffee that's not from Columbia.
Jamaica Blue is expensive coffee.
Expensive coffee has a high price.
*** Conclusion:
 Jamaica Blue is favored by local residents.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All devices belonging to the company are connected to Google Home.
All devices belonging to employees are connected to the company's wifi.
All devices connected to Google Home are controlled by the managers.
All devices that connect to the company's wifi are easy to operate.
ModelXX belongs to employees.
*** Conclusion:
 ModelXX is easy to operate.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All devices belonging to the company are connected to Google Home.
All devices belonging to employees are connected to the company's wifi.
All devices connected to Google Home are controlled by the managers.
All devices that connect to the company's wifi are easy to operate.
ModelXX belongs to employees.
*** Conclusion:
 ModelXX is controlled by managers.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All devices belonging to the company are connected to Google Home.
All devices belonging to employees are connected to the company's wifi.
All devices connected to Google Home are controlled by the managers.
All devices that connect to the company's wifi are easy to operate.
ModelXX belongs to employees.
*** Conclusion:
 ModelXX is connected to Google Home.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All students who attend in person have registered for the conference.
Students either attend the conference in person or remotely.
No students from China attend the conference remotely.
James attends the conference, but he does not attend the conference remotely.
Jack attends the conference, and he is a student from China.
*** Conclusion:
 James attends the conference but not in person.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All students who attend in person have registered for the conference.
Students either attend the conference in person or remotely.
No students from China attend the conference remotely.
James attends the conference, but he does not attend the conference remotely.
Jack attends the conference, and he is a student from China.
*** Conclusion:
 Jack attends the conference in person.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All students who attend in person have registered for the conference.
Students either attend the conference in person or remotely.
No students from China attend the conference remotely.
James attends the conference, but he does not attend the conference remotely.
Jack attends the conference, and he is a student from China.
*** Conclusion:
 Jack has registered for the conference.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A podcast is not a novel.
If a person is born in American City, the person is American.
If a book is a novel and it is written by a person, then the person is a novel writer.
Dani Shapiro is an American writer.
Family History is written by Dani Shapiro.
Family History is a novel written in 2003.
Dani Shapiro created a podcast called Family Secrets.
Boston is an American city.
*** Conclusion:
 Dani Shapiro is a novel writer.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A podcast is not a novel.
If a person is born in American City, the person is American.
If a book is a novel and it is written by a person, then the person is a novel writer.
Dani Shapiro is an American writer.
Family History is written by Dani Shapiro.
Family History is a novel written in 2003.
Dani Shapiro created a podcast called Family Secrets.
Boston is an American city.
*** Conclusion:
 Family Secrets is a novel.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 A podcast is not a novel.
If a person is born in American City, the person is American.
If a book is a novel and it is written by a person, then the person is a novel writer.
Dani Shapiro is an American writer.
Family History is written by Dani Shapiro.
Family History is a novel written in 2003.
Dani Shapiro created a podcast called Family Secrets.
Boston is an American city.
*** Conclusion:
 Dani Shapiro was born in Boston.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person coaches a football club, the person is a football coach.
If a person has a position in a club in a year, and the club is in NFL in the same year, the person plays in NFL.
Minnesota Vikings is a football club.
Dennis Green coached Minnesota Vikings.
Cris Carter had 13 touchdown receptions.
Minnesota Vikings were in the National Football League in 1997.
John Randle was Minnesota Vikings defensive tackle in 1997.
*** Conclusion:
 Dennis Green is a football coach.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person coaches a football club, the person is a football coach.
If a person has a position in a club in a year, and the club is in NFL in the same year, the person plays in NFL.
Minnesota Vikings is a football club.
Dennis Green coached Minnesota Vikings.
Cris Carter had 13 touchdown receptions.
Minnesota Vikings were in the National Football League in 1997.
John Randle was Minnesota Vikings defensive tackle in 1997.
*** Conclusion:
 John Randle didn't play in the National Football League.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a person coaches a football club, the person is a football coach.
If a person has a position in a club in a year, and the club is in NFL in the same year, the person plays in NFL.
Minnesota Vikings is a football club.
Dennis Green coached Minnesota Vikings.
Cris Carter had 13 touchdown receptions.
Minnesota Vikings were in the National Football League in 1997.
John Randle was Minnesota Vikings defensive tackle in 1997.
*** Conclusion:
 Cris Carter played for Minnesota Vikings.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a city holds a Summer Olympics, and the city is a US city, then the Summer Olympics will be in the US.
If a city is in a state in the US, the city is a US city.
If a city is in a state, and a Summer Olympics is in this city, then the Summer Olympics is in this state.
The 2028 Summer Olympics is scheduled to take place in Los Angeles.
Los Angeles is a city in California.
Atlanta is a US city.
Atlanta is in Georgia.
California is a state in the United States.
Boxing, modern pentathlon, and weightlifting will be removed from The 2028 Summer Olympics.
Atlanta in the United States held the 1996 Summer Olympics.
*** Conclusion:
 The 2028 Summer Olympics will take place in the US.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a city holds a Summer Olympics, and the city is a US city, then the Summer Olympics will be in the US.
If a city is in a state in the US, the city is a US city.
If a city is in a state, and a Summer Olympics is in this city, then the Summer Olympics is in this state.
The 2028 Summer Olympics is scheduled to take place in Los Angeles.
Los Angeles is a city in California.
Atlanta is a US city.
Atlanta is in Georgia.
California is a state in the United States.
Boxing, modern pentathlon, and weightlifting will be removed from The 2028 Summer Olympics.
Atlanta in the United States held the 1996 Summer Olympics.
*** Conclusion:
 The 1996 Summer Olympics is not in Georgia.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a city holds a Summer Olympics, and the city is a US city, then the Summer Olympics will be in the US.
If a city is in a state in the US, the city is a US city.
If a city is in a state, and a Summer Olympics is in this city, then the Summer Olympics is in this state.
The 2028 Summer Olympics is scheduled to take place in Los Angeles.
Los Angeles is a city in California.
Atlanta is a US city.
Atlanta is in Georgia.
California is a state in the United States.
Boxing, modern pentathlon, and weightlifting will be removed from The 2028 Summer Olympics.
Atlanta in the United States held the 1996 Summer Olympics.
*** Conclusion:
 Skateboarding will appear at The 2028 Summer Olympics.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If an album is written by a rock band, then the genre of the album is rock.
If a band writes an album winning an award, then this band wins this award.
Trouble at the Henhouse is an album by The Tragically Hip.
The Tragically Hip is a Canadian rock band.
The song "Butts Wigglin'" is in Trouble at the Henhouse.
Trouble at the Henhouse won the Album of the Year award.
A song in Trouble at the Henhouse appeared in a film.
*** Conclusion:
 The genre of Trouble at the Henhouse is rock.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If an album is written by a rock band, then the genre of the album is rock.
If a band writes an album winning an award, then this band wins this award.
Trouble at the Henhouse is an album by The Tragically Hip.
The Tragically Hip is a Canadian rock band.
The song "Butts Wigglin'" is in Trouble at the Henhouse.
Trouble at the Henhouse won the Album of the Year award.
A song in Trouble at the Henhouse appeared in a film.
*** Conclusion:
 No Canadian rock band has won the Album of the Year award.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If an album is written by a rock band, then the genre of the album is rock.
If a band writes an album winning an award, then this band wins this award.
Trouble at the Henhouse is an album by The Tragically Hip.
The Tragically Hip is a Canadian rock band.
The song "Butts Wigglin'" is in Trouble at the Henhouse.
Trouble at the Henhouse won the Album of the Year award.
A song in Trouble at the Henhouse appeared in a film.
*** Conclusion:
 "Butts Wigglin'" appeared in a film.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lana Wilson directed After Tiller, The Departure, and Miss Americana.
If a film is directed by a person, the person is a filmmaker.
After Tiller is a documentary.
The documentary is a type of film.
Lana Wilson is from Kirkland.
Kirkland is a US city.
If a person is from a city in a country, the person is from the country.
After Tiller is nominated for the Independent Spirit Award for Best Documentary.
*** Conclusion:
 Lana Wilson is a US filmmaker.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lana Wilson directed After Tiller, The Departure, and Miss Americana.
If a film is directed by a person, the person is a filmmaker.
After Tiller is a documentary.
The documentary is a type of film.
Lana Wilson is from Kirkland.
Kirkland is a US city.
If a person is from a city in a country, the person is from the country.
After Tiller is nominated for the Independent Spirit Award for Best Documentary.
*** Conclusion:
 Miss Americana is not directed by a filmmaker from Kirkland.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lana Wilson directed After Tiller, The Departure, and Miss Americana.
If a film is directed by a person, the person is a filmmaker.
After Tiller is a documentary.
The documentary is a type of film.
Lana Wilson is from Kirkland.
Kirkland is a US city.
If a person is from a city in a country, the person is from the country.
After Tiller is nominated for the Independent Spirit Award for Best Documentary.
*** Conclusion:
 Lana Wilson has won the Independent Spirit Award.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Brian Winter is a Scottish football referee.
After being injured, Brian Winter retired in 2012.
Brian Winter was appointed as a referee observer after his retirement.
Some football referees become referee observers.
The son of Brian Winter, Andy Winter, is a football player who plays for Hamilton Academical.
*** Conclusion:
 There is a son of a referee observer that plays football.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Brian Winter is a Scottish football referee.
After being injured, Brian Winter retired in 2012.
Brian Winter was appointed as a referee observer after his retirement.
Some football referees become referee observers.
The son of Brian Winter, Andy Winter, is a football player who plays for Hamilton Academical.
*** Conclusion:
 Brian Winter was not a referee observer.
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Brian Winter is a Scottish football referee.
After being injured, Brian Winter retired in 2012.
Brian Winter was appointed as a referee observer after his retirement.
Some football referees become referee observers.
The son of Brian Winter, Andy Winter, is a football player who plays for Hamilton Academical.
*** Conclusion:
 Brian Winter is retired.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Brian Winter is a Scottish football referee.
After being injured, Brian Winter retired in 2012.
Brian Winter was appointed as a referee observer after his retirement.
Some football referees become referee observers.
The son of Brian Winter, Andy Winter, is a football player who plays for Hamilton Academical.
*** Conclusion:
 Andy Winter is a referee.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Michael O'Donnell is a British physician, journalist, author, and broadcaster.
One of the word-setters of My Word! was Michael O'Donnell.
The magazine World Medicine was edited by Michael O'Donnell.
Michael O'Donnell was born in Yorkshire as the son of a general practitioner.
*** Conclusion:
 The son of a general practitioner was a word-setter of My Word!.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Michael O'Donnell is a British physician, journalist, author, and broadcaster.
One of the word-setters of My Word! was Michael O'Donnell.
The magazine World Medicine was edited by Michael O'Donnell.
Michael O'Donnell was born in Yorkshire as the son of a general practitioner.
*** Conclusion:
 World Medicine is not a magazine.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Michael O'Donnell is a British physician, journalist, author, and broadcaster.
One of the word-setters of My Word! was Michael O'Donnell.
The magazine World Medicine was edited by Michael O'Donnell.
Michael O'Donnell was born in Yorkshire as the son of a general practitioner.
*** Conclusion:
 There are no British authors.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Michael O'Donnell is a British physician, journalist, author, and broadcaster.
One of the word-setters of My Word! was Michael O'Donnell.
The magazine World Medicine was edited by Michael O'Donnell.
Michael O'Donnell was born in Yorkshire as the son of a general practitioner.
*** Conclusion:
 There are no journalists that were born in Yorkshire.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Michael O'Donnell is a British physician, journalist, author, and broadcaster.
One of the word-setters of My Word! was Michael O'Donnell.
The magazine World Medicine was edited by Michael O'Donnell.
Michael O'Donnell was born in Yorkshire as the son of a general practitioner.
*** Conclusion:
 There is a son of a general practitioner that is not an author.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Herodicus was a Greek physician, dietician, sophist, and gymnast.
Herodicus was born in the city of Selymbria.
Selymbria is a colony of the city-state Megara.
One of the tutors of Hippocrates was Herodicus.
Massages were recommended by Herodicus.
Some of the theories of Herodicus are considered to be the foundation of sports medicine.
*** Conclusion:
 Herodicus tutored Hippocrates.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Herodicus was a Greek physician, dietician, sophist, and gymnast.
Herodicus was born in the city of Selymbria.
Selymbria is a colony of the city-state Megara.
One of the tutors of Hippocrates was Herodicus.
Massages were recommended by Herodicus.
Some of the theories of Herodicus are considered to be the foundation of sports medicine.
*** Conclusion:
 Herodicus was tutored by Hippocrates.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Herodicus was a Greek physician, dietician, sophist, and gymnast.
Herodicus was born in the city of Selymbria.
Selymbria is a colony of the city-state Megara.
One of the tutors of Hippocrates was Herodicus.
Massages were recommended by Herodicus.
Some of the theories of Herodicus are considered to be the foundation of sports medicine.
*** Conclusion:
 Herodicus was born in a city-state.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Herodicus was a Greek physician, dietician, sophist, and gymnast.
Herodicus was born in the city of Selymbria.
Selymbria is a colony of the city-state Megara.
One of the tutors of Hippocrates was Herodicus.
Massages were recommended by Herodicus.
Some of the theories of Herodicus are considered to be the foundation of sports medicine.
*** Conclusion:
 Herodicus did not recommend massages.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Herodicus was a Greek physician, dietician, sophist, and gymnast.
Herodicus was born in the city of Selymbria.
Selymbria is a colony of the city-state Megara.
One of the tutors of Hippocrates was Herodicus.
Massages were recommended by Herodicus.
Some of the theories of Herodicus are considered to be the foundation of sports medicine.
*** Conclusion:
 Herodicus was born in a colony of a city-state.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Enterococcus durans is a species of Enterococcus.
Enterococcus durans is a gram-positive, catalase- and oxidase-negative, coccus bacterium.
Some strains of Enterococcus durans have been identified as producers of anti-inflammatory agents.
All known anti-inflammatory agents have been studied in medical research.
*** Conclusion:
 Enterococcus durans is a catalase-negative bacteria.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Enterococcus durans is a species of Enterococcus.
Enterococcus durans is a gram-positive, catalase- and oxidase-negative, coccus bacterium.
Some strains of Enterococcus durans have been identified as producers of anti-inflammatory agents.
All known anti-inflammatory agents have been studied in medical research.
*** Conclusion:
 A gram-positive organism is being studied.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Enterococcus durans is a species of Enterococcus.
Enterococcus durans is a gram-positive, catalase- and oxidase-negative, coccus bacterium.
Some strains of Enterococcus durans have been identified as producers of anti-inflammatory agents.
All known anti-inflammatory agents have been studied in medical research.
*** Conclusion:
 Enterococcus durans does not produce anything that is being studied.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ambiortus is a prehistoric bird genus.
Ambiortus Dementjevi is the only known species of Ambiortus.
Mongolia was where Ambiortus Dementjevi lived.
Yevgeny Kurochkin was the discoverer of Ambiortus.
*** Conclusion:
 Yevgeny Kurochkin discovered a new bird genus.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ambiortus is a prehistoric bird genus.
Ambiortus Dementjevi is the only known species of Ambiortus.
Mongolia was where Ambiortus Dementjevi lived.
Yevgeny Kurochkin was the discoverer of Ambiortus.
*** Conclusion:
 There is a species of Ambiortus that doesn't live in Mongolia.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ambiortus is a prehistoric bird genus.
Ambiortus Dementjevi is the only known species of Ambiortus.
Mongolia was where Ambiortus Dementjevi lived.
Yevgeny Kurochkin was the discoverer of Ambiortus.
*** Conclusion:
 Yevgeny Kurochkin lived in Mongolia.
*** True Label:
 U
*** Predicted Label:
  T </output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ambiortus is a prehistoric bird genus.
Ambiortus Dementjevi is the only known species of Ambiortus.
Mongolia was where Ambiortus Dementjevi lived.
Yevgeny Kurochkin was the discoverer of Ambiortus.
*** Conclusion:
 All species of Ambiortus live in Mongolia.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Camp Davern is a traditional summer camp for boys and girls.
Camp Davern was established in the year 1946.
Camp Davern was operated by the YMCA until the year 2015.
Camp Davern is an old summer camp.
*** Conclusion:
 One of Ontario's oldest summer camps is a traditional summer camp for boys and girls.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Camp Davern is a traditional summer camp for boys and girls.
Camp Davern was established in the year 1946.
Camp Davern was operated by the YMCA until the year 2015.
Camp Davern is an old summer camp.
*** Conclusion:
 A traditional summer camp for boys and girls was operated by the YMCA until the year 2015.
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Camp Davern is a traditional summer camp for boys and girls.
Camp Davern was established in the year 1946.
Camp Davern was operated by the YMCA until the year 2015.
Camp Davern is an old summer camp.
*** Conclusion:
 Camp Davern was established in 1989.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Zimmer was a philosopher born in Germany.
Robert Zimmer is an essayist.
Robert Zimmer was born in 1953.
Every essayist is a writer.
*** Conclusion:
 Robert Zimmer is German.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Zimmer was a philosopher born in Germany.
Robert Zimmer is an essayist.
Robert Zimmer was born in 1953.
Every essayist is a writer.
*** Conclusion:
 Robert Zimmer is not a writer.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Zimmer was a philosopher born in Germany.
Robert Zimmer is an essayist.
Robert Zimmer was born in 1953.
Every essayist is a writer.
*** Conclusion:
 Robert Zimmer is a biographer.
*** True Label:
 U
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Asa Hoffmann was born in New York City.
Asa Hoffman lives in Manhattan.
Asa Hoffman is a chess player.
Some chess players are grandmasters.
People born and living in New York City are New Yorkers.
People living in Manhattan live in New York City.
*** Conclusion:
 Asa Hoffmann is a New Yorker.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Asa Hoffmann was born in New York City.
Asa Hoffman lives in Manhattan.
Asa Hoffman is a chess player.
Some chess players are grandmasters.
People born and living in New York City are New Yorkers.
People living in Manhattan live in New York City.
*** Conclusion:
 Asa Hoffmann is a grandmaster.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Asa Hoffmann was born in New York City.
Asa Hoffman lives in Manhattan.
Asa Hoffman is a chess player.
Some chess players are grandmasters.
People born and living in New York City are New Yorkers.
People living in Manhattan live in New York City.
*** Conclusion:
 Asa Hoffmann does not live in New York.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jan Jelinek makes glitch and minimal techno music.
Anyone making glitch, minimal techno, or microhouse is an electronic musician.
Jan Jelinek publishes music through the Faitiche label.
Any musician releasing music through a label is a signed musician.
*** Conclusion:
 Jan Jelinek is an electronic musician.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jan Jelinek makes glitch and minimal techno music.
Anyone making glitch, minimal techno, or microhouse is an electronic musician.
Jan Jelinek publishes music through the Faitiche label.
Any musician releasing music through a label is a signed musician.
*** Conclusion:
 Jan Jelinek is not a signed musician.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Jan Jelinek makes glitch and minimal techno music.
Anyone making glitch, minimal techno, or microhouse is an electronic musician.
Jan Jelinek publishes music through the Faitiche label.
Any musician releasing music through a label is a signed musician.
*** Conclusion:
 Jan Jelinek is German.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ableton has an office in Germany.
Ableton has an office in the USA.
USA and Germany are different countries.
Any company that has offices in different countries is a multinational company.
Ableton makes music software.
*** Conclusion:
 Ableton is a multinational company.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ableton has an office in Germany.
Ableton has an office in the USA.
USA and Germany are different countries.
Any company that has offices in different countries is a multinational company.
Ableton makes music software.
*** Conclusion:
 Ableton makes AI software.
*** True Label:
 U
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ableton has an office in Germany.
Ableton has an office in the USA.
USA and Germany are different countries.
Any company that has offices in different countries is a multinational company.
Ableton makes music software.
*** Conclusion:
 Ableton does not have an office in Germany.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Lewandowski is a striker.
Strikers are soccer players.
Robert Lewandowski left Bayern Munchen.
If a player leaves a team they no longer play for that team.
*** Conclusion:
 Robert Lewandowski is a soccer player.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Lewandowski is a striker.
Strikers are soccer players.
Robert Lewandowski left Bayern Munchen.
If a player leaves a team they no longer play for that team.
*** Conclusion:
 Robert Lewandowski plays for Bayern Munchen.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Robert Lewandowski is a striker.
Strikers are soccer players.
Robert Lewandowski left Bayern Munchen.
If a player leaves a team they no longer play for that team.
*** Conclusion:
 Robert Lewandowski is a star.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 New Vessel Press is a publishing house specializing in translating foreign literature into English.
All of New Vessel Press's published books are in English.
Neapolitan Chronicles is a book published by New Vessel Press.
Neapolitan Chronicles was translated from Italian.
Palace of Flies is a book published by New Vessel Press.
*** Conclusion:
 Neapolitan Chronicles is an English book.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 New Vessel Press is a publishing house specializing in translating foreign literature into English.
All of New Vessel Press's published books are in English.
Neapolitan Chronicles is a book published by New Vessel Press.
Neapolitan Chronicles was translated from Italian.
Palace of Flies is a book published by New Vessel Press.
*** Conclusion:
 Harry Potter was published by New Vessel Press.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 New Vessel Press is a publishing house specializing in translating foreign literature into English.
All of New Vessel Press's published books are in English.
Neapolitan Chronicles is a book published by New Vessel Press.
Neapolitan Chronicles was translated from Italian.
Palace of Flies is a book published by New Vessel Press.
*** Conclusion:
 Palace of Flies was translated from Italian.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quiksilver sells sportswear, clothing, footwear, and accessories.
Flannels are a type of clothing.
Joe owns an item from Quiksilver.
*** Conclusion:
 Quiksilver sells beer.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quiksilver sells sportswear, clothing, footwear, and accessories.
Flannels are a type of clothing.
Joe owns an item from Quiksilver.
*** Conclusion:
 Joe owns a flannel.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Quiksilver sells sportswear, clothing, footwear, and accessories.
Flannels are a type of clothing.
Joe owns an item from Quiksilver.
*** Conclusion:
 Joe owns at least one piece of sportswear, clothing, footwear, or accessory
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lawton Park is a neighborhood in Seattle.
All citizens of Lawton Park use the zip code 98199.
Tom is a citizen of Lawton Park.
Daniel uses the zip code 98199.
*** Conclusion:
 Tom uses the zip code 98199.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lawton Park is a neighborhood in Seattle.
All citizens of Lawton Park use the zip code 98199.
Tom is a citizen of Lawton Park.
Daniel uses the zip code 98199.
*** Conclusion:
 Tom doesn't use the zip code 98199.
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lawton Park is a neighborhood in Seattle.
All citizens of Lawton Park use the zip code 98199.
Tom is a citizen of Lawton Park.
Daniel uses the zip code 98199.
*** Conclusion:
 Tom is a citizen of Washington.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Lawton Park is a neighborhood in Seattle.
All citizens of Lawton Park use the zip code 98199.
Tom is a citizen of Lawton Park.
Daniel uses the zip code 98199.
*** Conclusion:
 Daniel is a citizen of Lawton Park.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All vehicle registration plates in Istanbul begin with the number 34.
Plates that do not begin with the number 34 are not from Istanbul.
Joe's vehicle registration plate is from Istanbul.
Tom's license plate begins with the number 35.
If a license plate begins with the number 35, then it does not begin with the number 34.
*** Conclusion:
 Joe's license plate begins with the number 34.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 All vehicle registration plates in Istanbul begin with the number 34.
Plates that do not begin with the number 34 are not from Istanbul.
Joe's vehicle registration plate is from Istanbul.
Tom's license plate begins with the number 35.
If a license plate begins with the number 35, then it does not begin with the number 34.
*** Conclusion:
 Tom's license plate is from Istanbul.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Luzon is an island in the Philippines.
In December 1999, an earthquake struck Luzon.
People died in the December 1999 earthquake in Luzon.
*** Conclusion:
 Leyte is an island in the Philippines.
*** True Label:
 U
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Luzon is an island in the Philippines.
In December 1999, an earthquake struck Luzon.
People died in the December 1999 earthquake in Luzon.
*** Conclusion:
 No one has ever died in an earthquake that struck the Philippines.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Luzon is an island in the Philippines.
In December 1999, an earthquake struck Luzon.
People died in the December 1999 earthquake in Luzon.
*** Conclusion:
 In 1999, there was at least one earthquake in the Philippines.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diethylcarbamazine is a medication discovered in the year 1947.
Diethylcarbamazine can be used to treat river blindness.
The only preferred treatment for river blindness is ivermectin.
Diethylcarbamazine is not ivermectin.
*** Conclusion:
 Diethylcarbamazine is not preferred for the treatment of river blindness.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diethylcarbamazine is a medication discovered in the year 1947.
Diethylcarbamazine can be used to treat river blindness.
The only preferred treatment for river blindness is ivermectin.
Diethylcarbamazine is not ivermectin.
*** Conclusion:
 Diethylcarbamazine was often used to treat river blindness.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diethylcarbamazine is a medication discovered in the year 1947.
Diethylcarbamazine can be used to treat river blindness.
The only preferred treatment for river blindness is ivermectin.
Diethylcarbamazine is not ivermectin.
*** Conclusion:
 Diethylcarbamazine is used in the treatment of filariasis.
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a legislator is found guilty of stealing government funds, they will be suspended from office.
Tiffany T. Alston was a legislator in Maryland's House of Delegates from 2011 to 2013.
Tiffany T. Alston was found guilty of stealing government funds in 2012.
*** Conclusion:
 Tiffany T. Alston was suspended from the Maryland House of Delegates.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a legislator is found guilty of stealing government funds, they will be suspended from office.
Tiffany T. Alston was a legislator in Maryland's House of Delegates from 2011 to 2013.
Tiffany T. Alston was found guilty of stealing government funds in 2012.
*** Conclusion:
 Tiffany T. Alston was not suspended from the Maryland House of Delegates.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 If a legislator is found guilty of stealing government funds, they will be suspended from office.
Tiffany T. Alston was a legislator in Maryland's House of Delegates from 2011 to 2013.
Tiffany T. Alston was found guilty of stealing government funds in 2012.
*** Conclusion:
 Tiffany T. Alston went to prison for stealing government funds.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Daveed Diggs is an actor and film producer.
Daveed Diggs played two roles in the musical Hamilton on Broadway.
One of the actors from Hamilton won the best actor award.
The actor playing Thomas Jefferson won the best actor award.
Daveed Diggs played Thomas Jefferson.
Musicals on Broadway are not films.
*** Conclusion:
 Hamilton is a film.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Daveed Diggs is an actor and film producer.
Daveed Diggs played two roles in the musical Hamilton on Broadway.
One of the actors from Hamilton won the best actor award.
The actor playing Thomas Jefferson won the best actor award.
Daveed Diggs played Thomas Jefferson.
Musicals on Broadway are not films.
*** Conclusion:
 Daveed Diggs won the best actor award.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Daveed Diggs is an actor and film producer.
Daveed Diggs played two roles in the musical Hamilton on Broadway.
One of the actors from Hamilton won the best actor award.
The actor playing Thomas Jefferson won the best actor award.
Daveed Diggs played Thomas Jefferson.
Musicals on Broadway are not films.
*** Conclusion:
 Hamilton won two awards.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bernarda Bryson Shahn was a painter and lithographer.
Bernarda Bryson Shahn was born in Athens, Ohio.
Bernarda Bryson Shahn was married to Ben Shahn.
People born in Athens, Ohio, are Americans.
*** Conclusion:
 Bernarda Bryson Shahn was born in Greece.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bernarda Bryson Shahn was a painter and lithographer.
Bernarda Bryson Shahn was born in Athens, Ohio.
Bernarda Bryson Shahn was married to Ben Shahn.
People born in Athens, Ohio, are Americans.
*** Conclusion:
 Bernarda Bryson Shahn was American.
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bernarda Bryson Shahn was a painter and lithographer.
Bernarda Bryson Shahn was born in Athens, Ohio.
Bernarda Bryson Shahn was married to Ben Shahn.
People born in Athens, Ohio, are Americans.
*** Conclusion:
 Bernarda Bryson Shahn had been divorced once.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bobby Flynn is a singer-songwriter.
Bobby Flynn finished 7th while competing on Australian Idol.
Australian Idol competitors are Australian citizens.
The Omega Three band made a nationwide tour in 2007.
Bobby Flynn is a member of The Omega Three band.
Bobby Flynn was born in Queensland.
*** Conclusion:
 Bobby Flynn is an Australian citizen.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bobby Flynn is a singer-songwriter.
Bobby Flynn finished 7th while competing on Australian Idol.
Australian Idol competitors are Australian citizens.
The Omega Three band made a nationwide tour in 2007.
Bobby Flynn is a member of The Omega Three band.
Bobby Flynn was born in Queensland.
*** Conclusion:
 Bobby Flynn flew to America in 2007.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Bobby Flynn is a singer-songwriter.
Bobby Flynn finished 7th while competing on Australian Idol.
Australian Idol competitors are Australian citizens.
The Omega Three band made a nationwide tour in 2007.
Bobby Flynn is a member of The Omega Three band.
Bobby Flynn was born in Queensland.
*** Conclusion:
 Bobby Flynn was born in Queens.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Koei Tecmo is a Japanese video game and anime holding company.
Holding companies hold several companies.
Tecmo was disbanded in Japan, while Koei survived but was renamed.
Video game holding companies are holding companies.
*** Conclusion:
 Koei Tecmo holds another company.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Koei Tecmo is a Japanese video game and anime holding company.
Holding companies hold several companies.
Tecmo was disbanded in Japan, while Koei survived but was renamed.
Video game holding companies are holding companies.
*** Conclusion:
 Tecmo holds another company.
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Koei Tecmo is a Japanese video game and anime holding company.
Holding companies hold several companies.
Tecmo was disbanded in Japan, while Koei survived but was renamed.
Video game holding companies are holding companies.
*** Conclusion:
 Koei Tecmo holds anime.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Virginia Lee is an Australian rower.
Virginia Lee competed in both sweep oared and sculling events.
Sydney is Virginia Lee's home city.
New South Wales was represented by Virginia Lee.
*** Conclusion:
 Sydney is not the home city to any rower.
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Virginia Lee is an Australian rower.
Virginia Lee competed in both sweep oared and sculling events.
Sydney is Virginia Lee's home city.
New South Wales was represented by Virginia Lee.
*** Conclusion:
 No Australian has represented New South Wales.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Virginia Lee is an Australian rower.
Virginia Lee competed in both sweep oared and sculling events.
Sydney is Virginia Lee's home city.
New South Wales was represented by Virginia Lee.
*** Conclusion:
 An Australian who competed in sweep oared events represented New South Wales.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Adventures of Rusty is a drama film and children's film.
Columbia Pictures produced Adventures of Rusty.
Tintin was produced by Paramount.
Tintin is an adventure film.
*** Conclusion:
 Columbia pictures produced some drama film.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Adventures of Rusty is a drama film and children's film.
Columbia Pictures produced Adventures of Rusty.
Tintin was produced by Paramount.
Tintin is an adventure film.
*** Conclusion:
 Columbia pictures produced some adventure film.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Adventures of Rusty is a drama film and children's film.
Columbia Pictures produced Adventures of Rusty.
Tintin was produced by Paramount.
Tintin is an adventure film.
*** Conclusion:
 Paramount produces children's films.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Adventures of Rusty is a drama film and children's film.
Columbia Pictures produced Adventures of Rusty.
Tintin was produced by Paramount.
Tintin is an adventure film.
*** Conclusion:
 Paramount produces adventure films.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Roy Richardson was a cricketer who played for Sint Maarten, a constituent country.
Roy Richardson was a right-handed batsman and medium-pace bowler.
Roy Richardson was old when he debuted in cricket.
Sherville Huggins dismissed Roy Richardson.
*** Conclusion:
 Sherville Huggins has never dismissed anyone playing cricket for a constituent country.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Roy Richardson was a cricketer who played for Sint Maarten, a constituent country.
Roy Richardson was a right-handed batsman and medium-pace bowler.
Roy Richardson was old when he debuted in cricket.
Sherville Huggins dismissed Roy Richardson.
*** Conclusion:
 No right-handed medium-pace bowlers were playing for Sint Maarten.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ainderby Quernhow is a village and civil parish in the Hambleton District.
Hambleton District is in North Yorkshire.
North Yorkshire is in England.
If place A is located in place B and place B is located in place C, then place A is located in place C.
*** Conclusion:
 There is a village in England.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Ainderby Quernhow is a village and civil parish in the Hambleton District.
Hambleton District is in North Yorkshire.
North Yorkshire is in England.
If place A is located in place B and place B is located in place C, then place A is located in place C.
*** Conclusion:
 There is no civil parish in England.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 DI Ray is a police procedural television series.
DI Ray was created and written by Maya Sondhi.
DI Ray was produced by Jed Mercurio.
Maya Sondhi and Jed Mercurio are both British.
*** Conclusion:
 DI Ray was created by a Brit.
*** True Label:
 T
*** Predicted Label:
 U</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 DI Ray is a police procedural television series.
DI Ray was created and written by Maya Sondhi.
DI Ray was produced by Jed Mercurio.
Maya Sondhi and Jed Mercurio are both British.
*** Conclusion:
 Some Brit produced a television series.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diamond Mine is a professional wrestling stable formed in WWE.
Roderick Strong leads Diamond Mine.
Diamond Mine includes the Creed Brothers and Ivy Nile.
Imperium has a feud with Diamond Mine.
*** Conclusion:
 Roderick Strong leads a professional wrestling stable.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diamond Mine is a professional wrestling stable formed in WWE.
Roderick Strong leads Diamond Mine.
Diamond Mine includes the Creed Brothers and Ivy Nile.
Imperium has a feud with Diamond Mine.
*** Conclusion:
 Roderick Strong leads the Creed Brothers.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Diamond Mine is a professional wrestling stable formed in WWE.
Roderick Strong leads Diamond Mine.
Diamond Mine includes the Creed Brothers and Ivy Nile.
Imperium has a feud with Diamond Mine.
*** Conclusion:
 Imperium doesn't have a feud with a professional wrestling stable that includes Ivy Nile.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Deborah Wallace is a Scottish-born actress, playwright, and producer.
Psyche is a play based on the life of James Miranda Barry.
Homesick, Psyche and The Void are plays by Deborah Wallace.
Deborah Wallace co-produced Gasland.
*** Conclusion:
 Gasland was coproduced by the same person Homesick was from.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Deborah Wallace is a Scottish-born actress, playwright, and producer.
Psyche is a play based on the life of James Miranda Barry.
Homesick, Psyche and The Void are plays by Deborah Wallace.
Deborah Wallace co-produced Gasland.
*** Conclusion:
 No plays by Deborah Wallace are based on the life of James Miranda Barry.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Deborah Wallace is a Scottish-born actress, playwright, and producer.
Psyche is a play based on the life of James Miranda Barry.
Homesick, Psyche and The Void are plays by Deborah Wallace.
Deborah Wallace co-produced Gasland.
*** Conclusion:
 Gasland is a play.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Maggie Friedman is an American screenwriter and producer.
Maggie Friedman was the showrunner and executive producer of the lifetime television series Witches of East End.
Witches of East End is a fantasy-drama series.
Maggie Friedman produced and developed Eastwick.
Eastwick is a series by ABC.
*** Conclusion:
 There is a series by ABC that was developed by the showrunner of Witches of East End.
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Maggie Friedman is an American screenwriter and producer.
Maggie Friedman was the showrunner and executive producer of the lifetime television series Witches of East End.
Witches of East End is a fantasy-drama series.
Maggie Friedman produced and developed Eastwick.
Eastwick is a series by ABC.
*** Conclusion:
 No series by ABC was developed by the showrunner of Witches of East End.
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Maggie Friedman is an American screenwriter and producer.
Maggie Friedman was the showrunner and executive producer of the lifetime television series Witches of East End.
Witches of East End is a fantasy-drama series.
Maggie Friedman produced and developed Eastwick.
Eastwick is a series by ABC.
*** Conclusion:
 Maggie Friedman developed Witches of East End.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Shafaq-Asiman is a large complex of offshore geological structures in the Caspian Sea.
Baku is northwest of Shafaq-Asiman.
If place A is northwest of place B, then place B is southeast of place A.
*** Conclusion:
 Baku is southeast of Shafaq-Asiman.
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 Shafaq-Asiman is a large complex of offshore geological structures in the Caspian Sea.
Baku is northwest of Shafaq-Asiman.
If place A is northwest of place B, then place B is southeast of place A.
*** Conclusion:
 A large complex is southeast of Baku.
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 Shafaq-Asiman is a large complex of offshore geological structures in the Caspian Sea.
Baku is northwest of Shafaq-Asiman.
If place A is northwest of place B, then place B is southeast of place A.
*** Conclusion:
 Baku is not northwest of offshore geological structures.
*** True Label:
 F
*** Predicted Label:
 None
Classification Report:                  precision    recall  f1-score   support

                      0.00      0.00      0.00         0
    T </output>       0.00      0.00      0.00         0
</output> tags.       0.00      0.00      0.00         0
              F       0.36      0.13      0.19        69
     F</output>       0.00      0.00      0.00         0
    F</output>        0.00      0.00      0.00         0
           None       0.00      0.00      0.00         0
              T       0.64      0.13      0.22       122
     T</output>       0.00      0.00      0.00         0
    T</output>        0.00      0.00      0.00         0
              U       1.00      0.03      0.05       110
     U</output>       0.00      0.00      0.00         0

       accuracy                           0.09       301
      macro avg       0.17      0.02      0.04       301
   weighted avg       0.71      0.09      0.15       301

*************** INFERENCE COMPLETE ***************

In [16]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.09302325581395349
***** PRECISION *****
0.16666666666666666
***** RECALL *****
0.02407125423875246
***** F1 *****
0.038522815138733575

   Accuracy  Precision    Recall        F1
0  0.093023   0.166667  0.024071  0.038523

In [18]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

config.json: 0.00B [00:00, ?B/s]

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [19]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default')

*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Ocellated wild turkey.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Tom is an Eastern wild turkey.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 There are six types of wild turkeys: Eastern wild turkey, Osceola wild turkey, Gould’s wild turkey, Merriam’s wild turkey, Rio Grande wild turkey, and Ocellated wild turkey.
Tom is not an Eastern wild turkey.
Tom is not an Osceola wild turkey.
Tom is not a Gould's wild turkey.
Tom is neither a Merriam's wild turkey nor a Rio Grande wild turkey.
Tom is a wild turkey.
*** Conclusion:
 Joey is a wild turkey.
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 Mary has the flu.
If someone has the flu, then they have influenza.
Susan doesn't have influenza.
*** Conclusion:
 Either Mary or Susan has influenza.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Butte and St Pierre are in the same state.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 St Pierre and Bismarck are in the same state.
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 Billings is a city in the state of Montana in U.S.
The state of Montana includes the cities of Butte, Helena, and Missoula.
White Sulphur Springs and Butte are cities in the same state in U.S.
The city of St Pierre is not in the state of Montana.
Any city in Butte is not in St Pierre.
A city can only be in one state in U.S.  except for Bristol, Texarkana, Texhoma and Union City.
*** Conclusion:
 Montana is home to the city of Missoula.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New France.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Pierre de Rigaud de Vaudreuil built a fort in New England.
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 Fort Ticonderoga is the current name for Fort Carillon.
Pierre de Rigaud de Vaudreuil built Fort Carillon.
Fort Carillon was located in New France.
New France is not in Europe.
*** Conclusion:
 Fort Carillon was located in Europe.
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 Sūduva Marijampolė holds the Lithuanian Super Cup.
Sūduva Marijampolė is a soccer team.
*** Conclusion:
 Some soccer team holds the Lithuanian Super Cup.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If the Hulk does not wake up, then Thor is not happy.
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is happy, then Peter Parker wears a uniform.
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 Peter Parker is either a superhero or a civilian.
The Hulk is a destroyer.
The Hulk wakes up when he is angry.
If the Hulk wakes up, then he will break a bridge.
Thor is a god.
Thor will break a bridge when he is happy.
A god is not a destroyer.
Peter Parker wears a uniform when he is a superhero.
Peter Parker is not a civilian if a destroyer is breaking a bridge.
If Thor is happy, the Hulk is angry.
*** Conclusion:
 If Thor is not happy, then no bridge will be broken.
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is situated on the Paris–Lille railway.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Boves is not in Europe.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Boves is a railway station located in France.
The preceding station of Boves is Longueau.
The preceding station of Dommartin is Boves.
France is a European country.
Dommartin is situated on the Paris–Lille railway.
Any two contiguous stations are on the same railway.
Boves is served by regional TER Hauts-de-France trains.
If place A is located in place B and place B is located in place C, then place A is located in place C.
If place A precedes place B and place B precedes place C, then place A precedes place C.
*** Conclusion:
 Longueau is served by regional TER Hauts-de-France trains.
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is larger than seven.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Eight is positive.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Six, seven and eight are real numbers.
If a real number equals another real number added by one, the first number is larger.
If the number x is larger than the number y, then y is not larger than x.
Seven equals six plus one.
Eight equals seven plus one.
Two is positive.
If a number is positive, then the double of it is also positive.
Eight is the double of four.
Four is the double of two.
*** Conclusion:
 Six is larger than seven.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 Miroslav Venhoda loved music.
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 A Czech published a book in 1946.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Miroslav Venhoda was a Czech choral conductor who specialized in the performance of Renaissance and Baroque music.
Any choral conductor is a musician.
Some musicians love music.
Miroslav Venhoda published a book in 1946 called Method of Studying Gregorian Chant.
*** Conclusion:
 No choral conductor specialized in the performance of Renaissance.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Cats like playing with taiga vole.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 The taiga vole is a large vole found in northwestern North America.
Cats like playing with all voles.
The taiga vole lives in the boreal taiga zone.
The boreal taiga zone in North America is a cold place to live in.
*** Conclusion:
 Taiga vole's living place is not cold.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner worked with Greenwillow Books.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 The Mede Empire plans to swallow up Attolia.
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Thick as Thieves is not set in the Mede Empire.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 Thick as Thieves is a young adult fantasy novel written by Megan Whalen Turner.
Thick as Thieves was published by Greenwillow Books.
If a book was published by a company, then the author of that book worked with the company that published the book.
The fictional Mede Empire is where Thick as Thieves is set.
The Mede Empire plots to swallow up some nearby countries.
Attolia and Sounis are countries near the Mede Empire.
Thick as Thieves was sold both as a hardcover and an e-book.
*** Conclusion:
 Megan Whalen Turner did not work with Greenwillow Books.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown graduated with a Bachelor of Arts.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown's father was in Toledo.
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 Walter Folger Brown was an American politician and lawyer who served as the postmaster general.
Walter Folger Brown graduated from Harvard University with a Bachelor of Arts.
While they were both in Toledo, Walter Folger Brown's father practiced law with Walter Folger Brown.
Katherin Hafer married Walter Folger Brown.
*** Conclusion:
 Walter Folger Brown was not in Toledo.
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River watershed flows to somewhere in New York.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 The Croton River watershed is in the Bronx.
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 The Croton River watershed is the drainage basin of the Croton River.
The Croton River is in southwestern New York.
Water from the Croton River watershed flows to the Bronx.
The Bronx is in New York.
*** Conclusion:
 Water from the Croton River flows to the Bronx.
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 was formed by former members of Gong.
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 has released several singles.
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 System 7 is a UK-based electronic dance music band.
Steve Hillage and Miquette Giraudy formed System 7.
Steve Hillage and Miquette Giraudy are former members of the band Gong.
Electric dance music bands are bands.
System 7 has released several club singles.
Club singles are not singles.
*** Conclusion:
 System 7 is not a band.
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem is open to the public.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 There is a museum ship open to the public that served in the Mediterranean.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 The USS Salem is a heavy cruiser built for the United States Navy.
The last heavy cruiser to enter service was the USS Salem.
The USS Salem is a museum ship.
Museum ships are open to the public.
The USS Salem served in the Atlantic and Mediterranean.
*** Conclusion:
 The USS Salem was not the last heavy cruiser to enter service.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is found in Australia and Southern Asia.
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 No Elephantopus is native to the southeastern United States.
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 Elephantopus is a genus of perennial plants in the daisy family.
Elephantopus is widespread over much of Africa, southern Asia, Australia, and the Americas.
Several species of Elephantopus are native to the southeastern United States.
Elephantopus scaber is a traditional medicine.
*** Conclusion:
 Elephantopus is a traditional medicine.
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 Notable people with the given name include Dagfinn Aarskog, Dagfinn Bakke and Dagfinn Dahl.
Dagfinn Aarskog is a Norwegian physician.
Dagfinn Dahl is a Norwegian barrister.
*** Conclusion:
 Dagfinn Aarskog is a notable person.
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:

In [20]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.26578073089701
***** PRECISION *****
0.2631033182503771
***** RECALL *****
0.1011814510032614
***** F1 *****
0.14389661316572197

   Accuracy  Precision    Recall        F1
0  0.265781   0.263103  0.101181  0.143897

In [21]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)