In [ ]:
'''
task: classify syllogism validity with CLIF notation
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: pfolio
evaluation: zero-shot + sef category
'''
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.5.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.24.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)

In [ ]:
import pandas as pd

pfolio_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/p-folio/data/pfolio_kr_gold_train_sef.csv")

In [ ]:
# evaluation metrics

import numpy as np
import re
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

def predict_answer(model, tokenizer, obj, subject, sef, ref_relation=None, source_knowledge=None):
  # define sef categories
  sef_disjunctive = r"""
  A disjunctive syllogism contains "∨" or "⊕". Here is an example:
  <PREMISES>forall x (kid(x) implies young(x))
forall x (toddler(x) implies kid(x))
forall x (young(x) implies not elderly(x))
forall x (pirate(x) implies seafarer(x))
not pirate(nancy) implies young(nancy)
not toddler(nancy) implies seafarer(nancy)</PREMISES>
  <CONCLUSION>not (pirate(nancy) xor toddler(nancy))</CONCLUSION>
  """

  sef_complex = r"""
  A complex syllogism has more than 2 premises. Here is an example:
  <PREMISES>woncup(aberdeen, year2013final)
woncup(rangers, year2014final)
not (aberdeen=rangers)
forall x forall y forall z forall w (not (x=y) and woncup(x, z) and woncup(y, w) implies not (z=w))</PREMISES>
  <CONCLUSION>exists x (woncup(aberdeen, x))</CONCLUSION>
  """

  sef_categorical = r"""
  A categorical syllogism contains any word from the list ["all", "any", "some", "no", "few", "most", "none", "several"]. Here is an example:
  <PREMISES>unincorporatedcommunity(ordinary)
locatedin(ordinary, elliotcounty) and on(ordinary, kentuckyroute32)
locatednorthwestof(ordinary, sandyhook)</PREMISES>
  <CONCLUSION>exists x (unincorporatedcommunity(x) and locatedin(x, elliotcounty))</CONCLUSION>
  """

  sef_hypothetical = r"""
  A hypothetical syllogism is not disjunctive, complex or categorical. Here is an example:
  <PREMISES>forall x (homework(x) implies not fun(x))
exists x (reading(x) and homework(x))</PREMISES>
  <CONCLUSION>exists x (reading(x) and fun(x))</CONCLUSION>
  """

  sef_categories = dict()
  sef_categories["disjunctive"] = sef_disjunctive
  sef_categories["complex"] = sef_complex
  sef_categories["categorical"] = sef_categorical
  sef_categories["hypothetical"] = sef_hypothetical


  # define notation grammar
  grammar = r"""
    start: program
    program: [stat]+
    stat: proposition newline | keyword* quantifier* symbol* leftparen* (quantifier symbol)* proposition rightparen* newline | keyword* (quantifier symbol)* leftparen* (quantifier symbol)* proposition rightparen* newline
    proposition: atomicproposition | complexproposition
    complexproposition: keyword* proposition keyword leftparen* (quantifier symbol)* proposition rightparen*
    atomicproposition: leftparen* term* leftparen* term* rightparen*
    !term: (LETTER+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠")* | (DIGIT+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠")*
    !leftparen: "("
    !rightparen: ")"
    !keyword: "and" | "not" | "implies" | "or" | "xor" | "implies" | "implies"
    !quantifier: "exists" | "forall"
    symbol: LETTER
    newline: /\n/

    %import common.LETTER
    %import common.DIGIT
    %import common.INT -> NUMBER
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS
"""
  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert logician. You are given a syllogism in CLIF with premises between <PREMISES></PREMISES> and conclusion between <CONCLUSION></CONCLUSION> tags.
  The CLIF BNF grammar to understand and reason in the language is given in the <GRAMMAR></GRAMMAR> tags.
  <GRAMMAR>{grammar}</GRAMMAR>
  <PREMISES>{subject}</PREMISES>
  <CONCLUSION>{obj}</CONCLUSION>
  You are also given the category of the syllogism to help you understand it: {sef_categories[sef]}.
  Classify the conclusion as "T" if true, "F" if false or "U" if uncertain based on the premises. Present your answer only between <output></output> tags.
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  predicted_relation = tokenizer.decode(response[0])
  matches = re.findall('<output>(.*)</output>', predicted_relation, flags=re.DOTALL)
  res = re.findall(r"<output>(.*)", matches[-1])  # from ['</output> tags.\n  <end_of_turn>\n  <start_of_turn>model\n  <output>T'] to ['T']
  predicted_label = res[0] if res else "None" # take first element from list ['T'] to get 'T'

  print("*** Premises: \n", subject)
  print("*** Conclusion: \n", obj)
  print("*** True Label: \n", ref_relation)
  print("*** Predicted Label: \n", predicted_label)
  return predicted_label

In [ ]:
def infer_from_ontology(dataset, model, tokenizer, mode='default', notation='NL'):
  evaluation_metrics_df = pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1"])
  reference_labels = []
  predicted_labels = []
  for index, row in dataset.iterrows():
      conclusion = row["Conclusions - " + notation]
      premises = row["Premises - " + notation]
      sef_category = row["sef"]
      label = row["Truth Values"]
      if mode.lower() == "grammar":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        source_information = """BNF GRAMMAR"""
        print("*** RAG INFORMATION:", source_information)
      # predict answer with model
      predicted_label = predict_answer(model, tokenizer, conclusion, premises, sef_category, label)
      reference_labels.append(label)
      predicted_labels.append(predicted_label)
  # fill evaluation metrics dataframe
  accuracy_metric = accuracy_score(reference_labels, predicted_labels)
  precision_metric = precision_score(reference_labels, predicted_labels, average="macro")
  recall_metric = recall_score(reference_labels, predicted_labels, average="macro")
  f1_metric = f1_score(reference_labels, predicted_labels, average="macro")
  evaluation_metrics_df["Accuracy"] = [accuracy_metric]
  evaluation_metrics_df["Precision"] = [precision_metric]
  evaluation_metrics_df["Recall"] = [recall_metric]
  evaluation_metrics_df["F1"] = [f1_metric]
  print("Classification Report:", classification_report(reference_labels, predicted_labels))
  print("*************** INFERENCE COMPLETE ***************")
  return reference_labels, predicted_labels, evaluation_metrics_df, accuracy_metric, precision_metric, recall_metric, f1_metric

In [ ]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [ ]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLIF')

*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 has(mary, flu)
forall x (has(x, flu) implies has(x, influenza))
not has(susan, influenza)
*** Conclusion:
 has(mary, influenza) xor has(susan, influenza)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (in(butte, x) and in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (city(pierre) and in(pierre, x) and city(bismarck) and in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 city(missoula) and in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
 exists x (soccerteam(x) and holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not wakesup(thehulk) implies not happy(thor)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 happy(thor) implies wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not happy(thor) implies not breaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 not in(boves, europe)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 exists x exists y (czech(x) and publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall x (choralconductor(x) implies not specializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 not livein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not setin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not workedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(not in(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x ((water(x) and from(x, crotonriverwatershed)) implies exists y(flowsto(x, y) and in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x (water(x) and from(x, crotonriver) implies flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (form(x, system7) and formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (single(x) and release(system7, x))
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 not band(system7)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 exists x (museumship(x) and opentopublic(x) and servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 not lastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 forall x (elephantopus(x) implies (genus(x, perennialplants) and belongto(x, daisyfamily)))
exists x exists y exists z(elephantopus(x) and in(x,africa) and (not (x=y)) and elephantopus(y) and in(y, southernasia) and (not (x=z)) and (not (y=z)) and elephantopus(z) and in(z, australia))

In [ ]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.47840531561461797
***** PRECISION *****
0.4422816977561503
***** RECALL *****
0.44381088144452363
***** F1 *****
0.3686868686868687

   Accuracy  Precision    Recall        F1
0  0.478405   0.442282  0.443811  0.368687

In [ ]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [ ]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLIF')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 has(mary, flu)
forall x (has(x, flu) implies has(x, influenza))
not has(susan, influenza)
*** Conclusion:
 has(mary, influenza) xor has(susan, influenza)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (in(butte, x) and in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (city(pierre) and in(pierre, x) and city(bismarck) and in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 city(missoula) and in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
 exists x (soccerteam(x) and holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not wakesup(thehulk) implies not happy(thor)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 happy(thor) implies wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not happy(thor) implies not breaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 not in(boves, europe)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 exists x exists y (czech(x) and publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall x (choralconductor(x) implies not specializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 not livein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not setin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not workedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(not in(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x ((water(x) and from(x, crotonriverwatershed)) implies exists y(flowsto(x, y) and in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x (water(x) and from(x, crotonriver) implies flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (form(x, system7) and formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (single(x) and release(system7, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 not band(system7)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 exists x (museumship(x) and opentopublic(x) and servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 not lastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (elephantopus(x) implies (genus(x, perennialplants) and belongto(x, daisyfamily)))
exists x exists y exists z(elephantopus(x) and in(x,africa) and (not (x=y)) and elephantopus(y) and in(y, southernasia) and (not (x=z)) and (not (y=z)) and elephantopus(z) and in(z, australia))
exists x exists y (elephantopus(x) and nativeto(x, southeasternunitedstates) and (not (x=y)) and elephantopus(y) and nativeto(y, southeasternunitedstates))
forall x (elephantopusscaber(x) implies traditionalmedicine(x))
*** Conclusion:
 exists xexists y(elephantopus(x) and in(x,africa) and elephantopus(y) and in(y,africa))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (elephantopus(x) implies (genus(x, perennialplants) and belongto(x, daisyfamily)))
exists x exists y exists z(elephantopus(x) and in(x,africa) and (not (x=y)) and elephantopus(y) and in(y, southernasia) and (not (x=z)) and (not (y=z)) and elephantopus(z) and in(z, australia))
exists x exists y (elephantopus(x) and nativeto(x, southeasternunitedstates) and (not (x=y)) and elephantopus(y) and nativeto(y, southeasternunitedstates))
forall x (elephantopusscaber(x) implies traditionalmedicine(x))
*** Conclusion:
 forall x (elephantopus(x) implies not nativeto(x, southeasternunitedstates))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (elephantopus(x) implies (genus(x, perennialplants) and belongto(x, daisyfamily)))
exists x exists y exists z(elephantopus(x) and in(x,africa) and (not (x=y)) and elephantopus(y) and in(y, southernasia) and (not (x=z)) and (not (y=z)) and elephantopus(z) and in(z, australia))
exists x exists y (elephantopus(x) and nativeto(x, southeasternunitedstates) and (not (x=y)) and elephantopus(y) and nativeto(y, southeasternunitedstates))
forall x (elephantopusscaber(x) implies traditionalmedicine(x))
*** Conclusion:
 forall x (elephantopus(x) implies traditionalmedicine(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) and named(dagfinnaarskog, namedagfinn) and notableperson(dagfinnaarskog) and named(dagfinnbakke, namedagfinn) and notableperson(dagfinnbakke)  and named(dagfinndahl, namedagfinn) and notableperson(dagfinndahl)
norwegian(dagfinnaarskog) and physician(dagfinnaarskog)
norwegian(dagfinndahl) and barrister(dagfinndahl)
*** Conclusion:
 notableperson(dagfinnaarskog)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) and named(dagfinnaarskog, namedagfinn) and notableperson(dagfinnaarskog) and named(dagfinnbakke, namedagfinn) and notableperson(dagfinnbakke)  and named(dagfinndahl, namedagfinn) and notableperson(dagfinndahl)
norwegian(dagfinnaarskog) and physician(dagfinnaarskog)
norwegian(dagfinndahl) and barrister(dagfinndahl)
*** Conclusion:
 named(dagfinnaarskog, namedagfinn)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:

givenname(namedagfinn) and named(dagfinnaarskog, namedagfinn) and notableperson(dagfinnaarskog) and named(dagfinnbakke, namedagfinn) and notableperson(dagfinnbakke)  and named(dagfinndahl, namedagfinn) and notableperson(dagfinndahl)
norwegian(dagfinnaarskog) and physician(dagfinnaarskog)
norwegian(dagfinndahl) and barrister(dagfinndahl)
*** Conclusion:
 norwegian(dagfinndahl) and physician(dagfinndahl)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) and from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) and (exists xexists y(family(x) and named(x, nameo'dell) and (not (x=y)) and family(y) and named(y, nameo'dell))
named(amyodell, nameodell) and notableperson(amyodell) and named(jackodell, nameodell) and notableperson(jackodell) and named(matsodell, nameodell) and notableperson(matsodell)
british(amyodell) and singer(amyodell) and songwriter(amyodell)
english(jackodell) and toyinventor(jackodell)
*** Conclusion:
 notableperson(jackodell)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) and from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) and (exists xexists y(family(x) and named(x, nameo'dell) and (not (x=y)) and family(y) and named(y, nameo'dell))
named(amyodell, nameodell) and notableperson(amyodell) and named(jackodell, nameodell) and notableperson(jackodell) and named(matsodell, nameodell) and notableperson(matsodell)
british(amyodell) and singer(amyodell) and songwriter(amyodell)
english(jackodell) and toyinventor(jackodell)
*** Conclusion:
 named(amyodell, nameodell)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) and from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) and (exists xexists y(family(x) and named(x, nameo'dell) and (not (x=y)) and family(y) and named(y, nameo'dell))
named(amyodell, nameodell) and notableperson(amyodell) and named(jackodell, nameodell) and notableperson(jackodell) and named(matsodell, nameodell) and notableperson(matsodell)
british(amyodell) and singer(amyodell) and songwriter(amyodell)
english(jackodell) and toyinventor(jackodell)
*** Conclusion:
 english(amyodell) and toyinventor(amyodell)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 surname(nameodell) and from(nameodell, odellbedfordshire)
mistakenspellingof(nameo'dell, nameodell) and (exists xexists y(family(x) and named(x, nameo'dell) and (not (x=y)) and family(y) and named(y, nameo'dell))
named(amyodell, nameodell) and notableperson(amyodell) and named(jackodell, nameodell) and notableperson(jackodell) and named(matsodell, nameodell) and notableperson(matsodell)
british(amyodell) and singer(amyodell) and songwriter(amyodell)
english(jackodell) and toyinventor(jackodell)
*** Conclusion:
 named(amyodell, nameodell) and named(amyodell, nameo'dell)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) and mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
 exists x (thesecondsmallesteigenvalueof(x, thegraphlaplacian) and honoredby(miroslavfiedler, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) and mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
 french(miroslavfiedler) and mathematician(miroslavfiedler)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 czech(miroslavfiedler) and mathematician(miroslavfiedler)
knownfor(miroslavfiedler, contributionstolinearalgebraandgraphtheory)
honoredby(miroslavfiedler, fiedlereigenvalue)
thesecondsmallesteigenvalueof(fiedlereigenvalue, thegraphlaplacian)
*** Conclusion:
 exists x (czech(x) and mathematician(x) and knownfor(x, contributionstolinearalgebraandgraphtheory))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) and professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) and playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) and playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
 playedfor(thomasbarber, boltonwanderers) and playedin(boltonwanderers,thefootballleague)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) and professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) and playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) and playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
 playedas(thomasbarber, insideleft)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 english(thomasbarber) and professionalfootballer(thomasbarber)
playedfor(thomasbarber, astonvilla) and playedin(astonvilla,thefootballleague)
playedas(thomasbarber, halfback) and playedas(thomasbarber, insideleft)
scoredthewinninggoalin(thomasbarber, facupfinal1913)
*** Conclusion:
 exists x (english(x) and professionalfootballer(x) and scoredthewinninggoalin(x, facupfinal1913))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) and exists x (japanese(x) and videogamecompany(x) and created(x, thelegendofzelda))
forall x forall y ((game(x) and intop10(x) and created(y,x)) implies japanese(y))
forall x ((game(x) and exists y(greaterthan(y, onemillion) and copiessold(x, y))) implies top10(x)))
exists y(greaterthan(y, onemillion) and copiessold(thelegendofzelda,y))
*** Conclusion:
 top10(thelegendofzelda)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) and exists x (japanese(x) and videogamecompany(x) and created(x, thelegendofzelda))
forall x forall y ((game(x) and intop10(x) and created(y,x)) implies japanese(y))
forall x ((game(x) and exists y(greaterthan(y, onemillion) and copiessold(x, y))) implies top10(x)))
exists y(greaterthan(y, onemillion) and copiessold(thelegendofzelda,y))
*** Conclusion:
 exists x(created(x, fifa22) and japanese(x) and videogamecompany(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 game(thelegendofzelda) and exists x (japanese(x) and videogamecompany(x) and created(x, thelegendofzelda))
forall x forall y ((game(x) and intop10(x) and created(y,x)) implies japanese(y))
forall x ((game(x) and exists y(greaterthan(y, onemillion) and copiessold(x, y))) implies top10(x)))
exists y(greaterthan(y, onemillion) and copiessold(thelegendofzelda,y))
*** Conclusion:
 not top10(thelegendofzelda)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) and from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall x ((team(x) and attending(x, nbafinals)) implies wonmanygames(x))
team(bostonceltics) and lost(bostonceltics, nbafinals)
forall x ((team(x) and won(x, nbafinals)) implies moreincome(x))
forall x ((won(x, nbafinals) or lost(x, nbafinals)) implies attending(x, nbafinals))
*** Conclusion:
 from(bostonceltics, sanfrancisco)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) and from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall x ((team(x) and attending(x, nbafinals)) implies wonmanygames(x))
team(bostonceltics) and lost(bostonceltics, nbafinals)
forall x ((team(x) and won(x, nbafinals)) implies moreincome(x))
forall x ((won(x, nbafinals) or lost(x, nbafinals)) implies attending(x, nbafinals))
*** Conclusion:
 hasmorethanthirtyyearsofhistory(bostonceltics)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 team(goldenstatewarriors) and from(goldenstatewarriors, sanfrancisco)
won(goldenstatewarriors, nbafinals)
forall x ((team(x) and attending(x, nbafinals)) implies wonmanygames(x))
team(bostonceltics) and lost(bostonceltics, nbafinals)
forall x ((team(x) and won(x, nbafinals)) implies moreincome(x))
forall x ((won(x, nbafinals) or lost(x, nbafinals)) implies attending(x, nbafinals))
*** Conclusion:
 moreincome(goldenstatewarriors)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (subscribedto(x, amcalist) implies eligibleforthreefreemovies(x))
exists x (cinemaeveryweek(x))
forall x (prefer(x, tvseries) implies not watchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 not eligibleforthreefreemovies(james)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (subscribedto(x, amcalist) implies eligibleforthreefreemovies(x))
exists x (cinemaeveryweek(x))
forall x (prefer(x, tvseries) implies not watchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 cinemaeveryweek(james)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (subscribedto(x, amcalist) implies eligibleforthreefreemovies(x))
exists x (cinemaeveryweek(x))
forall x (prefer(x, tvseries) implies not watchtvin(x, cinemas))
watchtvin(james, cinemas)
subscribedto(james, amcalist)
prefer(peter, tvseries)
*** Conclusion:
 not watchtvin(peter, cinemas)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((book(x) and writtenby(x, cixinliu)) implies exists y(morethan(y, onemillion) and sold(x,y)))
exists x (won(x, hugoaward) and book(x) and writtenby(x, cixinliu))
forall x ((book(x) and aboutfuture(x)) implies fowardlooking(x))
book(threebodyproblem) and exists y(morethan(y, onemillion) and sold(threebodyproblem,y))
aboutfuture(threebodyproblem)
*** Conclusion:
 won(threebodyproblem, hugoaward)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((book(x) and writtenby(x, cixinliu)) implies exists y(morethan(y, onemillion) and sold(x,y)))
exists x (won(x, hugoaward) and book(x) and writtenby(x, cixinliu))
forall x ((book(x) and aboutfuture(x)) implies fowardlooking(x))
book(threebodyproblem) and exists y(morethan(y, onemillion) and sold(threebodyproblem,y))
aboutfuture(threebodyproblem)
*** Conclusion:
 aboutfuture(threebodyproblem)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((book(x) and writtenby(x, cixinliu)) implies exists y(morethan(y, onemillion) and sold(x,y)))
exists x (won(x, hugoaward) and book(x) and writtenby(x, cixinliu))
forall x ((book(x) and aboutfuture(x)) implies fowardlooking(x))
book(threebodyproblem) and exists y(morethan(y, onemillion) and sold(threebodyproblem,y))
aboutfuture(threebodyproblem)
*** Conclusion:
 writtenby(threebodyproblem, cixinliu)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (easy(x) implies exists y (lessthan(y, percent20) and acrate(x,y)))
forall x (recommended(x) implies easy(x))
forall x (easy(x) xor hard(x))
forall x (starred(x)) implies hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 easy(twosum)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (easy(x) implies exists y (lessthan(y, percent20) and acrate(x,y)))
forall x (recommended(x) implies easy(x))
forall x (easy(x) xor hard(x))
forall x (starred(x)) implies hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 recommended(foursum)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (easy(x) implies exists y (lessthan(y, percent20) and acrate(x,y)))
forall x (recommended(x) implies easy(x))
forall x (easy(x) xor hard(x))
forall x (starred(x)) implies hard(x))
recommended(twosum)
starred(foursum)
*** Conclusion:
 exists y(greaterthan(y, percent20) and acrate(2sum,y))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (philateliclit(x) implies (stamp(x) or periodical(x) or auction(x) or book(x) or bibliography(x) or background(x)))
not stamp(mort)
not (periodical(mort) or auction(mort) or bibliography(mort) or background(mort))
philateliclit(mort)
*** Conclusion:
 background(mort)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (philateliclit(x) implies (stamp(x) or periodical(x) or auction(x) or book(x) or bibliography(x) or background(x)))
not stamp(mort)
not (periodical(mort) or auction(mort) or bibliography(mort) or background(mort))
philateliclit(mort)
*** Conclusion:
 philateliclit(eragon)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y (mammal(x) and mammal(y) and (not (x=y)) and have(x, teeth) and have(y, teeth))
not have(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 mammal(platypus) and (not have(platypus, teeth))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y (mammal(x) and mammal(y) and (not (x=y)) and have(x, teeth) and have(y, teeth))
not have(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 reptile(platypus)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y (mammal(x) and mammal(y) and (not (x=y)) and have(x, teeth) and have(y, teeth))
not have(platypus, teeth)
mammal(platypus)
have(humans, teeth)
*** Conclusion:
 mammal(humans)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) and districtin(xiangshan, guilin) and districtin(diecai, guilin) and districtin(qixing, guilin) and city(guilin)
not districtin(yangshuo, guilin)
*** Conclusion:
 exists x (districtin(xiangshan, x) and districtin(diecai, x) and city(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) and districtin(xiangshan, guilin) and districtin(diecai, guilin) and districtin(qixing, guilin) and city(guilin)
not districtin(yangshuo, guilin)
*** Conclusion:
 districtin(xiufeng, guilin)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 districtin(xiufeng, guilin) and districtin(xiangshan, guilin) and districtin(diecai, guilin) and districtin(qixing, guilin) and city(guilin)
not districtin(yangshuo, guilin)
*** Conclusion:
 districtin(kowloon, hongkong)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) and american(jasonkramer)
exists x exists y (american(x) and musicsupervisor(x) and radiopersonality(x) and (not (x=y)) and american(y) and musicsupervisor(y) and radiopersonality(y))
forall x forall y((hostshowon(x, y) and publicradiostation(x)) implies radiopersonality(x))
radiopersonality(joerogan)
exists x(hostshowon(jasonkramer, x) and publicradiostation(x))
*** Conclusion:
 american(joerogan)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) and american(jasonkramer)
exists x exists y (american(x) and musicsupervisor(x) and radiopersonality(x) and (not (x=y)) and american(y) and musicsupervisor(y) and radiopersonality(y))
forall x forall y((hostshowon(x, y) and publicradiostation(x)) implies radiopersonality(x))
radiopersonality(joerogan)
exists x(hostshowon(jasonkramer, x) and publicradiostation(x))
*** Conclusion:
 musicsupervisor(jasonkramer)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 musicsupervisor(jasonkramer) and american(jasonkramer)
exists x exists y (american(x) and musicsupervisor(x) and radiopersonality(x) and (not (x=y)) and american(y) and musicsupervisor(y) and radiopersonality(y))
forall x forall y((hostshowon(x, y) and publicradiostation(x)) implies radiopersonality(x))
radiopersonality(joerogan)
exists x(hostshowon(jasonkramer, x) and publicradiostation(x))
*** Conclusion:
 radiopersonality(jasonkramer)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) and province(drenthe) and in(gasteren, drenthe)
province(drenthe) and in(drenthe, netherlands)
forall x (city(x) implies not village(x))
exists x (population(x, num155) and village(x) and in(x, drenthe))
*** Conclusion:
 village(gasteren) and in(gasteren, netherlands)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) and province(drenthe) and in(gasteren, drenthe)
province(drenthe) and in(drenthe, netherlands)
forall x (city(x) implies not village(x))
exists x (population(x, num155) and village(x) and in(x, drenthe))
*** Conclusion:
 city(gasteren)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(gasteren) and province(drenthe) and in(gasteren, drenthe)
province(drenthe) and in(drenthe, netherlands)
forall x (city(x) implies not village(x))
exists x (population(x, num155) and village(x) and in(x, drenthe))
*** Conclusion:
 population(gasteren, num155)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) and released(endgame, yr2006)
setin(endgame, washington)
not (filmedin(endgame, washington))
exists xexists y(filmedin(x, newyork) and (not (x=y)) and filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 filmedin(endgame, newyork)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) and released(endgame, yr2006)
setin(endgame, washington)
not (filmedin(endgame, washington))
exists xexists y(filmedin(x, newyork) and (not (x=y)) and filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 forall x (not (directed(x, endgame) and from(x, hongkong)))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 movie(endgame) and released(endgame, yr2006)
setin(endgame, washington)
not (filmedin(endgame, washington))
exists xexists y(filmedin(x, newyork) and (not (x=y)) and filmedin(y, newyork))
directed(andychang, endgame)
from(andychang, hongkong)
*** Conclusion:
 forall x (directed(andychang, x) implies not (filmedin(x, washington)))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) and exists y (colleagueofjustinkruger(y) and proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
 proposed(thomasgilovich, naivecynicism)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) and exists y (colleagueofjustinkruger(y) and proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
 exists x (proposed(justinkruger, x) and philosophyofmind(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 proposed(justinkruger, naivecynicism) and exists y (colleagueofjustinkruger(y) and proposed(y, naivecynicism))
colleagues(thomasgilovich, justinkruger)
philosophyofmind(naivecynicism)
*** Conclusion:
 exists x (workedon(thomasgilovich, x) and philosophyofmind(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
exists x(greaterthan(x, num160) and litproductions(hughvanstone,x))
exists x(hometown(hughvanstone,x) and attendedschoolin(hughvanstone,x))
*** Conclusion:
 worldleadinglightingdesigner(hughvanstone) and from(hughvanstone, unitedkingdom)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
exists x(greaterthan(x, num160) and litproductions(hughvanstone,x))
exists x(hometown(hughvanstone,x) and attendedschoolin(hughvanstone,x))
*** Conclusion:
 exists x(greaterthan(x, num170) and litproductions(hughvanstone,x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 worldleadinglightingdesigner(hughvanstone)
from(hughvanstone, unitedkingdom)
exists x(greaterthan(x, num160) and litproductions(hughvanstone,x))
exists x(hometown(hughvanstone,x) and attendedschoolin(hughvanstone,x))
*** Conclusion:
 attendedschoolin(hughvanstone, unitedstates)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall x (professionalbaseballplayer(x) implies playinmlb(x))
forall x (bornin(x, california) implies nationality(x, american))
forall x (nationality(x, american)implies not nationality(x, german))
*** Conclusion:
 nationality(josephkmak, german)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall x (professionalbaseballplayer(x) implies playinmlb(x))
forall x (bornin(x, california) implies nationality(x, american))
forall x (nationality(x, american)implies not nationality(x, german))
*** Conclusion:
 playinmlb(josephkmak)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(josephkmak, napa)
professionalbaseballplayer(josephkmak)
forall x (professionalbaseballplayer(x) implies playinmlb(x))
forall x (bornin(x, california) implies nationality(x, american))
forall x (nationality(x, american)implies not nationality(x, german))
*** Conclusion:
 iscatcher(josephkmak)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall x ((professionaltennisplayer(x) and inbig3(x)) implies highwinratio(x))
*** Conclusion:
 not bornin(rafanadal, mallorca)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall x ((professionaltennisplayer(x) and inbig3(x)) implies highwinratio(x))
*** Conclusion:
 inbig3(rafanadal)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(rafanadal, mallorca)
professionaltennisplayer(rafanadal)
highwinratio(rafanadal)
forall x ((professionaltennisplayer(x) and inbig3(x)) implies highwinratio(x))
*** Conclusion:
 greatestofalltime(rafanadal)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((doesolympicsport(x) and goestoolympicgames(x)) implies olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall x (welterweight(x) implies not  heavyweight(x))
*** Conclusion:
 olympian(carlosreyes)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((doesolympicsport(x) and goestoolympicgames(x)) implies olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall x (welterweight(x) implies not  heavyweight(x))
*** Conclusion:
 heavyweight(carlosreyes)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((doesolympicsport(x) and goestoolympicgames(x)) implies olympian(x))
doesolympicsport(carlosreyes)
goestoolympicgames(carlosreyes)
welterweight(carlosreyes)
forall x (welterweight(x) implies not  heavyweight(x))
*** Conclusion:
 wonolympicmedal(carlosreyes)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall x forall y ((israpper(x) and releasedalbum(x, y)) implies israpalbum(y))
releasedalbum(tyga, welldone3)
forall x (israpper(x) implies not isoperasinger(x))
*** Conclusion:
 israpalbum(welldone3)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall x forall y ((israpper(x) and releasedalbum(x, y)) implies israpalbum(y))
releasedalbum(tyga, welldone3)
forall x (israpper(x) implies not isoperasinger(x))
*** Conclusion:
 isoperasinger(tyga)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 israpper(tyga)
forall x forall y ((israpper(x) and releasedalbum(x, y)) implies israpalbum(y))
releasedalbum(tyga, welldone3)
forall x (israpper(x) implies not isoperasinger(x))
*** Conclusion:
 isworthlistening(welldone3)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sevendistinctworks(x) implies heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 heptalogy(harrypotter)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sevendistinctworks(x) implies heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 not heptalogy(chroniclesofnarnia)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sevendistinctworks(x) implies heptalogy(x))
sevendistinctworks(harrypotter)
sevendistinctworks(chroniclesofnarnia)
*** Conclusion:
 heptalogy(lordofrings)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) and in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) and in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) and in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) and include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
 exists x (museum(x) and in(x, nyc) and include(x, byzantineart) and include(x, islamicart))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) and in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) and in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) and in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) and include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
 exists x (museum(x) and in(x, nyc) and include(x, americanart))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 museum(metropolitanmuseumofart) and in(metropolitanmuseumofart, nyc)
museum(whitneymuseumofamericanart) and in(metropolitanmuseumofart, nyc)
museum(museumofmodernart) and in(museumofmodernart, nyc)
include(metropolitanmuseumofart, byzantineart) and include(metropolitanmuseumofart, islamicart)
include(whitneymuseumofamericanart, americanart)
*** Conclusion:
 exists x (museum(x) and in(x, nyc) and include(x, greekart))
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) and onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall x ((exists y(peak(x, y))) implies popular(x))
peak(yourwoman, iceland) and peak(yourwoman, israel) and peak(yourwoman, spain)
*** Conclusion:
 popular(yourwoman)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) and onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall x ((exists y(peak(x, y))) implies popular(x))
peak(yourwoman, iceland) and peak(yourwoman, israel) and peak(yourwoman, spain)
*** Conclusion:
 forall x (produce(whitetown, x) implies not popular(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 produce(whitetown, yourwoman) and onepersonband(whitetown)
peak(yourwoman, uksingleschart)
forall x ((exists y(peak(x, y))) implies popular(x))
peak(yourwoman, iceland) and peak(yourwoman, israel) and peak(yourwoman, spain)
*** Conclusion:
 successful(whitetown)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((runfar(x) and usemap(x)) implies orienteer(x))
forall x (fit(x) implies runfar(x))
forall x (sensedirection(x) implies usemap(x))
forall x (militaryofficer(x) implies fit(x))
militaryofficer(hailee) and sensedirection(hailee)
not militaryofficer(karl) and usemap(karl)
*** Conclusion:
 orienteer(hailee)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((runfar(x) and usemap(x)) implies orienteer(x))
forall x (fit(x) implies runfar(x))
forall x (sensedirection(x) implies usemap(x))
forall x (militaryofficer(x) implies fit(x))
militaryofficer(hailee) and sensedirection(hailee)
not militaryofficer(karl) and usemap(karl)
*** Conclusion:
 not orienteer(karl)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 talentedpoet(lorca) and support(lorca, populists)
forall x (support(x, populists) implies opposed(nationalists, x))
forall x (talentedpoet(x) implies popular(x))
forall x ((opposed(nationalists, x) and popular(x)) implies killed(nationalists, x))
support(daniel, populists) and (not popular(daniel))
*** Conclusion:
 not killed(nationalists, daniel)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 talentedpoet(lorca) and support(lorca, populists)
forall x (support(x, populists) implies opposed(nationalists, x))
forall x (talentedpoet(x) implies popular(x))
forall x ((opposed(nationalists, x) and popular(x)) implies killed(nationalists, x))
support(daniel, populists) and (not popular(daniel))
*** Conclusion:
 killed(nationalists, lorca)
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) and lawyer(james)
whig(james) and politician(james) and satinhouseofcommons(james)
forall x (british(x) implies european(x))
forall x (lawyer(x) implies familiarwithlaws(x))
exists x exists y (whig(x) and speakfrench(x)) and (not (x=y)) and (whig(y) and speakfrench(y))
*** Conclusion:
 forall x (lawyer(x) implies not satinhouseofcommons(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) and lawyer(james)
whig(james) and politician(james) and satinhouseofcommons(james)
forall x (british(x) implies european(x))
forall x (lawyer(x) implies familiarwithlaws(x))
exists x exists y (whig(x) and speakfrench(x)) and (not (x=y)) and (whig(y) and speakfrench(y))
*** Conclusion:
 exists x (european(x) and familiarwithlaws(x))
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(james) and lawyer(james)
whig(james) and politician(james) and satinhouseofcommons(james)
forall x (british(x) implies european(x))
forall x (lawyer(x) implies familiarwithlaws(x))
exists x exists y (whig(x) and speakfrench(x)) and (not (x=y)) and (whig(y) and speakfrench(y))
*** Conclusion:
 speakfrench(james)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) and rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall x forall y (leadsinger(x, y) implies singer(y))
forall x (singer(x) implies musician(x))
popularsingle(imaginedragon, demons)
exists x exists y (popularsingle(imaginedragon, x) and billboardhot100(x)) and (not (x=y)) and (popularsingle(imaginedragon, y) and billboardhot100(y))
*** Conclusion:
 exists x exists y (rockband(x) and leadsinger(x, y) and songwriter(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) and rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall x forall y (leadsinger(x, y) implies singer(y))
forall x (singer(x) implies musician(x))
popularsingle(imaginedragon, demons)
exists x exists y (popularsingle(imaginedragon, x) and billboardhot100(x)) and (not (x=y)) and (popularsingle(imaginedragon, y) and billboardhot100(y))
*** Conclusion:
 not musician(dan)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(imaginedragon) and rockband(imaginedragon)
leadsinger(imaginedragon, dan)
songwriter(dan)
forall x forall y (leadsinger(x, y) implies singer(y))
forall x (singer(x) implies musician(x))
popularsingle(imaginedragon, demons)
exists x exists y (popularsingle(imaginedragon, x) and billboardhot100(x)) and (not (x=y)) and (popularsingle(imaginedragon, y) and billboardhot100(y))
*** Conclusion:
 billboardhot100(demons)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) and historian(andrewwilson) and politicalscientist(andrewwilson)
forall x (locatedin(x, easterneurope)implies specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
not locatedin(britain, easterneurope)
*** Conclusion:
 bornin(andrewwilson, easterneurope)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) and historian(andrewwilson) and politicalscientist(andrewwilson)
forall x (locatedin(x, easterneurope)implies specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
not locatedin(britain, easterneurope)
*** Conclusion:
 specializein(andrewwilson, poland)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) and historian(andrewwilson) and politicalscientist(andrewwilson)
forall x (locatedin(x, easterneurope)implies specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
not locatedin(britain, easterneurope)
*** Conclusion:
 specializein(andrewwilson, britain)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(andrewwilson) and historian(andrewwilson) and politicalscientist(andrewwilson)
forall x (locatedin(x, easterneurope)implies specializein(andrewwilson, x))
locatedin(poland, easterneurope)
bornin(andrewwilson, britain)
not locatedin(britain, easterneurope)
*** Conclusion:
 forall x (british(x) implies not politicalscientist(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
*** Conclusion:
 in(us31, alabama)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
*** Conclusion:
 not in(cr47, alabama)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 in(sr287, alabama)
in(alabama, unitedstates)
intersect(us31, sr287)
intersect(cr47, sr287)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
*** Conclusion:
 in(sr287, unitedstates)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (breedingback(x) implies (artificialselection(x) and deliberateselectivebreedingofdomesticanimals(x)))
exists x exists y (heckcattle(x) and breedingback(x) and auroch(y) and resemble(x, y))
forall x (heckcattle(x) implies animal(x))
forall x (auroch(x) implies animal(x))
exists x exists y (animal(x) and animal(y) and (not (x=y)) and breedingback(x) and breedingback(y) and (exists w(dead(w) and resemble(x, w)) and (not (w=z)) and (exists z(dead(z) and resemble(y, z))))
*** Conclusion:
 exists x exists y(heckcattle(x) and artificialselection(x) and (not (x=y)) and heckcattle(y) and artificialselection(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (breedingback(x) implies (artificialselection(x) and deliberateselectivebreedingofdomesticanimals(x)))
exists x exists y (heckcattle(x) and breedingback(x) and auroch(y) and resemble(x, y))
forall x (heckcattle(x) implies animal(x))
forall x (auroch(x) implies animal(x))
exists x exists y (animal(x) and animal(y) and (not (x=y)) and breedingback(x) and breedingback(y) and (exists w(dead(w) and resemble(x, w)) and (not (w=z)) and (exists z(dead(z) and resemble(y, z))))
*** Conclusion:
 forall x (auroch(x) implies dead(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (controlledsubstances(x) implies drugs(x))
exists x exists y (controlledsubstances(x) and controlledsubstances(y) and (not (x=y)) and beneficial(x) and harmful(y))
forall x forall y ((child(x) and controlledsubstances(y) and exposedto(x, y)) implies inchemicalendangerment(x))
forall x (inchemicalendangerment(x) implies harmful(x))
passedin(controlledsubstancesact, yr1971) and act(controlledsubstancesact)
exists x exists y(act(x) and preventsharm(x) and (not (x=y)) and act(y) and preventsharm(y))
*** Conclusion:
 preventsharm(controlledsubstancesact)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (controlledsubstances(x) implies drugs(x))
exists x exists y (controlledsubstances(x) and controlledsubstances(y) and (not (x=y)) and beneficial(x) and harmful(y))
forall x forall y ((child(x) and controlledsubstances(y) and exposedto(x, y)) implies inchemicalendangerment(x))
forall x (inchemicalendangerment(x) implies harmful(x))
passedin(controlledsubstancesact, yr1971) and act(controlledsubstancesact)
exists x exists y(act(x) and preventsharm(x) and (not (x=y)) and act(y) and preventsharm(y))
*** Conclusion:
 exists x exists y(drugs(x) and beneficial(x) and (not (x=y)) and drugs(y) and beneficial(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (controlledsubstances(x) implies drugs(x))
exists x exists y (controlledsubstances(x) and controlledsubstances(y) and (not (x=y)) and beneficial(x) and harmful(y))
forall x forall y ((child(x) and controlledsubstances(y) and exposedto(x, y)) implies inchemicalendangerment(x))
forall x (inchemicalendangerment(x) implies harmful(x))
passedin(controlledsubstancesact, yr1971) and act(controlledsubstancesact)
exists x exists y(act(x) and preventsharm(x) and (not (x=y)) and act(y) and preventsharm(y))
*** Conclusion:
 forall x ((child(x) and inchemicalendangerment(x)) implies harmful(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) and authored(douglasadams, thesalmonofdoubt) and book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) and about(thesalmonofdoubt, technology)
forall x (author(x) implies writer(x))
forall x (writer(x) implies create(x, innovativeidea))
exists x exists y (contain(x, innovativeidea) and about(x, technology) and (not (x=y)) and (contain(y, innovativeidea) and about(y, technology)))
*** Conclusion:
 writer(douglasadams)
*** True Label:
 T
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) and authored(douglasadams, thesalmonofdoubt) and book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) and about(thesalmonofdoubt, technology)
forall x (author(x) implies writer(x))
forall x (writer(x) implies create(x, innovativeidea))
exists x exists y (contain(x, innovativeidea) and about(x, technology) and (not (x=y)) and (contain(y, innovativeidea) and about(y, technology)))
*** Conclusion:
 create(douglasadams, innovativeidea)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 author(douglasadams) and authored(douglasadams, thesalmonofdoubt) and book(thesalmonofdoubt)
about(thesalmonofdoubt, lifeexperience) and about(thesalmonofdoubt, technology)
forall x (author(x) implies writer(x))
forall x (writer(x) implies create(x, innovativeidea))
exists x exists y (contain(x, innovativeidea) and about(x, technology) and (not (x=y)) and (contain(y, innovativeidea) and about(y, technology)))
*** Conclusion:
 not contain(thesalmonofdoubt, innovativeidea)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) and professional(quincymcduffie) and widereciever(quincymcduffie) and playsin(quincymcduffie, cfl)
forall x ((exists y(cancatch(x, y) and ball(y))) implies goodwidereceiver(x))
exists x exists y (football(x) and cancatch(quincymcduffie, x)) and (not (x=y) and (football(y) and cancatch(quincymcduffie, y))
forall x (goodwidereceiver(x) implies professional(x))
forall x (goodwidereceiver(x) implies (cancatchwith(x, lefthand) and cancatchwith(x, righthand)))
forall x (football(x) implies ball(x))
*** Conclusion:
 goodwidereceiver(quincymcduffie)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) and professional(quincymcduffie) and widereciever(quincymcduffie) and playsin(quincymcduffie, cfl)
forall x ((exists y(cancatch(x, y) and ball(y))) implies goodwidereceiver(x))
exists x exists y (football(x) and cancatch(quincymcduffie, x)) and (not (x=y) and (football(y) and cancatch(quincymcduffie, y))
forall x (goodwidereceiver(x) implies professional(x))
forall x (goodwidereceiver(x) implies (cancatchwith(x, lefthand) and cancatchwith(x, righthand)))
forall x (football(x) implies ball(x))
*** Conclusion:
 forall x (ball(x) implies cancatch(quincymcduffie, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(quincymcduffie) and professional(quincymcduffie) and widereciever(quincymcduffie) and playsin(quincymcduffie, cfl)
forall x ((exists y(cancatch(x, y) and ball(y))) implies goodwidereceiver(x))
exists x exists y (football(x) and cancatch(quincymcduffie, x)) and (not (x=y) and (football(y) and cancatch(quincymcduffie, y))
forall x (goodwidereceiver(x) implies professional(x))
forall x (goodwidereceiver(x) implies (cancatchwith(x, lefthand) and cancatchwith(x, righthand)))
forall x (football(x) implies ball(x))
*** Conclusion:
 forall x ((professional(x) and widereciever(x)) implies good(x, catchingballs))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (topcover(x) implies (exists y(roof(y)))
forall x (roof(x) implies (protect(x) and blocksunlight(x)))
exists x exists y  (roof(x) and concrete(x)) and (not (x=y) and roof(y) and concrete(y))
exists x exists y  (roof(x) and seagrass(x)) and (not (x=y) and roof(y) and seagrass(y))
forall x forall y ((concrete(x) and seagrass(y)) implies stronger(x, y))
*** Conclusion:
 forall x (not roof(x) implies not protect(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (topcover(x) implies (exists y(roof(y)))
forall x (roof(x) implies (protect(x) and blocksunlight(x)))
exists x exists y  (roof(x) and concrete(x)) and (not (x=y) and roof(y) and concrete(y))
exists x exists y  (roof(x) and seagrass(x)) and (not (x=y) and roof(y) and seagrass(y))
forall x forall y ((concrete(x) and seagrass(y)) implies stronger(x, y))
*** Conclusion:
 forall x forall y ((roof(x) and concrete(x) and roof(y) and seagrass(y)) implies stronger(x, y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (topcover(x) implies (exists y(roof(y)))
forall x (roof(x) implies (protect(x) and blocksunlight(x)))
exists x exists y  (roof(x) and concrete(x)) and (not (x=y) and roof(y) and concrete(y))
exists x exists y  (roof(x) and seagrass(x)) and (not (x=y) and roof(y) and seagrass(y))
forall x forall y ((concrete(x) and seagrass(y)) implies stronger(x, y))
*** Conclusion:
 forall x ((roof(x) and concrete(x)) implies (not blocksunlight(x)))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
 sportingevent(champs)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
 not lastsummerolympics(tokyo)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 sportingevent(olympics)
lastsummerolympics(tokyo)
mostmedals(unitedstates, tokyo)
*** Conclusion:
 exists x (lastsummerolympics(x) and mostmedals(unitedstates, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) and van(astro)
forall x (vehicle(x) and producedby(x, chevrolet) and inthisbatch(x) implies (car(x) xor van(x)))
*** Conclusion:
 van(luminaapv)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) and van(astro)
forall x (vehicle(x) and producedby(x, chevrolet) and inthisbatch(x) implies (car(x) xor van(x)))
*** Conclusion:
 car(luminaapv) xor van(luminaapv)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) and van(astro)
forall x (vehicle(x) and producedby(x, chevrolet) and inthisbatch(x) implies (car(x) xor van(x)))
*** Conclusion:
 van(astro)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 producedby(luminaapv, chevrolet)
producedby(astro, chevrolet) and van(astro)
forall x (vehicle(x) and producedby(x, chevrolet) and inthisbatch(x) implies (car(x) xor van(x)))
*** Conclusion:
 car(astro)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pasifikanewzealanders(x) implies newzealanders(x)) and exists yexists z (pasifikanewzealanders(y) and pasifikanewzealanders(z) and differentethnicgroups(y,z))
forall x (asiannewzealanders(x) implies newzealanders(x)) and exists yexists z (asiannewzealanders(y) and asiannewzealanders(z) and differentethnicgroups(y,z))
forall x (pasifikanewzealanders(x) implies not asiannewzealanders(x))
forall x (pasifikanewzealanders(x) implies speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 pasifikanewzealanders(amy)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pasifikanewzealanders(x) implies newzealanders(x)) and exists yexists z (pasifikanewzealanders(y) and pasifikanewzealanders(z) and differentethnicgroups(y,z))
forall x (asiannewzealanders(x) implies newzealanders(x)) and exists yexists z (asiannewzealanders(y) and asiannewzealanders(z) and differentethnicgroups(y,z))
forall x (pasifikanewzealanders(x) implies not asiannewzealanders(x))
forall x (pasifikanewzealanders(x) implies speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 asiannewzealanders(amy)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pasifikanewzealanders(x) implies newzealanders(x)) and exists yexists z (pasifikanewzealanders(y) and pasifikanewzealanders(z) and differentethnicgroups(y,z))
forall x (asiannewzealanders(x) implies newzealanders(x)) and exists yexists z (asiannewzealanders(y) and asiannewzealanders(z) and differentethnicgroups(y,z))
forall x (pasifikanewzealanders(x) implies not asiannewzealanders(x))
forall x (pasifikanewzealanders(x) implies speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 asiannewzealanders(joe)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pasifikanewzealanders(x) implies newzealanders(x)) and exists yexists z (pasifikanewzealanders(y) and pasifikanewzealanders(z) and differentethnicgroups(y,z))
forall x (asiannewzealanders(x) implies newzealanders(x)) and exists yexists z (asiannewzealanders(y) and asiannewzealanders(z) and differentethnicgroups(y,z))
forall x (pasifikanewzealanders(x) implies not asiannewzealanders(x))
forall x (pasifikanewzealanders(x) implies speaksamoan(x))
pasifikanewzealanders(joe)
speaksamoan(amy)
*** Conclusion:
 speaksamoan(joe)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (roundel(x) implies (rounded(x) and artilleryfortification(x)))
forall x forall y ((roundel(x) and adjacentwalls(x,y)) implies not higher(x, y))
forall x (artilleryfortification(x) implies deploycannons(x))
forall x forall y ((roundel(x) and artilleryfortification(y)) implies older(x, y))
forall x (batterytower(x) implies artilleryfortification(x))
*** Conclusion:
 forall x (batterytower(x) implies deploycannons(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (roundel(x) implies (rounded(x) and artilleryfortification(x)))
forall x forall y ((roundel(x) and adjacentwalls(x,y)) implies not higher(x, y))
forall x (artilleryfortification(x) implies deploycannons(x))
forall x forall y ((roundel(x) and artilleryfortification(y)) implies older(x, y))
forall x (batterytower(x) implies artilleryfortification(x))
*** Conclusion:
 forall x forall y ((roundel(x) and batterytower(y)) implies older(x, y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (roundel(x) implies (rounded(x) and artilleryfortification(x)))
forall x forall y ((roundel(x) and adjacentwalls(x,y)) implies not higher(x, y))
forall x (artilleryfortification(x) implies deploycannons(x))
forall x forall y ((roundel(x) and artilleryfortification(y)) implies older(x, y))
forall x (batterytower(x) implies artilleryfortification(x))
*** Conclusion:
 forall x forall y ((batterytower(x) and adjacentwall(x,y)) implies higher(x, y))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (roundel(x) implies (rounded(x) and artilleryfortification(x)))
forall x forall y ((roundel(x) and adjacentwalls(x,y)) implies not higher(x, y))
forall x (artilleryfortification(x) implies deploycannons(x))
forall x forall y ((roundel(x) and artilleryfortification(y)) implies older(x, y))
forall x (batterytower(x) implies artilleryfortification(x))
*** Conclusion:
 forall x (roundel(x) implies deploycannons(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (businessperson(x) implies exists y(company(y) and ownership(x, y)))
forall x forall y (ownership(x, y) implies makemoney(x, y))
forall x (businessperson(x) implies (businessman(x) xor businesswoman(x)))
exists x (businessperson(x) and extrovert(x))
forall x (businessperson(x) implies handlemoney(x))
businessperson(bob) and ownership(bob, microsoft)
*** Conclusion:
 extrovert(bob)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (businessperson(x) implies exists y(company(y) and ownership(x, y)))
forall x forall y (ownership(x, y) implies makemoney(x, y))
forall x (businessperson(x) implies (businessman(x) xor businesswoman(x)))
exists x (businessperson(x) and extrovert(x))
forall x (businessperson(x) implies handlemoney(x))
businessperson(bob) and ownership(bob, microsoft)
*** Conclusion:
 handlemoney(bob)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (businessperson(x) implies exists y(company(y) and ownership(x, y)))
forall x forall y (ownership(x, y) implies makemoney(x, y))
forall x (businessperson(x) implies (businessman(x) xor businesswoman(x)))
exists x (businessperson(x) and extrovert(x))
forall x (businessperson(x) implies handlemoney(x))
businessperson(bob) and ownership(bob, microsoft)
*** Conclusion:
 businessperson(bob) and makemoney(bob, microsoft)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (leader(x) implies havepower(x))
forall x (leader(x) implies (king(x) xor queen(x)))
forall x (queen(x) implies female(x))
forall x (king(x) implies male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 king(elizabeth)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (leader(x) implies havepower(x))
forall x (leader(x) implies (king(x) xor queen(x)))
forall x (queen(x) implies female(x))
forall x (king(x) implies male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 havepower(elizabeth)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (leader(x) implies havepower(x))
forall x (leader(x) implies (king(x) xor queen(x)))
forall x (queen(x) implies female(x))
forall x (king(x) implies male(x))
queen(elizabeth)
leader(elizabeth)
*** Conclusion:
 leader(elizabeth)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pet(x) implies animal(x))
forall x (pet(x) implies (dog(x) xor cat(x)))
forall x forall y ((pet(y) and ownedby(x,y)) implies cares(x, y))
exists x exists y (cat(x) and naughty(x) and (not (x=y)) and dog(y) and naughty(y))
forall x forall y ((pet(x) and naughty(x) and ownedby(x,y)) implies not liked(x, y))
ownedby(leo, charlie) and pet(leo) and dog(leo) and naughty(leo)
*** Conclusion:
 animal(leo)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pet(x) implies animal(x))
forall x (pet(x) implies (dog(x) xor cat(x)))
forall x forall y ((pet(y) and ownedby(x,y)) implies cares(x, y))
exists x exists y (cat(x) and naughty(x) and (not (x=y)) and dog(y) and naughty(y))
forall x forall y ((pet(x) and naughty(x) and ownedby(x,y)) implies not liked(x, y))
ownedby(leo, charlie) and pet(leo) and dog(leo) and naughty(leo)
*** Conclusion:
 not liked(leo, charlie) and not cares(charlie, leo)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (pet(x) implies animal(x))
forall x (pet(x) implies (dog(x) xor cat(x)))
forall x forall y ((pet(y) and ownedby(x,y)) implies cares(x, y))
exists x exists y (cat(x) and naughty(x) and (not (x=y)) and dog(y) and naughty(y))
forall x forall y ((pet(x) and naughty(x) and ownedby(x,y)) implies not liked(x, y))
ownedby(leo, charlie) and pet(leo) and dog(leo) and naughty(leo)
*** Conclusion:
 forall x (dog(x) implies not naughty(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (book(x) implies contains(x, knowledge))
forall x forall y (readbook(x, y) implies gains(x, knowledge))
forall x (gains(x, knowledge) implies smarter(x))
readbook(harry, walden) and book(walden)
*** Conclusion:
 gains(harry, knowledge)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (book(x) implies contains(x, knowledge))
forall x forall y (readbook(x, y) implies gains(x, knowledge))
forall x (gains(x, knowledge) implies smarter(x))
readbook(harry, walden) and book(walden)
*** Conclusion:
 smarter(harry)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (book(x) implies contains(x, knowledge))
forall x forall y (readbook(x, y) implies gains(x, knowledge))
forall x (gains(x, knowledge) implies smarter(x))
readbook(harry, walden) and book(walden)
*** Conclusion:
 forall x (smarter(x) implies gainknowledge(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y  (labmonitor(x) and aoc(x) and (not (x=y)) and labmonitor(y) and aoc(y))
forall x (labmonitor(x) implies discounted(x))
forall x (discounted(x) implies a1080p(x))
forall x (a1080p(x) implies not typec(x))
labmonitor(lg-34)
*** Conclusion:
 aoc(lg-34)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y  (labmonitor(x) and aoc(x) and (not (x=y)) and labmonitor(y) and aoc(y))
forall x (labmonitor(x) implies discounted(x))
forall x (discounted(x) implies a1080p(x))
forall x (a1080p(x) implies not typec(x))
labmonitor(lg-34)
*** Conclusion:
 not typec(lg-34)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 exists x exists y  (labmonitor(x) and aoc(x) and (not (x=y)) and labmonitor(y) and aoc(y))
forall x (labmonitor(x) implies discounted(x))
forall x (discounted(x) implies a1080p(x))
forall x (a1080p(x) implies not typec(x))
labmonitor(lg-34)
*** Conclusion:
 not a1080p(lg-34)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (in(x, newhaven) implies not high(x))
forall x (yalehousing(x) implies in(x, newhaven))
forall x (in(x, manhattan) implies high(x))
forall x (bloomberg(x) implies in(x, manhattan))
forall x (bloomberglogo(x) implies bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 not high(tower-a)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (in(x, newhaven) implies not high(x))
forall x (yalehousing(x) implies in(x, newhaven))
forall x (in(x, manhattan) implies high(x))
forall x (bloomberg(x) implies in(x, manhattan))
forall x (bloomberglogo(x) implies bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 not in(tower-b, manhattan)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (in(x, newhaven) implies not high(x))
forall x (yalehousing(x) implies in(x, newhaven))
forall x (in(x, manhattan) implies high(x))
forall x (bloomberg(x) implies in(x, manhattan))
forall x (bloomberglogo(x) implies bloomberg(x))
yalehousing(tower-a)
bloomberglogo(tower-b)
*** Conclusion:
 not in(tower-b, newhaven)
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((coffee(x) and soldin(x, walmart)) implies not from(x, france))
forall x ((coffee(x) and favoredby(x, localresidents)) implies from(x, colombia))
forall x ((coffee(x) and highprice(x)) implies favoredbylocalresidents(x))
coffee(civetcoffee) and not from(colombia)
expensive(jamaicablue) and coffee(jamaicablue)
forall x ((expensive(x) and coffee(x)) implies highprice(x))
*** Conclusion:
 from(civetcoffee, france)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((coffee(x) and soldin(x, walmart)) implies not from(x, france))
forall x ((coffee(x) and favoredby(x, localresidents)) implies from(x, colombia))
forall x ((coffee(x) and highprice(x)) implies favoredbylocalresidents(x))
coffee(civetcoffee) and not from(colombia)
expensive(jamaicablue) and coffee(jamaicablue)
forall x ((expensive(x) and coffee(x)) implies highprice(x))
*** Conclusion:
 from(jamaicablue, colombia)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((coffee(x) and soldin(x, walmart)) implies not from(x, france))
forall x ((coffee(x) and favoredby(x, localresidents)) implies from(x, colombia))
forall x ((coffee(x) and highprice(x)) implies favoredbylocalresidents(x))
coffee(civetcoffee) and not from(colombia)
expensive(jamaicablue) and coffee(jamaicablue)
forall x ((expensive(x) and coffee(x)) implies highprice(x))
*** Conclusion:
 favoredby(jamaicablue, localresidents)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (ownedby(x, company) implies connectedto(x, googlehome))
forall x (ownedby(x, employee) implies connectedto(x, companywifi))
forall x (connectedto(x, googlehome) implies controlledby(x, managers))
forall x (connectedto(x, companywifi) implies easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 easytooperate(modelxx)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (ownedby(x, company) implies connectedto(x, googlehome))
forall x (ownedby(x, employee) implies connectedto(x, companywifi))
forall x (connectedto(x, googlehome) implies controlledby(x, managers))
forall x (connectedto(x, companywifi) implies easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 controlledby(modelxx, managers)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (ownedby(x, company) implies connectedto(x, googlehome))
forall x (ownedby(x, employee) implies connectedto(x, companywifi))
forall x (connectedto(x, googlehome) implies controlledby(x, managers))
forall x (connectedto(x, companywifi) implies easytooperate(x))
ownedby(modelxx, employee)
*** Conclusion:
 connectedto(modelxx, googlehome)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (attendinperson(x) implies registered(x))
forall x (attend(x) implies (attendinperson(x) xor attendremotely(x)))
forall x ((attend(x) and fromchina(x)) implies not attendremotely(x))
attend(james) and (not attendremotely(james))
fromchina(jack) and attend(jack)
*** Conclusion:
 attend(james) and (not attendinperson(james))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (attendinperson(x) implies registered(x))
forall x (attend(x) implies (attendinperson(x) xor attendremotely(x)))
forall x ((attend(x) and fromchina(x)) implies not attendremotely(x))
attend(james) and (not attendremotely(james))
fromchina(jack) and attend(jack)
*** Conclusion:
 attend(jack) and attendinperson(jack)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (attendinperson(x) implies registered(x))
forall x (attend(x) implies (attendinperson(x) xor attendremotely(x)))
forall x ((attend(x) and fromchina(x)) implies not attendremotely(x))
attend(james) and (not attendremotely(james))
fromchina(jack) and attend(jack)
*** Conclusion:
 registered(jack)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (podcast(x) implies not novel(x))
forall x((exists y(bornin(x, y) and city(y) and locatedin(y,america)) implies american(x))
forall x forall y ((novel(x) and writtenby(x, y)) implies writesnovel(y))
american(dani_shapiro) and writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) and writtenin(family_history, yr2003)
podcast(family_secrets) and createdby(family_secrets, dani_shapiro)
city(boston) and american(boston)
*** Conclusion:
 writesnovel(dani_shapiro)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (podcast(x) implies not novel(x))
forall x((exists y(bornin(x, y) and city(y) and locatedin(y,america)) implies american(x))
forall x forall y ((novel(x) and writtenby(x, y)) implies writesnovel(y))
american(dani_shapiro) and writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) and writtenin(family_history, yr2003)
podcast(family_secrets) and createdby(family_secrets, dani_shapiro)
city(boston) and american(boston)
*** Conclusion:
 isnovel(family_secrets)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (podcast(x) implies not novel(x))
forall x((exists y(bornin(x, y) and city(y) and locatedin(y,america)) implies american(x))
forall x forall y ((novel(x) and writtenby(x, y)) implies writesnovel(y))
american(dani_shapiro) and writer(dani_shapiro)
writtenby(family_history, dani_shapiro)
novel(family_history) and writtenin(family_history, yr2003)
podcast(family_secrets) and createdby(family_secrets, dani_shapiro)
city(boston) and american(boston)
*** Conclusion:
 bornin(dani_shapiro, boston)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((coach(x, y) and footballclub(y)) implies footballcoach(x))
forall w forall x forall y forall z ((playpositionfor(x, w, y, z) and innfl(y, z)) implies playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 footballcoach(dennisgreen)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((coach(x, y) and footballclub(y)) implies footballcoach(x))
forall w forall x forall y forall z ((playpositionfor(x, w, y, z) and innfl(y, z)) implies playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 not playinnfl(johnrandle)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((coach(x, y) and footballclub(y)) implies footballcoach(x))
forall w forall x forall y forall z ((playpositionfor(x, w, y, z) and innfl(y, z)) implies playinnfl(x))
footballclub(minnesotavikings)
coach(dennisgreen, minnesotavikings)
receivetd(criscarter, num13)
innfl(minnesotavikings, yr1997)
playpositionfor(johnrandle, defensivetackle, minnesotavikings, yr1997)
*** Conclusion:
 playpositionfor(criscarter, wr, minnesotavikings, year1997)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((summerolympicsin(x,y) and in(x, unitedstates)) implies summerolympicsin(x, unitedstates))
forall x forall y ((in(x, y) and in(y, unitedstates)) implies in(x, unitedstates))
forall x forall y forall z ((in(x, z) and state(z) and summerolympicsin(x,y)) implies summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
not insummerolympicsin(boxing, yr2028) and (not insummerolympicsin(modern_pentathlon, yr2028)) and (not insummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 summerolympicsin(unitedstates, yr2028)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((summerolympicsin(x,y) and in(x, unitedstates)) implies summerolympicsin(x, unitedstates))
forall x forall y ((in(x, y) and in(y, unitedstates)) implies in(x, unitedstates))
forall x forall y forall z ((in(x, z) and state(z) and summerolympicsin(x,y)) implies summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
not insummerolympicsin(boxing, yr2028) and (not insummerolympicsin(modern_pentathlon, yr2028)) and (not insummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 not summerolympicsin(georgia, yr1996)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y ((summerolympicsin(x,y) and in(x, unitedstates)) implies summerolympicsin(x, unitedstates))
forall x forall y ((in(x, y) and in(y, unitedstates)) implies in(x, unitedstates))
forall x forall y forall z ((in(x, z) and state(z) and summerolympicsin(x,y)) implies summerolympicsin(z, y))
summerolympicsin(losangeles, yr2028)
in(losangeles, california)
in(atlanta, unitedstates)
in(california, unitedstates)
in(atlanta, georgia)
not insummerolympicsin(boxing, yr2028) and (not insummerolympicsin(modern_pentathlon, yr2028)) and (not insummerolympicsin(weightlifting, yr2028))
summerolympicsin(atlanta, yr1996)
*** Conclusion:
 insummerolympicsin(skateboarding, yr2028)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y forall z (albumbyband(x, y) and rockband(y, z) implies genre(x, rock))
forall x forall y forall z (albumbyband(x, y) and albumaward(x, z) implies rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
exists x (songinfilm(x) and songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 genre(troubleatthehenhouse, rock)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y forall z (albumbyband(x, y) and rockband(y, z) implies genre(x, rock))
forall x forall y forall z (albumbyband(x, y) and albumaward(x, z) implies rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
exists x (songinfilm(x) and songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 not exists x(rockband(x, canada) and award(x, thealbumoftheyear))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x forall y forall z (albumbyband(x, y) and rockband(y, z) implies genre(x, rock))
forall x forall y forall z (albumbyband(x, y) and albumaward(x, z) implies rockbandaward(y, z))
albumbyband(trouble_at_the_henhouse, the_tragically_hip)
rockband(the_tragically_hip, canada)
songinalbum(butts_wigglin, trouble_at_the_henhouse)
albumaward(trouble_at_the_henhouse, the_album_of_the_year)
exists x (songinfilm(x) and songinalbum(x, trouble_at_the_henhouse))
*** Conclusion:
 songinfilm(buttswigglin)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) and directedby(thedeparture, lanawilson) and directedby(missamericana, lanawilson)
forall x forall y (directedby(x, y) implies filmmaker(y))
documentary(aftertiller)
forall x (documentary(x) implies film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall x forall y forall z ((from(x, y) and in(y, z)) implies from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 from(lanawilson, unitedstates) and filmmaker(lanawilson)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) and directedby(thedeparture, lanawilson) and directedby(missamericana, lanawilson)
forall x forall y (directedby(x, y) implies filmmaker(y))
documentary(aftertiller)
forall x (documentary(x) implies film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall x forall y forall z ((from(x, y) and in(y, z)) implies from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 not exists x(filmmaker(x) and from(x, kirkland) and directedby(missamericana, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 directedby(aftertiller, lanawilson) and directedby(thedeparture, lanawilson) and directedby(missamericana, lanawilson)
forall x forall y (directedby(x, y) implies filmmaker(y))
documentary(aftertiller)
forall x (documentary(x) implies film(x))
from(lanawilson, kirkland)
in(kirkland, unitedstates)
forall x forall y forall z ((from(x, y) and in(y, z)) implies from(x, z))
nomination(aftertiller, theindependentspiritawardforbestdocumentary)
*** Conclusion:
 filmmakeraward(lanawilson, theindependentspiritawardforbestdocumentary)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) and footballreferee(brianwinter)
retired(brianwinter) and retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
exists x (footballreferee(x) and refereeobserver(x))
sonof(andywinter, brianwinter) and footballplayer(andywinter) and playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 exists x exists y(sonof(x, y) and refereeobserver(y) and footballplayer(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) and footballreferee(brianwinter)
retired(brianwinter) and retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
exists x (footballreferee(x) and refereeobserver(x))
sonof(andywinter, brianwinter) and footballplayer(andywinter) and playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 not refereeobserver(brianwinter)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) and footballreferee(brianwinter)
retired(brianwinter) and retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
exists x (footballreferee(x) and refereeobserver(x))
sonof(andywinter, brianwinter) and footballplayer(andywinter) and playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 retired(brianwinter)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 scottish(brianwinter) and footballreferee(brianwinter)
retired(brianwinter) and retiredin(brianwinter, yr2012)
refereeobserver(brianwinter)
exists x (footballreferee(x) and refereeobserver(x))
sonof(andywinter, brianwinter) and footballplayer(andywinter) and playsfor(andywinter, hamiltonacademical)
*** Conclusion:
 referee(andywinter)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) and physician(michael) and journalist(michael) and author(michael) and broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) and editedby(worldmedicine, michael)
bornin(michael, yorkshire) and exists x(sonof(michael, x) and generalpractitioner(x))
*** Conclusion:
 exists x exists y (sonof(x, y) and generalpractitioner(y) and wordsetter(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) and physician(michael) and journalist(michael) and author(michael) and broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) and editedby(worldmedicine, michael)
bornin(michael, yorkshire) and exists x(sonof(michael, x) and generalpractitioner(x))
*** Conclusion:
 not magazine(worldmedicine)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) and physician(michael) and journalist(michael) and author(michael) and broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) and editedby(worldmedicine, michael)
bornin(michael, yorkshire) and exists x(sonof(michael, x) and generalpractitioner(x))
*** Conclusion:
 forall x (british(x) implies not author(x))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) and physician(michael) and journalist(michael) and author(michael) and broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) and editedby(worldmedicine, michael)
bornin(michael, yorkshire) and exists x(sonof(michael, x) and generalpractitioner(x))
*** Conclusion:
 forall x (journalist(x) implies not bornin(x, yorkshire))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 british(michael) and physician(michael) and journalist(michael) and author(michael) and broadcaster(michael)
wordsetter(michael)
magazine(worldmedicine) and editedby(worldmedicine, michael)
bornin(michael, yorkshire) and exists x(sonof(michael, x) and generalpractitioner(x))
*** Conclusion:
 exists x exists y (son(x, y) and generalpractitioner(y) and not author(x))
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) and physician(herodicus) and dietician(herodicus) and sophist(herodicus) and gymnast(herodicus)
born(herodicus, selymbia) and city(selymbia)
colony(selymbia, megara) and citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
exists x exists y (theory(x) and from(x, herodicus) and foundationof(x, sportsmedicine) and (not (x=y)) and theory(y) and from(y, herodicus) and foundationof(y, sportsmedicine))
*** Conclusion:
 tutor(herodicus, hippocrates)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) and physician(herodicus) and dietician(herodicus) and sophist(herodicus) and gymnast(herodicus)
born(herodicus, selymbia) and city(selymbia)
colony(selymbia, megara) and citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
exists x exists y (theory(x) and from(x, herodicus) and foundationof(x, sportsmedicine) and (not (x=y)) and theory(y) and from(y, herodicus) and foundationof(y, sportsmedicine))
*** Conclusion:
 tutor(hippocrates, herodicus)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) and physician(herodicus) and dietician(herodicus) and sophist(herodicus) and gymnast(herodicus)
born(herodicus, selymbia) and city(selymbia)
colony(selymbia, megara) and citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
exists x exists y (theory(x) and from(x, herodicus) and foundationof(x, sportsmedicine) and (not (x=y)) and theory(y) and from(y, herodicus) and foundationof(y, sportsmedicine))
*** Conclusion:
 exists x (born(herodicus, x) and citystate(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) and physician(herodicus) and dietician(herodicus) and sophist(herodicus) and gymnast(herodicus)
born(herodicus, selymbia) and city(selymbia)
colony(selymbia, megara) and citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
exists x exists y (theory(x) and from(x, herodicus) and foundationof(x, sportsmedicine) and (not (x=y)) and theory(y) and from(y, herodicus) and foundationof(y, sportsmedicine))
*** Conclusion:
 not recommend(herodicus, massages)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 greek(herodicus) and physician(herodicus) and dietician(herodicus) and sophist(herodicus) and gymnast(herodicus)
born(herodicus, selymbia) and city(selymbia)
colony(selymbia, megara) and citystate(megara)
tutor(herodicus, hippocrates)
recommend(herodicus, massages)
exists x exists y (theory(x) and from(x, herodicus) and foundationof(x, sportsmedicine) and (not (x=y)) and theory(y) and from(y, herodicus) and foundationof(y, sportsmedicine))
*** Conclusion:
 exists x exists y (born(herodicus, x) and colony(x, y) and citystate(y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (enterococcusdurans(x) implies species(x, enterococcus))
forall x (enterococcusdurans(x) implies grampositive(x) and catalasenegative(x) and oxidasenegative(x) and coccus(x) and bacteria(x))
exists x exists y (enterococcusdurans(x) and antiinflammatoryagent(y) and produces(x, y))
forall x (antiinflammatoryagent(x) implies studied(x))
*** Conclusion:
 forall x (enterococcusdurans(x) implies catalasenegative(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (enterococcusdurans(x) implies species(x, enterococcus))
forall x (enterococcusdurans(x) implies grampositive(x) and catalasenegative(x) and oxidasenegative(x) and coccus(x) and bacteria(x))
exists x exists y (enterococcusdurans(x) and antiinflammatoryagent(y) and produces(x, y))
forall x (antiinflammatoryagent(x) implies studied(x))
*** Conclusion:
 exists x (grampositive(x) and studied(x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (enterococcusdurans(x) implies species(x, enterococcus))
forall x (enterococcusdurans(x) implies grampositive(x) and catalasenegative(x) and oxidasenegative(x) and coccus(x) and bacteria(x))
exists x exists y (enterococcusdurans(x) and antiinflammatoryagent(y) and produces(x, y))
forall x (antiinflammatoryagent(x) implies studied(x))
*** Conclusion:
 forall x forall y (enterococcusdurans(x) and produces(x, y) implies not studied(y))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) and birdgenus(ambiortus)
forall x(knownspeciesof(x, ambiortus) implies isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 exists x (discover(yevgenykurochkin, x) and birdgenus(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) and birdgenus(ambiortus)
forall x(knownspeciesof(x, ambiortus) implies isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 exists x (knownspeciesof(x, ambiortus) and not livein(x, mongolia))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) and birdgenus(ambiortus)
forall x(knownspeciesof(x, ambiortus) implies isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 livein(yevgenykurochkin, mongolia)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 prehistoric(ambiortus) and birdgenus(ambiortus)
forall x(knownspeciesof(x, ambiortus) implies isspecies(x, ambiortusdementjevi))
livein(ambiortusdementjevi, mongolia)
discover(yevgenykurochkin, ambiortus)
*** Conclusion:
 forall x (speciesof(x, ambiortus) implies livein(x, mongolia))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) and forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
 exists x (old(x) and traditionalsummercamp(x) and forboysandgirls(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) and forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
 exists x (traditionalsummercamp(x) and forboysandgirls(x) and operateduntil(ymca, x, year2015))
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 traditionalsummercamp(campdavern) and forboysandgirls(campdavern)
establishedin(campdavern, year1946)
operateduntil(ymca, campdavern, year2015)
old(campdavern)
*** Conclusion:
 establishedin(campdavern, year1989)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) and philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall x (essayist(x) implies writer(x))
*** Conclusion:
 bornin(robertzimmer, germany)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) and philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall x (essayist(x) implies writer(x))
*** Conclusion:
 not writer(robertzimmer)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(robertzimmer, germany) and philosopher(robertzimmer)
essayist(robertzimmer)
bornin(robertzimmer, yr1953)
forall x (essayist(x) implies writer(x))
*** Conclusion:
 biographer(robertzimmer)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
exists x exists y (chessplayer(x) and grandmaster(x) and (not (x=y)) and chessplayer(y) and grandmaster(y))
forall x ((bornin(x, newyorkcity) and livein(x, newyorkcity)) implies newyorker(x))
forall x (livein(x, manhattan) implies livein(x, newyorkcity))
*** Conclusion:
 newyorker(asahoffmann)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
exists x exists y (chessplayer(x) and grandmaster(x) and (not (x=y)) and chessplayer(y) and grandmaster(y))
forall x ((bornin(x, newyorkcity) and livein(x, newyorkcity)) implies newyorker(x))
forall x (livein(x, manhattan) implies livein(x, newyorkcity))
*** Conclusion:
 grandmaster(asahoffmann)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(asahoffmann, newyorkcity)
livein(asahoffmann, manhattan)
chessplayer(asahoffmann)
exists x exists y (chessplayer(x) and grandmaster(x) and (not (x=y)) and chessplayer(y) and grandmaster(y))
forall x ((bornin(x, newyorkcity) and livein(x, newyorkcity)) implies newyorker(x))
forall x (livein(x, manhattan) implies livein(x, newyorkcity))
*** Conclusion:
 not livein(asahoffmann, newyorkcity)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) and make(janjelinek, minimaltechno)
forall x ((make(x, glitch) or make(x, minimaltechno) or make(x, microhouse)) implies electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall x ((exists y(publishthroughlabel(x, y))) implies signedmusician(x))
*** Conclusion:
 electronicmusician(janjelinek)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) and make(janjelinek, minimaltechno)
forall x ((make(x, glitch) or make(x, minimaltechno) or make(x, microhouse)) implies electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall x ((exists y(publishthroughlabel(x, y))) implies signedmusician(x))
*** Conclusion:
 not signedmusician(janjelinek)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 make(janjelinek, glitch) and make(janjelinek, minimaltechno)
forall x ((make(x, glitch) or make(x, minimaltechno) or make(x, microhouse)) implies electronicmusician(x))
publishthroughlabel(janjelinek, faitiche)
forall x ((exists y(publishthroughlabel(x, y))) implies signedmusician(x))
*** Conclusion:
 german(janjelinek)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
not samecountry(germany, unitedstates)
forall x forall y forall z (officein(x, y) and officein(x, z) and (not samecountry(y, z)) implies multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 multinationalcompany(ableton)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
not samecountry(germany, unitedstates)
forall x forall y forall z (officein(x, y) and officein(x, z) and (not samecountry(y, z)) implies multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 makesaisoftware(ableton)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 officein(ableton, germany)
officein(ableton, unitedstates)
not samecountry(germany, unitedstates)
forall x forall y forall z (officein(x, y) and officein(x, z) and (not samecountry(y, z)) implies multinationalcompany(x))
makesmusicsoftware(ableton)
*** Conclusion:
 not officein(ableton, germany)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall x (striker(x) implies soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall x forall y (left(x, y) implies not playsfor(x, y))
*** Conclusion:
 soccerplayer(robertlewandowski)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall x (striker(x) implies soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall x forall y (left(x, y) implies not playsfor(x, y))
*** Conclusion:
 playsfor(robertlewandowski, bayernmunchen)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 striker(robertlewandowski)
forall x (striker(x) implies soccerplayer(x))
left(robertlewandowski, bayernmunchen)
forall x forall y (left(x, y) implies not playsfor(x, y))
*** Conclusion:
 soccerstar(robertlewandowski)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) and specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall x ((book(x) and publishedby(x, newvesselpress)) implies in(x, english))
book(neapolitanchronicles) and publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) and publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 book(neapolitanchronicles) and in(neapolitanchronicles, english)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) and specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall x ((book(x) and publishedby(x, newvesselpress)) implies in(x, english))
book(neapolitanchronicles) and publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) and publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 publishedby(harrypotter, newvesselpress)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 publishinghouse(newvesselpress) and specializesintranslatingintoenglish(newvesselpress, foreignliterature)
forall x ((book(x) and publishedby(x, newvesselpress)) implies in(x, english))
book(neapolitanchronicles) and publishedby(neapolitanchronicles, newvesselpress)
translatedfrom(neapolitanchronicles, italian)
book(palaceofflies) and publishedby(palaceofflies, newvesselpress)
*** Conclusion:
 translatedfrom(palaceofflies, italian)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sells(quiksilver, x) implies (sportswear(x) or clothing(x) or footwear(x) or accessory(x)))
clothing(flannel)
exists x (sells(quiksilver, x) and owns(joe, x))
*** Conclusion:
 sells(quiksilver, beer)
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sells(quiksilver, x) implies (sportswear(x) or clothing(x) or footwear(x) or accessory(x)))
clothing(flannel)
exists x (sells(quiksilver, x) and owns(joe, x))
*** Conclusion:
 owns(joe, flannel)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (sells(quiksilver, x) implies (sportswear(x) or clothing(x) or footwear(x) or accessory(x)))
clothing(flannel)
exists x (sells(quiksilver, x) and owns(joe, x))
*** Conclusion:
 exists x (owns(joe, x) and sportswear(x) or clothing(x) or footwear(x) or accessory(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall x (residentof(x, lawtonpark) implies usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 usezipcode(tom, num98199)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall x (residentof(x, lawtonpark) implies usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 not usezipcode(tom, num98199)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall x (residentof(x, lawtonpark) implies usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 residentof(tom, washington)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 neighbourhoodin(lawtonpark, seattle)
forall x (residentof(x, lawtonpark) implies usezipcode(x, num98199))
residentof(tom, lawtonpark)
usezipcode(daniel, num98199)
*** Conclusion:
 residentof(daniel, lawtonpark)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (vehicleregistrationplatein(x, istanbul) implies beginwith(x, num34))
forall x (not beginwith(x, num34) implies not fromistanbul(x))
exists x (owns(joe, x) and vehicleregistrationplatein(x, istanbul))
exists x (owns(tom, x) and beginwith(x, num35))
forall x (beginwith(x, num35) implies not beginwith(x, num34))
*** Conclusion:
 exists x (owns(joe, x) and beginwith(x, num34))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x (vehicleregistrationplatein(x, istanbul) implies beginwith(x, num34))
forall x (not beginwith(x, num34) implies not fromistanbul(x))
exists x (owns(joe, x) and vehicleregistrationplatein(x, istanbul))
exists x (owns(tom, x) and beginwith(x, num35))
forall x (beginwith(x, num35) implies not beginwith(x, num34))
*** Conclusion:
 exists x (owns(tom, x) and vehicleregistrationplatein(x, istanbul))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) and in(luzon, philippines)
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon))
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon) and deadly(x))
*** Conclusion:
 island(leyte) and in(leyte, philippines)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) and in(luzon, philippines)
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon))
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon) and deadly(x))
*** Conclusion:
 forall x forall y ((earthquake(x) and strikeincity(x, y) and in(y, philippines)) implies not deadly(x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 island(luzon) and in(luzon, philippines)
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon))
exists x (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, luzon) and deadly(x))
*** Conclusion:
 exists x exists y (earthquake(x) and strikeinyr(x, year1999) and strikeinmo(x, december) and strikeincity(x, y) and in(y, philippines))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) and discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not (is(diethylcarbamazine, ivermectin))
*** Conclusion:
 not (preferredtreatmentfor(riverblindness, diethylcarbamazine))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) and discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not (is(diethylcarbamazine, ivermectin))
*** Conclusion:
 treats(diethylcarbamazine, riverblindness)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 medication(diethylcarbamazine) and discoversin(diethylcarbamazine, yr1947)
treats(diethylcarbamazine, riverblindness)
preferredtreatmentfor(riverblindness, ivermectin)
not (is(diethylcarbamazine, ivermectin))
*** Conclusion:
 treats(diethylcarbamazine, filariasis)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((legislator(x) and stealsfunds(x)) implies suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) and stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 suspended(tiffanytalston)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((legislator(x) and stealsfunds(x)) implies suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) and stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 not suspended(tiffanytalston)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 forall x ((legislator(x) and stealsfunds(x)) implies suspended(x))
legislator(tiffanytalston)
stealsfunds(tiffanytalston) and stealsfundsinyr(tiffanytalston, yr2012)
*** Conclusion:
 prison(tiffanytalston)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) and filmproducer(daveeddiggs)
exists x exists y(playsin(daveeddiggs, x, hamilton) and (not (x=y)) and playsin(daveeddiggs, y, hamilton)) and onbroadway(hamilton) and musical(hamilton)
exists x exists y(actor(x) and playsin(x, y, hamilton) and wins(x, bestactoraward))
exists x (actor(x) and playsin(x, thomasjefferson, hamilton) and wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall x ((musical(x) and onbroadway(x)) implies not film(x))
*** Conclusion:
 film(hamilton)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) and filmproducer(daveeddiggs)
exists x exists y(playsin(daveeddiggs, x, hamilton) and (not (x=y)) and playsin(daveeddiggs, y, hamilton)) and onbroadway(hamilton) and musical(hamilton)
exists x exists y(actor(x) and playsin(x, y, hamilton) and wins(x, bestactoraward))
exists x (actor(x) and playsin(x, thomasjefferson, hamilton) and wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall x ((musical(x) and onbroadway(x)) implies not film(x))
*** Conclusion:
 wins(daveeddiggs, bestactoraward)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 actor(daveeddiggs) and filmproducer(daveeddiggs)
exists x exists y(playsin(daveeddiggs, x, hamilton) and (not (x=y)) and playsin(daveeddiggs, y, hamilton)) and onbroadway(hamilton) and musical(hamilton)
exists x exists y(actor(x) and playsin(x, y, hamilton) and wins(x, bestactoraward))
exists x (actor(x) and playsin(x, thomasjefferson, hamilton) and wins(x, bestactoraward))
plays(daveeddiggs, thomasjefferson)
forall x ((musical(x) and onbroadway(x)) implies not film(x))
*** Conclusion:
 exists x exists y(wins(hamilton, x) and (not (x=y)) and wins(hamilton, y))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) and lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall x (bornin(x, athensohio) implies american(x))
*** Conclusion:
 bornin(bernardabrysonshahn, greece)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) and lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall x (bornin(x, athensohio) implies american(x))
*** Conclusion:
 american(bernardabrysonshahn)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 painter(bernardabrysonshahn) and lithographer(bernardabrysonshahn)
bornin(bernardabrysonshahn, athensohio)
marriedto(bernardabrysonshahn, benshahn)
forall x (bornin(x, athensohio) implies american(x))
*** Conclusion:
 divorced(bernardabrysonshahn)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) and songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) and competesonaustralianidol(bobbyflynn)
forall x (competesonaustralianidol(x) implies australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 australiancitizen(bobbyflynn)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) and songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) and competesonaustralianidol(bobbyflynn)
forall x (competesonaustralianidol(x) implies australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 flewtoin(bobbyflynn, america, year2007)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 singer(bobbyflynn) and songwriter(bobbyflynn)
finishesin(bobbyflynn, number7) and competesonaustralianidol(bobbyflynn)
forall x (competesonaustralianidol(x) implies australiancitizen(x))
nationwidetourin(theomegathreeband, year2007)
member(bobbyflynn, theomegathreeband)
bornin(bobbyflynn, queensland)
*** Conclusion:
 bornin(bobbyflynn, queens)
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) and videogameholdingcompany(koeitecmo) and animeholdingcompany(koeitecmo) and holdingcompany(x)
forall x (holdingcompany(x) implies exists y(company(y) and holds(x, y)))
disbandsin(tecmo, japan) and survives(koei) and renames(koei)
forall x (videogameholdingcompany(x) implies holdingcompany(x))
*** Conclusion:
 exists x (company(x) and holds(koeitecmo, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) and videogameholdingcompany(koeitecmo) and animeholdingcompany(koeitecmo) and holdingcompany(x)
forall x (holdingcompany(x) implies exists y(company(y) and holds(x, y)))
disbandsin(tecmo, japan) and survives(koei) and renames(koei)
forall x (videogameholdingcompany(x) implies holdingcompany(x))
*** Conclusion:
 exists x (company(x) and holds(tecmo, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 japanese(koeitecmo) and videogameholdingcompany(koeitecmo) and animeholdingcompany(koeitecmo) and holdingcompany(x)
forall x (holdingcompany(x) implies exists y(company(y) and holds(x, y)))
disbandsin(tecmo, japan) and survives(koei) and renames(koei)
forall x (videogameholdingcompany(x) implies holdingcompany(x))
*** Conclusion:
 animeholdingcompany(koeitecmo)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) and rower(virginialee)
competesin(virginialee, sweepoaredevents) and competesin(virginialee, scullingevents)
city(sydney) and homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
 forall x (rower(x) implies not homecity(sydney, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) and rower(virginialee)
competesin(virginialee, sweepoaredevents) and competesin(virginialee, scullingevents)
city(sydney) and homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
 forall x (australian(x) implies not represented(x, newsouthwales))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 australian(virginialee) and rower(virginialee)
competesin(virginialee, sweepoaredevents) and competesin(virginialee, scullingevents)
city(sydney) and homecity(sydney, virginialee)
represents(virginialee, newsouthwales)
*** Conclusion:
 exists x (australian(x) and competesin(x, sweepoaredevents) and represents(x, newsouthwales))
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) and childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
 exists x (dramafilm(x) and produces(columbiapictures, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) and childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
 exists x (adventurefilm(x) and produces(columbiapictures, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) and childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
 exists x (childrensfilm(x) and produces(paramount, x))
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 dramafilm(adventuresofrusty) and childrensfilm(adventuresofrusty)
produces(columbiapictures, adventuresofrusty)
produces(paramount, tintin)
adventurefilm(tintin)
*** Conclusion:
 exists x (adventurefilm(x) and produces(paramount, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 cricketeer(royrichardson) and playsfor(royrichardson, sintmaarten) and constituentcountry(sintmaarten)
righthanded(royrichardson) and batsman(royrichardson) and mediumpacebowler(royrichardson)
oldatdebut(royrichardson)
dismisses(shervillehuggins, royrichardson)
*** Conclusion:
 forall x forall y ((consituentcountry(y) and playedfor(x, y)) implies  not dismissed(shervillehuggins, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 cricketeer(royrichardson) and playsfor(royrichardson, sintmaarten) and constituentcountry(sintmaarten)
righthanded(royrichardson) and batsman(royrichardson) and mediumpacebowler(royrichardson)
oldatdebut(royrichardson)
dismisses(shervillehuggins, royrichardson)
*** Conclusion:
 forall x ((righthanded(x) and mediumpacebowler(x)) implies not playedfor(x, sintmaarten))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(ainderbyquernhow) and civilparish(ainderbyquernhow) and in(ainderbyquernhow, hambletondistrict)
in(hambletondistrict, northyorkshire)
in(northyorkshire, england)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
*** Conclusion:
 exists x (village(x) and in(x, england))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 village(ainderbyquernhow) and civilparish(ainderbyquernhow) and in(ainderbyquernhow, hambletondistrict)
in(hambletondistrict, northyorkshire)
in(northyorkshire, england)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
*** Conclusion:
 not (exists x (civilparish(x) and in(x, england)))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 televisionseries(diray) and policeprocedural(diray)
creates(maya, diray) and writes(maya, diray)
produces(jed, diray)
british(maya) and british(jed)
*** Conclusion:
 exists x (british(x) and creates(x, diray))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 televisionseries(diray) and policeprocedural(diray)
creates(maya, diray) and writes(maya, diray)
produces(jed, diray)
british(maya) and british(jed)
*** Conclusion:
 exists x exists y(british(x) and televisionseries(y) and produces(x, y))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) and in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) and includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
 exists x (leads(roderickstrong, x) and professionalwrestlingstable(x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) and in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) and includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
 leads(roderickstrong, creedbrothers)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 professionalwrestlingstable(diamondmine) and in(diamondmine, wwe)
leads(roderickstrong, diamondmine)
includes(diamondmine, creedbrothers) and includes(diamondmine, ivynile)
feuds(imperium, diamondmine)
*** Conclusion:
 forall x ((professionalwrestlingstable(x) and includes(x, ivynile)) implies not feuds(imperium, x))
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) and actress(deborahwallace) and playwright(deborahwallace) and producer(deborahwallace)
play(psyche) and basedon(psyche, lifeofjamesmirandabarry)
play(homesick) and writtenby(homesick, deborahwallace) and play(psyche) and writtenby(psyche, deborahwallace) and play(thevoid) and writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
 exists x (coproduces(x, gasland) and writtenby(homesick, x))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) and actress(deborahwallace) and playwright(deborahwallace) and producer(deborahwallace)
play(psyche) and basedon(psyche, lifeofjamesmirandabarry)
play(homesick) and writtenby(homesick, deborahwallace) and play(psyche) and writtenby(psyche, deborahwallace) and play(thevoid) and writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
 forall x (play(x) and writtenby(x, deborahwallace) implies not basedon(x, lifeofjamesmirandabarry))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 bornin(deborahwallace, scotland) and actress(deborahwallace) and playwright(deborahwallace) and producer(deborahwallace)
play(psyche) and basedon(psyche, lifeofjamesmirandabarry)
play(homesick) and writtenby(homesick, deborahwallace) and play(psyche) and writtenby(psyche, deborahwallace) and play(thevoid) and writtenby(thevoid, deborahwallace)
coproduce(deborahwallace, gasland)
*** Conclusion:
 play(gasland)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) and screenwriter(maggiefriedman) and producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) and executiveproducerof(maggiefriedman, witchesofeastend) and lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) and series(witchesofeastend)
produces(maggiefriedman, eastwick) and develops(maggiefriedman, eastwick)
series(eastwick) and airedon(eastwick, abc)
*** Conclusion:
 exists x exists y (series(x) and airedon(x, abc) and develops(y, x) and showrunnerof(y, witchesofeastend))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) and screenwriter(maggiefriedman) and producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) and executiveproducerof(maggiefriedman, witchesofeastend) and lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) and series(witchesofeastend)
produces(maggiefriedman, eastwick) and develops(maggiefriedman, eastwick)
series(eastwick) and airedon(eastwick, abc)
*** Conclusion:
 forall x (series(x) and airedon(x, abc) and exists y(showrunnerof(y, witchesofeastend)) implies not develops(y, x))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 american(maggiefriedman) and screenwriter(maggiefriedman) and producer(maggiefriedman)
showrunnerof(maggiefriedman, witchesofeastend) and executiveproducerof(maggiefriedman, witchesofeastend) and lifetimetelevisionseries(maggiefriedman)
fantasydrama(witchesofeastend) and series(witchesofeastend)
produces(maggiefriedman, eastwick) and develops(maggiefriedman, eastwick)
series(eastwick) and airedon(eastwick, abc)
*** Conclusion:
 develops(maggiefriedman, witchesofeastend)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 largecomplex(shafaq-asiman) and largecomplex(shafaq-asiman) and offshore(shafaq-asiman) and geologicalstructures(shafaq-asiman) and in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall x forall y (northwestof(x, y) implies southeastof(y, x))
*** Conclusion:
 southeastof(baku, shafaq-asiman)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 largecomplex(shafaq-asiman) and largecomplex(shafaq-asiman) and offshore(shafaq-asiman) and geologicalstructures(shafaq-asiman) and in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall x forall y (northwestof(x, y) implies southeastof(y, x))
*** Conclusion:
 exists x (largecomplex(x) and southeastof(x, baku))
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 largecomplex(shafaq-asiman) and largecomplex(shafaq-asiman) and offshore(shafaq-asiman) and geologicalstructures(shafaq-asiman) and in(shafaq-asiman, caspiansea)
northwestof(baku, shafaq-asiman)
forall x forall y (northwestof(x, y) implies southeastof(y, x))
*** Conclusion:
 forall x (geologicalstructures(x) and offshore(x) implies not northwestof(baku, x))
*** True Label:
 F
*** Predicted Label:
 None
Classification Report:               precision    recall  f1-score   support

                   0.00      0.00      0.00         0
           F       0.43      0.04      0.08        69
  F</output>       0.00      0.00      0.00         0
        None       0.00      0.00      0.00         0
           T       0.19      0.04      0.07       122
  T</output>       0.00      0.00      0.00         0
           U       0.00      0.00      0.00       110

    accuracy                           0.03       301
   macro avg       0.09      0.01      0.02       301
weighted avg       0.17      0.03      0.05       301

*************** INFERENCE COMPLETE ***************

In [ ]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.026578073089700997
***** PRECISION *****
0.08767951625094482
***** RECALL *****
0.012065981060991752
***** F1 *****
0.02086592319725488

   Accuracy  Precision    Recall        F1
0  0.026578    0.08768  0.012066  0.020866

In [ ]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

config.json: 0.00B [00:00, ?B/s]

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [ ]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CLIF')

*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 ocellatedwildturkey(tom)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 easternwildturkey(tom)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 forall x (wildturkey(x) implies (easternwildturkey(x) or osceolawildturkey(x) or gouldswildturkey(x) or merriamswildturkey(x) or riograndewildturkey(x) or ocellatedwildturkey(x)))
not (easternwildturkey(tom))
not (osceolawildturkey(tom))
not (gouldswildturkey(tom))
not (merriamswildturkey(tom) or riograndewildturkey(tom))
wildturkey(tom)
*** Conclusion:
 wildturkey(joey)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 has(mary, flu)
forall x (has(x, flu) implies has(x, influenza))
not has(susan, influenza)
*** Conclusion:
 has(mary, influenza) xor has(susan, influenza)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (in(butte, x) and in(stpierre, x))
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 exists x (city(pierre) and in(pierre, x) and city(bismarck) and in(bismarck, x))
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 city(billings) and in(billings, montana)
city(butte) and in(butte, montana) and city(helena) and in(helena, montana) and city(missoula) and in(missoula, montana)
exists x (city(whitesulphursprings) and in(whitesulphursprings, x) and city(butte) and in(butte, x))
city(pierre) and not (in(pierre, montana))
forall x ((city(x) and city(butte) and in(x, butte)) implies not (in(x, pierre)))
forall x exists y ((city(x) and (in(x, y) and not (x=bristol) and not (x=texarkana) and not (x=texhoma) and not (x=unioncity)) implies not exists z (not (z=y) and in(x, z)))
*** Conclusion:
 city(missoula) and in(missoula, montana)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newfrance))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 exists x (built(pierrederigauddevaudreuil, x) and locatedin(x, newengland))
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 renamedas(fortcarillon, fortticonderoga)
built(pierrederigauddevaudreuil, fortcarillon)
locatedin(fortcarillon, newfrance)
not locatedin(newfrance, europe)
*** Conclusion:
 locatedin(fortcarillon, europe)
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 holds(suduva, thelithuaniansupercup)
soccerteam(suduva)
*** Conclusion:
 exists x (soccerteam(x) and holds(x, thelithuaniansupercup))
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not wakesup(thehulk) implies not happy(thor)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 happy(thor) implies wears(peterparker, uniform)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 superhero(peterparker) xor civilian(peterparker)
destroyer(thehulk)
angry(thehulk) implies wakesup(thehulk)
wakesup(thehulk) implies breaks(thehulk, bridge)
god(thor)
happy(thor) implies breaks(thor, bridge)
forall x (god(x) implies not destroyer(x))
superhero(peter) implies wears(peter, uniform)
forall x ((destroyer(x) and breaks(x,bridge)) implies not civilian(peter))
happy(thor) implies angry(thehulk)
*** Conclusion:
 not happy(thor) implies not breaks(thor, bridge)
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 situatedon(longueau, pairslille)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 not in(boves, europe)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 railwaystation(boves) and in(boves, france)
precede(longueau, boves)
precede(boves, dommartin)
in(france, europe)
situatedon(dommartin, pairslille)
forall x forall y forall z ((situatedon(x, z) and (precede(x, y) or precede(y, x)) implies situatedon(y, z))
serve(boves, hautsdefrance)
forall x forall y forall z ((in(x, y) and in(y, z)) implies in(x, z))
forall x forall y forall z ((precede(x, y) and precede(y, z)) implies precede(x, z))
*** Conclusion:
 serve(longueau, hautsdefrance)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(eight, seven)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 positive(eight)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 realnum(num6) and realnum(num7) and realnum(num8)
forall x forall y ((realnum(x) and realnum(y) and issuccessorof(x, y)) implies larger(x, y))
forall x forall y (larger(x, y) implies not larger(y, x))
exists y(issuccessorof(y, num6) and equals(num7, y))
exists y(issuccessorof(y, num7) and equals(num8, y))
positive(num2)
forall x forall y ((positive(x) and isdouble(y, x)) implies positive(y))
isdouble(num8, num4)
isdouble(num4, num2)
*** Conclusion:
 larger(six, seven)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 love(miroslav, music)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 exists x exists y (czech(x) and publishedbook(x, y, year1946))
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 czech(miroslav) and choralconductor(miroslav) and specializeinperformanceof(miroslav, renaissancemusic) and specializeinperformanceof(miroslav, baroquemusic)
forall x (choralconductor(x) implies musician(x))
exists x exists y ((musician(x) implies love(x, music)) and (not (x=y) and musician(y) implies love(y, music)))
publishedbook(miroslav, methodofstudyinggregorianchant, yr1946)
*** Conclusion:
 forall x (choralconductor(x) implies not specializeinperformanceof(x, renaissancemusic))
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 likeplayingwith(cat, taigavole)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 vole(taigavole) and livein(taigavole, northamerica)
likeplayingwith(cat, taigavole)
livein(taigavole, borealtaigazone)
forall x ((livein(x, northamerica) and livein(x, borealtaigazone)) implies livein(x, coldplace))
*** Conclusion:
 not livein(taigavole, coldplace)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 workedwith(whalenturner, greenwillowbooks)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 plotstoswallowup(medeempire, attolia)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not setin(thickastheives, medeempire)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 youngadultfantasy(thickastheives) and novel(thickastheives) and writtenby(thickastheives, meganwhalenturner)
publishedby(thickastheives, greenwillowbooks)
forall x forall y forall z ((writtenby(x, y) and publishedby(x, z)) implies workedwith(y, z))
fictional(medeempire) and setin(thickastheives, medeempire)
exists x exists y ((country(x) and near(x, medeempire) and plotstoswallowup(medeempire, x)) and (not (x=y) and near(y, medeempire) and plotstoswallowup(medeempire, y)))
country(attolia) and near(attolia, medeempire) and country(sounis) and near(sounis, medeempire)
soldas(thickastheives, hardcover) and soldas(thickastheives, softcover)
*** Conclusion:
 not workedwith(megan, greenwillowbooks)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 graduatedwith(walterbrown, bachelorsofart)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(in(walterbrownfather, toledo, t))
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 americanpolitician(walterbrown) and lawyer(walterbrown) and servedas(walterbrown, postmastergeneral)
graduated(walterbrown, harvard) and graduatedwith(walterbrown, bachelorsofart)
exists t(in(walterbrown, toledo, t) and in(walterbrownfather, toledo, t) and practicedlawtogether(walterbrown, walterbrownfather, t))
married(katherinhafer, walterbrown)
*** Conclusion:
 exists t(not in(walterbrownfather, toledo, t))
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x ((water(x) and from(x, crotonriverwatershed)) implies exists y(flowsto(x, y) and in(y, newyork)))
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 in(crotonriverwatershed, bronx)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 drainagebasinof(crotonriverwatershed, crotonriver)
in(crotonriver, southwesternnewyork)
forall x ((water(x) and in(x, crotonriverwatershed)) implies flowsto(x, bronx))
in(bronx, newyork)
*** Conclusion:
 forall x (water(x) and from(x, crotonriver) implies flowsto(x, bronx))
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (form(x, system7) and formermemberof(x, gong))
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 exists x (single(x) and release(system7, x))
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 basedin(system7, uk) and electronicdancemusicband(system7)
form(stevehillage, system7) and form(miquettegiraudy, system7)
formermemberof(stevehillage, gong) and formermemberof(miquettegiraudy, gong)
forall x (electronicdancemusicband(x) implies band(x))
exists x (clubsingle(x) and release(system7, x))
forall x (clubsingle(x) implies not single(x))
*** Conclusion:
 not band(system7)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 opentopublic(usssalem)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 exists x (museumship(x) and opentopublic(x) and servedin(x, mediterranean))
*** True Label:
 T
*** Predicted Label:
 F
*** Premises:
 heavycruiser(usssalem) and builtfor(usssalem, unitedstatesnavy)
lastheavycruisertoenterservice(usssalem)
museumship(usssalem)
forall x (museumship(x) implies opentopublic(x))
servedin(usssalem, atlantic) and servedin(usssalem, mediterranean)
*** Conclusion:
 not lastheavycruisertoenterservice(usssalem)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 forall x (elephantopus(x) implies (genus(x, perennialplants) and belongto(x, daisyfamily)))

In [ ]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.23588039867109634
***** PRECISION *****
0.25078285282366913
***** RECALL *****
0.1072846374343167
***** F1 *****
0.14156317996630002

   Accuracy  Precision    Recall        F1
0   0.23588   0.250783  0.107285  0.141563

In [ ]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)