In [1]:
'''
task: classify syllogism validity with TFL+ notation
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: pfolio
evaluation: zero-shot
'''
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 115.4 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.4.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)

In [3]:
import pandas as pd

pfolio_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/p-folio/data/pfolio_kr_gold_train.csv")

In [4]:
# evaluation metrics

import numpy as np
import re
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

def predict_answer(model, tokenizer, obj, subject, ref_relation=None, source_knowledge=None):
  # define notation grammar
  grammar = r"""
    start: program
    program: [stat]+
    stat: proposition newline
    proposition: atomicproposition | complexproposition
    complexproposition: leftparen proposition rightparen | proposition plus proposition | proposition minus proposition
    atomicproposition: term
    leftparen: "("
    rightparen: ")"
    plus: "+"
    minus: "-"
    term: plus T n | minus T n
    T: LETTER
    n: NUMBER
    newline: /\n/

    %import common.LETTER
    %import common.INT -> NUMBER
    %import common.WS
    %ignore WS
"""
  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert logician. You are given a syllogism in TFL with premises between <PREMISES></PREMISES> and conclusion between <CONCLUSION></CONCLUSION> tags.
  The TFL BNF grammar to understand and reason in the language is given in the <GRAMMAR></GRAMMAR> tags.
  <GRAMMAR>{grammar}</GRAMMAR>
  <PREMISES>{subject}</PREMISES>
  <CONCLUSION>{obj}</CONCLUSION>
  Classify the conclusion as "T" if true, "F" if false or "U" if uncertain based on the premises. Present your answer only between <output></output> tags.
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  predicted_relation = tokenizer.decode(response[0])
  matches = re.findall('<output>(.*)</output>', predicted_relation, flags=re.DOTALL)
  res = re.findall(r"<output>(.*)", matches[-1])  # from ['</output> tags.\n  <end_of_turn>\n  <start_of_turn>model\n  <output>T'] to ['T']
  predicted_label = res[0] if res else "None" # take first element from list ['T'] to get 'T'

  print("*** Premises: \n", subject)
  print("*** Conclusion: \n", obj)
  print("*** True Label: \n", ref_relation)
  print("*** Predicted Label: \n", predicted_label)
  return predicted_label

In [5]:
def infer_from_ontology(dataset, model, tokenizer, mode='default', notation='NL'):
  evaluation_metrics_df = pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1"])
  reference_labels = []
  predicted_labels = []
  for index, row in dataset.iterrows():
      conclusion = row["Conclusions - " + notation]
      premises = row["Premises - " + notation]
      label = row["Truth Values"]
      if mode.lower() == "grammar":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        source_information = """BNF GRAMMAR"""
        print("*** RAG INFORMATION:", source_information)
      # predict answer with model
      predicted_label = predict_answer(model, tokenizer, conclusion, premises, label)
      reference_labels.append(label)
      predicted_labels.append(predicted_label)
  # fill evaluation metrics dataframe
  accuracy_metric = accuracy_score(reference_labels, predicted_labels)
  precision_metric = precision_score(reference_labels, predicted_labels, average="macro")
  recall_metric = recall_score(reference_labels, predicted_labels, average="macro")
  f1_metric = f1_score(reference_labels, predicted_labels, average="macro")
  evaluation_metrics_df["Accuracy"] = [accuracy_metric]
  evaluation_metrics_df["Precision"] = [precision_metric]
  evaluation_metrics_df["Recall"] = [recall_metric]
  evaluation_metrics_df["F1"] = [f1_metric]
  print("Classification Report:", classification_report(reference_labels, predicted_labels))
  print("*************** INFERENCE COMPLETE ***************")
  return reference_labels, predicted_labels, evaluation_metrics_df, accuracy_metric, precision_metric, recall_metric, f1_metric

In [6]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [7]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [10]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='TFLPLUS')

*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +O2(+t2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +W2(+j2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +H2-(+H0-+H0)-+H2
*** Conclusion:
 +H2-+H2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+I1++I1)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+C1(+p1)++I1++C1(+b1)++I1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +C2(+m2)++I2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +H2+S2(+s2)
*** Conclusion:
 +(+S1++H1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+W2(+t2)--+H2(+t2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 +H2(+t2)-+W2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+H2(+t2)--+B2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 -+I2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +P2(+e2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 ++(+C1++P1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 -(+C0--+S0)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 -+L2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +W2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+S2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+W2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +G2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(+I1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(-+I1)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -((+W0++F0)-+(+F1++I1))
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -(+W0++F0-+F0)
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+F1++F1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+S1++R1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 -+B2(+s2)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +O2(+u2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +(+M1++O1++S1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 -+L2(+u2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 ++(+E1++I1++E1++I1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0--+N0)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0-+T0)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)++P2(+d2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2(+j2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +E2(+a2)++T2(+a2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2++N2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+T1++H1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +F2(+m2)++M2(+m2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+C1++M1++K1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2++P2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +(+E1++P1++S1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +T2(+t2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +(+C1++J1++V1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 -+T2(+t2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +H2(+b2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +M2(+g2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+E2(+j2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 +C2(+j2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+W2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +A2(+t2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +R2(+f2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +(+G1++A1)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +B2(+m2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +P2(+e2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+p2)+(-+H2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +R2(+p2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+h2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +(+D1++D1++C1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +A2(+j2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +M2(+j2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +R2(+j2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +V2(+g2)++I2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +C2(+g2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(-(+D0++F0))
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(+D0--(+F0))
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+P1++P1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+W1++P1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +W2(+h2)++F2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +(+G1++L1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +A2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +N2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +P2(+j2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +I2(+j2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 -+B2
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +I2(+r2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +G2(+r2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +O2(+c2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +H2(+c2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +W2(+c2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+t2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+h2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 -+H2(+c2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+l2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1++I1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +P2(+y2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 -(+P0--+P0)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +S2(+w2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 +O2(+h2)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 -+O2(+k2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 -+K2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 +K2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 -(+L0--+S0)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +(+E1++F1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +S2(+j2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 ++(+R1++L1++S1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 -+M2(+d2)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 +B2(+d2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 -(+B0--+P0)
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 -+I2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 +I2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+B0-(+A0++D0))++(+H1++B1++A1++R1)-(+H0-+A0)-(+A0-+A0)++(+A1++A1+(-(+x1))++B1++B1+(+(+D1++R1)+(-(+w1))+(+(+D1++R1)))
*** Conclusion:

In [11]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.44518272425249167
***** PRECISION *****
0.38326135322601756
***** RECALL *****
0.39340302526332466
***** F1 *****
0.2987938129700582

   Accuracy  Precision    Recall        F1
0  0.445183   0.383261  0.393403  0.298794

In [13]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [14]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='TFLPLUS')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +O2(+t2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +W2(+j2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +H2-(+H0-+H0)-+H2
*** Conclusion:
 +H2-+H2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+I1++I1)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+C1(+p1)++I1++C1(+b1)++I1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +C2(+m2)++I2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +H2+S2(+s2)
*** Conclusion:
 +(+S1++H1)
*** True Label:
 T
*** Predicted Label:
 T</output>");

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+W2(+t2)--+H2(+t2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 +H2(+t2)-+W2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+H2(+t2)--+B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 -+I2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +P2(+e2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 ++(+C1++P1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 -(+C0--+S0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 -+L2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +W2
*** True Label:
 T
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+S2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+W2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +G2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(+I1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(-+I1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -((+W0++F0)-+(+F1++I1))
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -(+W0++F0-+F0)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+F1++F1)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+S1++R1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 -+B2(+s2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +O2(+u2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +(+M1++O1++S1)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 -+L2(+u2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 ++(+E1++I1++E1++I1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0--+N0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0-+T0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)++P2(+d2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2(+j2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +E2(+a2)++T2(+a2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2++N2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+T1++H1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +F2(+m2)++M2(+m2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+C1++M1++K1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2++P2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +(+E1++P1++S1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +T2(+t2)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +(+C1++J1++V1)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 -+T2(+t2)
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +H2(+b2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +M2(+g2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+E2(+j2)
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 +C2(+j2)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+W2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +A2(+t2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +R2(+f2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +(+G1++A1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +B2(+m2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +P2(+e2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+p2)+(-+H2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +R2(+p2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+h2)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +(+D1++D1++C1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +A2(+j2)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +M2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +R2(+j2)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +V2(+g2)++I2
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +C2(+g2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(-(+D0++F0))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(+D0--(+F0))
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+P1++P1)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+W1++P1)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +W2(+h2)++F2
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +(+G1++L1)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +A2
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +N2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +P2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +I2(+j2)
*** True Label:
 U
*** Predicted Label:
 T</output>')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 -+B2
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +I2(+r2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +G2(+r2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +O2(+c2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +H2(+c2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +W2(+c2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+t2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+h2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 -+H2(+c2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+l2)
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1++I1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +P2(+y2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 -(+P0--+P0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +S2(+w2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 +O2(+h2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 -+O2(+k2)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 -+K2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 +K2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 -(+L0--+S0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +(+E1++F1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +S2(+j2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 ++(+R1++L1++S1)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 -+M2(+d2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 +B2(+d2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 -(+B0--+P0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 -+I2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2+I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 +I2
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-(+A0++D0))++(+H1++B1++A1++R1)-(+H0-+A0)-(+A0-+A0)++(+A1++A1+(-(+x1))++B1++B1+(+(+D1++R1)+(-(+w1))+(+(+D1++R1)))
*** Conclusion:
 ++(+H1++A1+(-(+x1))++H1++A1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-(+A0++D0))++(+H1++B1++A1++R1)-(+H0-+A0)-(+A0-+A0)++(+A1++A1+(-(+x1))++B1++B1+(+(+D1++R1)+(-(+w1))+(+(+D1++R1)))
*** Conclusion:
 -(+A0-+D0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+C0-+D0)++(+C1++C1+(-(+x1))++B1++H1)--((+C0++C0++E0)-+I0)-(+I0-+H0)+P2++A2(+c2)++(+A1++P1+(-(+x1))++A1++P1)
*** Conclusion:
 +P2(+c2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+C0-+D0)++(+C1++C1+(-(+x1))++B1++H1)--((+C0++C0++E0)-+I0)-(+I0-+H0)+P2++A2(+c2)++(+A1++P1+(-(+x1))++A1++P1)
*** Conclusion:
 ++(+D1++B1+(-(+x1))++D1++B1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+C0-+D0)++(+C1++C1+(-(+x1))++B1++H1)--((+C0++C0++E0)-+I0)-(+I0-+H0)+P2++A2(+c2)++(+A1++P1+(-(+x1))++A1++P1)
*** Conclusion:
 -((+C0++I0)-+H0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++A2++B2(+t2)+A2++A2-(+A0-+W0)-(+W0-+C0)++(+C1++A1+(-(+x1))+(+C1++A1))
*** Conclusion:
 +W2(+d2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++A2++B2(+t2)+A2++A2-(+A0-+W0)-(+W0-+C0)++(+C1++A1+(-(+x1))+(+C1++A1))
*** Conclusion:
 +C2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++A2++B2(+t2)+A2++A2-(+A0-+W0)-(+W0-+C0)++(+C1++A1+(-(+x1))+(+C1++A1))
*** Conclusion:
 -+C2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+q2)++P2(+q2)++W2(+q2)++P2-((+(+C1++B1))-+G1)++(+F1++C1)+(-(+x1)+(+F1++C1)-(+G0-+P0)-(+G0-(+C0++C0))-(+F0-+B0)
*** Conclusion:
 +G2(+q2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+q2)++P2(+q2)++W2(+q2)++P2-((+(+C1++B1))-+G1)++(+F1++C1)+(-(+x1)+(+F1++C1)-(+G0-+P0)-(+G0-(+C0++C0))-(+F0-+B0)
*** Conclusion:
 -(+B0-+C0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+q2)++P2(+q2)++W2(+q2)++P2-((+(+C1++B1))-+G1)++(+F1++C1)+(-(+x1)+(+F1++C1)-(+G0-+P0)-(+G0-(+C0++C0))-(+F0-+B0)
*** Conclusion:
 -((+P0++W0)-+G0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+T0-(+(+R1))-(+R0-(+P0++B0))++(+R1++C1)+(-(+x1)++R1++C1)++(+R1++S1)+(-(+x1)++R1++S1)--((+C0++S0)-+S0)
*** Conclusion:
 -(-+R0--+P0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+T0-(+(+R1))-(+R0-(+P0++B0))++(+R1++C1)+(-(+x1)++R1++C1)++(+R1++S1)+(-(+x1)++R1++S1)--((+C0++S0)-+S0)
*** Conclusion:
 --((+R0++C0++R0++S0)-+S0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+T0-(+(+R1))-(+R0-(+P0++B0))++(+R1++C1)+(-(+x1)++R1++C1)++(+R1++S1)+(-(+x1)++R1++S1)--((+C0++S0)-+S0)
*** Conclusion:
 -((+R0++C0)-(-+B0))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+o2)+L2(+t2)+M2
*** Conclusion:
 +S2(+c2)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+o2)+L2(+t2)+M2
*** Conclusion:
 -+L2(+t2)
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+o2)+L2(+t2)+M2
*** Conclusion:
 +(+L1++M1)
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2+P2++V2(+a2)-(+V0++P0++I0-(+C0-+V0))
*** Conclusion:
 +V2(+l2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2+P2++V2(+a2)-(+V0++P0++I0-(+C0-+V0))
*** Conclusion:
 +C2(+l2)-+V2(+l2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2+P2++V2(+a2)-(+V0++P0++I0-(+C0-+V0))
*** Conclusion:
 +V2(+a2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2+P2++V2(+a2)-(+V0++P0++I0-(+C0-+V0))
*** Conclusion:
 +C2(+a2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+N0)+++(+P1++P1++D1)-(+A0-+N0)+++(+A1++A1++D1)-(+P0--+A0)-(+P0-+S0)+P2(+j2)+S2(+a2)
*** Conclusion:
 +P2(+a2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+N0)+++(+P1++P1++D1)-(+A0-+N0)+++(+A1++A1++D1)-(+P0--+A0)-(+P0-+S0)+P2(+j2)+S2(+a2)
*** Conclusion:
 +A2(+a2)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+N0)+++(+P1++P1++D1)-(+A0-+N0)+++(+A1++A1++D1)-(+P0--+A0)-(+P0-+S0)+P2(+j2)+S2(+a2)
*** Conclusion:
 +A2(+j2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+N0)+++(+P1++P1++D1)-(+A0-+N0)+++(+A1++A1++D1)-(+P0--+A0)-(+P0-+S0)+P2(+j2)+S2(+a2)
*** Conclusion:
 +S2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+R0-(+R0++A0))--((+R0++A0)--+H0)-(+A0-+D0)--((+R0++A0)-+O0)-(+B0-+A0)
*** Conclusion:
 -(+B0-+D0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+R0-(+R0++A0))--((+R0++A0)--+H0)-(+A0-+D0)--((+R0++A0)-+O0)-(+B0-+A0)
*** Conclusion:
 --((+R0++B0)-+O0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+R0-(+R0++A0))--((+R0++A0)--+H0)-(+A0-+D0)--((+R0++A0)-+O0)-(+B0-+A0)
*** Conclusion:
 --((+B0++A0)-+H0)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+R0-(+R0++A0))--((+R0++A0)--+H0)-(+A0-+D0)--((+R0++A0)-+O0)-(+B0-+A0)
*** Conclusion:
 -(+R0-+D0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+(+C1++O1))--(+O0-+M0)-(+B0-(+B0-+B0))+(+B1++E1)-(+B0-+H0)+B2(+b2)++O2
*** Conclusion:
 +E2(+b2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+(+C1++O1))--(+O0-+M0)-(+B0-(+B0-+B0))+(+B1++E1)-(+B0-+H0)+B2(+b2)++O2
*** Conclusion:
 +H2(+b2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+(+C1++O1))--(+O0-+M0)-(+B0-(+B0-+B0))+(+B1++E1)-(+B0-+H0)+B2(+b2)++O2
*** Conclusion:
 +B2(+b2)++M2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+L0-+H0)-(+L0-(+K0-+Q0))-(+Q0-+F0)-(+K0-+M0)+Q2(+e2)+L2(+e2)
*** Conclusion:
 +K2(+e2)
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+L0-+H0)-(+L0-(+K0-+Q0))-(+Q0-+F0)-(+K0-+M0)+Q2(+e2)+L2(+e2)
*** Conclusion:
 +H2(+e2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+L0-+H0)-(+L0-(+K0-+Q0))-(+Q0-+F0)-(+K0-+M0)+Q2(+e2)+L2(+e2)
*** Conclusion:
 +L2(+e2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+A0)-(+P0-(+D0-+C0))--((+P0++O0)-+C0)++(+C1++N1+(-(+x1))++D1++N1)--((+P0++N0++O0)--+L0)+O2++P2(+l2)++D2(+l2)++N2(+l2)
*** Conclusion:
 +A2(+l2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+A0)-(+P0-(+D0-+C0))--((+P0++O0)-+C0)++(+C1++N1+(-(+x1))++D1++N1)--((+P0++N0++O0)--+L0)+O2++P2(+l2)++D2(+l2)++N2(+l2)
*** Conclusion:
 -+L2+-+C2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0-+A0)-(+P0-(+D0-+C0))--((+P0++O0)-+C0)++(+C1++N1+(-(+x1))++D1++N1)--((+P0++N0++O0)--+L0)+O2++P2(+l2)++D2(+l2)++N2(+l2)
*** Conclusion:
 -(+D0--+N0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+C0)--(+R0-+G0)-(+G0-+S0)+R2++B2(+w2)
*** Conclusion:
 +G2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+C0)--(+R0-+G0)-(+G0-+S0)+R2++B2(+w2)
*** Conclusion:
 +S2(+h2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+B0-+C0)--(+R0-+G0)-(+G0-+S0)+R2++B2(+w2)
*** Conclusion:
 -(+S0-+G0)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+L1++A1+(-(+x1))++L1++A1)-(+L0-+D0)-(+D0-+A0)-(+A0--+T0)+L2(+l2)
*** Conclusion:
 +A2(+l2)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+L1++A1+(-(+x1))++L1++A1)-(+L0-+D0)-(+D0-+A0)-(+A0--+T0)+L2(+l2)
*** Conclusion:
 -+T2(+l2)
*** True Label:
 T
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ++(+L1++A1+(-(+x1))++L1++A1)-(+L0-+D0)-(+D0-+A0)-(+A0--+T0)+L2(+l2)
*** Conclusion:
 -+A2(+l2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+I0--+H0)-(+Y0-+I0)-(+I0-+H0)-(+B0-+I0)-(+B0-+B0)+Y2(+t2)+B2(+t2)
*** Conclusion:
 -+H2(+t2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+I0--+H0)-(+Y0-+I0)-(+I0-+H0)-(+B0-+I0)-(+B0-+B0)+Y2(+t2)+B2(+t2)
*** Conclusion:
 -+I2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+I0--+H0)-(+Y0-+I0)-(+I0-+H0)-(+B0-+I0)-(+B0-+B0)+Y2(+t2)+B2(+t2)
*** Conclusion:
 -+I2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+C0++S0)--+F0)-((+C0++F0)-+F0)-((+C0++H0)-+F0)+C2(+c2)+-+F2(+c2)+E2(+j2)++C2(+j2)-((+E0++C0)-+H0)
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+C0++S0)--+F0)-((+C0++F0)-+F0)-((+C0++H0)-+F0)+C2(+c2)+-+F2(+c2)+E2(+j2)++C2(+j2)-((+E0++C0)-+H0)
*** Conclusion:
 +F2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+C0++S0)--+F0)-((+C0++F0)-+F0)-((+C0++H0)-+F0)+C2(+c2)+-+F2(+c2)+E2(+j2)++C2(+j2)-((+E0++C0)-+H0)
*** Conclusion:
 +F2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+O0-+C0)-(+O0-+C0)-(+C0-+C0)-(+C0-+E0)+O2
*** Conclusion:
 +E2(+m2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+O0-+C0)-(+O0-+C0)-(+C0-+C0)-(+C0-+E0)+O2
*** Conclusion:
 +C2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+O0-+C0)-(+O0-+C0)-(+C0-+C0)-(+C0-+E0)+O2
*** Conclusion:
 +C2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+A0-+R0)-(+A0-(+A0-+A0))-((+A0++F0)--+A0)+A2(+j2)+(-+A2(+j2))+F2(+j2)++A2(+j2)
*** Conclusion:
 +A2(+j2)+(-+A2(+j2))
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+A0-+R0)-(+A0-(+A0-+A0))-((+A0++F0)--+A0)+A2(+j2)+(-+A2(+j2))+F2(+j2)++A2(+j2)
*** Conclusion:
 +A2(+j2)++A2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+A0-+R0)-(+A0-(+A0-+A0))-((+A0++F0)--+A0)+A2(+j2)+(-+A2(+j2))+F2(+j2)++A2(+j2)
*** Conclusion:
 +R2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0--+N0)-((+(+B1++C1++L1)-+A1)--((+N0++W0)-+W0)+A2(+d2)++W2(+d2)+W2+N2(+f2)++W2+P2(+f2)++C2+C2(+b2)++A2(+b2)
*** Conclusion:
 +W2(+d2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0--+N0)-((+(+B1++C1++L1)-+A1)--((+N0++W0)-+W0)+A2(+d2)++W2(+d2)+W2+N2(+f2)++W2+P2(+f2)++C2+C2(+b2)++A2(+b2)
*** Conclusion:
 +I2(+f2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+P0--+N0)-((+(+B1++C1++L1)-+A1)--((+N0++W0)-+W0)+A2(+d2)++W2(+d2)+W2+N2(+f2)++W2+P2(+f2)++C2+C2(+b2)++A2(+b2)
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+C0++F0)-+F0)----((+P0++I0)-+P0)+F2(+m2)+C2+R2+I2+P2
*** Conclusion:
 +F2(+d2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+C0++F0)-+F0)----((+P0++I0)-+P0)+F2(+m2)+C2+R2+I2+P2
*** Conclusion:
 -+P2(+j2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+C0++F0)-+F0)----((+P0++I0)-+P0)+F2(+m2)+C2+R2+I2+P2
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+S0++I0)-+S0)--((+I0++I0)-+I0)---((+I0++S0++S0)-+S0)+S2+I2+I2+I2+I2-+I2+(-+I2)+(-+I2)+S2
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+S0++I0)-+S0)--((+I0++I0)-+I0)---((+I0++S0++S0)-+S0)+S2+I2+I2+I2+I2-+I2+(-+I2)+(-+I2)+S2
*** Conclusion:
 -+S2
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 --((+S0++I0)-+S0)--((+I0++I0)-+I0)---((+I0++S0++S0)-+S0)+S2+I2+I2+I2+I2-+I2+(-+I2)+(-+I2)+S2
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ---(+A0++R0-+G0)---(+A0++A0-+R0)+A2+R2+S2+A2+(+S1++S1)
*** Conclusion:
 +G2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ---(+A0++R0-+G0)---(+A0++A0-+R0)+A2+R2+S2+A2+(+S1++S1)
*** Conclusion:
 -+(+R1++A1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 ---(+A0++R0-+G0)---(+A0++A0-+R0)+A2+R2+S2+A2+(+S1++S1)
*** Conclusion:
 +S2(+b2)
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2--(+D0-+F0)+D2(+a2)-(+D0-+F0)+F2+I2---((+F0++I0)-+F0)+N2
*** Conclusion:
 +F2++F2(+l2)
*** True Label:
 T
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2--(+D0-+F0)+D2(+a2)-(+D0-+F0)+F2+I2---((+F0++I0)-+F0)+N2
*** Conclusion:
 -+(+F1++F1++D1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2++D2++D2--(+D0-+F0)+D2(+a2)-(+D0-+F0)+F2+I2---((+F0++I0)-+F0)+N2
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++F2(+b2)+R2(+b2)++R2+R2(+b2)+(+F1++R1)+S2++F2(+a2)++P2
*** Conclusion:
 ++(+S1++R1++F1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++F2(+b2)+R2(+b2)++R2+R2(+b2)+(+F1++R1)+S2++F2(+a2)++P2
*** Conclusion:
 -+R2(+b2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++F2(+b2)+R2(+b2)++R2+R2(+b2)+(+F1++R1)+S2++F2(+a2)++P2
*** Conclusion:
 +R2(+b2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++F2(+b2)+R2(+b2)++R2+R2(+b2)+(+F1++R1)+S2++F2(+a2)++P2
*** Conclusion:
 +R2(+a2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+m2)++P2(+m2)++J2(+m2)++A2(+m2)++B2(+m2)+W2(+m2)+M2(+w2)++E2+B2++(+S1++G1)
*** Conclusion:
 ++(+S1++G1++W1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+m2)++P2(+m2)++J2(+m2)++A2(+m2)++B2(+m2)+W2(+m2)+M2(+w2)++E2+B2++(+S1++G1)
*** Conclusion:
 -+M2(+w2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+m2)++P2(+m2)++J2(+m2)++A2(+m2)++B2(+m2)+W2(+m2)+M2(+w2)++E2+B2++(+S1++G1)
*** Conclusion:
 -(+B0--+A0)
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+m2)++P2(+m2)++J2(+m2)++A2(+m2)++B2(+m2)+W2(+m2)+M2(+w2)++E2+B2++(+S1++G1)
*** Conclusion:
 -(+J0--+B0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2(+m2)++P2(+m2)++J2(+m2)++A2(+m2)++B2(+m2)+W2(+m2)+M2(+w2)++E2+B2++(+S1++G1)
*** Conclusion:
 ++(+S1++G1+-+A1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+h2)++P2(+h2)++D2(+h2)++S2(+h2)++G2(+h2)+B2++C2(+s2)+C2++C2(+m2)+T2+R2++(+T1++F1++F1+(-(+x1))++T1++F1++F1)
*** Conclusion:
 +T2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+h2)++P2(+h2)++D2(+h2)++S2(+h2)++G2(+h2)+B2++C2(+s2)+C2++C2(+m2)+T2+R2++(+T1++F1++F1+(-(+x1))++T1++F1++F1)
*** Conclusion:
 +T2
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+h2)++P2(+h2)++D2(+h2)++S2(+h2)++G2(+h2)+B2++C2(+s2)+C2++C2(+m2)+T2+R2++(+T1++F1++F1+(-(+x1))++T1++F1++F1)
*** Conclusion:
 +(+B1++C1)
*** True Label:
 U
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+h2)++P2(+h2)++D2(+h2)++S2(+h2)++G2(+h2)+B2++C2(+s2)+C2++C2(+m2)+T2+R2++(+T1++F1++F1+(-(+x1))++T1++F1++F1)
*** Conclusion:
 -+R2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +G2(+h2)++P2(+h2)++D2(+h2)++S2(+h2)++G2(+h2)+B2++C2(+s2)+C2++C2(+m2)+T2+R2++(+T1++F1++F1+(-(+x1))++T1++F1++F1)
*** Conclusion:
 ++(+B1++C1++C1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+S0)-(+E0-+G0++C0++O0++C0++B0)++(+E1++A1++P1)-(+A0-+S0)
*** Conclusion:
 -(+E0-+C0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+S0)-(+E0-+G0++C0++O0++C0++B0)++(+E1++A1++P1)-(+A0-+S0)
*** Conclusion:
 +(+G1++S1)
*** True Label:
 U
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+E0-+S0)-(+E0-+G0++C0++O0++C0++B0)++(+E1++A1++P1)-(+A0-+S0)
*** Conclusion:
 --(+E0++P0--+S0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+a2)++B2(+a2)-(+K0-+I0)+L2+D2
*** Conclusion:
 +(+D1++B1)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+a2)++B2(+a2)-(+K0-+I0)+L2+D2
*** Conclusion:
 +(+K1+-+L1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+a2)++B2(+a2)-(+K0-+I0)+L2+D2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+a2)++B2(+a2)-(+K0-+I0)+L2+D2
*** Conclusion:
 -(+S0-+L0)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+c2)++F2(+c2)+E2+O2+O2(+c2)
*** Conclusion:
 +(+O1++T1++F1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+c2)++F2(+c2)+E2+O2+O2(+c2)
*** Conclusion:
 +(+T1++F1++O1)
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+c2)++F2(+c2)+E2+O2+O2(+c2)
*** Conclusion:
 +E2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++P2(+r2)+E2(+r2)+B2-(+E0-+W0)
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++P2(+r2)+E2(+r2)+B2-(+E0-+W0)
*** Conclusion:
 -+W2(+r2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++P2(+r2)+E2(+r2)+B2-(+E0-+W0)
*** Conclusion:
 +B2(+r2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+L2+C2(+a2)++(+C1++G1+(-(+x1))++C1++G1)-((+B0++L0)-+N0)-(+L0-+L0)
*** Conclusion:
 +N2(+a2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+L2+C2(+a2)++(+C1++G1+(-(+x1))++C1++G1)-((+B0++L0)-+N0)-(+L0-+L0)
*** Conclusion:
 +G2(+a2)
*** True Label:
 U
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2+L2+C2(+a2)++(+C1++G1+(-(+x1))++C1++G1)-((+B0++L0)-+N0)-(+L0-+L0)
*** Conclusion:
 -+L2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2++M2-((+M0-+M0-+M0)-+E0)+P2-((+(+P1))-+S1)
*** Conclusion:
 +E2(+j2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2++M2-((+M0-+M0-+M0)-+E0)+P2-((+(+P1))-+S1)
*** Conclusion:
 -+S2(+j2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2++M2-((+M0-+M0-+M0)-+E0)+P2-((+(+P1))-+S1)
*** Conclusion:
 +G2(+j2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +O2+O2-+S2---(+O0++O0+(-+S0)-+M0)+M2(+a2)
*** Conclusion:
 +M2(+a2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +O2+O2-+S2---(+O0++O0+(-+S0)-+M0)+M2(+a2)
*** Conclusion:
 +M2(+a2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +O2+O2-+S2---(+O0++O0+(-+S0)-+M0)+M2(+a2)
*** Conclusion:
 -+O2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+r2)-(+S0-+S0)+L2--(+L0--+P0)
*** Conclusion:
 +S2(+r2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+r2)-(+S0-+S0)+L2--(+L0--+P0)
*** Conclusion:
 +P2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+r2)-(+S0-+S0)+L2--(+L0--+P0)
*** Conclusion:
 +S2(+r2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+n2)++S2-((+B0++P0)-+I0)+B2(+n2)++P2+T2+B2(+p2)++P2
*** Conclusion:
 +B2(+n2)++I2
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+n2)++S2-((+B0++P0)-+I0)+B2(+n2)++P2+T2+B2(+p2)++P2
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+n2)++S2-((+B0++P0)-+I0)+B2(+n2)++P2+T2+B2(+p2)++P2
*** Conclusion:
 +T2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-(+S0-+C0-+F0-+A0))+C2(+f2)+(+S1++O1)
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-(+S0-+C0-+F0-+A0))+C2(+f2)+(+S1++O1)
*** Conclusion:
 +O2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+S0-(+S0-+C0-+F0-+A0))+C2(+f2)+(+S1++O1)
*** Conclusion:
 +(+O1++S1-+C1-+F1-+A1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +N2-(+R0-+U0)+R2+U2
*** Conclusion:
 +U2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +N2-(+R0-+U0)+R2+U2
*** Conclusion:
 -+U2
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +N2-(+R0-+U0)+R2+U2
*** Conclusion:
 +R2
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +N2-(+R0-+U0)+R2+U2
*** Conclusion:
 +R2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+V0-+B0)-(-+B0--+F0)+(+O1++V1)+(+O1++B1)-(+B0--+B0)
*** Conclusion:
 +(+O1++B1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -(+V0-+B0)-(-+B0--+F0)+(+O1++V1)+(+O1++B1)-(+B0--+B0)
*** Conclusion:
 +(+O1++V1)
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+l2)++I2+(+E1++S1++S1++S1)+(+E1++S1++S1++S1++D1)
*** Conclusion:
 +I2(+l2)++I2
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+l2)++I2+(+E1++S1++S1++S1)+(+E1++S1++S1++S1++D1)
*** Conclusion:
 --((+E0++S0++I0)--+D0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +I2(+l2)++I2+(+E1++S1++S1++S1)+(+E1++S1++S1++S1++D1)
*** Conclusion:
 ++(+E1++S1++S1++S1++I1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+d2)++D2+T2+P2-(+I2)
*** Conclusion:
 -(+P2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+d2)++D2+T2+P2-(+I2)
*** Conclusion:
 +T2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +M2(+d2)++D2+T2+P2-(+I2)
*** Conclusion:
 +T2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+L0++S0)-+S0)+L2(+t2)+S2(+t2)++S2
*** Conclusion:
 +S2(+t2)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+L0++S0)-+S0)+L2(+t2)+S2(+t2)++S2
*** Conclusion:
 -+S2(+t2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 -((+L0++S0)-+S0)+L2(+t2)+S2(+t2)++S2
*** Conclusion:
 +P2(+t2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++F2(+d2)++(+P1+(-(+x1))++P1)++O1(+h1)++M1(+h1)++(+A1++P1++W1)+(+A1++P1++W1)+P2-((+M0++O0)--+F0)
*** Conclusion:
 +F2(+h2)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++F2(+d2)++(+P1+(-(+x1))++P1)++O1(+h1)++M1(+h1)++(+A1++P1++W1)+(+A1++P1++W1)+P2-((+M0++O0)--+F0)
*** Conclusion:
 +W2
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+d2)++F2(+d2)++(+P1+(-(+x1))++P1)++O1(+h1)++M1(+h1)++(+A1++P1++W1)+(+A1++P1++W1)+P2-((+M0++O0)--+F0)
*** Conclusion:
 ++(+W1+(-(+x1))++W1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+b2)++L2(+b2)+B2+M2-(+B0-+A0)
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+b2)++L2(+b2)+B2+M2-(+B0-+A0)
*** Conclusion:
 +A2(+b2)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+b2)++L2(+b2)+B2+M2-(+B0-+A0)
*** Conclusion:
 +D2(+b2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++S2(+b2)+F2++C2(+b2)-(+C0-+A0)+N2+M2+B2
*** Conclusion:
 +A2(+b2)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++S2(+b2)+F2++C2(+b2)-(+C0-+A0)+N2+M2+B2
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +S2(+b2)++S2(+b2)+F2++C2(+b2)-(+C0-+A0)+N2+M2+B2
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +J2(+k2)++V2(+k2)++A2(+k2)++H2-(+H0-+(+C1++H1))+D2++S2(+k2)++R2(+k2)-(+V0-+H0)
*** Conclusion:
 +(+C1++H1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +J2(+k2)++V2(+k2)++A2(+k2)++H2-(+H0-+(+C1++H1))+D2++S2(+k2)++R2(+k2)-(+V0-+H0)
*** Conclusion:
 +(+C1++H1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +J2(+k2)++V2(+k2)++A2(+k2)++H2-(+H0-+(+C1++H1))+D2++S2(+k2)++R2(+k2)-(+V0-+H0)
*** Conclusion:
 +A2(+k2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+v2)++R2(+v2)+C2++C2+C2(+s2)++H2+R2
*** Conclusion:
 -(+R0--+H0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+v2)++R2(+v2)+C2++C2+C2(+s2)++H2+R2
*** Conclusion:
 -(+A0--+R0)
*** True Label:
 F
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+v2)++R2(+v2)+C2++C2+C2(+s2)++H2+R2
*** Conclusion:
 +(+A1++C1++R1)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2(+a2)++C2(+a2)+P2+P2+A2(+t2)
*** Conclusion:
 +(+D1++P1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2(+a2)++C2(+a2)+P2+P2+A2(+t2)
*** Conclusion:
 +(+A1++P1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2(+a2)++C2(+a2)+P2+P2+A2(+t2)
*** Conclusion:
 +(+C1++P1)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +D2(+a2)++C2(+a2)+P2+P2+A2(+t2)
*** Conclusion:
 +(+A1++P1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+r2)++P2++C2(+s2)+R2(+r2)++B2(+r2)++M2(+r2)+O2(+r2)+D2
*** Conclusion:
 --((+C0++P0)--+D0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +C2(+r2)++P2++C2(+s2)+R2(+r2)++B2(+r2)++M2(+r2)+O2(+r2)+D2
*** Conclusion:
 -((+R0++M0)--+P0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+a2)++C2(+a2)++I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 +(+V1++I1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +V2(+a2)++C2(+a2)++I2+I2+I2---((+I0++I0)-+I0)
*** Conclusion:
 -(+(+C1++I1))
*** True Label:
 F
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+d2)++P2(+d2)+C2++W2+P2+B2(+m2)++B2(+j2)
*** Conclusion:
 +(+B1++C1)
*** True Label:
 T
*** Predicted Label:
 </output> tags.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +T2(+d2)++P2(+d2)+C2++W2+P2+B2(+m2)++B2(+j2)
*** Conclusion:
 ++(+B1++T1++P1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+d2)++I2+L2+I2++I2+F2
*** Conclusion:
 +(+L1++P1)
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+d2)++I2+L2+I2++I2+F2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +P2(+d2)++I2+L2+I2++I2+F2
*** Conclusion:
 -((+P0++I0)--+F0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++A2(+d2)++P2(+d2)++P2(+d2)+P2(+p2)++B2+P2(+h2)++W2++P2(+p2)++W2++P2(+t2)++W2+C2
*** Conclusion:
 +(+C1++W1)
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++A2(+d2)++P2(+d2)++P2(+d2)+P2(+p2)++B2+P2(+h2)++W2++P2(+p2)++W2++P2(+t2)++W2+C2
*** Conclusion:
 -(+P0++W0--+B0)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +B2++A2(+d2)++P2(+d2)++P2(+d2)+P2(+p2)++B2+P2(+h2)++W2++P2(+p2)++W2++P2(+t2)++W2+C2
*** Conclusion:
 +P2(+g2)
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+m2)++S2(+m2)++P2(+m2)+S2++E2++L2(+m2)+F2(+w2)++S2(+w2)+P2++D2+S2(+e2)++A2
*** Conclusion:
 ++(+S1++A1++D1++S1)
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+m2)++S2(+m2)++P2(+m2)+S2++E2++L2(+m2)+F2(+w2)++S2(+w2)+P2++D2+S2(+e2)++A2
*** Conclusion:
 -(+S0++A0++(+S1)--+D1)
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +A2(+m2)++S2(+m2)++P2(+m2)+S2++E2++L2(+m2)+F2(+w2)++S2(+w2)+P2++D2+S2(+e2)++A2
*** Conclusion:
 +D2
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +L2(+s2)++L2(+s2)++O2(+s2)++G2(+s2)++I2+N2--(+N0-+S0)
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 +L2(+s2)++L2(+s2)++O2(+s2)++G2(+s2)++I2+N2--(+N0-+S0)
*** Conclusion:
 +(+L1++S1)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +L2(+s2)++L2(+s2)++O2(+s2)++G2(+s2)++I2+N2--(+N0-+S0)
*** Conclusion:
 -(+G0++O0--+N0)
*** True Label:
 F
*** Predicted Label:

Classification Report:                  precision    recall  f1-score   support

                      0.00      0.00      0.00         0
</output> tags.       0.00      0.00      0.00         0
              F       0.00      0.00      0.00        69
     F</output>       0.00      0.00      0.00         0
           None       0.00      0.00      0.00         0
              T       0.52      0.11      0.18       122
     T</output>       0.00      0.00      0.00         0
    T</output>        0.00      0.00      0.00         0
  T</output>");       0.00      0.00      0.00         0
   T</output>')       0.00      0.00      0.00         0
              U       0.00      0.00      0.00       110

       accuracy                           0.04       301
      macro avg       0.05      0.01      0.02       301
   weighted avg       0.21      0.04      0.07       301

*************** INFERENCE COMPLETE ***************

In [15]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.04318936877076412
***** PRECISION *****
0.04727272727272727
***** RECALL *****
0.009687034277198211
***** F1 *****
0.016079158936301793

   Accuracy  Precision    Recall        F1
0  0.043189   0.047273  0.009687  0.016079

In [17]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

config.json: 0.00B [00:00, ?B/s]

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [18]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='TFLPLUS')

*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +O2(+t2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 -(+W0-(+E0-+O0-+G0-+M0-+R0-+O0))-(+E0(+t0))-(+O0(+t0))-(+G0(+t0))-(+M0(+t0)-+R0(+t0))+W2(+t2)
*** Conclusion:
 +W2(+j2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +H2-(+H0-+H0)-+H2
*** Conclusion:
 +H2-+H2
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+I1++I1)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +(+C1(+p1)++I1++C1(+b1)++I1)
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 +C2(+b2)++I2+C2(+b2)++I2++C2(+h2)++I2++C2(+m2)++I2+(+C1(+w1)++I1++C1(+b1)++I1)+C2(+p2)+-(+I2)-((+C0++C0(+b0)++I0)--(+I0))-+((+C1+(+I1+-(+x1+b1)+-(+x1+t1)+-(+x1+t1)+-(+x1+u1))--+(-(+z1)++I1))
*** Conclusion:
 +C2(+m2)++I2
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +(+B1++L1)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +R2+B2+L2-+L2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +H2+S2(+s2)
*** Conclusion:
 +(+S1++H1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+W2(+t2)--+H2(+t2)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 +H2(+t2)-+W2
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +S2(+p2)-+C2(+p2)+D2(+t2)+A2(+t2)-+W2(+t2)+W2(+t2)-+B2+G2(+t2)+H2(+t2)-+B2-(+G0--+D0)+S2(+p2)-+W2-((+D0++B0)--+C0(+p0))+H2(+t2)-+A2(+t2)
*** Conclusion:
 -+H2(+t2)--+B2
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 -+I2
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +R2(+b2)++I2+P2+P2+I2+S2---((+S0+(+P0-+P0)-+S0)+S2---((+I0++I0)-+I0)---((+P0++P0)-+P0)
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +P2(+e2)
*** True Label:
 T
*** Predicted Label:
 F
*** Premises:
 +R2(+n2)++R2(+n2)++R2(+n2)--((+R0++R0++I0)-+L0)--(+L0--+L0)+(+I1++E1)+(+I1++E1)+P2(+n2)--((+P0++I0)-+P0)+I2+I2
*** Conclusion:
 +L2
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 +L2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 ++(+C1++P1)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +C2(+m2)++C2(+m2)++S2++S2-(+C0-+M0)++((+M1-+L1)+(-(+x1)++M1-+L1))+P2
*** Conclusion:
 -(+C0--+S0)
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 +L2
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +V2(+t2)++L2+L2+L2-((+L0++L0)-+L0)
*** Conclusion:
 -+L2
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +W2
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+S2
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +Y2(+t2)++N2(+t2)++W2+P2---((+W0++P0)-+W0)+F2(+m2)++S2++((+C1++N1++P1)+(-(+x1)++N1++P1))+C2(+a2)++N2++C2(+s2)++N2+S2++S2
*** Conclusion:
 -+W2
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +G2
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(+I1)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 +A2(+w2)++L2(+w2)++S2+G2++G2+(+I1++I1++P1)+M2
*** Conclusion:
 +(-+I1)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -((+W0++F0)-+(+F1++I1))
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 +I2
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +D2+I2-((+W0++I0)-+F0)+I2
*** Conclusion:
 -(+W0++F0-+F0)
*** True Label:
 U
*** Predicted Label:
 F</output>
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+F1++F1)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 +(+S1++R1)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +B2++E2(+s2)+F2++F2+F2++F2-(+E0-+B0)+(+C1++R1)-(+C0--+S0)
*** Conclusion:
 -+B2(+s2)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +O2(+u2)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 +(+M1++O1++S1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +H2(+u2)++B2+L2(+u2)+M2(+u2)-(+M0-+O0)+S2++S2
*** Conclusion:
 -+L2(+u2)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 ++(+E1++I1++E1++I1)
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0--+N0)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 -(+E0-(+G0++B0))+++(+E1++I1+(-(+x1))++E1++I1+(-(+x1))+(-(+y1))++E1++I1)++(+E1++N1+(-(+x1))++E1++N1)-(+E0-+T0)
*** Conclusion:
 -(+E0-+T0)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +G2(+n2)++N2++N2(+d2)++N2++N2(+d2)++N2++N2(+d2)+N2(+d2)++P2(+d2)+N2(+d2)++B2(+d2)
*** Conclusion:
 +N2(+d2)++P2(+d2)
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2(+j2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +E2(+a2)++T2(+a2)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +S2(+n2)++F2+M2+(++(+F1++N1+(-(+x1))++F1++N1)+N2++N2(+a2)++N2++N2(+j2)++N2++N2(+m2)+B2(+a2)++S2(+a2)++S2(+a2)+E2(+j2)++T2(+j2)
*** Conclusion:
 +N2++N2
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+T1++H1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +F2(+m2)++M2(+m2)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +C2(+m2)++M2(+m2)+K2+H2+T2
*** Conclusion:
 +(+C1++M1++K1)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2++P2
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +P2
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +E2(+t2)++P2(+t2)+P2++P2+P2++P2+S2
*** Conclusion:
 +(+E1++P1++S1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +T2(+t2)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 +(+C1++J1++V1)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +G2(+t2)++(+J1++V1++C1)--((+G0++I0++C0)-+J0)-((+G0++(+G1++C1))-+T1))+(+G1++C1)
*** Conclusion:
 -+T2(+t2)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +H2(+b2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +T2(+g2)++F2+W2-((+T0++A0)-+W0)+T2(+b2)++L2-((+T0++W0)-+M0)-((+W0-+L0)-+A0)
*** Conclusion:
 +M2(+g2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+E2(+j2)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 +C2(+j2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 -(+S0-+E0)+(+C1)-(+P0--+W0)+W2+S2+P2
*** Conclusion:
 -+W2
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +A2(+t2)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 -((+B0++W0)-+(+M1++S1))+(+W1++B1++W1)-((+B0++A0)-+F0)+B2(+t2)++(+M1++S1)+A2(+t2)
*** Conclusion:
 +W2
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +E2(+t2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +R2(+f2)
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 -(+E0-+(+L1++A1))-(+R0-+E0)-(+E0-+H0)-(+S0)-+H0)+R2(+t2)+S2(+f2)
*** Conclusion:
 +(+G1++A1)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +B2(+m2)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 -(+P0-(+S0-+P0-+A0-+B0-+B0-+B0))-+S0(+m0)-(+P0(+m0)-+A0(+m0)-+B0(+m0)-+B0(+m0))+P2(+m2)
*** Conclusion:
 +P2(+e2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+p2)+(-+H2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +R2(+p2)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 ++(+M1++M1+(-(+x1))++H1++H1)-+H1+M2(+p2)+H2
*** Conclusion:
 +M2(+h2)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +(+D1++D1++C1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +D2++D2++D2++D2++C2(+g2)-+D2
*** Conclusion:
 +D2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +A2(+j2)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +M2(+j2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +M2(+j2)++A2(+j2)++(+A1++M1++R1+(-(+x1))++A1++M1++R1)--((+H0++P0)-+R0)+R2(+j2)+(+H1++P1)
*** Conclusion:
 +R2(+j2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +V2(+g2)++I2
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +C2(+g2)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 +V2(+g2)++P2(+d2)++I2+P2(+d2)++I2-(+C0--+V0)+(+P1++V1++I1)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 +F2
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(-(+D0++F0))
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 +M2(+e2)++R2+S2-(+F2)++(+F1+(-(+x1))++F1)+D2+F2
*** Conclusion:
 -(+D0--(+F0))
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +P2
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+P1++P1)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +P2++(+c1++P1)+C2+P2(+n2)
*** Conclusion:
 +(+W1++P1)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +W2(+h2)++F2
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +(+G1++L1)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +W2(+h2)+F2+(+G1++L1)+(+H1++A1)
*** Conclusion:
 +A2
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +N2
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +P2(+j2)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +B2+P2(+j2)-(+P0-+P0)-(+B0-+N0)-(+N0--+N0)
*** Conclusion:
 +I2(+j2)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 -+B2
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +I2(+r2)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 +B2+P2(+r2)+H2(+r2)-((+P0++I0)-+H0)
*** Conclusion:
 +G2(+r2)
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +O2(+c2)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +H2(+c2)
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 -((+D0++G0)-+O0)+D2(+c2)+G2(+c2)+W2(+c2)-(+W0--+H0)
*** Conclusion:
 +W2(+c2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+t2)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +I2(+t2)--((+I0++R0)-+I0)+R2-(+I0--+I0)
*** Conclusion:
 +I2(+w2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+h2)
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 -+H2(+c2)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 -(+S0-+H0)+S2(+h2)+S2(+c2)
*** Conclusion:
 +H2(+l2)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1++I1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +M2(+m2)++I2+M2(+w2)++I2+M2(+m2)++I2+I2++I2+I2
*** Conclusion:
 +(+M1++I1++I1)
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +P2(+y2)
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 -(+P0--+P0)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +P2++O2(+w2)+P2-((+(+P1))-+P1)+P2++P2++P2
*** Conclusion:
 +S2(+w2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 +O2(+h2)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 -((+R0++U0)-+O0)-(+F0-+R0)-(+S0-+U0)-(+M0-+F0)+M2(+h2)++S2(+h2)-+M2(+k2)++U2(+k2)
*** Conclusion:
 -+O2(+k2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 -+K2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +T2(+l2)++S2-(+S0-+O0)-(+T0-+P0)-((+O0++P0)-+K0)+S2+(-+P2(+d2))
*** Conclusion:
 +K2
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 -(+L0--+S0)
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +(+E1++F1)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +B2(+j2)++L2(+j2)+W2(+j2)++P2(+j2)++S2(+j2)-(+B0-+E0)-(+L0-+F0)++(+W1++S1)+(-(+x1))+(+W1++S1)
*** Conclusion:
 +S2(+j2)
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 ++(+R1++L1++S1)
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 -+M2(+d2)
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 +A2(+i2)++R2(+i2)+L2+S2(+d2)--(+L0-+S0)-(+S0-+M0)+P2++(+P1++B1)+(-(+x1))+(+P1++B1)
*** Conclusion:
 +B2(+d2)
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +B2
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 +B2(+a2)++H2(+a2)++P2(+a2)-(+L0-+S0)+L2+B2-+L2
*** Conclusion:
 +S2
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:

In [19]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.13953488372093023
***** PRECISION *****
0.17116846738695482
***** RECALL *****
0.05918085240964784
***** F1 *****
0.07913924374456112

   Accuracy  Precision    Recall        F1
0  0.139535   0.171168  0.059181  0.079139

In [16]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)