In [1]:
'''
task: classify syllogism validity with CGIF notation
models: gemma-2-2b-it, llama-3.2-3b-instruct, phi-3.5-mini-instruct
dataset: pfolio
evaluation: zero-shot
'''
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# start preparing for QA pipeline
! pip install -U accelerate
! pip install -U transformers
!pip install transformers
!pip install evaluate

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 141.6 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.3.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)

In [3]:
import pandas as pd

pfolio_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/p-folio/data/pfolio_kr_gold_train.csv")

In [4]:
# evaluation metrics

import numpy as np
import re
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

def predict_answer(model, tokenizer, obj, subject, ref_relation=None, source_knowledge=None):
  # define notation grammar
  grammar = r"""
    start: program
    program: [stat]+
    stat: proposition newline | keyword* quantifier* symbol* leftparen* (quantifier symbol)* proposition rightparen* newline | keyword* (quantifier symbol)* leftparen* (quantifier symbol)* proposition rightparen* newline
    proposition: atomicproposition | complexproposition
    complexproposition: keyword* proposition keyword leftparen* (quantifier symbol)* proposition rightparen*
    atomicproposition: leftparen* term* leftparen* term* rightparen*
    !term: (LETTER+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠" | "?")* | (DIGIT+) (LETTER+|DIGIT+|"=" | "+" | "-" | "," | "≠" | "?")*
    !leftparen: "[("
    !rightparen: ")]"
    !keyword: "~" | "?"
    !quantifier: "*" | "@every *"
    symbol: LETTER
    newline: /\n/

    %import common.LETTER
    %import common.DIGIT
    %import common.INT -> NUMBER
    %import common.ESCAPED_STRING -> STRING
    %import common.WS
    %ignore WS
"""
  # prepare prompt
  rag_prompt = f"""
  <start_of_turn>user
  You are an expert logician. You are given a syllogism in CGIF with premises between <PREMISES></PREMISES> and conclusion between <CONCLUSION></CONCLUSION> tags.
  The CGIF BNF grammar to understand and reason in the language is given in the <GRAMMAR></GRAMMAR> tags.
  <GRAMMAR>{grammar}</GRAMMAR>
  <PREMISES>{subject}</PREMISES>
  <CONCLUSION>{obj}</CONCLUSION>
  Classify the conclusion as "T" if true, "F" if false or "U" if uncertain based on the premises. Present your answer only between <output></output> tags.
  <end_of_turn>
  <start_of_turn>model
  """
  input_ids = tokenizer(rag_prompt, return_tensors="pt").to(model.device)
  response = model.generate(**input_ids, max_new_tokens=500)
  predicted_relation = tokenizer.decode(response[0])
  matches = re.findall('<output>(.*)</output>', predicted_relation, flags=re.DOTALL)
  res = re.findall(r"<output>(.*)", matches[-1])  # from ['</output> tags.\n  <end_of_turn>\n  <start_of_turn>model\n  <output>T'] to ['T']
  predicted_label = res[0] if res else "None" # take first element from list ['T'] to get 'T'

  print("*** Premises: \n", subject)
  print("*** Conclusion: \n", obj)
  print("*** True Label: \n", ref_relation)
  print("*** Predicted Label: \n", predicted_label)
  return predicted_label

In [5]:
def infer_from_ontology(dataset, model, tokenizer, mode='default', notation='NL'):
  evaluation_metrics_df = pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1"])
  reference_labels = []
  predicted_labels = []
  for index, row in dataset.iterrows():
      conclusion = row["Conclusions - " + notation]
      premises = row["Premises - " + notation]
      label = row["Truth Values"]
      if mode.lower() == "grammar":
        # conduct query with RAG retrival of sources
        # set number of candidate answers to consider as half the total triple store axioms
        source_information = """BNF GRAMMAR"""
        print("*** RAG INFORMATION:", source_information)
      # predict answer with model
      predicted_label = predict_answer(model, tokenizer, conclusion, premises, label)
      reference_labels.append(label)
      predicted_labels.append(predicted_label)
  # fill evaluation metrics dataframe
  accuracy_metric = accuracy_score(reference_labels, predicted_labels)
  precision_metric = precision_score(reference_labels, predicted_labels, average="macro")
  recall_metric = recall_score(reference_labels, predicted_labels, average="macro")
  f1_metric = f1_score(reference_labels, predicted_labels, average="macro")
  evaluation_metrics_df["Accuracy"] = [accuracy_metric]
  evaluation_metrics_df["Precision"] = [precision_metric]
  evaluation_metrics_df["Recall"] = [recall_metric]
  evaluation_metrics_df["F1"] = [f1_metric]
  print("Classification Report:", classification_report(reference_labels, predicted_labels))
  print("*************** INFERENCE COMPLETE ***************")
  return reference_labels, predicted_labels, evaluation_metrics_df, accuracy_metric, precision_metric, recall_metric, f1_metric

In [6]:
import torch
import json
from tqdm import tqdm
import torch.nn as nn
from torch.optim import Adam
import nltk
import spacy
import string
import evaluate  # Bleu
from torch.utils.data import Dataset, DataLoader, RandomSampler
import pandas as pd
import numpy as np
import transformers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from transformers import AutoTokenizer, AutoModelForCausalLM

import warnings
warnings.filterwarnings("ignore")

In [7]:
# login to hugging face to have access to the model
!pip install huggingface_hub
from huggingface_hub import notebook_login
notebook_login()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
# try rag search with gemma
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [10]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CGIF')

*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [ocellatedwildturkey[(tom)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [easternwildturkey[(tom)]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [wildturkey[(joey)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [has[(mary  flu)]
@every *x [(has[(?x  flu)]  has[(?x  influenza)])]
~has[(susan  influenza)]]
*** Conclusion:
 [has[(mary  influenza)]  has[(susan  influenza)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(in[(butte  x)]  in[(stpierre  x)])]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(city[(pierre)]  in[(pierre  x)]  city[(bismarck)]  in[(bismarck  x)])]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [city[(missoula)]  in[(missoula  montana)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newfrance)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newengland)])]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [locatedin[(fortcarillon  europe)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [holds[(suduva  thelithuaniansupercup)]
soccerteam[(suduva)]]
*** Conclusion:
 [*x [(soccerteam[(?x)]  holds[(?x  thelithuaniansupercup)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[wakesup[(thehulk)]  ~happy[(thor)]]
*** True Label:
 T
*** Predicted Label:
 F
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 [happy[(thor)]  wears[(peterparker  uniform)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[happy[(thor)]  ~breaks[(thor  bridge)]]
*** True Label:
 U
*** Predicted Label:
 F
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [situatedon[(longueau  pairslille)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 ~[in[(boves  europe)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [serve[(longueau  hautsdefrance)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(eight  seven)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [positive[(eight)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(six  seven)]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [love[(miroslav  music)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [*x *y [(czech[(?x)]  publishedbook[(?x  y  year1946)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [@every *x [(choralconductor[(?x)]  ~specializeinperformanceof[(?x  renaissancemusic)])]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 [likeplayingwith[(cat  taigavole)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 ~[livein[(taigavole  coldplace)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [workedwith[(whalenturner  greenwillowbooks)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [plotstoswallowup[(medeempire  attolia)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[setin[(thickastheives  medeempire)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[workedwith[(megan  greenwillowbooks)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [graduatedwith[(walterbrown  bachelorsofart)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(in[(walterbrownfather  toledo  t)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(~in[(walterbrownfather  toledo  t)])]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [([(water[(?x)]  from[(?x  crotonriverwatershed)])]  *y[(flowsto[(?x  y)]  in[(?y  newyork)])])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [in[(crotonriverwatershed  bronx)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [(water[(?x)]  from[(?x  crotonriver)]  flowsto[(?x  bronx)])]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(form[(?x  system7)]  formermemberof[(?x  gong)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(single[(?x)]  release[(system7  x)])]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 ~[band[(system7)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [opentopublic[(usssalem)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [*x [(museumship[(?x)]  opentopublic[(?x)]  servedin[(?x  mediterranean)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 ~[lastheavycruisertoenterservice[(usssalem)]]
*** True Label:
 F
*** Predicted Label:
 F
*** Premises:
 [@every *x [(elephantopus[(?x)]  [(genus[(?x  perennialplants)]  belongto[(?x  daisyfamily)])])]

In [11]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.48172757475083056
***** PRECISION *****
0.3922331422331422
***** RECALL *****
0.4528391541933951
***** F1 *****
0.37361097533157367

   Accuracy  Precision    Recall        F1
0  0.481728   0.392233  0.452839  0.373611

In [13]:
# try rag search with llama
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B-Instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B-Instruct", device_map="auto")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [14]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CGIF')

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [ocellatedwildturkey[(tom)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [easternwildturkey[(tom)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [wildturkey[(joey)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [has[(mary  flu)]
@every *x [(has[(?x  flu)]  has[(?x  influenza)])]
~has[(susan  influenza)]]
*** Conclusion:
 [has[(mary  influenza)]  has[(susan  influenza)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(in[(butte  x)]  in[(stpierre  x)])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(city[(pierre)]  in[(pierre  x)]  city[(bismarck)]  in[(bismarck  x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [city[(missoula)]  in[(missoula  montana)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newfrance)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newengland)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [locatedin[(fortcarillon  europe)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [holds[(suduva  thelithuaniansupercup)]
soccerteam[(suduva)]]
*** Conclusion:
 [*x [(soccerteam[(?x)]  holds[(?x  thelithuaniansupercup)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[wakesup[(thehulk)]  ~happy[(thor)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 [happy[(thor)]  wears[(peterparker  uniform)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[happy[(thor)]  ~breaks[(thor  bridge)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [situatedon[(longueau  pairslille)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 ~[in[(boves  europe)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [serve[(longueau  hautsdefrance)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(eight  seven)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [positive[(eight)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(six  seven)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [love[(miroslav  music)]]
*** True Label:
 U
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [*x *y [(czech[(?x)]  publishedbook[(?x  y  year1946)])]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [@every *x [(choralconductor[(?x)]  ~specializeinperformanceof[(?x  renaissancemusic)])]]
*** True Label:
 F
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 [likeplayingwith[(cat  taigavole)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 ~[livein[(taigavole  coldplace)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [workedwith[(whalenturner  greenwillowbooks)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [plotstoswallowup[(medeempire  attolia)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[setin[(thickastheives  medeempire)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[workedwith[(megan  greenwillowbooks)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [graduatedwith[(walterbrown  bachelorsofart)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(in[(walterbrownfather  toledo  t)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(~in[(walterbrownfather  toledo  t)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [([(water[(?x)]  from[(?x  crotonriverwatershed)])]  *y[(flowsto[(?x  y)]  in[(?y  newyork)])])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [in[(crotonriverwatershed  bronx)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [(water[(?x)]  from[(?x  crotonriver)]  flowsto[(?x  bronx)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(form[(?x  system7)]  formermemberof[(?x  gong)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(single[(?x)]  release[(system7  x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 ~[band[(system7)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [opentopublic[(usssalem)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [*x [(museumship[(?x)]  opentopublic[(?x)]  servedin[(?x  mediterranean)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 ~[lastheavycruisertoenterservice[(usssalem)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(elephantopus[(?x)]  [(genus[(?x  perennialplants)]  belongto[(?x  daisyfamily)])])]
*x *y *z[(elephantopus[(?x)]  in[(?x africa)]  [(~[(?x=y)])]  elephantopus[(?y)]  in[(?y  southernasia)]  [(~[(?x=z)])]  [(~[(?y=z)])]  elephantopus[(?z)]  in[(?z  australia)])]
*x *y [(elephantopus[(?x)]  nativeto[(?x  southeasternunitedstates)]  [(~[(?x=y)])]  elephantopus[(?y)]  nativeto[(?y  southeasternunitedstates)])]
@every *x [(elephantopusscaber[(?x)]  traditionalmedicine[(?x)])]]
*** Conclusion:
 [*x*y[(elephantopus[(?x)]  in[(?x africa)]  elephantopus[(?y)]  in[(?y africa)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(elephantopus[(?x)]  [(genus[(?x  perennialplants)]  belongto[(?x  daisyfamily)])])]
*x *y *z[(elephantopus[(?x)]  in[(?x africa)]  [(~[(?x=y)])]  elephantopus[(?y)]  in[(?y  southernasia)]  [(~[(?x=z)])]  [(~[(?y=z)])]  elephantopus[(?z)]  in[(?z  australia)])]
*x *y [(elephantopus[(?x)]  nativeto[(?x  southeasternunitedstates)]  [(~[(?x=y)])]  elephantopus[(?y)]  nativeto[(?y  southeasternunitedstates)])]
@every *x [(elephantopusscaber[(?x)]  traditionalmedicine[(?x)])]]
*** Conclusion:
 [@every *x [(elephantopus[(?x)]  ~nativeto[(?x  southeasternunitedstates)])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(elephantopus[(?x)]  [(genus[(?x  perennialplants)]  belongto[(?x  daisyfamily)])])]
*x *y *z[(elephantopus[(?x)]  in[(?x africa)]  [(~[(?x=y)])]  elephantopus[(?y)]  in[(?y  southernasia)]  [(~[(?x=z)])]  [(~[(?y=z)])]  elephantopus[(?z)]  in[(?z  australia)])]
*x *y [(elephantopus[(?x)]  nativeto[(?x  southeasternunitedstates)]  [(~[(?x=y)])]  elephantopus[(?y)]  nativeto[(?y  southeasternunitedstates)])]
@every *x [(elephantopusscaber[(?x)]  traditionalmedicine[(?x)])]]
*** Conclusion:
 [@every *x [(elephantopus[(?x)]  traditionalmedicine[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [
givenname[(namedagfinn)]  named[(dagfinnaarskog  namedagfinn)]  notableperson[(dagfinnaarskog)]  named[(dagfinnbakke  namedagfinn)]  notableperson[(dagfinnbakke)]   named[(dagfinndahl  namedagfinn)]  notableperson[(dagfinndahl)]
norwegian[(dagfinnaarskog)]  physician[(dagfinnaarskog)]
norwegian[(dagfinndahl)]  barrister[(dagfinndahl)]]
*** Conclusion:
 [notableperson[(dagfinnaarskog)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [
givenname[(namedagfinn)]  named[(dagfinnaarskog  namedagfinn)]  notableperson[(dagfinnaarskog)]  named[(dagfinnbakke  namedagfinn)]  notableperson[(dagfinnbakke)]   named[(dagfinndahl  namedagfinn)]  notableperson[(dagfinndahl)]
norwegian[(dagfinnaarskog)]  physician[(dagfinnaarskog)]
norwegian[(dagfinndahl)]  barrister[(dagfinndahl)]]
*** Conclusion:
 [named[(dagfinnaarskog  namedagfinn)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [
givenname[(namedagfinn)]  named[(dagfinnaarskog  namedagfinn)]  notableperson[(dagfinnaarskog)]  named[(dagfinnbakke  namedagfinn)]  notableperson[(dagfinnbakke)]   named[(dagfinndahl  namedagfinn)]  notableperson[(dagfinndahl)]
norwegian[(dagfinnaarskog)]  physician[(dagfinnaarskog)]
norwegian[(dagfinndahl)]  barrister[(dagfinndahl)]]
*** Conclusion:
 [norwegian[(dagfinndahl)]  physician[(dagfinndahl)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [surname[(nameodell)]  from[(nameodell  odellbedfordshire)]
mistakenspellingof[(nameo'dell  nameodell)]  [(*x*y[(family[(?x)]  named[(?x  nameo'dell)]  [(~[(?x=y)])]  family[(?y)]  named[(?y  nameo'dell)])]
named[(amyodell  nameodell)]  notableperson[(amyodell)]  named[(jackodell  nameodell)]  notableperson[(jackodell)]  named[(matsodell  nameodell)]  notableperson[(matsodell)]
british[(amyodell)]  singer[(amyodell)]  songwriter[(amyodell)]
english[(jackodell)]  toyinventor[(jackodell)]]
*** Conclusion:
 [notableperson[(jackodell)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [surname[(nameodell)]  from[(nameodell  odellbedfordshire)]
mistakenspellingof[(nameo'dell  nameodell)]  [(*x*y[(family[(?x)]  named[(?x  nameo'dell)]  [(~[(?x=y)])]  family[(?y)]  named[(?y  nameo'dell)])]
named[(amyodell  nameodell)]  notableperson[(amyodell)]  named[(jackodell  nameodell)]  notableperson[(jackodell)]  named[(matsodell  nameodell)]  notableperson[(matsodell)]
british[(amyodell)]  singer[(amyodell)]  songwriter[(amyodell)]
english[(jackodell)]  toyinventor[(jackodell)]]
*** Conclusion:
 [named[(amyodell  nameodell)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [surname[(nameodell)]  from[(nameodell  odellbedfordshire)]
mistakenspellingof[(nameo'dell  nameodell)]  [(*x*y[(family[(?x)]  named[(?x  nameo'dell)]  [(~[(?x=y)])]  family[(?y)]  named[(?y  nameo'dell)])]
named[(amyodell  nameodell)]  notableperson[(amyodell)]  named[(jackodell  nameodell)]  notableperson[(jackodell)]  named[(matsodell  nameodell)]  notableperson[(matsodell)]
british[(amyodell)]  singer[(amyodell)]  songwriter[(amyodell)]
english[(jackodell)]  toyinventor[(jackodell)]]
*** Conclusion:
 [english[(amyodell)]  toyinventor[(amyodell)]]
*** True Label:
 U
*** Predicted Label:
 F</output>  <!-- The conclusion is false. -->

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [surname[(nameodell)]  from[(nameodell  odellbedfordshire)]
mistakenspellingof[(nameo'dell  nameodell)]  [(*x*y[(family[(?x)]  named[(?x  nameo'dell)]  [(~[(?x=y)])]  family[(?y)]  named[(?y  nameo'dell)])]
named[(amyodell  nameodell)]  notableperson[(amyodell)]  named[(jackodell  nameodell)]  notableperson[(jackodell)]  named[(matsodell  nameodell)]  notableperson[(matsodell)]
british[(amyodell)]  singer[(amyodell)]  songwriter[(amyodell)]
english[(jackodell)]  toyinventor[(jackodell)]]
*** Conclusion:
 [named[(amyodell  nameodell)]  named[(amyodell  nameo'dell)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslavfiedler)]  mathematician[(miroslavfiedler)]
knownfor[(miroslavfiedler  contributionstolinearalgebraandgraphtheory)]
honoredby[(miroslavfiedler  fiedlereigenvalue)]
thesecondsmallesteigenvalueof[(fiedlereigenvalue  thegraphlaplacian)]]
*** Conclusion:
 [*x [(thesecondsmallesteigenvalueof[(?x  thegraphlaplacian)]  honoredby[(miroslavfiedler  x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslavfiedler)]  mathematician[(miroslavfiedler)]
knownfor[(miroslavfiedler  contributionstolinearalgebraandgraphtheory)]
honoredby[(miroslavfiedler  fiedlereigenvalue)]
thesecondsmallesteigenvalueof[(fiedlereigenvalue  thegraphlaplacian)]]
*** Conclusion:
 [french[(miroslavfiedler)]  mathematician[(miroslavfiedler)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [czech[(miroslavfiedler)]  mathematician[(miroslavfiedler)]
knownfor[(miroslavfiedler  contributionstolinearalgebraandgraphtheory)]
honoredby[(miroslavfiedler  fiedlereigenvalue)]
thesecondsmallesteigenvalueof[(fiedlereigenvalue  thegraphlaplacian)]]
*** Conclusion:
 [*x [(czech[(?x)]  mathematician[(?x)]  knownfor[(?x  contributionstolinearalgebraandgraphtheory)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [english[(thomasbarber)]  professionalfootballer[(thomasbarber)]
playedfor[(thomasbarber  astonvilla)]  playedin[(astonvilla thefootballleague)]
playedas[(thomasbarber  halfback)]  playedas[(thomasbarber  insideleft)]
scoredthewinninggoalin[(thomasbarber  facupfinal1913)]]
*** Conclusion:
 [playedfor[(thomasbarber  boltonwanderers)]  playedin[(boltonwanderers thefootballleague)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [english[(thomasbarber)]  professionalfootballer[(thomasbarber)]
playedfor[(thomasbarber  astonvilla)]  playedin[(astonvilla thefootballleague)]
playedas[(thomasbarber  halfback)]  playedas[(thomasbarber  insideleft)]
scoredthewinninggoalin[(thomasbarber  facupfinal1913)]]
*** Conclusion:
 [playedas[(thomasbarber  insideleft)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [english[(thomasbarber)]  professionalfootballer[(thomasbarber)]
playedfor[(thomasbarber  astonvilla)]  playedin[(astonvilla thefootballleague)]
playedas[(thomasbarber  halfback)]  playedas[(thomasbarber  insideleft)]
scoredthewinninggoalin[(thomasbarber  facupfinal1913)]]
*** Conclusion:
 [*x [(english[(?x)]  professionalfootballer[(?x)]  scoredthewinninggoalin[(?x  facupfinal1913)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [game[(thelegendofzelda)]  *x [(japanese[(?x)]  videogamecompany[(?x)]  created[(?x  thelegendofzelda)])]
@every *x @every *y [([(game[(?x)]  intop10[(?x)]  created[(?y ?x)])]  japanese[(?y)])]
@every *x [([(game[(?x)]  *y[(greaterthan[(?y  onemillion)]  copiessold[(?x  y)])])]  top10[(?x)])])]
*y[(greaterthan[(?y  onemillion)]  copiessold[(thelegendofzelda ?y)])]]
*** Conclusion:
 [top10[(thelegendofzelda)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [game[(thelegendofzelda)]  *x [(japanese[(?x)]  videogamecompany[(?x)]  created[(?x  thelegendofzelda)])]
@every *x @every *y [([(game[(?x)]  intop10[(?x)]  created[(?y ?x)])]  japanese[(?y)])]
@every *x [([(game[(?x)]  *y[(greaterthan[(?y  onemillion)]  copiessold[(?x  y)])])]  top10[(?x)])])]
*y[(greaterthan[(?y  onemillion)]  copiessold[(thelegendofzelda ?y)])]]
*** Conclusion:
 [*x[(created[(?x  fifa22)]  japanese[(?x)]  videogamecompany[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [game[(thelegendofzelda)]  *x [(japanese[(?x)]  videogamecompany[(?x)]  created[(?x  thelegendofzelda)])]
@every *x @every *y [([(game[(?x)]  intop10[(?x)]  created[(?y ?x)])]  japanese[(?y)])]
@every *x [([(game[(?x)]  *y[(greaterthan[(?y  onemillion)]  copiessold[(?x  y)])])]  top10[(?x)])])]
*y[(greaterthan[(?y  onemillion)]  copiessold[(thelegendofzelda ?y)])]]
*** Conclusion:
 ~[top10[(thelegendofzelda)]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [team[(goldenstatewarriors)]  from[(goldenstatewarriors  sanfrancisco)]
won[(goldenstatewarriors  nbafinals)]
@every *x [([(team[(?x)]  attending[(?x  nbafinals)])]  wonmanygames[(?x)])]
team[(bostonceltics)]  lost[(bostonceltics  nbafinals)]
@every *x [([(team[(?x)]  won[(?x  nbafinals)])]  moreincome[(?x)])]
@every *x [([(won[(?x  nbafinals)]  lost[(?x  nbafinals)])]  attending[(?x  nbafinals)])]]
*** Conclusion:
 [from[(bostonceltics  sanfrancisco)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [team[(goldenstatewarriors)]  from[(goldenstatewarriors  sanfrancisco)]
won[(goldenstatewarriors  nbafinals)]
@every *x [([(team[(?x)]  attending[(?x  nbafinals)])]  wonmanygames[(?x)])]
team[(bostonceltics)]  lost[(bostonceltics  nbafinals)]
@every *x [([(team[(?x)]  won[(?x  nbafinals)])]  moreincome[(?x)])]
@every *x [([(won[(?x  nbafinals)]  lost[(?x  nbafinals)])]  attending[(?x  nbafinals)])]]
*** Conclusion:
 [hasmorethanthirtyyearsofhistory[(bostonceltics)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [team[(goldenstatewarriors)]  from[(goldenstatewarriors  sanfrancisco)]
won[(goldenstatewarriors  nbafinals)]
@every *x [([(team[(?x)]  attending[(?x  nbafinals)])]  wonmanygames[(?x)])]
team[(bostonceltics)]  lost[(bostonceltics  nbafinals)]
@every *x [([(team[(?x)]  won[(?x  nbafinals)])]  moreincome[(?x)])]
@every *x [([(won[(?x  nbafinals)]  lost[(?x  nbafinals)])]  attending[(?x  nbafinals)])]]
*** Conclusion:
 [moreincome[(goldenstatewarriors)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(subscribedto[(?x  amcalist)]  eligibleforthreefreemovies[(?x)])]
*x [(cinemaeveryweek[(?x)])]
@every *x [(prefer[(?x  tvseries)]  ~watchtvin[(?x  cinemas)])]
watchtvin[(james  cinemas)]
subscribedto[(james  amcalist)]
prefer[(peter  tvseries)]]
*** Conclusion:
 ~[eligibleforthreefreemovies[(james)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(subscribedto[(?x  amcalist)]  eligibleforthreefreemovies[(?x)])]
*x [(cinemaeveryweek[(?x)])]
@every *x [(prefer[(?x  tvseries)]  ~watchtvin[(?x  cinemas)])]
watchtvin[(james  cinemas)]
subscribedto[(james  amcalist)]
prefer[(peter  tvseries)]]
*** Conclusion:
 [cinemaeveryweek[(james)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(subscribedto[(?x  amcalist)]  eligibleforthreefreemovies[(?x)])]
*x [(cinemaeveryweek[(?x)])]
@every *x [(prefer[(?x  tvseries)]  ~watchtvin[(?x  cinemas)])]
watchtvin[(james  cinemas)]
subscribedto[(james  amcalist)]
prefer[(peter  tvseries)]]
*** Conclusion:
 ~[watchtvin[(peter  cinemas)]]
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(book[(?x)]  writtenby[(?x  cixinliu)])]  *y[(morethan[(?y  onemillion)]  sold[(?x ?y)])])]
*x [(won[(?x  hugoaward)]  book[(?x)]  writtenby[(?x  cixinliu)])]
@every *x [([(book[(?x)]  aboutfuture[(?x)])]  fowardlooking[(?x)])]
book[(threebodyproblem)]  *y[(morethan[(?y  onemillion)]  sold[(threebodyproblem ?y)])]
aboutfuture[(threebodyproblem)]]
*** Conclusion:
 [won[(threebodyproblem  hugoaward)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(book[(?x)]  writtenby[(?x  cixinliu)])]  *y[(morethan[(?y  onemillion)]  sold[(?x ?y)])])]
*x [(won[(?x  hugoaward)]  book[(?x)]  writtenby[(?x  cixinliu)])]
@every *x [([(book[(?x)]  aboutfuture[(?x)])]  fowardlooking[(?x)])]
book[(threebodyproblem)]  *y[(morethan[(?y  onemillion)]  sold[(threebodyproblem ?y)])]
aboutfuture[(threebodyproblem)]]
*** Conclusion:
 [aboutfuture[(threebodyproblem)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(book[(?x)]  writtenby[(?x  cixinliu)])]  *y[(morethan[(?y  onemillion)]  sold[(?x ?y)])])]
*x [(won[(?x  hugoaward)]  book[(?x)]  writtenby[(?x  cixinliu)])]
@every *x [([(book[(?x)]  aboutfuture[(?x)])]  fowardlooking[(?x)])]
book[(threebodyproblem)]  *y[(morethan[(?y  onemillion)]  sold[(threebodyproblem ?y)])]
aboutfuture[(threebodyproblem)]]
*** Conclusion:
 [writtenby[(threebodyproblem  cixinliu)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(easy[(?x)]  *y [(lessthan[(?y  percent20)]  acrate[(?x ?y)])])]
@every *x [(recommended[(?x)]  easy[(?x)])]
@every *x [(easy[(?x)]  hard[(?x)])]
@every *x [(starred[(?x)])]  hard[(?x)])]
recommended[(twosum)]
starred[(foursum)]]
*** Conclusion:
 [easy[(twosum)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(easy[(?x)]  *y [(lessthan[(?y  percent20)]  acrate[(?x ?y)])])]
@every *x [(recommended[(?x)]  easy[(?x)])]
@every *x [(easy[(?x)]  hard[(?x)])]
@every *x [(starred[(?x)])]  hard[(?x)])]
recommended[(twosum)]
starred[(foursum)]]
*** Conclusion:
 [recommended[(foursum)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(easy[(?x)]  *y [(lessthan[(?y  percent20)]  acrate[(?x ?y)])])]
@every *x [(recommended[(?x)]  easy[(?x)])]
@every *x [(easy[(?x)]  hard[(?x)])]
@every *x [(starred[(?x)])]  hard[(?x)])]
recommended[(twosum)]
starred[(foursum)]]
*** Conclusion:
 [*y[(greaterthan[(?y  percent20)]  acrate[(2sum ?y)])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(philateliclit[(?x)]  [(stamp[(?x)]  periodical[(?x)]  auction[(?x)]  book[(?x)]  bibliography[(?x)]  background[(?x)])])]
~stamp[(mort)]
~[(periodical[(mort)]  auction[(mort)]  bibliography[(mort)]  background[(mort)])]
philateliclit[(mort)]]
*** Conclusion:
 [background[(mort)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(philateliclit[(?x)]  [(stamp[(?x)]  periodical[(?x)]  auction[(?x)]  book[(?x)]  bibliography[(?x)]  background[(?x)])])]
~stamp[(mort)]
~[(periodical[(mort)]  auction[(mort)]  bibliography[(mort)]  background[(mort)])]
philateliclit[(mort)]]
*** Conclusion:
 [philateliclit[(eragon)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y [(mammal[(?x)]  mammal[(?y)]  [(~[(?x=y)])]  have[(?x  teeth)]  have[(?y  teeth)])]
~have[(platypus  teeth)]
mammal[(platypus)]
have[(humans  teeth)]]
*** Conclusion:
 [mammal[(platypus)]  [(~have[(platypus  teeth)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y [(mammal[(?x)]  mammal[(?y)]  [(~[(?x=y)])]  have[(?x  teeth)]  have[(?y  teeth)])]
~have[(platypus  teeth)]
mammal[(platypus)]
have[(humans  teeth)]]
*** Conclusion:
 [reptile[(platypus)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y [(mammal[(?x)]  mammal[(?y)]  [(~[(?x=y)])]  have[(?x  teeth)]  have[(?y  teeth)])]
~have[(platypus  teeth)]
mammal[(platypus)]
have[(humans  teeth)]]
*** Conclusion:
 [mammal[(humans)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [districtin[(xiufeng  guilin)]  districtin[(xiangshan  guilin)]  districtin[(diecai  guilin)]  districtin[(qixing  guilin)]  city[(guilin)]
~districtin[(yangshuo  guilin)]]
*** Conclusion:
 [*x [(districtin[(?xiangshan  x)]  districtin[(diecai  x)]  city[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [districtin[(xiufeng  guilin)]  districtin[(xiangshan  guilin)]  districtin[(diecai  guilin)]  districtin[(qixing  guilin)]  city[(guilin)]
~districtin[(yangshuo  guilin)]]
*** Conclusion:
 [districtin[(xiufeng  guilin)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [districtin[(xiufeng  guilin)]  districtin[(xiangshan  guilin)]  districtin[(diecai  guilin)]  districtin[(qixing  guilin)]  city[(guilin)]
~districtin[(yangshuo  guilin)]]
*** Conclusion:
 [districtin[(kowloon  hongkong)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [musicsupervisor[(jasonkramer)]  american[(jasonkramer)]
*x *y [(american[(?x)]  musicsupervisor[(?x)]  radiopersonality[(?x)]  [(~[(?x=y)])]  american[(?y)]  musicsupervisor[(?y)]  radiopersonality[(?y)])]
@every *x @every *y[([(hostshowon[(?x  y)]  publicradiostation[(?x)])]  radiopersonality[(?x)])]
radiopersonality[(joerogan)]
*x[(hostshowon[(jasonkramer  x)]  publicradiostation[(?x)])]]
*** Conclusion:
 [american[(joerogan)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [musicsupervisor[(jasonkramer)]  american[(jasonkramer)]
*x *y [(american[(?x)]  musicsupervisor[(?x)]  radiopersonality[(?x)]  [(~[(?x=y)])]  american[(?y)]  musicsupervisor[(?y)]  radiopersonality[(?y)])]
@every *x @every *y[([(hostshowon[(?x  y)]  publicradiostation[(?x)])]  radiopersonality[(?x)])]
radiopersonality[(joerogan)]
*x[(hostshowon[(jasonkramer  x)]  publicradiostation[(?x)])]]
*** Conclusion:
 [musicsupervisor[(jasonkramer)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [musicsupervisor[(jasonkramer)]  american[(jasonkramer)]
*x *y [(american[(?x)]  musicsupervisor[(?x)]  radiopersonality[(?x)]  [(~[(?x=y)])]  american[(?y)]  musicsupervisor[(?y)]  radiopersonality[(?y)])]
@every *x @every *y[([(hostshowon[(?x  y)]  publicradiostation[(?x)])]  radiopersonality[(?x)])]
radiopersonality[(joerogan)]
*x[(hostshowon[(jasonkramer  x)]  publicradiostation[(?x)])]]
*** Conclusion:
 [radiopersonality[(jasonkramer)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [village[(gasteren)]  province[(drenthe)]  in[(gasteren  drenthe)]
province[(drenthe)]  in[(drenthe  netherlands)]
@every *x [(city[(?x)]  ~village[(?x)])]
*x [(population[(?x  num155)]  village[(?x)]  in[(?x  drenthe)])]]
*** Conclusion:
 [village[(gasteren)]  in[(gasteren  netherlands)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [village[(gasteren)]  province[(drenthe)]  in[(gasteren  drenthe)]
province[(drenthe)]  in[(drenthe  netherlands)]
@every *x [(city[(?x)]  ~village[(?x)])]
*x [(population[(?x  num155)]  village[(?x)]  in[(?x  drenthe)])]]
*** Conclusion:
 [city[(gasteren)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [village[(gasteren)]  province[(drenthe)]  in[(gasteren  drenthe)]
province[(drenthe)]  in[(drenthe  netherlands)]
@every *x [(city[(?x)]  ~village[(?x)])]
*x [(population[(?x  num155)]  village[(?x)]  in[(?x  drenthe)])]]
*** Conclusion:
 [population[(gasteren  num155)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [movie[(endgame)]  released[(endgame  yr2006)]
setin[(endgame  washington)]
~[(filmedin[(endgame  washington)])]
*x*y[(filmedin[(?x  newyork)]  [(~[(?x=y)])]  filmedin[(?y  newyork)])]
directed[(andychang  endgame)]
from[(andychang  hongkong)]]
*** Conclusion:
 [filmedin[(endgame  newyork)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [movie[(endgame)]  released[(endgame  yr2006)]
setin[(endgame  washington)]
~[(filmedin[(endgame  washington)])]
*x*y[(filmedin[(?x  newyork)]  [(~[(?x=y)])]  filmedin[(?y  newyork)])]
directed[(andychang  endgame)]
from[(andychang  hongkong)]]
*** Conclusion:
 [@every *x [(~[(directed[(?x  endgame)]  from[(?x  hongkong)])])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [movie[(endgame)]  released[(endgame  yr2006)]
setin[(endgame  washington)]
~[(filmedin[(endgame  washington)])]
*x*y[(filmedin[(?x  newyork)]  [(~[(?x=y)])]  filmedin[(?y  newyork)])]
directed[(andychang  endgame)]
from[(andychang  hongkong)]]
*** Conclusion:
 [@every *x [(directed[(andychang  x)]  ~[(filmedin[(?x  washington)])])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [proposed[(justinkruger  naivecynicism)]  *y [(colleagueofjustinkruger[(?y)]  proposed[(?y  naivecynicism)])]
colleagues[(thomasgilovich  justinkruger)]
philosophyofmind[(naivecynicism)]]
*** Conclusion:
 [proposed[(thomasgilovich  naivecynicism)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [proposed[(justinkruger  naivecynicism)]  *y [(colleagueofjustinkruger[(?y)]  proposed[(?y  naivecynicism)])]
colleagues[(thomasgilovich  justinkruger)]
philosophyofmind[(naivecynicism)]]
*** Conclusion:
 [*x [(proposed[(justinkruger  x)]  philosophyofmind[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [proposed[(justinkruger  naivecynicism)]  *y [(colleagueofjustinkruger[(?y)]  proposed[(?y  naivecynicism)])]
colleagues[(thomasgilovich  justinkruger)]
philosophyofmind[(naivecynicism)]]
*** Conclusion:
 [*x [(workedon[(thomasgilovich  x)]  philosophyofmind[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [worldleadinglightingdesigner[(hughvanstone)]
from[(hughvanstone  unitedkingdom)]
*x[(greaterthan[(?x  num160)]  litproductions[(hughvanstone ?x)])]
*x[(hometown[(hughvanstone ?x)]  attendedschoolin[(hughvanstone ?x)])]]
*** Conclusion:
 [worldleadinglightingdesigner[(hughvanstone)]  from[(hughvanstone  unitedkingdom)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [worldleadinglightingdesigner[(hughvanstone)]
from[(hughvanstone  unitedkingdom)]
*x[(greaterthan[(?x  num160)]  litproductions[(hughvanstone ?x)])]
*x[(hometown[(hughvanstone ?x)]  attendedschoolin[(hughvanstone ?x)])]]
*** Conclusion:
 [*x[(greaterthan[(?x  num170)]  litproductions[(hughvanstone ?x)])]]
*** True Label:
 U
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [worldleadinglightingdesigner[(hughvanstone)]
from[(hughvanstone  unitedkingdom)]
*x[(greaterthan[(?x  num160)]  litproductions[(hughvanstone ?x)])]
*x[(hometown[(hughvanstone ?x)]  attendedschoolin[(hughvanstone ?x)])]]
*** Conclusion:
 [attendedschoolin[(hughvanstone  unitedstates)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(josephkmak  napa)]
professionalbaseballplayer[(josephkmak)]
@every *x [(professionalbaseballplayer[(?x)]  playinmlb[(?x)])]
@every *x [(bornin[(?x  california)]  nationality[(?x  american)])]
@every *x [(nationality[(?x  american)] ~nationality[(?x  german)])]]
*** Conclusion:
 [nationality[(josephkmak  german)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(josephkmak  napa)]
professionalbaseballplayer[(josephkmak)]
@every *x [(professionalbaseballplayer[(?x)]  playinmlb[(?x)])]
@every *x [(bornin[(?x  california)]  nationality[(?x  american)])]
@every *x [(nationality[(?x  american)] ~nationality[(?x  german)])]]
*** Conclusion:
 [playinmlb[(josephkmak)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(josephkmak  napa)]
professionalbaseballplayer[(josephkmak)]
@every *x [(professionalbaseballplayer[(?x)]  playinmlb[(?x)])]
@every *x [(bornin[(?x  california)]  nationality[(?x  american)])]
@every *x [(nationality[(?x  american)] ~nationality[(?x  german)])]]
*** Conclusion:
 [iscatcher[(josephkmak)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(rafanadal  mallorca)]
professionaltennisplayer[(rafanadal)]
highwinratio[(rafanadal)]
@every *x [([(professionaltennisplayer[(?x)]  inbig3[(?x)])]  highwinratio[(?x)])]]
*** Conclusion:
 ~[bornin[(rafanadal  mallorca)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(rafanadal  mallorca)]
professionaltennisplayer[(rafanadal)]
highwinratio[(rafanadal)]
@every *x [([(professionaltennisplayer[(?x)]  inbig3[(?x)])]  highwinratio[(?x)])]]
*** Conclusion:
 [inbig3[(rafanadal)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(rafanadal  mallorca)]
professionaltennisplayer[(rafanadal)]
highwinratio[(rafanadal)]
@every *x [([(professionaltennisplayer[(?x)]  inbig3[(?x)])]  highwinratio[(?x)])]]
*** Conclusion:
 [greatestofalltime[(rafanadal)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(doesolympicsport[(?x)]  goestoolympicgames[(?x)])]  olympian[(?x)])]
doesolympicsport[(carlosreyes)]
goestoolympicgames[(carlosreyes)]
welterweight[(carlosreyes)]
@every *x [(welterweight[(?x)]  ~ heavyweight[(?x)])]]
*** Conclusion:
 [olympian[(carlosreyes)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(doesolympicsport[(?x)]  goestoolympicgames[(?x)])]  olympian[(?x)])]
doesolympicsport[(carlosreyes)]
goestoolympicgames[(carlosreyes)]
welterweight[(carlosreyes)]
@every *x [(welterweight[(?x)]  ~ heavyweight[(?x)])]]
*** Conclusion:
 [heavyweight[(carlosreyes)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(doesolympicsport[(?x)]  goestoolympicgames[(?x)])]  olympian[(?x)])]
doesolympicsport[(carlosreyes)]
goestoolympicgames[(carlosreyes)]
welterweight[(carlosreyes)]
@every *x [(welterweight[(?x)]  ~ heavyweight[(?x)])]]
*** Conclusion:
 [wonolympicmedal[(carlosreyes)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [israpper[(tyga)]
@every *x @every *y [([(israpper[(?x)]  releasedalbum[(?x  y)])]  israpalbum[(?y)])]
releasedalbum[(tyga  welldone3)]
@every *x [(israpper[(?x)]  ~isoperasinger[(?x)])]]
*** Conclusion:
 [israpalbum[(welldone3)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [israpper[(tyga)]
@every *x @every *y [([(israpper[(?x)]  releasedalbum[(?x  y)])]  israpalbum[(?y)])]
releasedalbum[(tyga  welldone3)]
@every *x [(israpper[(?x)]  ~isoperasinger[(?x)])]]
*** Conclusion:
 [isoperasinger[(tyga)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [israpper[(tyga)]
@every *x @every *y [([(israpper[(?x)]  releasedalbum[(?x  y)])]  israpalbum[(?y)])]
releasedalbum[(tyga  welldone3)]
@every *x [(israpper[(?x)]  ~isoperasinger[(?x)])]]
*** Conclusion:
 [isworthlistening[(welldone3)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sevendistinctworks[(?x)]  heptalogy[(?x)])]
sevendistinctworks[(harrypotter)]
sevendistinctworks[(chroniclesofnarnia)]]
*** Conclusion:
 [heptalogy[(harrypotter)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sevendistinctworks[(?x)]  heptalogy[(?x)])]
sevendistinctworks[(harrypotter)]
sevendistinctworks[(chroniclesofnarnia)]]
*** Conclusion:
 ~[heptalogy[(chroniclesofnarnia)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sevendistinctworks[(?x)]  heptalogy[(?x)])]
sevendistinctworks[(harrypotter)]
sevendistinctworks[(chroniclesofnarnia)]]
*** Conclusion:
 [heptalogy[(lordofrings)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [museum[(metropolitanmuseumofart)]  in[(metropolitanmuseumofart  nyc)]
museum[(whitneymuseumofamericanart)]  in[(metropolitanmuseumofart  nyc)]
museum[(museumofmodernart)]  in[(museumofmodernart  nyc)]
include[(metropolitanmuseumofart  byzantineart)]  include[(metropolitanmuseumofart  islamicart)]
include[(whitneymuseumofamericanart  americanart)]]
*** Conclusion:
 [*x [(museum[(?x)]  in[(?x  nyc)]  include[(?x  byzantineart)]  include[(?x  islamicart)])]]
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [museum[(metropolitanmuseumofart)]  in[(metropolitanmuseumofart  nyc)]
museum[(whitneymuseumofamericanart)]  in[(metropolitanmuseumofart  nyc)]
museum[(museumofmodernart)]  in[(museumofmodernart  nyc)]
include[(metropolitanmuseumofart  byzantineart)]  include[(metropolitanmuseumofart  islamicart)]
include[(whitneymuseumofamericanart  americanart)]]
*** Conclusion:
 [*x [(museum[(?x)]  in[(?x  nyc)]  include[(?x  americanart)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [museum[(metropolitanmuseumofart)]  in[(metropolitanmuseumofart  nyc)]
museum[(whitneymuseumofamericanart)]  in[(metropolitanmuseumofart  nyc)]
museum[(museumofmodernart)]  in[(museumofmodernart  nyc)]
include[(metropolitanmuseumofart  byzantineart)]  include[(metropolitanmuseumofart  islamicart)]
include[(whitneymuseumofamericanart  americanart)]]
*** Conclusion:
 [*x [(museum[(?x)]  in[(?x  nyc)]  include[(?x  greekart)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [produce[(whitetown  yourwoman)]  onepersonband[(whitetown)]
peak[(yourwoman  uksingleschart)]
@every *x [([(*y[(peak[(?x  y)])])]  popular[(?x)])]
peak[(?yourwoman  iceland)]  peak[(?yourwoman  israel)]  peak[(?yourwoman  spain)]]
*** Conclusion:
 [popular[(yourwoman)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [produce[(whitetown  yourwoman)]  onepersonband[(whitetown)]
peak[(yourwoman  uksingleschart)]
@every *x [([(*y[(peak[(?x  y)])])]  popular[(?x)])]
peak[(?yourwoman  iceland)]  peak[(?yourwoman  israel)]  peak[(?yourwoman  spain)]]
*** Conclusion:
 [@every *x [(produce[(whitetown  x)]  ~popular[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [produce[(whitetown  yourwoman)]  onepersonband[(whitetown)]
peak[(yourwoman  uksingleschart)]
@every *x [([(*y[(peak[(?x  y)])])]  popular[(?x)])]
peak[(?yourwoman  iceland)]  peak[(?yourwoman  israel)]  peak[(?yourwoman  spain)]]
*** Conclusion:
 [successful[(whitetown)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(runfar[(?x)]  usemap[(?x)])]  orienteer[(?x)])]
@every *x [(fit[(?x)]  runfar[(?x)])]
@every *x [(sensedirection[(?x)]  usemap[(?x)])]
@every *x [(militaryofficer[(?x)]  fit[(?x)])]
militaryofficer[(hailee)]  sensedirection[(hailee)]
~militaryofficer[(karl)]  usemap[(karl)]]
*** Conclusion:
 [orienteer[(hailee)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(runfar[(?x)]  usemap[(?x)])]  orienteer[(?x)])]
@every *x [(fit[(?x)]  runfar[(?x)])]
@every *x [(sensedirection[(?x)]  usemap[(?x)])]
@every *x [(militaryofficer[(?x)]  fit[(?x)])]
militaryofficer[(hailee)]  sensedirection[(hailee)]
~militaryofficer[(karl)]  usemap[(karl)]]
*** Conclusion:
 ~[orienteer[(karl)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [talentedpoet[(lorca)]  support[(lorca  populists)]
@every *x [(support[(?x  populists)]  opposed[(nationalists  x)])]
@every *x [(talentedpoet[(?x)]  popular[(?x)])]
@every *x [([(opposed[(nationalists  x)]  popular[(?x)])]  killed[(nationalists  x)])]
support[(daniel  populists)]  [(~popular[(daniel)])]]
*** Conclusion:
 ~[killed[(nationalists  daniel)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [talentedpoet[(lorca)]  support[(lorca  populists)]
@every *x [(support[(?x  populists)]  opposed[(nationalists  x)])]
@every *x [(talentedpoet[(?x)]  popular[(?x)])]
@every *x [([(opposed[(nationalists  x)]  popular[(?x)])]  killed[(nationalists  x)])]
support[(daniel  populists)]  [(~popular[(daniel)])]]
*** Conclusion:
 [killed[(nationalists  lorca)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(james)]  lawyer[(james)]
whig[(james)]  politician[(james)]  satinhouseofcommons[(james)]
@every *x [(british[(?x)]  european[(?x)])]
@every *x [(lawyer[(?x)]  familiarwithlaws[(?x)])]
*x *y [(whig[(?x)]  speakfrench[(?x)])]  [(~[(?x=y)])]  [(whig[(?y)]  speakfrench[(?y)])]]
*** Conclusion:
 [@every *x [(lawyer[(?x)]  ~satinhouseofcommons[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(james)]  lawyer[(james)]
whig[(james)]  politician[(james)]  satinhouseofcommons[(james)]
@every *x [(british[(?x)]  european[(?x)])]
@every *x [(lawyer[(?x)]  familiarwithlaws[(?x)])]
*x *y [(whig[(?x)]  speakfrench[(?x)])]  [(~[(?x=y)])]  [(whig[(?y)]  speakfrench[(?y)])]]
*** Conclusion:
 [*x [(european[(?x)]  familiarwithlaws[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(james)]  lawyer[(james)]
whig[(james)]  politician[(james)]  satinhouseofcommons[(james)]
@every *x [(british[(?x)]  european[(?x)])]
@every *x [(lawyer[(?x)]  familiarwithlaws[(?x)])]
*x *y [(whig[(?x)]  speakfrench[(?x)])]  [(~[(?x=y)])]  [(whig[(?y)]  speakfrench[(?y)])]]
*** Conclusion:
 [speakfrench[(james)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(imaginedragon)]  rockband[(imaginedragon)]
leadsinger[(imaginedragon  dan)]
songwriter[(dan)]
@every *x @every *y [(leadsinger[(?x  y)]  singer[(?y)])]
@every *x [(singer[(?x)]  musician[(?x)])]
popularsingle[(imaginedragon  demons)]
*x *y [(popularsingle[(imaginedragon  x)]  billboardhot100[(?x)])]  [(~[(?x=y)])]  [(popularsingle[(imaginedragon  y)]  billboardhot100[(?y)])]]
*** Conclusion:
 [*x *y [(rockband[(?x)]  leadsinger[(?x  y)]  songwriter[(?y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(imaginedragon)]  rockband[(imaginedragon)]
leadsinger[(imaginedragon  dan)]
songwriter[(dan)]
@every *x @every *y [(leadsinger[(?x  y)]  singer[(?y)])]
@every *x [(singer[(?x)]  musician[(?x)])]
popularsingle[(imaginedragon  demons)]
*x *y [(popularsingle[(imaginedragon  x)]  billboardhot100[(?x)])]  [(~[(?x=y)])]  [(popularsingle[(imaginedragon  y)]  billboardhot100[(?y)])]]
*** Conclusion:
 ~[musician[(dan)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(imaginedragon)]  rockband[(imaginedragon)]
leadsinger[(imaginedragon  dan)]
songwriter[(dan)]
@every *x @every *y [(leadsinger[(?x  y)]  singer[(?y)])]
@every *x [(singer[(?x)]  musician[(?x)])]
popularsingle[(imaginedragon  demons)]
*x *y [(popularsingle[(imaginedragon  x)]  billboardhot100[(?x)])]  [(~[(?x=y)])]  [(popularsingle[(imaginedragon  y)]  billboardhot100[(?y)])]]
*** Conclusion:
 [billboardhot100[(demons)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(andrewwilson)]  historian[(andrewwilson)]  politicalscientist[(andrewwilson)]
@every *x [(locatedin[(?x  easterneurope)] specializein[(andrewwilson  x)])]
locatedin[(poland  easterneurope)]
bornin[(andrewwilson  britain)]
~locatedin[(britain  easterneurope)]]
*** Conclusion:
 [bornin[(andrewwilson  easterneurope)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(andrewwilson)]  historian[(andrewwilson)]  politicalscientist[(andrewwilson)]
@every *x [(locatedin[(?x  easterneurope)] specializein[(andrewwilson  x)])]
locatedin[(poland  easterneurope)]
bornin[(andrewwilson  britain)]
~locatedin[(britain  easterneurope)]]
*** Conclusion:
 [specializein[(andrewwilson  poland)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(andrewwilson)]  historian[(andrewwilson)]  politicalscientist[(andrewwilson)]
@every *x [(locatedin[(?x  easterneurope)] specializein[(andrewwilson  x)])]
locatedin[(poland  easterneurope)]
bornin[(andrewwilson  britain)]
~locatedin[(britain  easterneurope)]]
*** Conclusion:
 [specializein[(andrewwilson  britain)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(andrewwilson)]  historian[(andrewwilson)]  politicalscientist[(andrewwilson)]
@every *x [(locatedin[(?x  easterneurope)] specializein[(andrewwilson  x)])]
locatedin[(poland  easterneurope)]
bornin[(andrewwilson  britain)]
~locatedin[(britain  easterneurope)]]
*** Conclusion:
 [@every *x [(british[(?x)]  ~politicalscientist[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [in[(sr287  alabama)]
in[(alabama  unitedstates)]
intersect[(us31  sr287)]
intersect[(cr47  sr287)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]]
*** Conclusion:
 [in[(us31  alabama)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [in[(sr287  alabama)]
in[(alabama  unitedstates)]
intersect[(us31  sr287)]
intersect[(cr47  sr287)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]]
*** Conclusion:
 ~[in[(cr47  alabama)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [in[(sr287  alabama)]
in[(alabama  unitedstates)]
intersect[(us31  sr287)]
intersect[(cr47  sr287)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]]
*** Conclusion:
 [in[(sr287  unitedstates)]]
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(breedingback[(?x)]  [(artificialselection[(?x)]  deliberateselectivebreedingofdomesticanimals[(?x)])])]
*x *y [(heckcattle[(?x)]  breedingback[(?x)]  auroch[(?y)]  resemble[(?x  y)])]
@every *x [(heckcattle[(?x)]  animal[(?x)])]
@every *x [(auroch[(?x)]  animal[(?x)])]
*x *y [(animal[(?x)]  animal[(?y)]  [(~[(?x=y)])]  breedingback[(?x)]  breedingback[(?y)]  [(*w[(dead[(?w)]  resemble[(?x  w)])]  [(~[(?w=z)])]  [(*z[(dead[(?z)]  resemble[(?y  z)])])])]]
*** Conclusion:
 [*x *y[(heckcattle[(?x)]  artificialselection[(?x)]  [(~[(?x=y)])]  heckcattle[(?y)]  artificialselection[(?y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(breedingback[(?x)]  [(artificialselection[(?x)]  deliberateselectivebreedingofdomesticanimals[(?x)])])]
*x *y [(heckcattle[(?x)]  breedingback[(?x)]  auroch[(?y)]  resemble[(?x  y)])]
@every *x [(heckcattle[(?x)]  animal[(?x)])]
@every *x [(auroch[(?x)]  animal[(?x)])]
*x *y [(animal[(?x)]  animal[(?y)]  [(~[(?x=y)])]  breedingback[(?x)]  breedingback[(?y)]  [(*w[(dead[(?w)]  resemble[(?x  w)])]  [(~[(?w=z)])]  [(*z[(dead[(?z)]  resemble[(?y  z)])])])]]
*** Conclusion:
 [@every *x [(auroch[(?x)]  dead[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(controlledsubstances[(?x)]  drugs[(?x)])]
*x *y [(controlledsubstances[(?x)]  controlledsubstances[(?y)]  [(~[(?x=y)])]  beneficial[(?x)]  harmful[(?y)])]
@every *x @every *y [([(child[(?x)]  controlledsubstances[(?y)]  exposedto[(?x  y)])]  inchemicalendangerment[(?x)])]
@every *x [(inchemicalendangerment[(?x)]  harmful[(?x)])]
passedin[(controlledsubstancesact  yr1971)]  act[(controlledsubstancesact)]
*x *y[(act[(?x)]  preventsharm[(?x)]  [(~[(?x=y)])]  act[(?y)]  preventsharm[(?y)])]]
*** Conclusion:
 [preventsharm[(controlledsubstancesact)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(controlledsubstances[(?x)]  drugs[(?x)])]
*x *y [(controlledsubstances[(?x)]  controlledsubstances[(?y)]  [(~[(?x=y)])]  beneficial[(?x)]  harmful[(?y)])]
@every *x @every *y [([(child[(?x)]  controlledsubstances[(?y)]  exposedto[(?x  y)])]  inchemicalendangerment[(?x)])]
@every *x [(inchemicalendangerment[(?x)]  harmful[(?x)])]
passedin[(controlledsubstancesact  yr1971)]  act[(controlledsubstancesact)]
*x *y[(act[(?x)]  preventsharm[(?x)]  [(~[(?x=y)])]  act[(?y)]  preventsharm[(?y)])]]
*** Conclusion:
 [*x *y[(drugs[(?x)]  beneficial[(?x)]  [(~[(?x=y)])]  drugs[(?y)]  beneficial[(?y)])]]
*** True Label:
 T
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(controlledsubstances[(?x)]  drugs[(?x)])]
*x *y [(controlledsubstances[(?x)]  controlledsubstances[(?y)]  [(~[(?x=y)])]  beneficial[(?x)]  harmful[(?y)])]
@every *x @every *y [([(child[(?x)]  controlledsubstances[(?y)]  exposedto[(?x  y)])]  inchemicalendangerment[(?x)])]
@every *x [(inchemicalendangerment[(?x)]  harmful[(?x)])]
passedin[(controlledsubstancesact  yr1971)]  act[(controlledsubstancesact)]
*x *y[(act[(?x)]  preventsharm[(?x)]  [(~[(?x=y)])]  act[(?y)]  preventsharm[(?y)])]]
*** Conclusion:
 [@every *x [([(child[(?x)]  inchemicalendangerment[(?x)])]  harmful[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [author[(douglasadams)]  authored[(douglasadams  thesalmonofdoubt)]  book[(thesalmonofdoubt)]
about[(thesalmonofdoubt  lifeexperience)]  about[(thesalmonofdoubt  technology)]
@every *x [(author[(?x)]  writer[(?x)])]
@every *x [(writer[(?x)]  create[(?x  innovativeidea)])]
*x *y [(contain[(?x  innovativeidea)]  about[(?x  technology)]  [(~[(?x=y)])]  [(contain[(?y  innovativeidea)]  about[(?y  technology)])])]]
*** Conclusion:
 [writer[(douglasadams)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [author[(douglasadams)]  authored[(douglasadams  thesalmonofdoubt)]  book[(thesalmonofdoubt)]
about[(thesalmonofdoubt  lifeexperience)]  about[(thesalmonofdoubt  technology)]
@every *x [(author[(?x)]  writer[(?x)])]
@every *x [(writer[(?x)]  create[(?x  innovativeidea)])]
*x *y [(contain[(?x  innovativeidea)]  about[(?x  technology)]  [(~[(?x=y)])]  [(contain[(?y  innovativeidea)]  about[(?y  technology)])])]]
*** Conclusion:
 [create[(douglasadams  innovativeidea)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [author[(douglasadams)]  authored[(douglasadams  thesalmonofdoubt)]  book[(thesalmonofdoubt)]
about[(thesalmonofdoubt  lifeexperience)]  about[(thesalmonofdoubt  technology)]
@every *x [(author[(?x)]  writer[(?x)])]
@every *x [(writer[(?x)]  create[(?x  innovativeidea)])]
*x *y [(contain[(?x  innovativeidea)]  about[(?x  technology)]  [(~[(?x=y)])]  [(contain[(?y  innovativeidea)]  about[(?y  technology)])])]]
*** Conclusion:
 ~[contain[(thesalmonofdoubt  innovativeidea)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(quincymcduffie)]  professional[(quincymcduffie)]  widereciever[(quincymcduffie)]  playsin[(quincymcduffie  cfl)]
@every *x [([(*y[(cancatch[(?x  y)]  ball[(?y)])])]  goodwidereceiver[(?x)])]
*x *y [(football[(?x)]  cancatch[(quincymcduffie  x)])]  [(~[(?x=y)]  [(football[(?y)]  cancatch[(quincymcduffie  y)])]
@every *x [(goodwidereceiver[(?x)]  professional[(?x)])]
@every *x [(goodwidereceiver[(?x)]  [(cancatchwith[(?x  lefthand)]  cancatchwith[(?x  righthand)])])]
@every *x [(football[(?x)]  ball[(?x)])]]
*** Conclusion:
 [goodwidereceiver[(quincymcduffie)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(quincymcduffie)]  professional[(quincymcduffie)]  widereciever[(quincymcduffie)]  playsin[(quincymcduffie  cfl)]
@every *x [([(*y[(cancatch[(?x  y)]  ball[(?y)])])]  goodwidereceiver[(?x)])]
*x *y [(football[(?x)]  cancatch[(quincymcduffie  x)])]  [(~[(?x=y)]  [(football[(?y)]  cancatch[(quincymcduffie  y)])]
@every *x [(goodwidereceiver[(?x)]  professional[(?x)])]
@every *x [(goodwidereceiver[(?x)]  [(cancatchwith[(?x  lefthand)]  cancatchwith[(?x  righthand)])])]
@every *x [(football[(?x)]  ball[(?x)])]]
*** Conclusion:
 [@every *x [(ball[(?x)]  cancatch[(quincymcduffie  x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(quincymcduffie)]  professional[(quincymcduffie)]  widereciever[(quincymcduffie)]  playsin[(quincymcduffie  cfl)]
@every *x [([(*y[(cancatch[(?x  y)]  ball[(?y)])])]  goodwidereceiver[(?x)])]
*x *y [(football[(?x)]  cancatch[(quincymcduffie  x)])]  [(~[(?x=y)]  [(football[(?y)]  cancatch[(quincymcduffie  y)])]
@every *x [(goodwidereceiver[(?x)]  professional[(?x)])]
@every *x [(goodwidereceiver[(?x)]  [(cancatchwith[(?x  lefthand)]  cancatchwith[(?x  righthand)])])]
@every *x [(football[(?x)]  ball[(?x)])]]
*** Conclusion:
 [@every *x [([(professional[(?x)]  widereciever[(?x)])]  good[(?x  catchingballs)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(topcover[(?x)]  [(*y[(roof[(?y)])])]
@every *x [(roof[(?x)]  [(protect[(?x)]  blocksunlight[(?x)])])]
*x *y  [(roof[(?x)]  concrete[(?x)])]  [(~[(?x=y)]  roof[(?y)]  concrete[(?y)])]
*x *y  [(roof[(?x)]  seagrass[(?x)])]  [(~[(?x=y)]  roof[(?y)]  seagrass[(?y)])]
@every *x @every *y [([(concrete[(?x)]  seagrass[(?y)])]  stronger[(?x  y)])]]
*** Conclusion:
 [@every *x [(~roof[(?x)]  ~protect[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(topcover[(?x)]  [(*y[(roof[(?y)])])]
@every *x [(roof[(?x)]  [(protect[(?x)]  blocksunlight[(?x)])])]
*x *y  [(roof[(?x)]  concrete[(?x)])]  [(~[(?x=y)]  roof[(?y)]  concrete[(?y)])]
*x *y  [(roof[(?x)]  seagrass[(?x)])]  [(~[(?x=y)]  roof[(?y)]  seagrass[(?y)])]
@every *x @every *y [([(concrete[(?x)]  seagrass[(?y)])]  stronger[(?x  y)])]]
*** Conclusion:
 [@every *x @every *y [([(roof[(?x)]  concrete[(?x)]  roof[(?y)]  seagrass[(?y)])]  stronger[(?x  y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(topcover[(?x)]  [(*y[(roof[(?y)])])]
@every *x [(roof[(?x)]  [(protect[(?x)]  blocksunlight[(?x)])])]
*x *y  [(roof[(?x)]  concrete[(?x)])]  [(~[(?x=y)]  roof[(?y)]  concrete[(?y)])]
*x *y  [(roof[(?x)]  seagrass[(?x)])]  [(~[(?x=y)]  roof[(?y)]  seagrass[(?y)])]
@every *x @every *y [([(concrete[(?x)]  seagrass[(?y)])]  stronger[(?x  y)])]]
*** Conclusion:
 [@every *x [([(roof[(?x)]  concrete[(?x)])]  [(~blocksunlight[(?x)])])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [sportingevent[(olympics)]
lastsummerolympics[(tokyo)]
mostmedals[(unitedstates  tokyo)]]
*** Conclusion:
 [sportingevent[(champs)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [sportingevent[(olympics)]
lastsummerolympics[(tokyo)]
mostmedals[(unitedstates  tokyo)]]
*** Conclusion:
 ~[lastsummerolympics[(tokyo)]]
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [sportingevent[(olympics)]
lastsummerolympics[(tokyo)]
mostmedals[(unitedstates  tokyo)]]
*** Conclusion:
 [*x [(lastsummerolympics[(?x)]  mostmedals[(unitedstates  x)])]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [producedby[(luminaapv  chevrolet)]
producedby[(astro  chevrolet)]  van[(astro)]
@every *x [(vehicle[(?x)]  producedby[(?x  chevrolet)]  inthisbatch[(?x)]  [(car[(?x)]  van[(?x)])])]]
*** Conclusion:
 [van[(luminaapv)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [producedby[(luminaapv  chevrolet)]
producedby[(astro  chevrolet)]  van[(astro)]
@every *x [(vehicle[(?x)]  producedby[(?x  chevrolet)]  inthisbatch[(?x)]  [(car[(?x)]  van[(?x)])])]]
*** Conclusion:
 [car[(luminaapv)]  van[(luminaapv)]]
*** True Label:
 T
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [producedby[(luminaapv  chevrolet)]
producedby[(astro  chevrolet)]  van[(astro)]
@every *x [(vehicle[(?x)]  producedby[(?x  chevrolet)]  inthisbatch[(?x)]  [(car[(?x)]  van[(?x)])])]]
*** Conclusion:
 [van[(astro)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [producedby[(luminaapv  chevrolet)]
producedby[(astro  chevrolet)]  van[(astro)]
@every *x [(vehicle[(?x)]  producedby[(?x  chevrolet)]  inthisbatch[(?x)]  [(car[(?x)]  van[(?x)])])]]
*** Conclusion:
 [car[(astro)]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pasifikanewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(pasifikanewzealanders[(?y)]  pasifikanewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(asiannewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(asiannewzealanders[(?y)]  asiannewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(pasifikanewzealanders[(?x)]  ~asiannewzealanders[(?x)])]
@every *x [(pasifikanewzealanders[(?x)]  speaksamoan[(?x)])]
pasifikanewzealanders[(joe)]
speaksamoan[(amy)]]
*** Conclusion:
 [pasifikanewzealanders[(amy)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pasifikanewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(pasifikanewzealanders[(?y)]  pasifikanewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(asiannewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(asiannewzealanders[(?y)]  asiannewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(pasifikanewzealanders[(?x)]  ~asiannewzealanders[(?x)])]
@every *x [(pasifikanewzealanders[(?x)]  speaksamoan[(?x)])]
pasifikanewzealanders[(joe)]
speaksamoan[(amy)]]
*** Conclusion:
 [asiannewzealanders[(amy)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pasifikanewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(pasifikanewzealanders[(?y)]  pasifikanewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(asiannewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(asiannewzealanders[(?y)]  asiannewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(pasifikanewzealanders[(?x)]  ~asiannewzealanders[(?x)])]
@every *x [(pasifikanewzealanders[(?x)]  speaksamoan[(?x)])]
pasifikanewzealanders[(joe)]
speaksamoan[(amy)]]
*** Conclusion:
 [asiannewzealanders[(joe)]]
*** True Label:
 F
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pasifikanewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(pasifikanewzealanders[(?y)]  pasifikanewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(asiannewzealanders[(?x)]  newzealanders[(?x)])]  *y*z [(asiannewzealanders[(?y)]  asiannewzealanders[(?z)]  differentethnicgroups[(?y ?z)])]
@every *x [(pasifikanewzealanders[(?x)]  ~asiannewzealanders[(?x)])]
@every *x [(pasifikanewzealanders[(?x)]  speaksamoan[(?x)])]
pasifikanewzealanders[(joe)]
speaksamoan[(amy)]]
*** Conclusion:
 [speaksamoan[(joe)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(roundel[(?x)]  [(rounded[(?x)]  artilleryfortification[(?x)])])]
@every *x @every *y [([(roundel[(?x)]  adjacentwalls[(?x ?y)])]  ~higher[(?x  y)])]
@every *x [(artilleryfortification[(?x)]  deploycannons[(?x)])]
@every *x @every *y [([(roundel[(?x)]  artilleryfortification[(?y)])]  older[(?x  y)])]
@every *x [(batterytower[(?x)]  artilleryfortification[(?x)])]]
*** Conclusion:
 [@every *x [(batterytower[(?x)]  deploycannons[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(roundel[(?x)]  [(rounded[(?x)]  artilleryfortification[(?x)])])]
@every *x @every *y [([(roundel[(?x)]  adjacentwalls[(?x ?y)])]  ~higher[(?x  y)])]
@every *x [(artilleryfortification[(?x)]  deploycannons[(?x)])]
@every *x @every *y [([(roundel[(?x)]  artilleryfortification[(?y)])]  older[(?x  y)])]
@every *x [(batterytower[(?x)]  artilleryfortification[(?x)])]]
*** Conclusion:
 [@every *x @every *y [([(roundel[(?x)]  batterytower[(?y)])]  older[(?x  y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(roundel[(?x)]  [(rounded[(?x)]  artilleryfortification[(?x)])])]
@every *x @every *y [([(roundel[(?x)]  adjacentwalls[(?x ?y)])]  ~higher[(?x  y)])]
@every *x [(artilleryfortification[(?x)]  deploycannons[(?x)])]
@every *x @every *y [([(roundel[(?x)]  artilleryfortification[(?y)])]  older[(?x  y)])]
@every *x [(batterytower[(?x)]  artilleryfortification[(?x)])]]
*** Conclusion:
 [@every *x @every *y [([(batterytower[(?x)]  adjacentwall[(?x ?y)])]  higher[(?x  y)])]]
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(roundel[(?x)]  [(rounded[(?x)]  artilleryfortification[(?x)])])]
@every *x @every *y [([(roundel[(?x)]  adjacentwalls[(?x ?y)])]  ~higher[(?x  y)])]
@every *x [(artilleryfortification[(?x)]  deploycannons[(?x)])]
@every *x @every *y [([(roundel[(?x)]  artilleryfortification[(?y)])]  older[(?x  y)])]
@every *x [(batterytower[(?x)]  artilleryfortification[(?x)])]]
*** Conclusion:
 [@every *x [(roundel[(?x)]  deploycannons[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 U

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(businessperson[(?x)]  *y[(company[(?y)]  ownership[(?x  y)])])]
@every *x @every *y [(ownership[(?x  y)]  makemoney[(?x  y)])]
@every *x [(businessperson[(?x)]  [(businessman[(?x)]  businesswoman[(?x)])])]
*x [(businessperson[(?x)]  extrovert[(?x)])]
@every *x [(businessperson[(?x)]  handlemoney[(?x)])]
businessperson[(bob)]  ownership[(bob  microsoft)]]
*** Conclusion:
 [extrovert[(bob)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(businessperson[(?x)]  *y[(company[(?y)]  ownership[(?x  y)])])]
@every *x @every *y [(ownership[(?x  y)]  makemoney[(?x  y)])]
@every *x [(businessperson[(?x)]  [(businessman[(?x)]  businesswoman[(?x)])])]
*x [(businessperson[(?x)]  extrovert[(?x)])]
@every *x [(businessperson[(?x)]  handlemoney[(?x)])]
businessperson[(bob)]  ownership[(bob  microsoft)]]
*** Conclusion:
 [handlemoney[(bob)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(businessperson[(?x)]  *y[(company[(?y)]  ownership[(?x  y)])])]
@every *x @every *y [(ownership[(?x  y)]  makemoney[(?x  y)])]
@every *x [(businessperson[(?x)]  [(businessman[(?x)]  businesswoman[(?x)])])]
*x [(businessperson[(?x)]  extrovert[(?x)])]
@every *x [(businessperson[(?x)]  handlemoney[(?x)])]
businessperson[(bob)]  ownership[(bob  microsoft)]]
*** Conclusion:
 [businessperson[(bob)]  makemoney[(bob  microsoft)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(leader[(?x)]  havepower[(?x)])]
@every *x [(leader[(?x)]  [(king[(?x)]  queen[(?x)])])]
@every *x [(queen[(?x)]  female[(?x)])]
@every *x [(king[(?x)]  male[(?x)])]
queen[(elizabeth)]
leader[(elizabeth)]]
*** Conclusion:
 [king[(elizabeth)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(leader[(?x)]  havepower[(?x)])]
@every *x [(leader[(?x)]  [(king[(?x)]  queen[(?x)])])]
@every *x [(queen[(?x)]  female[(?x)])]
@every *x [(king[(?x)]  male[(?x)])]
queen[(elizabeth)]
leader[(elizabeth)]]
*** Conclusion:
 [havepower[(elizabeth)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(leader[(?x)]  havepower[(?x)])]
@every *x [(leader[(?x)]  [(king[(?x)]  queen[(?x)])])]
@every *x [(queen[(?x)]  female[(?x)])]
@every *x [(king[(?x)]  male[(?x)])]
queen[(elizabeth)]
leader[(elizabeth)]]
*** Conclusion:
 [leader[(elizabeth)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pet[(?x)]  animal[(?x)])]
@every *x [(pet[(?x)]  [(dog[(?x)]  cat[(?x)])])]
@every *x @every *y [([(pet[(?y)]  ownedby[(?x ?y)])]  cares[(?x  y)])]
*x *y [(cat[(?x)]  naughty[(?x)]  [(~[(?x=y)])]  dog[(?y)]  naughty[(?y)])]
@every *x @every *y [([(pet[(?x)]  naughty[(?x)]  ownedby[(?x ?y)])]  ~liked[(?x  y)])]
ownedby[(leo  charlie)]  pet[(leo)]  dog[(leo)]  naughty[(leo)]]
*** Conclusion:
 [animal[(leo)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pet[(?x)]  animal[(?x)])]
@every *x [(pet[(?x)]  [(dog[(?x)]  cat[(?x)])])]
@every *x @every *y [([(pet[(?y)]  ownedby[(?x ?y)])]  cares[(?x  y)])]
*x *y [(cat[(?x)]  naughty[(?x)]  [(~[(?x=y)])]  dog[(?y)]  naughty[(?y)])]
@every *x @every *y [([(pet[(?x)]  naughty[(?x)]  ownedby[(?x ?y)])]  ~liked[(?x  y)])]
ownedby[(leo  charlie)]  pet[(leo)]  dog[(leo)]  naughty[(leo)]]
*** Conclusion:
 ~[liked[(leo  charlie)]  ~cares[(charlie  leo)]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(pet[(?x)]  animal[(?x)])]
@every *x [(pet[(?x)]  [(dog[(?x)]  cat[(?x)])])]
@every *x @every *y [([(pet[(?y)]  ownedby[(?x ?y)])]  cares[(?x  y)])]
*x *y [(cat[(?x)]  naughty[(?x)]  [(~[(?x=y)])]  dog[(?y)]  naughty[(?y)])]
@every *x @every *y [([(pet[(?x)]  naughty[(?x)]  ownedby[(?x ?y)])]  ~liked[(?x  y)])]
ownedby[(leo  charlie)]  pet[(leo)]  dog[(leo)]  naughty[(leo)]]
*** Conclusion:
 [@every *x [(dog[(?x)]  ~naughty[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(book[(?x)]  contains[(?x  knowledge)])]
@every *x @every *y [(readbook[(?x  y)]  gains[(?x  knowledge)])]
@every *x [(gains[(?x  knowledge)]  smarter[(?x)])]
readbook[(harry  walden)]  book[(walden)]]
*** Conclusion:
 [gains[(harry  knowledge)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(book[(?x)]  contains[(?x  knowledge)])]
@every *x @every *y [(readbook[(?x  y)]  gains[(?x  knowledge)])]
@every *x [(gains[(?x  knowledge)]  smarter[(?x)])]
readbook[(harry  walden)]  book[(walden)]]
*** Conclusion:
 [smarter[(harry)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(book[(?x)]  contains[(?x  knowledge)])]
@every *x @every *y [(readbook[(?x  y)]  gains[(?x  knowledge)])]
@every *x [(gains[(?x  knowledge)]  smarter[(?x)])]
readbook[(harry  walden)]  book[(walden)]]
*** Conclusion:
 [@every *x [(smarter[(?x)]  gainknowledge[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y  [(labmonitor[(?x)]  aoc[(?x)]  [(~[(?x=y)])]  labmonitor[(?y)]  aoc[(?y)])]
@every *x [(labmonitor[(?x)]  discounted[(?x)])]
@every *x [(discounted[(?x)]  a1080p[(?x)])]
@every *x [(a1080p[(?x)]  ~typec[(?x)])]
labmonitor[(lg-34)]]
*** Conclusion:
 [aoc[(lg-34)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y  [(labmonitor[(?x)]  aoc[(?x)]  [(~[(?x=y)])]  labmonitor[(?y)]  aoc[(?y)])]
@every *x [(labmonitor[(?x)]  discounted[(?x)])]
@every *x [(discounted[(?x)]  a1080p[(?x)])]
@every *x [(a1080p[(?x)]  ~typec[(?x)])]
labmonitor[(lg-34)]]
*** Conclusion:
 ~[typec[(lg-34)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [*x *y  [(labmonitor[(?x)]  aoc[(?x)]  [(~[(?x=y)])]  labmonitor[(?y)]  aoc[(?y)])]
@every *x [(labmonitor[(?x)]  discounted[(?x)])]
@every *x [(discounted[(?x)]  a1080p[(?x)])]
@every *x [(a1080p[(?x)]  ~typec[(?x)])]
labmonitor[(lg-34)]]
*** Conclusion:
 ~[a1080p[(lg-34)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(in[(?x  newhaven)]  ~high[(?x)])]
@every *x [(yalehousing[(?x)]  in[(?x  newhaven)])]
@every *x [(in[(?x  manhattan)]  high[(?x)])]
@every *x [(bloomberg[(?x)]  in[(?x  manhattan)])]
@every *x [(bloomberglogo[(?x)]  bloomberg[(?x)])]
yalehousing[(tower-a)]
bloomberglogo[(tower-b)]]
*** Conclusion:
 ~[high[(tower-a)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(in[(?x  newhaven)]  ~high[(?x)])]
@every *x [(yalehousing[(?x)]  in[(?x  newhaven)])]
@every *x [(in[(?x  manhattan)]  high[(?x)])]
@every *x [(bloomberg[(?x)]  in[(?x  manhattan)])]
@every *x [(bloomberglogo[(?x)]  bloomberg[(?x)])]
yalehousing[(tower-a)]
bloomberglogo[(tower-b)]]
*** Conclusion:
 ~[in[(tower-b  manhattan)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(in[(?x  newhaven)]  ~high[(?x)])]
@every *x [(yalehousing[(?x)]  in[(?x  newhaven)])]
@every *x [(in[(?x  manhattan)]  high[(?x)])]
@every *x [(bloomberg[(?x)]  in[(?x  manhattan)])]
@every *x [(bloomberglogo[(?x)]  bloomberg[(?x)])]
yalehousing[(tower-a)]
bloomberglogo[(tower-b)]]
*** Conclusion:
 ~[in[(tower-b  newhaven)]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(coffee[(?x)]  soldin[(?x  walmart)])]  ~from[(?x  france)])]
@every *x [([(coffee[(?x)]  favoredby[(?x  localresidents)])]  from[(?x  colombia)])]
@every *x [([(coffee[(?x)]  highprice[(?x)])]  favoredbylocalresidents[(?x)])]
coffee[(civetcoffee)]  ~from[(colombia)]
expensive[(jamaicablue)]  coffee[(jamaicablue)]
@every *x [([(expensive[(?x)]  coffee[(?x)])]  highprice[(?x)])]]
*** Conclusion:
 [from[(civetcoffee  france)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(coffee[(?x)]  soldin[(?x  walmart)])]  ~from[(?x  france)])]
@every *x [([(coffee[(?x)]  favoredby[(?x  localresidents)])]  from[(?x  colombia)])]
@every *x [([(coffee[(?x)]  highprice[(?x)])]  favoredbylocalresidents[(?x)])]
coffee[(civetcoffee)]  ~from[(colombia)]
expensive[(jamaicablue)]  coffee[(jamaicablue)]
@every *x [([(expensive[(?x)]  coffee[(?x)])]  highprice[(?x)])]]
*** Conclusion:
 [from[(jamaicablue  colombia)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(coffee[(?x)]  soldin[(?x  walmart)])]  ~from[(?x  france)])]
@every *x [([(coffee[(?x)]  favoredby[(?x  localresidents)])]  from[(?x  colombia)])]
@every *x [([(coffee[(?x)]  highprice[(?x)])]  favoredbylocalresidents[(?x)])]
coffee[(civetcoffee)]  ~from[(colombia)]
expensive[(jamaicablue)]  coffee[(jamaicablue)]
@every *x [([(expensive[(?x)]  coffee[(?x)])]  highprice[(?x)])]]
*** Conclusion:
 [favoredby[(jamaicablue  localresidents)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(ownedby[(?x  company)]  connectedto[(?x  googlehome)])]
@every *x [(ownedby[(?x  employee)]  connectedto[(?x  companywifi)])]
@every *x [(connectedto[(?x  googlehome)]  controlledby[(?x  managers)])]
@every *x [(connectedto[(?x  companywifi)]  easytooperate[(?x)])]
ownedby[(modelxx  employee)]]
*** Conclusion:
 [easytooperate[(modelxx)]]
*** True Label:
 T
*** Predicted Label:

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(ownedby[(?x  company)]  connectedto[(?x  googlehome)])]
@every *x [(ownedby[(?x  employee)]  connectedto[(?x  companywifi)])]
@every *x [(connectedto[(?x  googlehome)]  controlledby[(?x  managers)])]
@every *x [(connectedto[(?x  companywifi)]  easytooperate[(?x)])]
ownedby[(modelxx  employee)]]
*** Conclusion:
 [controlledby[(modelxx  managers)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(ownedby[(?x  company)]  connectedto[(?x  googlehome)])]
@every *x [(ownedby[(?x  employee)]  connectedto[(?x  companywifi)])]
@every *x [(connectedto[(?x  googlehome)]  controlledby[(?x  managers)])]
@every *x [(connectedto[(?x  companywifi)]  easytooperate[(?x)])]
ownedby[(modelxx  employee)]]
*** Conclusion:
 [connectedto[(modelxx  googlehome)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(attendinperson[(?x)]  registered[(?x)])]
@every *x [(attend[(?x)]  [(attendinperson[(?x)]  attendremotely[(?x)])])]
@every *x [([(attend[(?x)]  fromchina[(?x)])]  ~attendremotely[(?x)])]
attend[(james)]  [(~attendremotely[(james)])]
fromchina[(jack)]  attend[(jack)]]
*** Conclusion:
 [attend[(james)]  [(~attendinperson[(james)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(attendinperson[(?x)]  registered[(?x)])]
@every *x [(attend[(?x)]  [(attendinperson[(?x)]  attendremotely[(?x)])])]
@every *x [([(attend[(?x)]  fromchina[(?x)])]  ~attendremotely[(?x)])]
attend[(james)]  [(~attendremotely[(james)])]
fromchina[(jack)]  attend[(jack)]]
*** Conclusion:
 [attend[(jack)]  attendinperson[(jack)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(attendinperson[(?x)]  registered[(?x)])]
@every *x [(attend[(?x)]  [(attendinperson[(?x)]  attendremotely[(?x)])])]
@every *x [([(attend[(?x)]  fromchina[(?x)])]  ~attendremotely[(?x)])]
attend[(james)]  [(~attendremotely[(james)])]
fromchina[(jack)]  attend[(jack)]]
*** Conclusion:
 [registered[(jack)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(podcast[(?x)]  ~novel[(?x)])]
@every *x[([(*y[(bornin[(?x  y)]  city[(?y)]  locatedin[(?y america)])]  american[(?x)])]
@every *x @every *y [([(novel[(?x)]  writtenby[(?x  y)])]  writesnovel[(?y)])]
american[(dani_shapiro)]  writer[(dani_shapiro)]
writtenby[(family_history  dani_shapiro)]
novel[(family_history)]  writtenin[(family_history  yr2003)]
podcast[(family_secrets)]  createdby[(family_secrets  dani_shapiro)]
city[(boston)]  american[(boston)]]
*** Conclusion:
 [writesnovel[(dani_shapiro)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(podcast[(?x)]  ~novel[(?x)])]
@every *x[([(*y[(bornin[(?x  y)]  city[(?y)]  locatedin[(?y america)])]  american[(?x)])]
@every *x @every *y [([(novel[(?x)]  writtenby[(?x  y)])]  writesnovel[(?y)])]
american[(dani_shapiro)]  writer[(dani_shapiro)]
writtenby[(family_history  dani_shapiro)]
novel[(family_history)]  writtenin[(family_history  yr2003)]
podcast[(family_secrets)]  createdby[(family_secrets  dani_shapiro)]
city[(boston)]  american[(boston)]]
*** Conclusion:
 [isnovel[(family_secrets)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(podcast[(?x)]  ~novel[(?x)])]
@every *x[([(*y[(bornin[(?x  y)]  city[(?y)]  locatedin[(?y america)])]  american[(?x)])]
@every *x @every *y [([(novel[(?x)]  writtenby[(?x  y)])]  writesnovel[(?y)])]
american[(dani_shapiro)]  writer[(dani_shapiro)]
writtenby[(family_history  dani_shapiro)]
novel[(family_history)]  writtenin[(family_history  yr2003)]
podcast[(family_secrets)]  createdby[(family_secrets  dani_shapiro)]
city[(boston)]  american[(boston)]]
*** Conclusion:
 [bornin[(dani_shapiro  boston)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(coach[(?x  y)]  footballclub[(?y)])]  footballcoach[(?x)])]
@every *w @every *x @every *y @every *z [([(playpositionfor[(?x  w  y  z)]  innfl[(?y  z)])]  playinnfl[(?x)])]
footballclub[(minnesotavikings)]
coach[(dennisgreen  minnesotavikings)]
receivetd[(criscarter  num13)]
innfl[(minnesotavikings  yr1997)]
playpositionfor[(johnrandle  defensivetackle  minnesotavikings  yr1997)]]
*** Conclusion:
 [footballcoach[(dennisgreen)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(coach[(?x  y)]  footballclub[(?y)])]  footballcoach[(?x)])]
@every *w @every *x @every *y @every *z [([(playpositionfor[(?x  w  y  z)]  innfl[(?y  z)])]  playinnfl[(?x)])]
footballclub[(minnesotavikings)]
coach[(dennisgreen  minnesotavikings)]
receivetd[(criscarter  num13)]
innfl[(minnesotavikings  yr1997)]
playpositionfor[(johnrandle  defensivetackle  minnesotavikings  yr1997)]]
*** Conclusion:
 ~[playinnfl[(johnrandle)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(coach[(?x  y)]  footballclub[(?y)])]  footballcoach[(?x)])]
@every *w @every *x @every *y @every *z [([(playpositionfor[(?x  w  y  z)]  innfl[(?y  z)])]  playinnfl[(?x)])]
footballclub[(minnesotavikings)]
coach[(dennisgreen  minnesotavikings)]
receivetd[(criscarter  num13)]
innfl[(minnesotavikings  yr1997)]
playpositionfor[(johnrandle  defensivetackle  minnesotavikings  yr1997)]]
*** Conclusion:
 [playpositionfor[(criscarter  wr  minnesotavikings  year1997)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(summerolympicsin[(?x ?y)]  in[(?x  unitedstates)])]  summerolympicsin[(?x  unitedstates)])]
@every *x @every *y [([(in[(?x  y)]  in[(?y  unitedstates)])]  in[(?x  unitedstates)])]
@every *x @every *y @every *z [([(in[(?x  z)]  state[(?z)]  summerolympicsin[(?x ?y)])]  summerolympicsin[(?z  y)])]
summerolympicsin[(losangeles  yr2028)]
in[(losangeles  california)]
in[(atlanta  unitedstates)]
in[(california  unitedstates)]
in[(atlanta  georgia)]
~insummerolympicsin[(boxing  yr2028)]  [(~insummerolympicsin[(modern_pentathlon  yr2028)])]  [(~insummerolympicsin[(weightlifting  yr2028)])]
summerolympicsin[(atlanta  yr1996)]]
*** Conclusion:
 [summerolympicsin[(unitedstates  yr2028)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(summerolympicsin[(?x ?y)]  in[(?x  unitedstates)])]  summerolympicsin[(?x  unitedstates)])]
@every *x @every *y [([(in[(?x  y)]  in[(?y  unitedstates)])]  in[(?x  unitedstates)])]
@every *x @every *y @every *z [([(in[(?x  z)]  state[(?z)]  summerolympicsin[(?x ?y)])]  summerolympicsin[(?z  y)])]
summerolympicsin[(losangeles  yr2028)]
in[(losangeles  california)]
in[(atlanta  unitedstates)]
in[(california  unitedstates)]
in[(atlanta  georgia)]
~insummerolympicsin[(boxing  yr2028)]  [(~insummerolympicsin[(modern_pentathlon  yr2028)])]  [(~insummerolympicsin[(weightlifting  yr2028)])]
summerolympicsin[(atlanta  yr1996)]]
*** Conclusion:
 ~[summerolympicsin[(georgia  yr1996)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y [([(summerolympicsin[(?x ?y)]  in[(?x  unitedstates)])]  summerolympicsin[(?x  unitedstates)])]
@every *x @every *y [([(in[(?x  y)]  in[(?y  unitedstates)])]  in[(?x  unitedstates)])]
@every *x @every *y @every *z [([(in[(?x  z)]  state[(?z)]  summerolympicsin[(?x ?y)])]  summerolympicsin[(?z  y)])]
summerolympicsin[(losangeles  yr2028)]
in[(losangeles  california)]
in[(atlanta  unitedstates)]
in[(california  unitedstates)]
in[(atlanta  georgia)]
~insummerolympicsin[(boxing  yr2028)]  [(~insummerolympicsin[(modern_pentathlon  yr2028)])]  [(~insummerolympicsin[(weightlifting  yr2028)])]
summerolympicsin[(atlanta  yr1996)]]
*** Conclusion:
 [insummerolympicsin[(skateboarding  yr2028)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y @every *z [(albumbyband[(?x  y)]  rockband[(?y  z)]  genre[(?x  rock)])]
@every *x @every *y @every *z [(albumbyband[(?x  y)]  albumaward[(?x  z)]  rockbandaward[(?y  z)])]
albumbyband[(trouble_at_the_henhouse  the_tragically_hip)]
rockband[(the_tragically_hip  canada)]
songinalbum[(butts_wigglin  trouble_at_the_henhouse)]
albumaward[(trouble_at_the_henhouse  the_album_of_the_year)]
*x [(songinfilm[(?x)]  songinalbum[(?x  trouble_at_the_henhouse)])]]
*** Conclusion:
 [genre[(troubleatthehenhouse  rock)]]
*** True Label:
 T
*** Predicted Label:
 T</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y @every *z [(albumbyband[(?x  y)]  rockband[(?y  z)]  genre[(?x  rock)])]
@every *x @every *y @every *z [(albumbyband[(?x  y)]  albumaward[(?x  z)]  rockbandaward[(?y  z)])]
albumbyband[(trouble_at_the_henhouse  the_tragically_hip)]
rockband[(the_tragically_hip  canada)]
songinalbum[(butts_wigglin  trouble_at_the_henhouse)]
albumaward[(trouble_at_the_henhouse  the_album_of_the_year)]
*x [(songinfilm[(?x)]  songinalbum[(?x  trouble_at_the_henhouse)])]]
*** Conclusion:
 ~[*x[(rockband[(?x  canada)]  award[(?x  thealbumoftheyear)])]]
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x @every *y @every *z [(albumbyband[(?x  y)]  rockband[(?y  z)]  genre[(?x  rock)])]
@every *x @every *y @every *z [(albumbyband[(?x  y)]  albumaward[(?x  z)]  rockbandaward[(?y  z)])]
albumbyband[(trouble_at_the_henhouse  the_tragically_hip)]
rockband[(the_tragically_hip  canada)]
songinalbum[(butts_wigglin  trouble_at_the_henhouse)]
albumaward[(trouble_at_the_henhouse  the_album_of_the_year)]
*x [(songinfilm[(?x)]  songinalbum[(?x  trouble_at_the_henhouse)])]]
*** Conclusion:
 [songinfilm[(buttswigglin)]]
*** True Label:
 U
*** Predicted Label:
 F</output>

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [directedby[(aftertiller  lanawilson)]  directedby[(thedeparture  lanawilson)]  directedby[(missamericana  lanawilson)]
@every *x @every *y [(directedby[(?x  y)]  filmmaker[(?y)])]
documentary[(aftertiller)]
@every *x [(documentary[(?x)]  film[(?x)])]
from[(lanawilson  kirkland)]
in[(kirkland  unitedstates)]
@every *x @every *y @every *z [([(from[(?x  y)]  in[(?y  z)])]  from[(?x  z)])]
nomination[(aftertiller  theindependentspiritawardforbestdocumentary)]]
*** Conclusion:
 [from[(lanawilson  unitedstates)]  filmmaker[(lanawilson)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [directedby[(aftertiller  lanawilson)]  directedby[(thedeparture  lanawilson)]  directedby[(missamericana  lanawilson)]
@every *x @every *y [(directedby[(?x  y)]  filmmaker[(?y)])]
documentary[(aftertiller)]
@every *x [(documentary[(?x)]  film[(?x)])]
from[(lanawilson  kirkland)]
in[(kirkland  unitedstates)]
@every *x @every *y @every *z [([(from[(?x  y)]  in[(?y  z)])]  from[(?x  z)])]
nomination[(aftertiller  theindependentspiritawardforbestdocumentary)]]
*** Conclusion:
 ~[*x[(filmmaker[(?x)]  from[(?x  kirkland)]  directedby[(missamericana  x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [directedby[(aftertiller  lanawilson)]  directedby[(thedeparture  lanawilson)]  directedby[(missamericana  lanawilson)]
@every *x @every *y [(directedby[(?x  y)]  filmmaker[(?y)])]
documentary[(aftertiller)]
@every *x [(documentary[(?x)]  film[(?x)])]
from[(lanawilson  kirkland)]
in[(kirkland  unitedstates)]
@every *x @every *y @every *z [([(from[(?x  y)]  in[(?y  z)])]  from[(?x  z)])]
nomination[(aftertiller  theindependentspiritawardforbestdocumentary)]]
*** Conclusion:
 [filmmakeraward[(lanawilson  theindependentspiritawardforbestdocumentary)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [scottish[(brianwinter)]  footballreferee[(brianwinter)]
retired[(brianwinter)]  retiredin[(brianwinter  yr2012)]
refereeobserver[(brianwinter)]
*x [(footballreferee[(?x)]  refereeobserver[(?x)])]
sonof[(andywinter  brianwinter)]  footballplayer[(andywinter)]  playsfor[(andywinter  hamiltonacademical)]]
*** Conclusion:
 [*x *y[(sonof[(?x  y)]  refereeobserver[(?y)]  footballplayer[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [scottish[(brianwinter)]  footballreferee[(brianwinter)]
retired[(brianwinter)]  retiredin[(brianwinter  yr2012)]
refereeobserver[(brianwinter)]
*x [(footballreferee[(?x)]  refereeobserver[(?x)])]
sonof[(andywinter  brianwinter)]  footballplayer[(andywinter)]  playsfor[(andywinter  hamiltonacademical)]]
*** Conclusion:
 ~[refereeobserver[(brianwinter)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [scottish[(brianwinter)]  footballreferee[(brianwinter)]
retired[(brianwinter)]  retiredin[(brianwinter  yr2012)]
refereeobserver[(brianwinter)]
*x [(footballreferee[(?x)]  refereeobserver[(?x)])]
sonof[(andywinter  brianwinter)]  footballplayer[(andywinter)]  playsfor[(andywinter  hamiltonacademical)]]
*** Conclusion:
 [retired[(brianwinter)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [scottish[(brianwinter)]  footballreferee[(brianwinter)]
retired[(brianwinter)]  retiredin[(brianwinter  yr2012)]
refereeobserver[(brianwinter)]
*x [(footballreferee[(?x)]  refereeobserver[(?x)])]
sonof[(andywinter  brianwinter)]  footballplayer[(andywinter)]  playsfor[(andywinter  hamiltonacademical)]]
*** Conclusion:
 [referee[(andywinter)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(michael)]  physician[(michael)]  journalist[(michael)]  author[(michael)]  broadcaster[(michael)]
wordsetter[(michael)]
magazine[(worldmedicine)]  editedby[(worldmedicine  michael)]
bornin[(michael  yorkshire)]  *x[(sonof[(michael  x)]  generalpractitioner[(?x)])]]
*** Conclusion:
 [*x *y [(sonof[(?x  y)]  generalpractitioner[(?y)]  wordsetter[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(michael)]  physician[(michael)]  journalist[(michael)]  author[(michael)]  broadcaster[(michael)]
wordsetter[(michael)]
magazine[(worldmedicine)]  editedby[(worldmedicine  michael)]
bornin[(michael  yorkshire)]  *x[(sonof[(michael  x)]  generalpractitioner[(?x)])]]
*** Conclusion:
 ~[magazine[(worldmedicine)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(michael)]  physician[(michael)]  journalist[(michael)]  author[(michael)]  broadcaster[(michael)]
wordsetter[(michael)]
magazine[(worldmedicine)]  editedby[(worldmedicine  michael)]
bornin[(michael  yorkshire)]  *x[(sonof[(michael  x)]  generalpractitioner[(?x)])]]
*** Conclusion:
 [@every *x [(british[(?x)]  ~author[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(michael)]  physician[(michael)]  journalist[(michael)]  author[(michael)]  broadcaster[(michael)]
wordsetter[(michael)]
magazine[(worldmedicine)]  editedby[(worldmedicine  michael)]
bornin[(michael  yorkshire)]  *x[(sonof[(michael  x)]  generalpractitioner[(?x)])]]
*** Conclusion:
 [@every *x [(journalist[(?x)]  ~bornin[(?x  yorkshire)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [british[(michael)]  physician[(michael)]  journalist[(michael)]  author[(michael)]  broadcaster[(michael)]
wordsetter[(michael)]
magazine[(worldmedicine)]  editedby[(worldmedicine  michael)]
bornin[(michael  yorkshire)]  *x[(sonof[(michael  x)]  generalpractitioner[(?x)])]]
*** Conclusion:
 [*x *y [(son[(?x  y)]  generalpractitioner[(?y)]  ~author[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [greek[(herodicus)]  physician[(herodicus)]  dietician[(herodicus)]  sophist[(herodicus)]  gymnast[(herodicus)]
born[(herodicus  selymbia)]  city[(selymbia)]
colony[(selymbia  megara)]  citystate[(megara)]
tutor[(herodicus  hippocrates)]
recommend[(herodicus  massages)]
*x *y [(theory[(?x)]  from[(?x  herodicus)]  foundationof[(?x  sportsmedicine)]  [(~[(?x=y)])]  theory[(?y)]  from[(?y  herodicus)]  foundationof[(?y  sportsmedicine)])]]
*** Conclusion:
 [tutor[(herodicus  hippocrates)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [greek[(herodicus)]  physician[(herodicus)]  dietician[(herodicus)]  sophist[(herodicus)]  gymnast[(herodicus)]
born[(herodicus  selymbia)]  city[(selymbia)]
colony[(selymbia  megara)]  citystate[(megara)]
tutor[(herodicus  hippocrates)]
recommend[(herodicus  massages)]
*x *y [(theory[(?x)]  from[(?x  herodicus)]  foundationof[(?x  sportsmedicine)]  [(~[(?x=y)])]  theory[(?y)]  from[(?y  herodicus)]  foundationof[(?y  sportsmedicine)])]]
*** Conclusion:
 [tutor[(hippocrates  herodicus)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [greek[(herodicus)]  physician[(herodicus)]  dietician[(herodicus)]  sophist[(herodicus)]  gymnast[(herodicus)]
born[(herodicus  selymbia)]  city[(selymbia)]
colony[(selymbia  megara)]  citystate[(megara)]
tutor[(herodicus  hippocrates)]
recommend[(herodicus  massages)]
*x *y [(theory[(?x)]  from[(?x  herodicus)]  foundationof[(?x  sportsmedicine)]  [(~[(?x=y)])]  theory[(?y)]  from[(?y  herodicus)]  foundationof[(?y  sportsmedicine)])]]
*** Conclusion:
 [*x [(born[(herodicus  x)]  citystate[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [greek[(herodicus)]  physician[(herodicus)]  dietician[(herodicus)]  sophist[(herodicus)]  gymnast[(herodicus)]
born[(herodicus  selymbia)]  city[(selymbia)]
colony[(selymbia  megara)]  citystate[(megara)]
tutor[(herodicus  hippocrates)]
recommend[(herodicus  massages)]
*x *y [(theory[(?x)]  from[(?x  herodicus)]  foundationof[(?x  sportsmedicine)]  [(~[(?x=y)])]  theory[(?y)]  from[(?y  herodicus)]  foundationof[(?y  sportsmedicine)])]]
*** Conclusion:
 ~[recommend[(herodicus  massages)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [greek[(herodicus)]  physician[(herodicus)]  dietician[(herodicus)]  sophist[(herodicus)]  gymnast[(herodicus)]
born[(herodicus  selymbia)]  city[(selymbia)]
colony[(selymbia  megara)]  citystate[(megara)]
tutor[(herodicus  hippocrates)]
recommend[(herodicus  massages)]
*x *y [(theory[(?x)]  from[(?x  herodicus)]  foundationof[(?x  sportsmedicine)]  [(~[(?x=y)])]  theory[(?y)]  from[(?y  herodicus)]  foundationof[(?y  sportsmedicine)])]]
*** Conclusion:
 [*x *y [(born[(herodicus  x)]  colony[(?x  y)]  citystate[(?y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(enterococcusdurans[(?x)]  species[(?x  enterococcus)])]
@every *x [(enterococcusdurans[(?x)]  grampositive[(?x)]  catalasenegative[(?x)]  oxidasenegative[(?x)]  coccus[(?x)]  bacteria[(?x)])]
*x *y [(enterococcusdurans[(?x)]  antiinflammatoryagent[(?y)]  produces[(?x  y)])]
@every *x [(antiinflammatoryagent[(?x)]  studied[(?x)])]]
*** Conclusion:
 [@every *x [(enterococcusdurans[(?x)]  catalasenegative[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(enterococcusdurans[(?x)]  species[(?x  enterococcus)])]
@every *x [(enterococcusdurans[(?x)]  grampositive[(?x)]  catalasenegative[(?x)]  oxidasenegative[(?x)]  coccus[(?x)]  bacteria[(?x)])]
*x *y [(enterococcusdurans[(?x)]  antiinflammatoryagent[(?y)]  produces[(?x  y)])]
@every *x [(antiinflammatoryagent[(?x)]  studied[(?x)])]]
*** Conclusion:
 [*x [(grampositive[(?x)]  studied[(?x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(enterococcusdurans[(?x)]  species[(?x  enterococcus)])]
@every *x [(enterococcusdurans[(?x)]  grampositive[(?x)]  catalasenegative[(?x)]  oxidasenegative[(?x)]  coccus[(?x)]  bacteria[(?x)])]
*x *y [(enterococcusdurans[(?x)]  antiinflammatoryagent[(?y)]  produces[(?x  y)])]
@every *x [(antiinflammatoryagent[(?x)]  studied[(?x)])]]
*** Conclusion:
 [@every *x @every *y [(enterococcusdurans[(?x)]  produces[(?x  y)]  ~studied[(?y)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [prehistoric[(ambiortus)]  birdgenus[(ambiortus)]
@every *x[(knownspeciesof[(?x  ambiortus)]  isspecies[(?x  ambiortusdementjevi)])]
livein[(ambiortusdementjevi  mongolia)]
discover[(yevgenykurochkin  ambiortus)]]
*** Conclusion:
 [*x [(discover[(yevgenykurochkin  x)]  birdgenus[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [prehistoric[(ambiortus)]  birdgenus[(ambiortus)]
@every *x[(knownspeciesof[(?x  ambiortus)]  isspecies[(?x  ambiortusdementjevi)])]
livein[(ambiortusdementjevi  mongolia)]
discover[(yevgenykurochkin  ambiortus)]]
*** Conclusion:
 [*x [(knownspeciesof[(?x  ambiortus)]  ~livein[(?x  mongolia)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [prehistoric[(ambiortus)]  birdgenus[(ambiortus)]
@every *x[(knownspeciesof[(?x  ambiortus)]  isspecies[(?x  ambiortusdementjevi)])]
livein[(ambiortusdementjevi  mongolia)]
discover[(yevgenykurochkin  ambiortus)]]
*** Conclusion:
 [livein[(yevgenykurochkin  mongolia)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [prehistoric[(ambiortus)]  birdgenus[(ambiortus)]
@every *x[(knownspeciesof[(?x  ambiortus)]  isspecies[(?x  ambiortusdementjevi)])]
livein[(ambiortusdementjevi  mongolia)]
discover[(yevgenykurochkin  ambiortus)]]
*** Conclusion:
 [@every *x [(speciesof[(?x  ambiortus)]  livein[(?x  mongolia)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [traditionalsummercamp[(campdavern)]  forboysandgirls[(campdavern)]
establishedin[(campdavern  year1946)]
operateduntil[(ymca  campdavern  year2015)]
old[(campdavern)]]
*** Conclusion:
 [*x [(old[(?x)]  traditionalsummercamp[(?x)]  forboysandgirls[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [traditionalsummercamp[(campdavern)]  forboysandgirls[(campdavern)]
establishedin[(campdavern  year1946)]
operateduntil[(ymca  campdavern  year2015)]
old[(campdavern)]]
*** Conclusion:
 [*x [(traditionalsummercamp[(?x)]  forboysandgirls[(?x)]  operateduntil[(ymca  x  year2015)])]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [traditionalsummercamp[(campdavern)]  forboysandgirls[(campdavern)]
establishedin[(campdavern  year1946)]
operateduntil[(ymca  campdavern  year2015)]
old[(campdavern)]]
*** Conclusion:
 [establishedin[(campdavern  year1989)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(robertzimmer  germany)]  philosopher[(robertzimmer)]
essayist[(robertzimmer)]
bornin[(robertzimmer  yr1953)]
@every *x [(essayist[(?x)]  writer[(?x)])]]
*** Conclusion:
 [bornin[(robertzimmer  germany)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(robertzimmer  germany)]  philosopher[(robertzimmer)]
essayist[(robertzimmer)]
bornin[(robertzimmer  yr1953)]
@every *x [(essayist[(?x)]  writer[(?x)])]]
*** Conclusion:
 ~[writer[(robertzimmer)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(robertzimmer  germany)]  philosopher[(robertzimmer)]
essayist[(robertzimmer)]
bornin[(robertzimmer  yr1953)]
@every *x [(essayist[(?x)]  writer[(?x)])]]
*** Conclusion:
 [biographer[(robertzimmer)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(asahoffmann  newyorkcity)]
livein[(asahoffmann  manhattan)]
chessplayer[(asahoffmann)]
*x *y [(chessplayer[(?x)]  grandmaster[(?x)]  [(~[(?x=y)])]  chessplayer[(?y)]  grandmaster[(?y)])]
@every *x [([(bornin[(?x  newyorkcity)]  livein[(?x  newyorkcity)])]  newyorker[(?x)])]
@every *x [(livein[(?x  manhattan)]  livein[(?x  newyorkcity)])]]
*** Conclusion:
 [newyorker[(asahoffmann)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(asahoffmann  newyorkcity)]
livein[(asahoffmann  manhattan)]
chessplayer[(asahoffmann)]
*x *y [(chessplayer[(?x)]  grandmaster[(?x)]  [(~[(?x=y)])]  chessplayer[(?y)]  grandmaster[(?y)])]
@every *x [([(bornin[(?x  newyorkcity)]  livein[(?x  newyorkcity)])]  newyorker[(?x)])]
@every *x [(livein[(?x  manhattan)]  livein[(?x  newyorkcity)])]]
*** Conclusion:
 [grandmaster[(asahoffmann)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(asahoffmann  newyorkcity)]
livein[(asahoffmann  manhattan)]
chessplayer[(asahoffmann)]
*x *y [(chessplayer[(?x)]  grandmaster[(?x)]  [(~[(?x=y)])]  chessplayer[(?y)]  grandmaster[(?y)])]
@every *x [([(bornin[(?x  newyorkcity)]  livein[(?x  newyorkcity)])]  newyorker[(?x)])]
@every *x [(livein[(?x  manhattan)]  livein[(?x  newyorkcity)])]]
*** Conclusion:
 ~[livein[(asahoffmann  newyorkcity)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [make[(janjelinek  glitch)]  make[(janjelinek  minimaltechno)]
@every *x [([(make[(?x  glitch)]  make[(?x  minimaltechno)]  make[(?x  microhouse)])]  electronicmusician[(?x)])]
publishthroughlabel[(janjelinek  faitiche)]
@every *x [([(*y[(publishthroughlabel[(?x  y)])])]  signedmusician[(?x)])]]
*** Conclusion:
 [electronicmusician[(janjelinek)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [make[(janjelinek  glitch)]  make[(janjelinek  minimaltechno)]
@every *x [([(make[(?x  glitch)]  make[(?x  minimaltechno)]  make[(?x  microhouse)])]  electronicmusician[(?x)])]
publishthroughlabel[(janjelinek  faitiche)]
@every *x [([(*y[(publishthroughlabel[(?x  y)])])]  signedmusician[(?x)])]]
*** Conclusion:
 ~[signedmusician[(janjelinek)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [make[(janjelinek  glitch)]  make[(janjelinek  minimaltechno)]
@every *x [([(make[(?x  glitch)]  make[(?x  minimaltechno)]  make[(?x  microhouse)])]  electronicmusician[(?x)])]
publishthroughlabel[(janjelinek  faitiche)]
@every *x [([(*y[(publishthroughlabel[(?x  y)])])]  signedmusician[(?x)])]]
*** Conclusion:
 [german[(janjelinek)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [officein[(ableton  germany)]
officein[(ableton  unitedstates)]
~samecountry[(germany  unitedstates)]
@every *x @every *y @every *z [(officein[(?x  y)]  officein[(?x  z)]  [(~samecountry[(?y  z)])]  multinationalcompany[(?x)])]
makesmusicsoftware[(ableton)]]
*** Conclusion:
 [multinationalcompany[(ableton)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [officein[(ableton  germany)]
officein[(ableton  unitedstates)]
~samecountry[(germany  unitedstates)]
@every *x @every *y @every *z [(officein[(?x  y)]  officein[(?x  z)]  [(~samecountry[(?y  z)])]  multinationalcompany[(?x)])]
makesmusicsoftware[(ableton)]]
*** Conclusion:
 [makesaisoftware[(ableton)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [officein[(ableton  germany)]
officein[(ableton  unitedstates)]
~samecountry[(germany  unitedstates)]
@every *x @every *y @every *z [(officein[(?x  y)]  officein[(?x  z)]  [(~samecountry[(?y  z)])]  multinationalcompany[(?x)])]
makesmusicsoftware[(ableton)]]
*** Conclusion:
 ~[officein[(ableton  germany)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [striker[(robertlewandowski)]
@every *x [(striker[(?x)]  soccerplayer[(?x)])]
left[(robertlewandowski  bayernmunchen)]
@every *x @every *y [(left[(?x  y)]  ~playsfor[(?x  y)])]]
*** Conclusion:
 [soccerplayer[(robertlewandowski)]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [striker[(robertlewandowski)]
@every *x [(striker[(?x)]  soccerplayer[(?x)])]
left[(robertlewandowski  bayernmunchen)]
@every *x @every *y [(left[(?x  y)]  ~playsfor[(?x  y)])]]
*** Conclusion:
 [playsfor[(robertlewandowski  bayernmunchen)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [striker[(robertlewandowski)]
@every *x [(striker[(?x)]  soccerplayer[(?x)])]
left[(robertlewandowski  bayernmunchen)]
@every *x @every *y [(left[(?x  y)]  ~playsfor[(?x  y)])]]
*** Conclusion:
 [soccerstar[(robertlewandowski)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [publishinghouse[(newvesselpress)]  specializesintranslatingintoenglish[(newvesselpress  foreignliterature)]
@every *x [([(book[(?x)]  publishedby[(?x  newvesselpress)])]  in[(?x  english)])]
book[(neapolitanchronicles)]  publishedby[(neapolitanchronicles  newvesselpress)]
translatedfrom[(neapolitanchronicles  italian)]
book[(palaceofflies)]  publishedby[(palaceofflies  newvesselpress)]]
*** Conclusion:
 [book[(neapolitanchronicles)]  in[(neapolitanchronicles  english)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [publishinghouse[(newvesselpress)]  specializesintranslatingintoenglish[(newvesselpress  foreignliterature)]
@every *x [([(book[(?x)]  publishedby[(?x  newvesselpress)])]  in[(?x  english)])]
book[(neapolitanchronicles)]  publishedby[(neapolitanchronicles  newvesselpress)]
translatedfrom[(neapolitanchronicles  italian)]
book[(palaceofflies)]  publishedby[(palaceofflies  newvesselpress)]]
*** Conclusion:
 [publishedby[(harrypotter  newvesselpress)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [publishinghouse[(newvesselpress)]  specializesintranslatingintoenglish[(newvesselpress  foreignliterature)]
@every *x [([(book[(?x)]  publishedby[(?x  newvesselpress)])]  in[(?x  english)])]
book[(neapolitanchronicles)]  publishedby[(neapolitanchronicles  newvesselpress)]
translatedfrom[(neapolitanchronicles  italian)]
book[(palaceofflies)]  publishedby[(palaceofflies  newvesselpress)]]
*** Conclusion:
 [translatedfrom[(palaceofflies  italian)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sells[(quiksilver  x)]  [(sportswear[(?x)]  clothing[(?x)]  footwear[(?x)]  accessory[(?x)])])]
clothing[(flannel)]
*x [(sells[(quiksilver  x)]  owns[(joe  x)])]]
*** Conclusion:
 [sells[(quiksilver  beer)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sells[(quiksilver  x)]  [(sportswear[(?x)]  clothing[(?x)]  footwear[(?x)]  accessory[(?x)])])]
clothing[(flannel)]
*x [(sells[(quiksilver  x)]  owns[(joe  x)])]]
*** Conclusion:
 [owns[(joe  flannel)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(sells[(quiksilver  x)]  [(sportswear[(?x)]  clothing[(?x)]  footwear[(?x)]  accessory[(?x)])])]
clothing[(flannel)]
*x [(sells[(quiksilver  x)]  owns[(joe  x)])]]
*** Conclusion:
 [*x [(owns[(joe  x)]  sportswear[(?x)]  clothing[(?x)]  footwear[(?x)]  accessory[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [neighbourhoodin[(lawtonpark  seattle)]
@every *x [(residentof[(?x  lawtonpark)]  usezipcode[(?x  num98199)])]
residentof[(tom  lawtonpark)]
usezipcode[(daniel  num98199)]]
*** Conclusion:
 [usezipcode[(tom  num98199)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [neighbourhoodin[(lawtonpark  seattle)]
@every *x [(residentof[(?x  lawtonpark)]  usezipcode[(?x  num98199)])]
residentof[(tom  lawtonpark)]
usezipcode[(daniel  num98199)]]
*** Conclusion:
 ~[usezipcode[(tom  num98199)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [neighbourhoodin[(lawtonpark  seattle)]
@every *x [(residentof[(?x  lawtonpark)]  usezipcode[(?x  num98199)])]
residentof[(tom  lawtonpark)]
usezipcode[(daniel  num98199)]]
*** Conclusion:
 [residentof[(tom  washington)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [neighbourhoodin[(lawtonpark  seattle)]
@every *x [(residentof[(?x  lawtonpark)]  usezipcode[(?x  num98199)])]
residentof[(tom  lawtonpark)]
usezipcode[(daniel  num98199)]]
*** Conclusion:
 [residentof[(daniel  lawtonpark)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(vehicleregistrationplatein[(?x  istanbul)]  beginwith[(?x  num34)])]
@every *x [(~beginwith[(?x  num34)]  ~fromistanbul[(?x)])]
*x [(owns[(joe  x)]  vehicleregistrationplatein[(?x  istanbul)])]
*x [(owns[(tom  x)]  beginwith[(?x  num35)])]
@every *x [(beginwith[(?x  num35)]  ~beginwith[(?x  num34)])]]
*** Conclusion:
 [*x [(owns[(joe  x)]  beginwith[(?x  num34)])]]
*** True Label:
 T
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [(vehicleregistrationplatein[(?x  istanbul)]  beginwith[(?x  num34)])]
@every *x [(~beginwith[(?x  num34)]  ~fromistanbul[(?x)])]
*x [(owns[(joe  x)]  vehicleregistrationplatein[(?x  istanbul)])]
*x [(owns[(tom  x)]  beginwith[(?x  num35)])]
@every *x [(beginwith[(?x  num35)]  ~beginwith[(?x  num34)])]]
*** Conclusion:
 [*x [(owns[(tom  x)]  vehicleregistrationplatein[(?x  istanbul)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [island[(luzon)]  in[(luzon  philippines)]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)])]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)]  deadly[(?x)])]]
*** Conclusion:
 [island[(leyte)]  in[(leyte  philippines)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [island[(luzon)]  in[(luzon  philippines)]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)])]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)]  deadly[(?x)])]]
*** Conclusion:
 [@every *x @every *y [([(earthquake[(?x)]  strikeincity[(?x  y)]  in[(?y  philippines)])]  ~deadly[(?x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [island[(luzon)]  in[(luzon  philippines)]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)])]
*x [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  luzon)]  deadly[(?x)])]]
*** Conclusion:
 [*x *y [(earthquake[(?x)]  strikeinyr[(?x  year1999)]  strikeinmo[(?x  december)]  strikeincity[(?x  y)]  in[(?y  philippines)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [medication[(diethylcarbamazine)]  discoversin[(diethylcarbamazine  yr1947)]
treats[(diethylcarbamazine  riverblindness)]
preferredtreatmentfor[(riverblindness  ivermectin)]
~[(is[(diethylcarbamazine  ivermectin)])]]
*** Conclusion:
 ~[[(preferredtreatmentfor[(riverblindness  diethylcarbamazine)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [medication[(diethylcarbamazine)]  discoversin[(diethylcarbamazine  yr1947)]
treats[(diethylcarbamazine  riverblindness)]
preferredtreatmentfor[(riverblindness  ivermectin)]
~[(is[(diethylcarbamazine  ivermectin)])]]
*** Conclusion:
 [treats[(diethylcarbamazine  riverblindness)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [medication[(diethylcarbamazine)]  discoversin[(diethylcarbamazine  yr1947)]
treats[(diethylcarbamazine  riverblindness)]
preferredtreatmentfor[(riverblindness  ivermectin)]
~[(is[(diethylcarbamazine  ivermectin)])]]
*** Conclusion:
 [treats[(diethylcarbamazine  filariasis)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(legislator[(?x)]  stealsfunds[(?x)])]  suspended[(?x)])]
legislator[(tiffanytalston)]
stealsfunds[(tiffanytalston)]  stealsfundsinyr[(tiffanytalston  yr2012)]]
*** Conclusion:
 [suspended[(tiffanytalston)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(legislator[(?x)]  stealsfunds[(?x)])]  suspended[(?x)])]
legislator[(tiffanytalston)]
stealsfunds[(tiffanytalston)]  stealsfundsinyr[(tiffanytalston  yr2012)]]
*** Conclusion:
 ~[suspended[(tiffanytalston)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [@every *x [([(legislator[(?x)]  stealsfunds[(?x)])]  suspended[(?x)])]
legislator[(tiffanytalston)]
stealsfunds[(tiffanytalston)]  stealsfundsinyr[(tiffanytalston  yr2012)]]
*** Conclusion:
 [prison[(tiffanytalston)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [actor[(daveeddiggs)]  filmproducer[(daveeddiggs)]
*x *y[(playsin[(daveeddiggs  x  hamilton)]  [(~[(?x=y)])]  playsin[(daveeddiggs  y  hamilton)])]  onbroadway[(hamilton)]  musical[(hamilton)]
*x *y[(actor[(?x)]  playsin[(?x  y  hamilton)]  wins[(?x  bestactoraward)])]
*x [(actor[(?x)]  playsin[(?x  thomasjefferson  hamilton)]  wins[(?x  bestactoraward)])]
plays[(daveeddiggs  thomasjefferson)]
@every *x [([(musical[(?x)]  onbroadway[(?x)])]  ~film[(?x)])]]
*** Conclusion:
 [film[(hamilton)]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [actor[(daveeddiggs)]  filmproducer[(daveeddiggs)]
*x *y[(playsin[(daveeddiggs  x  hamilton)]  [(~[(?x=y)])]  playsin[(daveeddiggs  y  hamilton)])]  onbroadway[(hamilton)]  musical[(hamilton)]
*x *y[(actor[(?x)]  playsin[(?x  y  hamilton)]  wins[(?x  bestactoraward)])]
*x [(actor[(?x)]  playsin[(?x  thomasjefferson  hamilton)]  wins[(?x  bestactoraward)])]
plays[(daveeddiggs  thomasjefferson)]
@every *x [([(musical[(?x)]  onbroadway[(?x)])]  ~film[(?x)])]]
*** Conclusion:
 [wins[(daveeddiggs  bestactoraward)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [actor[(daveeddiggs)]  filmproducer[(daveeddiggs)]
*x *y[(playsin[(daveeddiggs  x  hamilton)]  [(~[(?x=y)])]  playsin[(daveeddiggs  y  hamilton)])]  onbroadway[(hamilton)]  musical[(hamilton)]
*x *y[(actor[(?x)]  playsin[(?x  y  hamilton)]  wins[(?x  bestactoraward)])]
*x [(actor[(?x)]  playsin[(?x  thomasjefferson  hamilton)]  wins[(?x  bestactoraward)])]
plays[(daveeddiggs  thomasjefferson)]
@every *x [([(musical[(?x)]  onbroadway[(?x)])]  ~film[(?x)])]]
*** Conclusion:
 [*x *y[(wins[(hamilton  x)]  [(~[(?x=y)])]  wins[(hamilton  y)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [painter[(bernardabrysonshahn)]  lithographer[(bernardabrysonshahn)]
bornin[(bernardabrysonshahn  athensohio)]
marriedto[(bernardabrysonshahn  benshahn)]
@every *x [(bornin[(?x  athensohio)]  american[(?x)])]]
*** Conclusion:
 [bornin[(bernardabrysonshahn  greece)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [painter[(bernardabrysonshahn)]  lithographer[(bernardabrysonshahn)]
bornin[(bernardabrysonshahn  athensohio)]
marriedto[(bernardabrysonshahn  benshahn)]
@every *x [(bornin[(?x  athensohio)]  american[(?x)])]]
*** Conclusion:
 [american[(bernardabrysonshahn)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [painter[(bernardabrysonshahn)]  lithographer[(bernardabrysonshahn)]
bornin[(bernardabrysonshahn  athensohio)]
marriedto[(bernardabrysonshahn  benshahn)]
@every *x [(bornin[(?x  athensohio)]  american[(?x)])]]
*** Conclusion:
 [divorced[(bernardabrysonshahn)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [singer[(bobbyflynn)]  songwriter[(bobbyflynn)]
finishesin[(bobbyflynn  number7)]  competesonaustralianidol[(bobbyflynn)]
@every *x [(competesonaustralianidol[(?x)]  australiancitizen[(?x)])]
nationwidetourin[(theomegathreeband  year2007)]
member[(bobbyflynn  theomegathreeband)]
bornin[(bobbyflynn  queensland)]]
*** Conclusion:
 [australiancitizen[(bobbyflynn)]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [singer[(bobbyflynn)]  songwriter[(bobbyflynn)]
finishesin[(bobbyflynn  number7)]  competesonaustralianidol[(bobbyflynn)]
@every *x [(competesonaustralianidol[(?x)]  australiancitizen[(?x)])]
nationwidetourin[(theomegathreeband  year2007)]
member[(bobbyflynn  theomegathreeband)]
bornin[(bobbyflynn  queensland)]]
*** Conclusion:
 [flewtoin[(bobbyflynn  america  year2007)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [singer[(bobbyflynn)]  songwriter[(bobbyflynn)]
finishesin[(bobbyflynn  number7)]  competesonaustralianidol[(bobbyflynn)]
@every *x [(competesonaustralianidol[(?x)]  australiancitizen[(?x)])]
nationwidetourin[(theomegathreeband  year2007)]
member[(bobbyflynn  theomegathreeband)]
bornin[(bobbyflynn  queensland)]]
*** Conclusion:
 [bornin[(bobbyflynn  queens)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [japanese[(koeitecmo)]  videogameholdingcompany[(koeitecmo)]  animeholdingcompany[(koeitecmo)]  holdingcompany[(x)]
@every *x [(holdingcompany[(?x)]  *y[(company[(?y)]  holds[(?x  y)])])]
disbandsin[(tecmo  japan)]  survives[(koei)]  renames[(koei)]
@every *x [(videogameholdingcompany[(?x)]  holdingcompany[(?x)])]]
*** Conclusion:
 [*x [(company[(?x)]  holds[(koeitecmo  x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [japanese[(koeitecmo)]  videogameholdingcompany[(koeitecmo)]  animeholdingcompany[(koeitecmo)]  holdingcompany[(x)]
@every *x [(holdingcompany[(?x)]  *y[(company[(?y)]  holds[(?x  y)])])]
disbandsin[(tecmo  japan)]  survives[(koei)]  renames[(koei)]
@every *x [(videogameholdingcompany[(?x)]  holdingcompany[(?x)])]]
*** Conclusion:
 [*x [(company[(?x)]  holds[(tecmo  x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [japanese[(koeitecmo)]  videogameholdingcompany[(koeitecmo)]  animeholdingcompany[(koeitecmo)]  holdingcompany[(x)]
@every *x [(holdingcompany[(?x)]  *y[(company[(?y)]  holds[(?x  y)])])]
disbandsin[(tecmo  japan)]  survives[(koei)]  renames[(koei)]
@every *x [(videogameholdingcompany[(?x)]  holdingcompany[(?x)])]]
*** Conclusion:
 [animeholdingcompany[(koeitecmo)]]
*** True Label:
 U
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [australian[(virginialee)]  rower[(virginialee)]
competesin[(virginialee  sweepoaredevents)]  competesin[(virginialee  scullingevents)]
city[(sydney)]  homecity[(sydney  virginialee)]
represents[(virginialee  newsouthwales)]]
*** Conclusion:
 [@every *x [(rower[(?x)]  ~homecity[(sydney  x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [australian[(virginialee)]  rower[(virginialee)]
competesin[(virginialee  sweepoaredevents)]  competesin[(virginialee  scullingevents)]
city[(sydney)]  homecity[(sydney  virginialee)]
represents[(virginialee  newsouthwales)]]
*** Conclusion:
 [@every *x [(australian[(?x)]  ~represented[(?x  newsouthwales)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [australian[(virginialee)]  rower[(virginialee)]
competesin[(virginialee  sweepoaredevents)]  competesin[(virginialee  scullingevents)]
city[(sydney)]  homecity[(sydney  virginialee)]
represents[(virginialee  newsouthwales)]]
*** Conclusion:
 [*x [(australian[(?x)]  competesin[(?x  sweepoaredevents)]  represents[(?x  newsouthwales)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [dramafilm[(adventuresofrusty)]  childrensfilm[(adventuresofrusty)]
produces[(columbiapictures  adventuresofrusty)]
produces[(paramount  tintin)]
adventurefilm[(tintin)]]
*** Conclusion:
 [*x [(dramafilm[(?x)]  produces[(columbiapictures  x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [dramafilm[(adventuresofrusty)]  childrensfilm[(adventuresofrusty)]
produces[(columbiapictures  adventuresofrusty)]
produces[(paramount  tintin)]
adventurefilm[(tintin)]]
*** Conclusion:
 [*x [(adventurefilm[(?x)]  produces[(columbiapictures  x)])]]
*** True Label:
 U
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [dramafilm[(adventuresofrusty)]  childrensfilm[(adventuresofrusty)]
produces[(columbiapictures  adventuresofrusty)]
produces[(paramount  tintin)]
adventurefilm[(tintin)]]
*** Conclusion:
 [*x [(childrensfilm[(?x)]  produces[(paramount  x)])]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [dramafilm[(adventuresofrusty)]  childrensfilm[(adventuresofrusty)]
produces[(columbiapictures  adventuresofrusty)]
produces[(paramount  tintin)]
adventurefilm[(tintin)]]
*** Conclusion:
 [*x [(adventurefilm[(?x)]  produces[(paramount  x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [cricketeer[(royrichardson)]  playsfor[(royrichardson  sintmaarten)]  constituentcountry[(sintmaarten)]
righthanded[(royrichardson)]  batsman[(royrichardson)]  mediumpacebowler[(royrichardson)]
oldatdebut[(royrichardson)]
dismisses[(shervillehuggins  royrichardson)]]
*** Conclusion:
 [@every *x @every *y [([(consituentcountry[(?y)]  playedfor[(?x  y)])]   ~dismissed[(shervillehuggins  x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [cricketeer[(royrichardson)]  playsfor[(royrichardson  sintmaarten)]  constituentcountry[(sintmaarten)]
righthanded[(royrichardson)]  batsman[(royrichardson)]  mediumpacebowler[(royrichardson)]
oldatdebut[(royrichardson)]
dismisses[(shervillehuggins  royrichardson)]]
*** Conclusion:
 [@every *x [([(righthanded[(?x)]  mediumpacebowler[(?x)])]  ~playedfor[(?x  sintmaarten)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [village[(ainderbyquernhow)]  civilparish[(ainderbyquernhow)]  in[(ainderbyquernhow  hambletondistrict)]
in[(hambletondistrict  northyorkshire)]
in[(northyorkshire  england)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]]
*** Conclusion:
 [*x [(village[(?x)]  in[(?x  england)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [village[(ainderbyquernhow)]  civilparish[(ainderbyquernhow)]  in[(ainderbyquernhow  hambletondistrict)]
in[(hambletondistrict  northyorkshire)]
in[(northyorkshire  england)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]]
*** Conclusion:
 ~[[(*x [(civilparish[(?x)]  in[(?x  england)])])]]
*** True Label:
 F
*** Predicted Label:
 T

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [televisionseries[(diray)]  policeprocedural[(diray)]
creates[(maya  diray)]  writes[(maya  diray)]
produces[(jed  diray)]
british[(maya)]  british[(jed)]]
*** Conclusion:
 [*x [(british[(?x)]  creates[(?x  diray)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [televisionseries[(diray)]  policeprocedural[(diray)]
creates[(maya  diray)]  writes[(maya  diray)]
produces[(jed  diray)]
british[(maya)]  british[(jed)]]
*** Conclusion:
 [*x *y[(british[(?x)]  televisionseries[(?y)]  produces[(?x  y)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [professionalwrestlingstable[(diamondmine)]  in[(diamondmine  wwe)]
leads[(roderickstrong  diamondmine)]
includes[(diamondmine  creedbrothers)]  includes[(diamondmine  ivynile)]
feuds[(imperium  diamondmine)]]
*** Conclusion:
 [*x [(leads[(roderickstrong  x)]  professionalwrestlingstable[(?x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [professionalwrestlingstable[(diamondmine)]  in[(diamondmine  wwe)]
leads[(roderickstrong  diamondmine)]
includes[(diamondmine  creedbrothers)]  includes[(diamondmine  ivynile)]
feuds[(imperium  diamondmine)]]
*** Conclusion:
 [leads[(roderickstrong  creedbrothers)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [professionalwrestlingstable[(diamondmine)]  in[(diamondmine  wwe)]
leads[(roderickstrong  diamondmine)]
includes[(diamondmine  creedbrothers)]  includes[(diamondmine  ivynile)]
feuds[(imperium  diamondmine)]]
*** Conclusion:
 [@every *x [([(professionalwrestlingstable[(?x)]  includes[(?x  ivynile)])]  ~feuds[(imperium  x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(deborahwallace  scotland)]  actress[(deborahwallace)]  playwright[(deborahwallace)]  producer[(deborahwallace)]
play[(psyche)]  basedon[(psyche  lifeofjamesmirandabarry)]
play[(homesick)]  writtenby[(homesick  deborahwallace)]  play[(psyche)]  writtenby[(psyche  deborahwallace)]  play[(thevoid)]  writtenby[(thevoid  deborahwallace)]
coproduce[(deborahwallace  gasland)]]
*** Conclusion:
 [*x [(coproduces[(?x  gasland)]  writtenby[(homesick  x)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(deborahwallace  scotland)]  actress[(deborahwallace)]  playwright[(deborahwallace)]  producer[(deborahwallace)]
play[(psyche)]  basedon[(psyche  lifeofjamesmirandabarry)]
play[(homesick)]  writtenby[(homesick  deborahwallace)]  play[(psyche)]  writtenby[(psyche  deborahwallace)]  play[(thevoid)]  writtenby[(thevoid  deborahwallace)]
coproduce[(deborahwallace  gasland)]]
*** Conclusion:
 [@every *x [(play[(?x)]  writtenby[(?x  deborahwallace)]  ~basedon[(?x  lifeofjamesmirandabarry)])]]
*** True Label:
 F
*** Predicted Label:
 F

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [bornin[(deborahwallace  scotland)]  actress[(deborahwallace)]  playwright[(deborahwallace)]  producer[(deborahwallace)]
play[(psyche)]  basedon[(psyche  lifeofjamesmirandabarry)]
play[(homesick)]  writtenby[(homesick  deborahwallace)]  play[(psyche)]  writtenby[(psyche  deborahwallace)]  play[(thevoid)]  writtenby[(thevoid  deborahwallace)]
coproduce[(deborahwallace  gasland)]]
*** Conclusion:
 [play[(gasland)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(maggiefriedman)]  screenwriter[(maggiefriedman)]  producer[(maggiefriedman)]
showrunnerof[(maggiefriedman  witchesofeastend)]  executiveproducerof[(maggiefriedman  witchesofeastend)]  lifetimetelevisionseries[(maggiefriedman)]
fantasydrama[(witchesofeastend)]  series[(witchesofeastend)]
produces[(maggiefriedman  eastwick)]  develops[(maggiefriedman  eastwick)]
series[(eastwick)]  airedon[(eastwick  abc)]]
*** Conclusion:
 [*x *y [(series[(?x)]  airedon[(?x  abc)]  develops[(?y  x)]  showrunnerof[(?y  witchesofeastend)])]]
*** True Label:
 T
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(maggiefriedman)]  screenwriter[(maggiefriedman)]  producer[(maggiefriedman)]
showrunnerof[(maggiefriedman  witchesofeastend)]  executiveproducerof[(maggiefriedman  witchesofeastend)]  lifetimetelevisionseries[(maggiefriedman)]
fantasydrama[(witchesofeastend)]  series[(witchesofeastend)]
produces[(maggiefriedman  eastwick)]  develops[(maggiefriedman  eastwick)]
series[(eastwick)]  airedon[(eastwick  abc)]]
*** Conclusion:
 [@every *x [(series[(?x)]  airedon[(?x  abc)]  *y[(showrunnerof[(?y  witchesofeastend)])]  ~develops[(?y  x)])]]
*** True Label:
 F
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [american[(maggiefriedman)]  screenwriter[(maggiefriedman)]  producer[(maggiefriedman)]
showrunnerof[(maggiefriedman  witchesofeastend)]  executiveproducerof[(maggiefriedman  witchesofeastend)]  lifetimetelevisionseries[(maggiefriedman)]
fantasydrama[(witchesofeastend)]  series[(witchesofeastend)]
produces[(maggiefriedman  eastwick)]  develops[(maggiefriedman  eastwick)]
series[(eastwick)]  airedon[(eastwick  abc)]]
*** Conclusion:
 [develops[(maggiefriedman  witchesofeastend)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [largecomplex[(shafaq-asiman)]  largecomplex[(shafaq-asiman)]  offshore[(shafaq-asiman)]  geologicalstructures[(shafaq-asiman)]  in[(shafaq-asiman  caspiansea)]
northwestof[(baku  shafaq-asiman)]
@every *x @every *y [(northwestof[(?x  y)]  southeastof[(?y  x)])]]
*** Conclusion:
 [southeastof[(baku  shafaq-asiman)]]
*** True Label:
 U
*** Predicted Label:
 None

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

*** Premises:
 [largecomplex[(shafaq-asiman)]  largecomplex[(shafaq-asiman)]  offshore[(shafaq-asiman)]  geologicalstructures[(shafaq-asiman)]  in[(shafaq-asiman  caspiansea)]
northwestof[(baku  shafaq-asiman)]
@every *x @every *y [(northwestof[(?x  y)]  southeastof[(?y  x)])]]
*** Conclusion:
 [*x [(largecomplex[(?x)]  southeastof[(?x  baku)])]]
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 [largecomplex[(shafaq-asiman)]  largecomplex[(shafaq-asiman)]  offshore[(shafaq-asiman)]  geologicalstructures[(shafaq-asiman)]  in[(shafaq-asiman  caspiansea)]
northwestof[(baku  shafaq-asiman)]
@every *x @every *y [(northwestof[(?x  y)]  southeastof[(?y  x)])]]
*** Conclusion:
 [@every *x [(geologicalstructures[(?x)]  offshore[(?x)]  ~northwestof[(baku  x)])]]
*** True Label:
 F
*** Predicted Label:
 F
Classification Report:                                                 precision    recall  f1-score   support

                                                     0.00      0.00      0.00         0
                                             F       0.56      0.07      0.13        69
                                    F</output>       0.00      0.00      0.00         0
F</output>  <!-- The conclusion is false. -->        0.00      0.00      0.00         0
                                          None       0.00      0.00      0.00         0
                                             T       0.47      0.14      0.22       122
                                    T</output>       0.00      0.00      0.00         0
                                             U       0.25      0.01      0.02       110

                                      accuracy                           0.08       301
                                     macro avg       0.16      0.03      0.05       301
                                  weighted avg       0.41      0.08      0.12       301

*************** INFERENCE COMPLETE ***************

In [15]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.07641196013289037
***** PRECISION *****
0.1597222222222222
***** RECALL *****
0.027612367437741633
***** F1 *****
0.04511735765899656

   Accuracy  Precision    Recall        F1
0  0.076412   0.159722  0.027612  0.045117

In [17]:
# try rag search with phi
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct")
# CPU Enabled uncomment below 👇🏽
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")
# GPU Enabled use below 👇🏽
model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct", device_map="auto")

config.json: 0.00B [00:00, ?B/s]

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [18]:
# experiment: ZS prediction without Grammar
ref_labels, pred_labels, eval_metrics_df, acc_metric, pr_metric, re_metric, f_metric = infer_from_ontology(pfolio_df, model, tokenizer, mode='default', notation='CGIF')

*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [ocellatedwildturkey[(tom)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [easternwildturkey[(tom)]]
*** True Label:
 F
*** Predicted Label:
 T</output>
*** Premises:
 [@every *x [(wildturkey[(?x)]  [(easternwildturkey[(?x)]  osceolawildturkey[(?x)]  gouldswildturkey[(?x)]  merriamswildturkey[(?x)]  riograndewildturkey[(?x)]  ocellatedwildturkey[(?x)])])]
~[(easternwildturkey[(tom)])]
~[(osceolawildturkey[(tom)])]
~[(gouldswildturkey[(tom)])]
~[(merriamswildturkey[(tom)]  riograndewildturkey[(tom)])]
wildturkey[(tom)]]
*** Conclusion:
 [wildturkey[(joey)]]
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 [has[(mary  flu)]
@every *x [(has[(?x  flu)]  has[(?x  influenza)])]
~has[(susan  influenza)]]
*** Conclusion:
 [has[(mary  influenza)]  has[(susan  influenza)]]
*** True Label:
 T
*** Predicted Label:
 F</output>
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(in[(butte  x)]  in[(stpierre  x)])]]
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [*x [(city[(pierre)]  in[(pierre  x)]  city[(bismarck)]  in[(bismarck  x)])]]
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 [city[(billings)]  in[(billings  montana)]
city[(butte)]  in[(butte  montana)]  city[(helena)]  in[(helena  montana)]  city[(missoula)]  in[(missoula  montana)]
*x [(city[(whitesulphursprings)]  in[(whitesulphursprings  x)]  city[(butte)]  in[(butte  x)])]
city[(pierre)]  ~[(in[(pierre  montana)])]
@every *x [([(city[(?x)]  city[(butte)]  in[(?x  butte)])]  ~[(in[(?x  pierre)])])]
@every *x *y [([(city[(?x)]  [(in[(?x  y)]  ~[(?x=bristol)]  ~[(?x=texarkana)]  ~[(?x=texhoma)]  ~[(?x=unioncity)])]  ~*z [(~[(?z=y)]  in[(?x  z)])])]]
*** Conclusion:
 [city[(missoula)]  in[(missoula  montana)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newfrance)])]]
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [*x [(built[(pierrederigauddevaudreuil  x)]  locatedin[(?x  newengland)])]]
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 [renamedas[(fortcarillon  fortticonderoga)]
built[(pierrederigauddevaudreuil  fortcarillon)]
locatedin[(fortcarillon  newfrance)]
~locatedin[(newfrance  europe)]]
*** Conclusion:
 [locatedin[(fortcarillon  europe)]]
*** True Label:
 U
*** Predicted Label:
 None
*** Premises:
 [holds[(suduva  thelithuaniansupercup)]
soccerteam[(suduva)]]
*** Conclusion:
 [*x [(soccerteam[(?x)]  holds[(?x  thelithuaniansupercup)])]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[wakesup[(thehulk)]  ~happy[(thor)]]
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 [happy[(thor)]  wears[(peterparker  uniform)]]
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 [superhero[(peterparker)]  civilian[(peterparker)]
destroyer[(thehulk)]
angry[(thehulk)]  wakesup[(thehulk)]
wakesup[(thehulk)]  breaks[(thehulk  bridge)]
god[(thor)]
happy[(thor)]  breaks[(thor  bridge)]
@every *x [(god[(?x)]  ~destroyer[(?x)])]
superhero[(peter)]  wears[(peter  uniform)]
@every *x [([(destroyer[(?x)]  breaks[(?x bridge)])]  ~civilian[(peter)])]
happy[(thor)]  angry[(thehulk)]]
*** Conclusion:
 ~[happy[(thor)]  ~breaks[(thor  bridge)]]
*** True Label:
 U
*** Predicted Label:
 U</output>
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [situatedon[(longueau  pairslille)]]
*** True Label:
 T
*** Predicted Label:
 </output> tags.
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 ~[in[(boves  europe)]]
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 [railwaystation[(boves)]  in[(boves  france)]
precede[(longueau  boves)]
precede[(boves  dommartin)]
in[(france  europe)]
situatedon[(dommartin  pairslille)]
@every *x @every *y @every *z [([(situatedon[(?x  z)]  [(precede[(?x  y)]  precede[(?y  x)])]  situatedon[(?y  z)])]
serve[(boves  hautsdefrance)]
@every *x @every *y @every *z [([(in[(?x  y)]  in[(?y  z)])]  in[(?x  z)])]
@every *x @every *y @every *z [([(precede[(?x  y)]  precede[(?y  z)])]  precede[(?x  z)])]]
*** Conclusion:
 [serve[(longueau  hautsdefrance)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(eight  seven)]]
*** True Label:
 T
*** Predicted Label:
 None
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [positive[(eight)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [realnum[(num6)]  realnum[(num7)]  realnum[(num8)]
@every *x @every *y [([(realnum[(?x)]  realnum[(?y)]  issuccessorof[(?x  y)])]  larger[(?x  y)])]
@every *x @every *y [(larger[(?x  y)]  ~larger[(?y  x)])]
*y[(issuccessorof[(?y  num6)]  equals[(num7  y)])]
*y[(issuccessorof[(?y  num7)]  equals[(num8  y)])]
positive[(num2)]
@every *x @every *y [([(positive[(?x)]  isdouble[(?y  x)])]  positive[(?y)])]
isdouble[(num8  num4)]
isdouble[(num4  num2)]]
*** Conclusion:
 [larger[(six  seven)]]
*** True Label:
 F
*** Predicted Label:
 None
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [love[(miroslav  music)]]
*** True Label:
 U
*** Predicted Label:
 T
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [*x *y [(czech[(?x)]  publishedbook[(?x  y  year1946)])]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [czech[(miroslav)]  choralconductor[(miroslav)]  specializeinperformanceof[(miroslav  renaissancemusic)]  specializeinperformanceof[(miroslav  baroquemusic)]
@every *x [(choralconductor[(?x)]  musician[(?x)])]
*x *y [([(musician[(?x)]  love[(?x  music)])]  [(~[(?x=y)]  musician[(?y)]  love[(?y  music)])])]
publishedbook[(miroslav  methodofstudyinggregorianchant  yr1946)]]
*** Conclusion:
 [@every *x [(choralconductor[(?x)]  ~specializeinperformanceof[(?x  renaissancemusic)])]]
*** True Label:
 F
*** Predicted Label:
 T
*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 [likeplayingwith[(cat  taigavole)]]
*** True Label:
 T
*** Predicted Label:
 T
*** Premises:
 [vole[(taigavole)]  livein[(taigavole  northamerica)]
likeplayingwith[(cat  taigavole)]
livein[(taigavole  borealtaigazone)]
@every *x [([(livein[(?x  northamerica)]  livein[(?x  borealtaigazone)])]  livein[(?x  coldplace)])]]
*** Conclusion:
 ~[livein[(taigavole  coldplace)]]
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [workedwith[(whalenturner  greenwillowbooks)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 [plotstoswallowup[(medeempire  attolia)]]
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[setin[(thickastheives  medeempire)]]
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 [youngadultfantasy[(thickastheives)]  novel[(thickastheives)]  writtenby[(thickastheives  meganwhalenturner)]
publishedby[(thickastheives  greenwillowbooks)]
@every *x @every *y @every *z [([(writtenby[(?x  y)]  publishedby[(?x  z)])]  workedwith[(?y  z)])]
fictional[(medeempire)]  setin[(thickastheives  medeempire)]
*x *y [([(country[(?x)]  near[(?x  medeempire)]  plotstoswallowup[(medeempire  x)])]  [(~[(?x=y)]  near[(?y  medeempire)]  plotstoswallowup[(medeempire  y)])])]
country[(attolia)]  near[(attolia  medeempire)]  country[(sounis)]  near[(sounis  medeempire)]
soldas[(thickastheives  hardcover)]  soldas[(thickastheives  softcover)]]
*** Conclusion:
 ~[workedwith[(megan  greenwillowbooks)]]
*** True Label:
 F
*** Predicted Label:
 U</output>
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [graduatedwith[(walterbrown  bachelorsofart)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(in[(walterbrownfather  toledo  t)])]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [americanpolitician[(walterbrown)]  lawyer[(walterbrown)]  servedas[(walterbrown  postmastergeneral)]
graduated[(walterbrown  harvard)]  graduatedwith[(walterbrown  bachelorsofart)]
*t[(in[(walterbrown  toledo  t)]  in[(walterbrownfather  toledo  t)]  practicedlawtogether[(walterbrown  walterbrownfather  t)])]
married[(katherinhafer  walterbrown)]]
*** Conclusion:
 [*t[(~in[(walterbrownfather  toledo  t)])]]
*** True Label:
 F
*** Predicted Label:
 U
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [([(water[(?x)]  from[(?x  crotonriverwatershed)])]  *y[(flowsto[(?x  y)]  in[(?y  newyork)])])]]
*** True Label:
 T
*** Predicted Label:
 U
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [in[(crotonriverwatershed  bronx)]]
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 [drainagebasinof[(crotonriverwatershed  crotonriver)]
in[(crotonriver  southwesternnewyork)]
@every *x [([(water[(?x)]  in[(?x  crotonriverwatershed)])]  flowsto[(?x  bronx)])]
in[(bronx  newyork)]]
*** Conclusion:
 [@every *x [(water[(?x)]  from[(?x  crotonriver)]  flowsto[(?x  bronx)])]]
*** True Label:
 U
*** Predicted Label:
 U
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(form[(?x  system7)]  formermemberof[(?x  gong)])]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 [*x [(single[(?x)]  release[(system7  x)])]]
*** True Label:
 U
*** Predicted Label:
 T</output>
*** Premises:
 [basedin[(system7  uk)]  electronicdancemusicband[(system7)]
form[(stevehillage  system7)]  form[(miquettegiraudy  system7)]
formermemberof[(stevehillage  gong)]  formermemberof[(miquettegiraudy  gong)]
@every *x [(electronicdancemusicband[(?x)]  band[(?x)])]
*x [(clubsingle[(?x)]  release[(system7  x)])]
@every *x [(clubsingle[(?x)]  ~single[(?x)])]]
*** Conclusion:
 ~[band[(system7)]]
*** True Label:
 F
*** Predicted Label:
 F</output>
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [opentopublic[(usssalem)]]
*** True Label:
 T
*** Predicted Label:
 T</output>
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]
servedin[(usssalem  atlantic)]  servedin[(usssalem  mediterranean)]]
*** Conclusion:
 [*x [(museumship[(?x)]  opentopublic[(?x)]  servedin[(?x  mediterranean)])]]
*** True Label:
 T
*** Predicted Label:
 U</output>
*** Premises:
 [heavycruiser[(usssalem)]  builtfor[(usssalem  unitedstatesnavy)]
lastheavycruisertoenterservice[(usssalem)]
museumship[(usssalem)]
@every *x [(museumship[(?x)]  opentopublic[(?x)])]

In [19]:
# output results
print("***** ACCURACY *****")
print(acc_metric)
print("***** PRECISION *****")
print(pr_metric)
print("***** RECALL *****")
print(re_metric)
print("***** F1 *****")
print(f_metric)
eval_metrics_df

***** ACCURACY *****
0.132890365448505
***** PRECISION *****
0.1557504873294347
***** RECALL *****
0.03921994955494599
***** F1 *****
0.0590454288264148

   Accuracy  Precision   Recall        F1
0   0.13289    0.15575  0.03922  0.059045

In [20]:
# empty torch cuda cache
torch.cuda.empty_cache()

# delete model from cpu
del(model)